### ISSUE TITLE
Allow to customize "selected day label" in dialog

### ISSUE THREAD

**Issue by Toub** [dmtrKovalenko/material-ui-pickers#1008]
**Is your feature request related to a problem? Please describe.**

`format` attribute allow to customize the "selected date" format in field, but I can't find any way to customize the selected date in dialog:

![image](https://user-images.githubusercontent.com/367762/56726078-c1560800-6756-11e9-9003-6d63ffb1f432.png)

__Note__: this screenshot is based on dateFns implementation

In that case, the default format is absolutely NOT understandable for this locale (french).

**Describe the solution you'd like**

Add a dedicated "format string" and/or a function to customize this label.

**Comment by dmtrKovalenko** [comment]
https://material-ui-pickers.dev/guides/formats

**Comment by Toub** [comment]
My bad, I missed this documentation.

Thanks.
