### ISSUE TITLE
Passing props to input element

### ISSUE THREAD

**Issue by dominictwlee** [dmtrKovalenko/material-ui-pickers#1009]
For the regular material Text field component, I would normally pass some props down by "inputProps", but this doesn't seem to work with the InlineDatePicker component despite the docs stating that any prop not detected by the picker and sub components get passed down to the TextField component.

Is there anyway to do this? Thanks!

**Comment by dmtrKovalenko** [comment]
Please mention the version of pickers you r using

**Comment by dominictwlee** [comment]
Ah, sorry about that! it's 2.2.4

**Comment by dmtrKovalenko** [comment]
Both InputProps and inputProps must work

**Comment by dominictwlee** [comment]
@dmtrKovalenko 

https://codesandbox.io/s/1v4wwz6xm4

Here's a minimal example of this issue. In a nutshell, I'm passing a data-testid down through to the input, and running test with react-testing-library. The test is unable to find the data-testid, and running debug() to check out the DOM tree, you'll see that the data-testid is missing from the input element.

**Comment by dmtrKovalenko** [comment]
That is already fixed in `v3`. Checkout [this sandbox](https://codesandbox.io/s/pyo90kv320)

**Comment by dmtrKovalenko** [comment]
Sorry this one => https://codesandbox.io/s/622v1vrp4w

**Comment by dominictwlee** [comment]
Confirmed that this works with newer version, thanks.
