### ISSUE TITLE
React 15 support

### ISSUE THREAD

**Issue by dmtrKovalenko** [dmtrKovalenko/material-ui-pickers#101]
We are not supporting react 15 since beta.8.
So if you are interested on support, please mention that in this issue, and we will back support in the next release :) 
Thank you.

**Comment by paulcedrick** [comment]
Please continue supporting react 15.x at the moment. :sweat_smile:

**Comment by mbjsonie** [comment]
👍 please support react 15.x

**Comment by SimplerSoftware** [comment]
Yes, please continue support for React 15! Thanks

**Comment by dmtrKovalenko** [comment]
We will not fully support react 15 anymore, but I can create a patch release like beta.8.1 to fix some bugs of react 15.

**Comment by cherniavskii** [comment]
I don't think supporting React 15 makes a lot of sense - in most cases [upgrading to React 16 is painless](https://reactjs.org/blog/2017/09/26/react-v16.0.html#upgrading).

**Comment by cherniavskii** [comment]
@dmtrKovalenko releasing beta.8.1 may break React 16 apps (NPM may upgrade mui-pickers from beta.8 to beta.8.1 automatically)

**Comment by andrewnaeve** [comment]
just an fyi, my companies project is stuck on 15 due to other dependencies that have not yet updated, as well as an OpenID provider being incompatible with the webpack 2 security upgrade that enabled strict checks for host origin. was going to pull this in, but cant for now.
