### ISSUE TITLE
Clock numbers are not localizing

### ISSUE THREAD

**Issue by Cyrus-d** [dmtrKovalenko/material-ui-pickers#1011]
Thank you for such great work.

Apparently clock numbers are not localizing as it should:

![Capture](https://user-images.githubusercontent.com/4041334/56849735-34df4d00-68f0-11e9-8507-ec6b9b1e9f19.PNG)
  
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  3.0.0-a      |
| material-ui         |      4.0.0-a      |
| React               |   16.8.6      |
| Browser             |    chrome     |
| Peer library        |    moment      | 

## Steps to reproduce
1. use DateTimePicker
2. use the moment for parsing
3. set locale to 'fa'(Farsi)

## Expected behavior
to localize clock numbers

## Actual behavior
not localizing clock numbers

## Live example
[codesandbox](https://codesandbox.io/s/2z0vz8m2zr)

**Comment by ahmad-rzk** [comment]
Hello Cyrus 
i reported the same issue at : #950 
Here is also the code example :  https://codesandbox.io/s/00kwz8v540?fontsize=14

**Comment by Cyrus-d** [comment]
hi Ahmad,

thank you for the links, I wish the library could handle the numbering system automatically, but it is not a big deal I will do it manually.

thanks,
