### ISSUE TITLE
How do I validate keyboard input?

### ISSUE THREAD

**Issue by Vigrond** [dmtrKovalenko/material-ui-pickers#1014]
If you use keyboard input, there's no documented way to validate it according to the rules of the picker... you just have to "wait" to see if it takes it or not.

Even in the demo on the site, an invalid date will come up with an error "invalid Date Format"... but if you actually try the code listed, it doesn't show an error message at all.  Code for showing the error is not documented.

As suggested in other issue threads, you can use onInputChange, but it is disconnected from the validation scheme of the component which defeats the purpose.  You cannot take a value from onInputChange and validate it against the picker options automatically.

**Comment by dmtrKovalenko** [comment]
Yep, that`s why in `v3` we completely redone the validation and state-management process.

**Comment by Vigrond** [comment]
I suppose my desire was to see a complete and actual code preview in the v2.2.2 keyboard documentation.  Currently it is this https://github.com/dmtrKovalenko/material-ui-pickers/blob/develop/docs/pages/api/datepicker/KeyboardDatePicker.example.jsx

But this isn't reflective of what is actually displayed.  Can you update with the actual code showing the validation?  Or at the very least put it in the repo somewhere?
