### ISSUE TITLE
React Support

### ISSUE THREAD

**Issue by dmoskovtsov** [dmtrKovalenko/material-ui-pickers#1015]
Hi, 
I would suggest specifying which react version is supported in docs (and improve compatibility). For example, I used 16.6.1 and than material-ui-pickers breaks the app. 

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |       3.0.0-alpha.3  |
| material-ui         |         |
| React               |      16.6.1   |
| Browser             |         |
| Peer library        |         | 

## Steps to reproduce
Run the demo app

**Comment by dmtrKovalenko** [comment]
The required version of react exists in [peerDependencies](https://github.com/dmtrKovalenko/material-ui-pickers/blob/next/lib/package.json#L38). Npm should warn you if you are not installed required version.
