### ISSUE TITLE
Typescript compilation error in KeyboardDatePicker

### ISSUE THREAD

**Issue by ee0pdt** [dmtrKovalenko/material-ui-pickers#1017]
![image](https://user-images.githubusercontent.com/6094917/56953761-2c2b8880-6b35-11e9-8f17-5e52fda781af.png)

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  3.0.0-alpha.3       |
| material-ui         |    4.0.0-beta.0     |
| React               |    16.8.2     |
| Browser             |    Chrome     |
| Typescript             |    3.3.3333     |
| Peer library        |   moment 2.24.0      | 

## Steps to reproduce
1. Import latest versions of the above
2. Include a KeyboardDateInput component
3. Try to compile (or view in VSCode with TS checking)

## Expected behavior
Compiles / no TS errors

## Actual behavior
TS errors with:

```Type '{ format: string; id: string; label: Element; onChange: (date: Moment) => void; value: string; }' is missing the following properties from type 'Pick<KeyboardDatePickerProps, "open" | "onAccept" | "okLabel" | "cancelLabel" | "clearLabel" | "todayLabel" | "showTodayButton" | "clearable" | "DialogProps" | "children" | ... 312 more ... | "invalidDateMessage">': onAuxClick, onAuxClickCapturets(2739)```

## Live example
Alas I'm not sure how to make a live demo with a typescript error

**Comment by ee0pdt** [comment]
My code for reference

```
<KeyboardDatePicker
        format={getLocalDateFormat()}
        label={<FormattedMessage id="reports.endDate" />}
        onChange={(date: Moment) => dateToUpdate(date)}
        value={toDate}
      />
```

**Comment by dmtrKovalenko** [comment]
Please checkout this sandbox https://codesandbox.io/s/74wj801koj
Everything works fine without any ts errors. Moreover it is not needed anymore to strictly type `(date: Moment) => dateToUpdate())`. It will automatically infer the type

**Comment by dmtrKovalenko** [comment]
I suppose the error coming from version conflict with material-ui or react

**Comment by zheeeng** [comment]
Have the same issue and have same versions

**Comment by dmtrKovalenko** [comment]
I suppose you have outdated @types/react

**Comment by ee0pdt** [comment]
@dmtrKovalenko I will update my React types and test

**Comment by ee0pdt** [comment]
Ok, with @types/react@16.8.15 I seem to have cleared that error

**Comment by oliviertassinari** [comment]
Upgrading from `@types/react@16.8.10` to `@types/react@16.8.15` solves the problem for me too.
