### ISSUE TITLE
100% width

### ISSUE THREAD

**Issue by SimplerSoftware** [dmtrKovalenko/material-ui-pickers#106]
Hello, I'm trying to make the DatePicker (or any of the components in this awesome library) fill the width of the parent container.  Is there a way to do this?

**Comment by tooppaaa** [comment]
Hi,

Pass the fullWidth attribute to your element.
`<DatePicker fullWidth />`

**Comment by alitaheri** [comment]
Any props not recognized by the DatePicker and it's sub-components are passed down to TextField.

**Comment by dln88** [comment]
Pass the fullWidth attribute to DatePicker not work to me
