### ISSUE TITLE
New way to pass icons to IconButton

### ISSUE THREAD

**Issue by rek** [dmtrKovalenko/material-ui-pickers#12]
https://github.com/dmtrKovalenko/material-ui-pickers/blob/2f3b0f41debf414957ee8beb9f9086ec329b0613/src/DatePicker/CalendarHeader.jsx#L16

Reading the [docs](https://material-ui-next.com/demos/buttons/), it seems you have to pass in an icon object now from material-ui-icons?

When using this in my current project I am getting: 

![image](https://user-images.githubusercontent.com/180949/32099430-f8de7110-bb2f-11e7-830f-1596b309a987.png)

**Comment by jamesskyoung** [comment]
Had the same issue ...

dmtrKovalenko  solved it by telling me to include the Roboto font...

 <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">

**Comment by dmtrKovalenko** [comment]
@jamesskyoung material-ui-icons font did the trick  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"

Seems that we need a new way to pass icons 😄  
Will work on it, but for now **use material-icons font**

**Comment by rek** [comment]
Hrmmm, still having trouble with it, perhaps there is an issue from some of the other styles sheets included in my project.

**Comment by dmtrKovalenko** [comment]
https://material-ui-next.com/style/icons/#font-icons

Check this out, in such way icons renders for pickers. Please can you provide also more information about the version of material ui and others

**Comment by rek** [comment]
![image](https://user-images.githubusercontent.com/180949/32156204-11a472ea-bd64-11e7-9ea6-778b1bf37a74.png)

I think that's all current, I will look at disabling my sites styles slowly and see if there is a conflict there somewhere.

**Comment by dmtrKovalenko** [comment]
Thus...
My point is you have overriden font-family for `<IconButton />` somehow. It should be `material-ui-icons`.

**Comment by rek** [comment]
Ok thanks, I have removed the material-ui-icons and it is working fine now. I will change my proj to work in this way (font ligatures), instead of importing the icon components.

**Comment by 54vanya** [comment]
Hello, can I fix this without removing `material-ui-icons`?

**Comment by dmtrKovalenko** [comment]
@54vanya  @rek 
It should not be affected by `material-ui-icons`, please can you add `<link href="https://fonts.googleapis.com/icon?family=Material+Icons">` to your html and show me a sources applied to the icon button with invalid icon. 
P.S. I have test it out in the project with material-ui-icons and icon font - all works fine.

**Comment by dmtrKovalenko** [comment]
#30

**Comment by rek** [comment]
Awesome thanks!
