### ISSUE TITLE
How to render with empty value?

### ISSUE THREAD

**Issue by filipenevola** [dmtrKovalenko/material-ui-pickers#125]
Hello, I don't want to suggest anything to my user.

How can I show an empty field? Can be just blank or with a placeholder like 'choose a date'.

I tried empty string and null but both don't work.

Thanks.

**Comment by cherniavskii** [comment]
Use `labelFunc` prop: https://codesandbox.io/s/qll08v0n06

**Comment by filipenevola** [comment]
Thanks, done! :)

**Comment by santosguilherme** [comment]
In the latest versions, the message "Invalid date format" was displayed again.

**Comment by CristobalSoto** [comment]
null works fine for me, just use value={null}
