### ISSUE TITLE
Old version on demo page?

### ISSUE THREAD

**Issue by cherniavskii** [dmtrKovalenko/material-ui-pickers#131]
Looks like [demo page](https://material-ui-pic.firebaseapp.com/) still uses beta.9 - when picking time in Custom DTP from `Date & Time pickers` section (which has `autoOk` set to `true`) this bug #116 appears.

cc @dmtrKovalenko

**Comment by dmtrKovalenko** [comment]
oh, need to redeploy it - thanks

**Comment by cherniavskii** [comment]
@dmtrKovalenko friendly ping :)

**Comment by dmtrKovalenko** [comment]
@cherniavskii  I have, try to hard-reload page seems that sw is cached for you))

**Comment by cherniavskii** [comment]
@dmtrKovalenko you are right, hard reload helped. But sw shouldn't serve old js bundle if new one is available :/
