### ISSUE TITLE
Wrapper styling

### ISSUE THREAD

**Issue by noah-potter** [dmtrKovalenko/material-ui-pickers#132]
https://github.com/dmtrKovalenko/material-ui-pickers/blob/c5e6076ae88adf2a1bf8ed85f2ee255d93717f60/lib/src/wrappers/ModalWrapper.jsx#L75

I don't see any hooks to style this. I'm willing to open a PR to add this. Thoughts?

**Comment by dmtrKovalenko** [comment]
Oh, it would be replaced with fragment in the next release.

**Comment by dmtrKovalenko** [comment]
#129

**Comment by cherniavskii** [comment]
Actually somehow I missed that `div` and didn't replace it with `Fragment`.
@noah-potter would you like to submit a PR to change this?

**Comment by cherniavskii** [comment]
Closed by #141
