### ISSUE TITLE
Option to change InputAdornment Icon

### ISSUE THREAD

**Issue by edidiway** [dmtrKovalenko/material-ui-pickers#134]
Hi, for first information, I set the option keyboard = true.
I need to change the InputAdornment icon. I have seen on the demo page, you were doing like this to change the icon. 
`InputProps={{
            endAdornment: (
              <InputAdornment position="end">
                <IconButton>  add_alarm  </IconButton>
              </InputAdornment>
            ),
          }}`

but unfortunately, since I set keyboard = true, when I clicked on the "Event Icon" the calendar dialog didn't appear.

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-beta.10     |
| material-ui         |    1.0.0-beta.25     |
| React               |     16.1.0    |
| Browser             |    All     |
| Platform            |     Windows 7    |

## Steps to reproduce
1. Set the component like this 
```
<DatePicker keyboard={true} InputProps={{
            endAdornment: (
              <InputAdornment position="end">
                <IconButton>  add_alarm  </IconButton>
              </InputAdornment>
            ),
          }} />
```
2. Click on the Adornment Icon

## Expected behavior

1. Calendar dialog appear

## Actual behavior

1. Calendar dialog doesn't appear

**Comment by JacquesBotha90** [comment]
Sorry to bring up an old issue, but has this issue been solved? I'm having exactly the same issue on rc.13. Perhaps I am missing something in the docs?

**Comment by dmtrKovalenko** [comment]
@JacquesBotha90  Now its allowed to pass `InputAdornmentProps` for adornment props and `keyboardIcon` for icon component and `adornmentPosition` for position. So you can change everything you need :)

**Comment by JacquesBotha90** [comment]
Fantastic! Thanks for the prompt response and fantastic library.

**Comment by lookWhatIvanDid** [comment]
is there option for two IconButtons? I need clear button aside DatePicker, would be nice to have it inside
