### ISSUE TITLE
Props for EventIcon

### ISSUE THREAD

**Issue by myungwoo** [dmtrKovalenko/material-ui-pickers#135]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-beta.9     |
| material-ui         |   1.0.0-beta.24      |
| React               |   15.6.1      |
| Browser             |   Chrome      |
| Platform            |    Windows 10     |

## Steps to reproduce
1. Don't using material-icons font.
2. Use DatePicker/TimePicker/DateTimePicker with `keyboard={true}`.

## Expected behavior

I expect props for `event` icon, like other icon does. (i.e. leftArrowIcon, rightArrowIcon, etc...)
I usually use material-ui-icons package instead of using fonts.

## Actual behavior

It only accepts material icon fonts.

## Live example

[codesandbox](https://codesandbox.io/s/rr1zl2nolm), [live preview](https://rr1zl2nolm.codesandbox.io/)

**Comment by dmtrKovalenko** [comment]
Fixed in 1.0.0-beta.11

**Comment by lmahapatra-oliver-it** [comment]
Just tried, `leftArrowIcon` and `rightArrowIcon` props take a MUI `Icon` element with the icon font of your choice.

**Comment by mahdiG** [comment]
I was looking for leftArrowIcon and rightArrowIcon props in the documents but couldn't find them and found them here instead. It would be nice to list all the available props in the documentation. Thanks for the great project <3
