### ISSUE TITLE
Error minified when build production with react

### ISSUE THREAD

**Issue by tanmynguyen** [dmtrKovalenko/material-ui-pickers#142]
Hi @LastDreamer !
I have been bug when build production with **material-ui-pickers@1.0.0-beta.11**. After i downgrade **material-ui-pickers@1.0.0-beta.7** then OK! 
You can check again with version material-ui-pickers@1.0.0-beta.11. 
Thanks you!

**Comment by cherniavskii** [comment]
Hi and thanks for finding our library useful.
Please fill up our issue template - we need more info to be able to help you

**Comment by cherniavskii** [comment]
Also, note that we do not support React < 16.0.0 since beta.8 and React < 16.2.0 since beta.11

**Comment by cherniavskii** [comment]
I'm closing this for now, feel free to reopen if necessary

**Comment by tanmynguyen** [comment]
@cherniavskii  Thanks you for support
