### ISSUE TITLE
React warning with invalidDateMessage

### ISSUE THREAD

**Issue by myungwoo** [dmtrKovalenko/material-ui-pickers#145]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   1.0.0-beta.11      |
| material-ui         |    1.0.0-beta.25     |
| React               |    16.2.0     |
| Browser             |    All     |
| Platform            |     All    |

## Steps to reproduce
1. Use DatePicker / DateTimePicker and React development mode.

## Expected behavior

No warning.

## Actual behavior

![image](https://user-images.githubusercontent.com/9026019/34397684-896d632e-ebbb-11e7-88fb-e50881c89341.png)

**Comment by cherniavskii** [comment]
Closed by #138
