### ISSUE TITLE
Minor formatting problem when moment locale is zh-cn

### ISSUE THREAD

**Issue by cthurston** [dmtrKovalenko/material-ui-pickers#153]
## Steps to reproduce
1.  Set the moment.locale('zh-cn')
2.  Open DateTimePicker

## Expected behavior
Date to be in a single line.

## Actual behavior
Date takes two lines.

<img width="332" alt="screen shot 2017-12-31 at 6 41 05 pm" src="https://user-images.githubusercontent.com/622081/34465065-9765efb8-ee5a-11e7-9acb-79a1ef931e22.png">

**Comment by cherniavskii** [comment]
Hi Christopher,
Please do not ignore our issue template - in your case Environment section is missing.

I can't reproduce your issue - here's the result:
(link to playground: https://codesandbox.io/s/m3zo490r4p)
![selection_014](https://user-images.githubusercontent.com/13808724/34470296-d4c1b976-ef2e-11e7-94d3-0581b780c125.png)

That being said, I think it would be better to change toolbar styles from `justify-content: center` to `justify-content: space-around`:
![selection_015](https://user-images.githubusercontent.com/13808724/34470310-32251392-ef2f-11e7-960b-969e9704f87f.png)

**Comment by cthurston** [comment]
## Environment
MacBook Pro OS High Sierra
Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Tried Safari and it had the issue as well.

It is reproducible on the codesandbox link that you provided in my environment.

<img width="576" alt="screen shot 2018-01-01 at 12 56 49 pm" src="https://user-images.githubusercontent.com/622081/34470642-47f55060-eef3-11e7-9c04-42f5b105478c.png">

**Comment by dmtrKovalenko** [comment]
I have no idea how to fix the issue that is not reproducible for us even  on the sandbox, only one thing, that can be a problem - default fontsize of system?
So closing this issue.

**Comment by cthurston** [comment]
Still occurs on my system.  

If the H1 font size that contains the date is 2.125em it bumps down.  If the font size is 2.110em is does not bump down. 

Also, if the font size is the same, but the margin-left on the H1 is -0.06em instead of -0.04em is does not bump down.

 So it's definitely close.

**Comment by cherniavskii** [comment]
huh, I actually can reproduce it now on 4k screen, so it's related to devicePixelRation I guess.

**Comment by cherniavskii** [comment]
@cthurston I've submitted a PR, could you check if it fixes your problem?

**Comment by cthurston** [comment]
That fixed it.  Thanks guys.
