### ISSUE TITLE
Leading Zeros

### ISSUE THREAD

**Issue by andokai** [dmtrKovalenko/material-ui-pickers#155]
Is it possible to remove the leading zeros from single digit dates to make the control look closer to the spec? Also single character day indicators.

Great work BTW, the control is very helpful.
<img width="331" alt="screen shot 2018-01-01 at 08 43 16" src="https://user-images.githubusercontent.com/3984138/34466571-60af74e6-eed0-11e7-9620-62ee442d3b1c.png">

**Comment by cherniavskii** [comment]
@andokai of course it is possible, nice catch btw ;)

Would you like to submit a PR?

**Comment by andokai** [comment]
@cherniavskii I'd love to, but I won't have any free time to work on it for at least a few weeks.

**Comment by andokai** [comment]
Beta 13 looks great! 👍
