### ISSUE TITLE
Discussion on default formats

### ISSUE THREAD

**Issue by cthurston** [dmtrKovalenko/material-ui-pickers#158]
Just curious on the decision behind the default formats?

I think that the following would be more logical defaults:

DatePicker
ll

DateTimePicker
lll

TimePicker
LT

**Comment by cherniavskii** [comment]
@cthurston are you talking about `format` prop?

**Comment by cthurston** [comment]
Yes.  The default format prop.

**Comment by cherniavskii** [comment]
Sounds good :+1: 

cc @dmtrKovalenko

**Comment by dmtrKovalenko** [comment]
Yep, I think it would be more helpful to shorthand the month name. 👍

**Comment by dmtrKovalenko** [comment]
Closing it because the format `II` for datepicker looks weird from the design prospective. It will be left as is, but if you really need this, from the next release you will be able to override any labels through the pickers.
