### ISSUE TITLE
[Docs] Documentation autogeneration

### ISSUE THREAD

**Issue by dmtrKovalenko** [dmtrKovalenko/material-ui-pickers#162]
I want to generate props documentation using https://github.com/reactjs/react-docgen to improve docs support (now really often contributors forgot to update readme with props table) and publish them on the demo website.
But firstly we need to migrate current documentation to props and I`m on it, but also any new changes and features should have documentation in react-docgen style. 
Any points about that?

**Comment by cherniavskii** [comment]
@dmtrKovalenko that would be great!
I believe `material-ui` uses `react-docgen` too, so we can generate our docs in similar way
