### ISSUE TITLE
Got Errror: Element type is invalid

### ISSUE THREAD

**Issue by chenop** [dmtrKovalenko/material-ui-pickers#166]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   1.0.0-beta.12      |
| material-ui         |   ^1.0.0-beta.22      |
| React               |  15.5.4       |
| Browser             |    Chrome     |
| Platform            |     Windws    |

## Steps to reproduce
1. Use `<TimePicker />`
2. 
3.

## Expected behavior
TimePicker should be displayed

## Actual behavior
Got error in console:
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `ModalWrapper`.

## Live example
```
 <TimePicker
          value={new Date()}
          onChange={() => {}}
  />
```

**Comment by cherniavskii** [comment]
Hi @chenop,
We do not support React < 16.2.0.
I'd suggest you to upgrade React to 16.2.0
