### ISSUE TITLE
Using DatePicker component without wrapper

### ISSUE THREAD

**Issue by brett-patterson** [dmtrKovalenko/material-ui-pickers#167]
First of all, thanks for all you're work on this project. The pickers look great!

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    ^1.0.0-beta.12     |
| material-ui         |    ^1.0.0-beta.23     |
| React               |     ^16.2.0    |
| Browser             |     Chrome 63.0.3239.84 64bit    |
| Platform            |     MacOS High Sierra 10.13.2    |

## Issue
Right now to use the components such as DatePicker without their wrapper and text field, you have to import from `material-ui-pickers/src/...`. The problem with this is that the code is not run through babel and transpiled at this point, so while this works for webpack, which does the transpiling itself, it does not work in all settings. In my case, I'm running into trouble with my SSR setup.

## Expected behavior
It would be nice to make the wrappers explicit and export them from the index script, i.e. `import {DatePickerDialog, DatePicker} from 'material-ui-pickers'`. Or maybe material-ui style: `import DatePickerDialog from 'material-ui-pickers/DatePickerDialog'`. I'm happy to help if needed.

**Comment by ValentinH** [comment]
Funny timing, I was actually coming to the issues to ask how to use the dialog only 😄  👍

**Comment by dmtrKovalenko** [comment]
You can do it now with
```js
import DatePickerDialog from 'material-ui-pickers/DatePicker/DatePicker'
```

**Comment by brett-patterson** [comment]
Great, thank you!
