### ISSUE TITLE
[discussion] `returnMoment` prop removal

### ISSUE THREAD

**Issue by rosskevin** [dmtrKovalenko/material-ui-pickers#172]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     `develop` d6aac106aa83435b5bd73e03488e769c4ac736c3    |

## Expected behavior
- Module has a consistent API that is stable for the future.
- README is correct
- Typescript usage does not require casting value

## Actual behavior
- README indicates that `returnMoment` defaults to true, when it is false.
- `returnMoment` changes the result of the API.  I found this when tightening up types for typescript in #171. 

## Context
Since it is contemplated to remove `Moment` anyway, and `Date` is part of the standard library, I suggest the removal of `returnMoment` and always return `Date`

I'm happy to PR - but wanted to discuss first.

**Comment by dmtrKovalenko** [comment]
Thank you for awesome issues. Yep we need to remove returnMoment. I just did not do this before to not cause breaking changes. 
P. S. It defaults to true as documented.

**Comment by rosskevin** [comment]
The default for `returnMoment` is `false` based on the code:

https://github.com/dmtrKovalenko/material-ui-pickers/blob/6bae271d648305edff15e66c86c77dbd77a2218c/lib/src/_shared/PickerBase.jsx#L18-L25

**Comment by dmtrKovalenko** [comment]
Oh thats just invalid, we should remove default props from the PickerBase - because they are not working together with inheritance. Default props comes from `Wrapper` 
https://github.com/dmtrKovalenko/material-ui-pickers/blob/08891717ffa83748536a6cbd40dd2e32a5de7039/lib/src/DatePicker/DatePickerWrapper.jsx#L54

**Comment by dmtrKovalenko** [comment]
Have done it in rc-1 :)
