### ISSUE TITLE
DatePicker is crashing app with material ui 1.0.0-beta.26

### ISSUE THREAD

**Issue by asveloper** [dmtrKovalenko/material-ui-pickers#178]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-beta.12     |
| material-ui         |   1.0.0-beta.26      |
| React               |   16.0.0      |
| Browser             |   Chrome      |
| Platform            |         |

**Comment by sakulstra** [comment]
@asveloper can't you upgrade to mui-27/28 (at least there it is working without problems for me)

**Comment by cherniavskii** [comment]
@asveloper I think it's because React version. We support ^16.2.0.
You can upgrade React version to 16.2.0 - usually this upgrade doesn't require any changes in codebase.
