### ISSUE TITLE
Breaking change in MUI v1.0.0-beta.28 -> colors not displayed

### ISSUE THREAD

**Issue by jonsbaa** [dmtrKovalenko/material-ui-pickers#181]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-beta.12     |
| material-ui         |    v1.0.0-beta.28     |
| React               |    ^16.0.0     |
| Browser             |    Chrome     |
| Platform            |         |

Breaking change in https://github.com/mui-org/material-ui/releases/tag/v1.0.0-beta.28 affects how colors are used in MUI. This results in colors not being displayed at the moment.

**Comment by chaitanya0bhagvan** [comment]
@jonsbaa Until this library fixes this issue you can use the below hack to make it work as before.

```
export const myPalette = {
  50: '#e9f2fc',
  100: '#c9def6',
  200: '#a5c8f1',
  300: '#80b1eb',
  400: '#65a1e6',
  500: '#4a90e2',
  600: '#4388df',
  700: '#3a7dda',
  800: '#3273d6',
  900: '#2261cf',
  A100: '#ffffff',
  A200: '#d5e3ff',
  A400: '#a2c1ff',
  A700: '#89b0ff',
  contrastDefaultColor: 'dark'
};

const theme = createMuiTheme({
  palette: {
    primary: {
      light: myPalette[300],
      main: myPalette[500],
      dark: myPalette[700],
      ...myPalette
    }
  }
});

```

**Comment by cherniavskii** [comment]
Hi Joanna,
please try [material-ui-v1.0.0-beta.29](https://github.com/mui-org/material-ui/releases/tag/v1.0.0-beta.29) and let us know if issue still present :)

**Comment by gcmestre** [comment]
@cherniavskii I tried with [material-ui-v1.0.0-beta.29](https://github.com/mui-org/material-ui/releases/tag/v1.0.0-beta.29) and still had the same problem

**Comment by jonsbaa** [comment]
@cherniavskii @gcmestre For me, v1.0.0-beta.29 solved the problem :)

**Comment by gcmestre** [comment]
@jonsbaa what version of the picker did you use? 1.0.0-beta.12?

**Comment by jonsbaa** [comment]
@gcmestre yup, 12!

**Comment by ValentinH** [comment]
I've installed beta.12 along with material-ui@1.0.0-beta.29 and I get this:
![image](https://user-images.githubusercontent.com/2678610/35195666-52f08d5c-fec7-11e7-8d38-203aeb2afce2.png)

**Comment by cherniavskii** [comment]
I think we should go for beta.30 now :)
https://github.com/mui-org/material-ui/releases/tag/v1.0.0-beta.30

**Comment by muhammadtalha-13** [comment]
Hi. I am having exactly this same issue and I am already on beta 12 of pickers and beta 30 of mui. Any other ideas what could the issue be?

**Comment by cherniavskii** [comment]
@muhammadtalha-13 wait for material-ui-pickers beta.13 - it will be compatible with mui-beta.30.
@dmtrKovalenko any ETA on beta.13 release?

**Comment by cherniavskii** [comment]
Closed by #187

**Comment by AidanRRR** [comment]
Any idea on when the new update comes? Thanks!

**Comment by dmtrKovalenko** [comment]
@AidanRRR  It was fixed, if you have any issues with the newest material-ui-pickers please provide steps to reproduce here or please open a new issue.
