### ISSUE TITLE
(Request) Add the name of the field to the onChange callback

### ISSUE THREAD

**Issue by rszemplinski** [dmtrKovalenko/material-ui-pickers#182]
Hi,

I am trying to use your project in conjunction with my project but I ran into a hiccup with your package. Your onChange event seems to only pass the value (the date) and it doesn't actually pass the event which is causing some major problems for my little system.

    protected handleChange = (event): void => {
        var formData = this.formData;

        if (event.target) {
            formData[event.target.name] = event.target.value;
        } else {
            //Dates are causing issues because they don't pass the target's name
        }

        this.setState({ formData: formData });
    }

So I was wondering if you guys could somehow just pass the name of the field in the onChange event or pass the event in a second parameter or if you have any other solutions I'm open ears.

Thanks!

**Comment by alitaheri** [comment]
@rszemplinski The event object may come from various places as there are numerous ways to change the date value ( keyboard, OK button, day or minute button ). none of them actually give valuable information.

I also don't have enough context to suggest a solution. Please provide the code where this component is used.

**Comment by dmtrKovalenko** [comment]
Found that its invalid - use refs and function decorators if you need to
