### ISSUE TITLE
minDate and maxDate not working

### ISSUE THREAD

**Issue by chaitanya0bhagvan** [dmtrKovalenko/material-ui-pickers#192]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   v1.0.0-beta.13   |
| material-ui         |    v1.0.0-beta.30     |
| React               |     16.2.0    |
| Browser             |     Chrome    |
| Platform            |     OSX    |

## Steps to reproduce
1. Set minDate and/or maxDate in the DatePicker

## Expected behavior
Dates outside the minDate and maxDate range should be disabled and not selectable

## Actual behavior
minDate and maxDate is not respected

Here is the diff from the last commit where minDate and maxDate are no longer passed to DatePicker

**Comment by dmtrKovalenko** [comment]
Fixed in beta.13.1
