### ISSUE TITLE
Calendar icon not displayed correctly when label property is set

### ISSUE THREAD

**Issue by ivan-nikitovic** [dmtrKovalenko/material-ui-pickers#202]
## Environment
```
  "react-dom": "16.2.0",
  "react": "16.2.0",
  "moment": "2.20.1",
  "material-ui-pickers": "1.0.0-beta.14",
  "material-ui-icons": "1.0.0-beta.17",
  "material-ui": "1.0.0-beta.31"
```

## Steps to reproduce
1. Set `label` property to `'Some text...'`
2. Set `keyboard` property to `true`

## Expected behavior
Calendar icon is displayed correctly

## Actual behavior
Icon overlaps with input line

## Live example
https://codesandbox.io/s/0qn25zorp

**Comment by cherniavskii** [comment]
Thanks for creating live example, it really saves our time :+1:

**Comment by z-ax** [comment]
Adding keyboardIcon breaks layout to me as well, but make the field's height bigger that it has to be compared to other fields (using it with `redux-form`). By default (specifying only the `keyboard` prop) it just renders the `event` text.

<img width="487" alt="screen shot 2018-02-08 at 19 33 42" src="https://user-images.githubusercontent.com/1391015/35988418-068774c8-0d07-11e8-9127-b0494f91af18.png">

Usage example:

```jsx
import { DatePicker } from 'material-ui-pickers';
import EventIcon from 'material-ui-icons/Event';

<DatePicker
  keyboard
  keyboardIcon={<EventIcon />}
/>
```

**Comment by dmtrKovalenko** [comment]
Fixed in beta.15
