### ISSUE TITLE
Ignored Seconds-Change

### ISSUE THREAD

**Issue by EaseRider** [dmtrKovalenko/material-ui-pickers#206]
Hello again, thank you for this project.
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   any (beta-14  currently)    |

## Steps to reproduce
1. DateTimePicker or TimePicker
2. format='DD.MM.YYYY HH:mm:ss' or 'HH:mm:ss'
3. Only change Seconds with keyboard
4. open Picker

## Expected behavior
Changing the Seconds should also fire the event, with the new time; maybe parsed by the format.

## Actual behavior
Chaning the seconds does not fire the event. So the old value is taken when opening the picker.

## Live example
https://codesandbox.io/s/7m97n5wm2j

**Comment by dmtrKovalenko** [comment]
Fixed in rc-1

**Comment by EaseRider** [comment]
Doesn't seem to be solved to me.
the error may lie on line 199 in DateTextField.jsx
      if (!error && utils.format(newValue, 'LLLL') !== utils.format(oldValue, 'LLLL')) {
Where LLLL formats the date into 'Monday, March 26, 2018 9:31 AM' where the seconds (and millis) are missing.
Something like: 'YYYY-MM-DDTHH:mm:ss.SSSZ' would be the most accurate. But I don't think that the Z would be needed to compare the timezones of the input.

https://codesandbox.io/s/pjzk802vym

**Comment by SerhiiBilyk** [comment]
I have same problem.Changing seconds from keyboard does not trigger onChange callback
