### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by Lewis945** [dmtrKovalenko/material-ui-pickers#208]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   1.0.0-beta.14      |
| material-ui         |    1.0.0-beta.31     |
| React               |   16.2.0     |
| Browser             |    chrome     |
| Platform            |     windows    |

## Expected behavior

No error is expected.

## Actual behavior
After version beta 12 receives this error.
Uncaught ReferenceError: process is not defined
    at Number.<anonymous> (material-ui-pickers@1.0.0-beta.14:2987)

I use typescript and fusebox as a bundler. Maybe there will be any guesses why it might happen?

**Comment by dmtrKovalenko** [comment]
Please can you provide a https://codesandbox.io/ it would be really helpful to have a way to reproduce that.
