### ISSUE TITLE
Warning: React.createElement: type is invalid -- expected a string

### ISSUE THREAD

**Issue by semiautomatix** [dmtrKovalenko/material-ui-pickers#209]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   ^1.0.0-beta.14      |
| material-ui         |   ^1.0.0-beta.32      |
| React               |     15.6.1    |
| Browser             |    Chrome 63.0.3239.132, FireFox 58.0.1   |
| Platform            |      Windows 10   |

warning.js:35 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `ModalWrapper`.

## Steps to reproduce
1. Use default example

## Expected behavior
To display correctly

## Actual behavior
Error is produced

**Comment by semiautomatix** [comment]
```
            <DatePicker
              value={new Date()}
              onChange={() => {}}
            /> 
```

**Comment by semiautomatix** [comment]
CodeSandbox: https://codesandbox.io/s/y233z8l32j

**Comment by mono424** [comment]
+1

**Comment by djhi** [comment]
That's because react `16.2.0` is required: the library uses `Fragment`

**Comment by cherniavskii** [comment]
@semiautomatix it *is* highlighted as a breaking change - see https://github.com/dmtrKovalenko/material-ui-pickers/releases/tag/v1.0.0-beta.11

**Comment by semiautomatix** [comment]
@cherniavskii My apologies, my searches did not bring this change to my attention - hopefully this thread will point others to the solution.
