### ISSUE TITLE
[Feature] is there any plans to add date range picker

### ISSUE THREAD

**Issue by salamaashoush** [dmtrKovalenko/material-ui-pickers#212]
just wondering if there are any plans to support date-range like this package [react-dates](https://github.com/airbnb/react-dates)

**Comment by dmtrKovalenko** [comment]
No we are not planning to implement range pickers in the nearest future.

**Comment by krazyjakee** [comment]
With the greatest respect (this project is awesome), I urge you to reconsider. The ability to put pickers side by side this way would add a lot of frequently used functionality. Take [this image](https://camo.githubusercontent.com/ff92c606a5b7f44fed2e9b08a1b2c4d3e138ab68/68747470733a2f2f73332d65752d776573742d312e616d617a6f6e6177732e636f6d2f6e706d2d696d616765732f7675652d6d6174657269616c2d646174657069636b65722f646f75626c65642d76657273696f6e2e706e67) for example. I am willing to supply a pull request if you'll consider it.

**Comment by dmtrKovalenko** [comment]
@krazyjakee #364 => I have reconsider already. But I thought about adding new package, which will rely on this one and add all new logic there. 
Just because really not at all of people needs range picker, and if somebody using dist build that may take bundle overhead)

**Comment by krazyjakee** [comment]
@dmtrKovalenko ok, thanks for the reference :)
