### ISSUE TITLE
The prop `inputRef` is marked as required in `Input`, but its value is `undefined`.

### ISSUE THREAD

**Issue by webbygregg** [dmtrKovalenko/material-ui-pickers#215]
I am receiving the error "The prop `inputRef` is marked as required in `Input`, but its value is `undefined`." 

I am using material-ui@next and this is my code:
```

const DateSelector = withDatePush(({onChange, selectedDate, format = 'MMMM Do, YYYY'}) =>
  <DatePicker
    value={selectedDate}
    onChange={onChange}
    leftArrowIcon={<KeyboardArrowLeft />}
    rightArrowIcon={<KeyboardArrowRight />}
    returnMoment
    format={format}
  />);
```

Would appreciate any help on this.

**Comment by jordangotbaum** [comment]
+1

**Comment by maZahaca** [comment]
any update in here? @webbygregg do you have styles of this component rendered ok? I'm using the same material-ui@next and apart of your error, half of styles disappeared

**Comment by webbygregg** [comment]
I haven't had an issue with styles, everything works correctly. I just get this error.

**Comment by Rick83600** [comment]
The same here, any news ?

**Comment by jordangotbaum** [comment]
My styles are all broken as well. Running React/react dom at 16.2 and material ui@latest.

**Comment by maZahaca** [comment]
@jordangotbaum the thing which helped me about styles -
I used v1.0.0-beta.15.1 of this library and exact material-ui vbeta.33

**Comment by dmtrKovalenko** [comment]
Update to v1.0.0-beta.15.1 and material-ui v1.0.0-beta.33 solves the issue

**Comment by Sandervanlaarhoven** [comment]
I am actually getting this now after updating to the latest version v1.0.0-rc.3. Anyone else getting this?

**Comment by aeciolevy** [comment]
I am getting the same "material-ui-pickers": "1.0.0-rc.14"

**Comment by dmtrKovalenko** [comment]
If you have a sandbox with a way to reproduce it feel free to open new issue.

**Comment by aeciolevy** [comment]
@dmtrKovalenko apologies @dmtrKovalenko actually "material-ui-pickers": "1.0.0-rc.14" solve this problem, but I am getting one error in the style.

![image](https://user-images.githubusercontent.com/16165803/44949417-90028380-ade5-11e8-9cd1-a4f6cdbbdf93.png)

I don't know what is cause it, there is not error on console.

**Comment by dmtrKovalenko** [comment]
You need to install icon font or pass icons manually. 
Reread he last step of install guide

**Comment by aeciolevy** [comment]
@dmtrKovalenko Thank you and sorry about the stupid question.
