### ISSUE TITLE
shouldDisableDate disabled all dates

### ISSUE THREAD

**Issue by stefensuhat** [dmtrKovalenko/material-ui-pickers#216]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    latest     |
| material-ui         |      latest beta   |
| React               |      16   |
| Browser             |      Chrome   |
| Platform            |      Mac   |

```
<DatePicker
                autoOk
                format="DD MMMM YYYY"
                shouldDisableDate={() => moment()}
                minDate={moment().add(1, 'd')}
                InputProps={{
                    endAdornment: (
                        <InputAdornment position="end">
                            <IconButton>
                                <CalendarIcon />
                            </IconButton>
                        </InputAdornment>
                    ),
                }}
                value={startDate}
                onChange={handleDateChanged}
                style={{ marginBottom: 16 }}
            />
```

I want to disabled today's date using shouldDisableDate when I put those props, it disables all my dates

**Comment by dmtrKovalenko** [comment]
No. You should use arguments that passed to should disable date. And return Boolean, now are returning moment object, which converts to true anytime
