### ISSUE TITLE
DatePicker Skips February

### ISSUE THREAD

**Issue by danmce** [dmtrKovalenko/material-ui-pickers#217]
## Environment

    "material-ui": "^1.0.0-beta.26",
    "material-ui-pickers": "1.0.0-beta.15.1",

## Steps to reproduce
1. Click date
2. Picker opens
3. Current month displayed as February
4. Use arrows to navigate next and previous months
5. February is always skipped over - happens on any year

## Expected behavior

February to be selected and available dates shown

## Actual behavior

February is skipped, can only view dates for other months

**Comment by dmtrKovalenko** [comment]
Please can you provide the way you using the picker? It can be caused by wrapping inside the FormControl. 
I cannot reproduce this bug, also on the demo page - all works fine

**Comment by danmce** [comment]
Possible edge case then or how we are implementing this.

We are using react-jsonschema to supply the data to the form and loading a widget that contains the picker based on the mapping in the data.

The widget renders a FormControl wrapping the DatePicker:
`<FormControl required={required} error={(rawErrors && rawErrors.length > 0) ? true : false} fullWidth={true}>
        <DatePicker
          value={formData}
          onChange={this.dateChange}
          format={DATE_FORMAT}
          className={classes.root}
          InputProps={inputProps}
        />
        <FormHelperText>{help}</FormHelperText>
      </FormControl>`

It's not particular to February, but the selected month i.e. if no date is supplied it defaults to todays date (February), if a date is supplied, the date is selected (i.e. January) - this is the month that renders on load but is then subsequently skipped when navigating next and previous months (even does it when the year changes).

**Comment by dmtrKovalenko** [comment]
Thank you!
