### ISSUE TITLE
Support for inline segmented dropdown

### ISSUE THREAD

**Issue by rocketraman** [dmtrKovalenko/material-ui-pickers#220]
Is there a way to do use the date picker as an inline segmented dropdown picker?

According to https://material.io/guidelines/components/pickers.html#:

> On mobile, pickers are best suited for display in a confirmation dialog.
>
> For inline display, such as on a form, **consider using compact controls such as segmented dropdown buttons**.

**Comment by dmtrKovalenko** [comment]
No there is no way for now to display it in the popover, this feature is in our roadmap, but it would not be implemented in the nearest feature
