### ISSUE TITLE
Icon positioning incorrect on IE11

### ISSUE THREAD

**Issue by alexanthony** [dmtrKovalenko/material-ui-pickers#222]
## Environment
(Reproducible on https://material-ui-pic.firebaseapp.com/)

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    v1.0.0-beta.15.1      |
| material-ui         |    1.0.0-beta.33     |
| React               |     16.2.0    |
| Browser             |    IE11     |
| Platform            |     Windows 7    |

## Steps to reproduce
1. Open https://material-ui-pic.firebaseapp.com/ in IE11
2. Look at icon
3.

## Expected behavior
Icon positioning should match other browsers

## Actual behavior
Icon is too low

## Live example
![image](https://user-images.githubusercontent.com/1242475/36299724-510cff46-12f6-11e8-9f6c-dc5443508cc9.png)

**Comment by alexanthony** [comment]
Setting height: 48px; on the MUIInputAdornment root fixes this (and doesn't change layout in other browsers).

Also, adornments are further right on IE11, but that's a material-ui issue (also present on https://material-ui-next.com/demos/text-fields/ whereas this one isn't) - width 100% on the input element.

**Comment by dmtrKovalenko** [comment]
I think this issue should be open in the material ui repository

**Comment by alexanthony** [comment]
Raised as https://github.com/mui-org/material-ui/issues/10342
