### ISSUE TITLE
Adornment customization

### ISSUE THREAD

**Issue by markthiessen** [dmtrKovalenko/material-ui-pickers#223]
Liking this library initially - thanks for your work..

It would be a nice improvement if the adornment placement could be configured to be placed on the start instead of forced to the end.

**Comment by dmtrKovalenko** [comment]
You mean keyboard button?

**Comment by markthiessen** [comment]
Yes, exactly

**Comment by cherniavskii** [comment]
Possible solution is adding `InputAdornmentProps` prop to pickers and spread all the props to InputAdornment component. This way we'll let users to do even more with InputAdornment

**Comment by dmtrKovalenko** [comment]
Fixed in rc-1
