### ISSUE TITLE
Provide a "Today" button

### ISSUE THREAD

**Issue by Lysander** [dmtrKovalenko/material-ui-pickers#225]
I would love to have an optional "Today" button at the bottom besides *Cancel* and *Ok* buttons. Clicking this button would lead to the current date. So if you open up a picker with a date far away from the current date, but you want to change to it, you don't have to tediously switch the year, month to pick the current day.

**Comment by tkachenko-tatiana** [comment]
I also think that this feature would be very useful so I would like to take a part in its development.

**Comment by dmtrKovalenko** [comment]
@tkachenko-tatiana ok 👍 
Thanks for contribting approach. Please make sure that new prop would be listed in generated prop types both for date and date time picker. 
And please write unit tests. We are intent on coverage from now :3

**Comment by dmtrKovalenko** [comment]
Done in rc.5
