### ISSUE TITLE
onOpen and onClose handlers

### ISSUE THREAD

**Issue by phazor** [dmtrKovalenko/material-ui-pickers#234]
Feature suggestion: It would be great to have handlers for when the pickers is opened and closed.

As an example use case, one might want to open a picker on the same page as a canvas element, and it could be desirable to pause re-rendering of the canvas while the picker is open.

Env: `material-ui-pickers: v1.0.0-beta.15.1`

**Comment by dmtrKovalenko** [comment]
@phazor I think nice idea, would you like to open a PR.

**Comment by dmtrKovalenko** [comment]
Added in rc-3
