### ISSUE TITLE
null value is making DatePicker act as 1970-01-01

### ISSUE THREAD

**Issue by danieljuhl** [dmtrKovalenko/material-ui-pickers#235]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.1     |
| material-ui         |     1.0.0-beta.35    |
| React               |     16.2.0    |
| Browser             |    N/A     |
| Platform            |      N/A   |

## Steps to reproduce
1. set `minDate` on `DatePicker`
2. set `value` to `null`, to render the input empty
3. open the `DatePicker`

## Expected behavior
I would expect no date to be selected and current view/focus to be on the current month, or at least be able to set it to current month. I would also expect the datepicker to not render the "minDateMessage", as no date has been picked/chosen yet.

## Actual behavior
The input shows the minDateMessage and if I open the DatePicker the current view is januar 1970, though nothing can be picked. Basically it looks like the DatePicker works on a date with the null value, new Date(null) which is equal to 1970-01-01 00:00:00.

If minDate is removed the errors goes away, but the rendering as new Date(null) is still the case.

**Comment by dmtrKovalenko** [comment]
I think it’s reproducing with date-fns utils?

**Comment by danieljuhl** [comment]
Sorry - Yes, its with date-fns

**Comment by dmtrKovalenko** [comment]
Fixed in 1.0.0-rc.2

**Comment by danieljuhl** [comment]
Thanks!
