### ISSUE TITLE
[Docs] How to set locale

### ISSUE THREAD

**Issue by bravecow** [dmtrKovalenko/material-ui-pickers#243]
Please describe how to change default locale using `DateFnsUtils`. Docs En / Fr button doesn't work.

**Comment by dmtrKovalenko** [comment]
Yep :)
Honestly this functionality has not implemented yet. I`m planning to integrated in rc-2

**Comment by AlexSmash** [comment]
No yet? :(

**Comment by dmtrKovalenko** [comment]
Added in rc-3 🎉
