### ISSUE TITLE
'Unknown' appearing in IE11

### ISSUE THREAD

**Issue by krethh** [dmtrKovalenko/material-ui-pickers#245]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    v1.0.0-rc.1     |
| material-ui         |   v1.0.0-beta.35      |
| React               |       16.2.0  |
| Browser             |     IE11    |

## Steps to reproduce
1. In IE11, try to add a Date in the picker.

## Expected behavior
Date should be displayed.

## Actual behavior
"Unknown" appears.

The possible reason for this is in the DateFnsUtils class: the _date_ function uses the constructor of the date class; in all browsers _new Date(10-Jan-2017)_ returns a valid Date. However, in IE11 this returns an "Invalid Date".

**Comment by dmtrKovalenko** [comment]
Would you like to open a PR? 
I have no ability to test on the IE now :(

**Comment by dmtrKovalenko** [comment]
Seems to be not reproducible with rc-3
