### ISSUE TITLE
How to set value by web driver?

### ISSUE THREAD

**Issue by ariesxje** [dmtrKovalenko/material-ui-pickers#249]
Question here:
How do you set value by web drivers (e.g. protractor) while doing automation tests?
something like `element().sendKeys("31/03/2018 10:13 am")`

Thanks

**Comment by dmtrKovalenko** [comment]
@ariesxje I am sorry but I cannot help you there. We are not doing regression, just unit tests.
I just know that there needs to make full cycle of date selection to apply new date. Or use a keyboard mode and add new value to the hhtml input element
