### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier when importing "date-fns-utils"

### ISSUE THREAD

**Issue by fudgecakes** [dmtrKovalenko/material-ui-pickers#250]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    material-ui-pickers@^1.0.0-rc.1     |
| material-ui         |     1.0.0-beta.35    |
| React               |    16.2.0     |
| Browser             |     Chrome    |
| Platform            |    OSX     |

## Steps to reproduce
1. import DateFnsUtils from 'material-ui-pickers/utils/date-fns-utils'

## Expected behavior
I should get no errors

## Actual behavior
I get an error "Uncaught SyntaxError: Unexpected identifier" 
on "import parse from 'date-fns/parse';"

**Comment by dmtrKovalenko** [comment]
You need to instill date-fns@next. 
I’ll point that in the readme

**Comment by fudgecakes** [comment]
I did install date-fns@next, however, still getting the same error. The error is coming from import statements in node_modules. It seems like your js file is not compiled to ES5 and is still using import statements. How would we get around that?

**Comment by dmtrKovalenko** [comment]
@fudgecakes we have released new version of pickers today (rc-2), there import statements was replaced with require.

**Comment by fudgecakes** [comment]
Thanks! everything works now.
