### ISSUE TITLE
Extends moment

### ISSUE THREAD

**Issue by oldwin** [dmtrKovalenko/material-ui-pickers#251]
In the case you are using extends moment (for example moment-timezone) it will have some conflicts, because material-ui-pickers imports moment from node_modules without possibility to pass extended moment directly.

Seems like the way to fix it pass moment to MomentUtils or setup moment in constructor. I can contribute if needed, let me know if you have any ideas or plans to fix it.

Another example it's a locale.
For example in main project you are using locale.

```
import moment from 'moment';
moment.locale('sv');
export default moment;
```

Locale will not work with material-ui-pickers, because it uses node_modules/moment

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  1.0.0-rc.1       |
| material-ui         | 1.0.0-beta.32        |
| React               |  16.2.0       |
| Browser             |  Any       |
| Platform            | MacOS        |

## Steps to reproduce
1. Use moment-timezone in main project.
```
import moment from 'moment-timezone';
moment.tz.setDefault(timezone);
export default moment;
```
2. Using DateTime picker will use your local timezone and have conflicts with current code base
3. As a result your moment logic will have timezone conflict with pickers if you use another timexone then local one.

## Expected behavior
Possibility to pass moment to MomentUtils

## Actual behavior
Using moment from node_modules

**Comment by dmtrKovalenko** [comment]
You can pass already formatted by moment value. 
`value={moment()}`

**Comment by oldwin** [comment]
@dmtrKovalenko I'm trying to use latest rc3 PR now https://github.com/dmtrKovalenko/material-ui-pickers/pull/278. But when I pass `value={moment()}` with defined timezone, calendar uses my local timezone now. In rc2 everything was ok in this case, defined timezone worked good. Any changes to use it in the new way?

**Comment by dmtrKovalenko** [comment]
You can now pass moment as a prop to the MuiPickersProvider

**Comment by dmtrKovalenko** [comment]
Fixed in rc-3
