### ISSUE TITLE
Switch to date-fns but moment is still imported

### ISSUE THREAD

**Issue by appshore** [dmtrKovalenko/material-ui-pickers#253]
The HOC below seems to work as expected however the stats (dev and prod) generated by webpack show that moment-utils and moment are still imported by material-ui-pickers alongside date-fns and date-fns-utils.

"date-fns": "^2.0.0-alpha.7"
"material-ui": "^1.0.0-beta.34"
"material-ui-pickers": "^1.0.0-rc.1"

````
import React from 'react'
import DateFnsUtils from 'material-ui-pickers/utils/date-fns-utils'
import {MuiPickersUtilsProvider} from 'material-ui-pickers'

function withTime(Component) {
    return class extends React.Component {
        render() {
            return (
                <MuiPickersUtilsProvider utils={DateFnsUtils}>
                    <Component {...this.props} />
                </MuiPickersUtilsProvider>
            )
        }
    }
}
export default withTime
````

**Comment by dmtrKovalenko** [comment]
I`m creating a release with fix of that now

**Comment by appshore** [comment]
Thanks!, works like a charm with 1.0.0-rc.2
