### ISSUE TITLE
Can't build with typescript if moment is not installed

### ISSUE THREAD

**Issue by Mario-Eis** [dmtrKovalenko/material-ui-pickers#255]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  rc2  |
| material-ui         |   beta.35   |
| React               |  16.3  |
| Browser             |   chrome   |
| Platform            |  win10  |
| Typescript            |  2.7.1  |

## Steps to reproduce
1. implement date picker like described in the docs
2. Build the project

## Expected behavior
Compilation should finish without warnings or errors.

## Actual behavior

```
[at-loader] ./node_modules/material-ui-pickers/_shared/DateTextField.d.ts:5:24 
    TS2307: Cannot find module 'moment'. 

[at-loader] ./node_modules/material-ui-pickers/_shared/PickerBase.d.ts:1:22 
    TS2307: Cannot find module 'moment'. 

[at-loader] ./node_modules/material-ui-pickers/typings/date.d.ts:1:24 
    TS2307: Cannot find module 'moment'. 
```

## Live example
The picker works, but there are typescript compile errors.

Update: 
The typings have multiple `import { Moment } from 'moment'`; I can see the reason for this. But if moment is imported, it MUST be installed at build time. Even if its not used. I would suggest a generic solution or even an `any` type (if there is REALLY no other solution).
The date implementation is now generic and optional. What is really a cool thing. But so should be the typings.

**Comment by caghand** [comment]
Let me also add that the `labelFunc` property of `<DateTimePicker>` is locked to a `Moment` object, so that's another factor that's blocking TypeScript users. :)

**Comment by dmtrKovalenko** [comment]
Fixed in rc-3
