### ISSUE TITLE
Can't override styles for Year and Day components

### ISSUE THREAD

**Issue by evgeniyannenkov** [dmtrKovalenko/material-ui-pickers#256]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    rc.2    |
| material-ui         |    1.0.0-beta.33     |
| React               |     16.2    |
| Browser             |    Any     |
| Platform            |    MacOS     |

## Steps to reproduce
1. Try to override styles for Date and Year components using material-ui-next theme overrides
```
import { createMuiTheme } from 'material-ui/styles';
export const materialTheme = createMuiTheme({
   MuiPickersCalendarHeader: {
      switchHeader: {
        ...
      },
    },
    Year: {
      root: {
        ...
      },
      selectedYear: {
        ...
      },
    },
    MuiPickersCalendar: {
      calendar: {
        ...
      },
    },
    Day: {
      day: {
        ...
      },
      selected: {
        ...
      },
    },
});
```
## Expected behavior

Styles for this components will be overrided
## Actual behavior

As a result we can't override styles for components Day and Year because they are decorated (withStyles) without `name` option.
 Something like this: 
```
export default withStyles(styles, {name: 'Year'})(Year);
```

**Comment by dmtrKovalenko** [comment]
O-o I didn`t know about such functionality at all.

**Comment by dmtrKovalenko** [comment]
#51 Related issue
Would you like to open a PR?

**Comment by evgeniyannenkov** [comment]
Sure, I'll do this

**Comment by dmtrKovalenko** [comment]
@evgeniyannenkov Does it works for you? Such override of style? Can you please provide a code snippet to help me figure out what have you done? Or just send me a link to material-ui docs page where I can find info about global overrides?
