### ISSUE TITLE
Typescript definitions: TextFieldComponent missing in DateTextFieldProps

### ISSUE THREAD

**Issue by chrumck** [dmtrKovalenko/material-ui-pickers#257]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc.2 |
| material-ui         | 1.0.0-beta.35 |
| React               | 16.2.0 |
| Browser             | Any |
| Platform            | Any  |

## Steps to reproduce
This snippet will return an error in TypeScript:
`<DateTimePicker TextFieldComponent={() => <div></div>}  />
`
## Expected behavior
DatetimePicker should have this property exposed

## Actual behavior
Missing property (might be more than that, I'm just trying to use this one for now)

**Comment by dmtrKovalenko** [comment]
Would you like to open a PR?

**Comment by chrumck** [comment]
Never done that before, but I'll try!

**Comment by dmtrKovalenko** [comment]
Fixed in rc-3
