### ISSUE TITLE
Adding label shifts keyboard icon all the way down

### ISSUE THREAD

**Issue by joergd** [dmtrKovalenko/material-ui-pickers#259]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     1.0.0-rc.2    |
| material-ui         |     1.0.0-beta.31    |
| React               |         |
| Browser             |    Chrome     |
| Platform            |         |

## Steps to reproduce
1. keyboard={true}
2. label={'My date'}
3.

## Expected behavior

To see a label, and to see the keyboard icon

## Actual behavior

I see the label correctly, and I see the keyboard icon - but it is shifted down so it is half way across the textfield input line

**Comment by cherniavskii** [comment]
Can you provide a link to live example?

Also, I don't think material-ui-beta.31 is supported in rc2

**Comment by joergd** [comment]
Ah - upgaded to beat 36 and it solved the problem - thank you!
