### ISSUE TITLE
Extending DateFnsUtils

### ISSUE THREAD

**Issue by danieljuhl** [dmtrKovalenko/material-ui-pickers#262]
I wanted to use DateFnsUtils and change the locale. So far it looks like I have to create a copy of the whole file, to override the `format` call. I had hopped that I could simply override the methods from DateFnsUtils that I needed to modify, and that `format` had been one of them, so that changing locale would be easier.

Is there a reason for not using "own methods" to abstract DateFns and thus giving more control to the application.

**Comment by danieljuhl** [comment]
I think to do the above, we need to create an instance and not use statics. Then we would be able to cal `this.format`, and make it possible to modify it.

**Comment by dmtrKovalenko** [comment]
Actually we will completely redo utils, to use localization. Now you will need to reassign static methods.
```js
DateFnsUtils.format = (date, string) => format(date, string, { locale: 'ua' })
```

**Comment by danieljuhl** [comment]
@dmtrKovalenko are you sure that would work? I already tried that.. as I see it, the problem is, that we don't call DateFnsUtils.format but all calls to format is passed directly to date-fns, and thus my overriding won't change anything.

**Comment by hongyuan1306** [comment]
@danieljuhl you are right that method does not work properly and we have to do now with a custom DateFnsUtils

**Comment by danieljuhl** [comment]
@dmtrKovalenko have you though about a new structure for utils?

**Comment by dmtrKovalenko** [comment]
@danieljuhl #269

**Comment by dmtrKovalenko** [comment]
Fixed in rc-3
