### ISSUE TITLE
Cannot get ref with new withUtilsDateTimePickerWrapper

### ISSUE THREAD

**Issue by wieseljonas** [dmtrKovalenko/material-ui-pickers#265]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    ^v1.0.0-rc.2     |
| material-ui         |    ^1.0.0-beta.34     |
| React               |    ^16.2.0     |
| Browser             |    Chrome     |
| Platform            |         |

## Steps to reproduce
```
              <DateTimePicker
                label="Due date"
                id="datetime-picker"
                autoOk
                innerRef={node => {
                  this.dateTimePicker = node;
                }}
                onChange={this.handleDateTimePickerChange}
                margin="normal"
                fullWidth
                returnMoment={false}
              />
```

## Expected behavior
Should be able to access picker ref to do things like `this.dateTimePicker.wrapper.open();`
## Actual behavior

Get this error 
```
Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.
```

**Comment by dmtrKovalenko** [comment]
Fixed in rc-3
