### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by cranst0n** [dmtrKovalenko/material-ui-pickers#268]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc2       |
| material-ui         | 1.0.0-beta.36        |
| React               |  16.2.0       |
| Browser             |         |
| Platform            |         |

I'm in the process of building a ScalaJS facade for this project an noticed a few type issues thus far:

1. `Utils` interface definition appears to be missing the `isBefore` function
1. `Utils` interface definition defines function as `getWeekDays` but should be `getWeekdays`.

Also, I'm **very** unfamiliar with JavaScript in general but is there a reason why [utils](https://github.com/dmtrKovalenko/material-ui-pickers/blob/da00ff9c44a49982706d7d5af570a42f946ce3c5/lib/src/utils/MuiPickersUtilsProvider.jsx#L6) is expected to be a function? At a glance it seems like you're only calling static functions from whatever object is passed in. Maybe I'm missing something but it's made it awkward to build the ScalaJS facade when it's expecting a function but never actually call it?

Lastly, thanks for your project and hard work!

**Comment by dmtrKovalenko** [comment]
😐 Sorry for type inconvenience. All in JavaScript is a function :)
Because utils now are classes with static methods they are transpilling into functions

**Comment by cranst0n** [comment]
Ok fair enough. Just wanted to check to see if something was a little off. Thanks!
