### ISSUE TITLE
[Help needed] Font size

### ISSUE THREAD

**Issue by darylong** [dmtrKovalenko/material-ui-pickers#270]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  ^1.0.0-rc.2 |
| material-ui         |    ^1.0.0-beta.36    |
| React               |     ^16.2.0   |

Hi, I'm having issue with font size for both the text in DateTimePicker & Input. Both of the font size are too small and I'm unable to find a way to adjust them (show in photo below).

## Font size for text in calendar is too small
![screen shot 2018-03-11 at 10 38 44 pm](https://user-images.githubusercontent.com/29003217/37254792-cc096bd2-257d-11e8-8f78-9e0b6fec139b.png)

## Font size for value is too small
![screen shot 2018-03-11 at 10 38 49 pm](https://user-images.githubusercontent.com/29003217/37254790-cba9d4ce-257d-11e8-96e2-d706d41d83ae.png)

I understand that they are labelClassName and helperTextClassName but I can't seem to change the style for text in calendar and input value. Any feedback or advice is highly appreciated! Thanks in advance :D

**Comment by dmtrKovalenko** [comment]
@darylong Please provide sandbox and try to reproduce it. We are actually depends on material-ui theme, but they are using `em` and `rem` so I can advice you check the font-size of `<html>` tag.

**Comment by dmtrKovalenko** [comment]
@darylong https://material-ui-pickers.dev/guides/css-overrides is an example of how to change styling of any pickers control

**Comment by jmdsg** [comment]
I had the same problem because i use:

```css
html {
  font-size: 62.5%; /* 62.5% of 16px = 10px */
}
```

I solved with this (as shown in material ui documentation):

```javascript
const theme = createMuiTheme({
  typography: {
    // ...
    // Tell Material-UI what's the font-size on the html element is.
    htmlFontSize: 10,
    // ...
  },
});
```

**Comment by dmtrKovalenko** [comment]
It is already fixed in v3

**Comment by ANANDKNIT** [comment]
> @darylong [here](https://material-ui-pickers.firebaseapp.com/guides/css-overrides) is an example of how to change styling of any pickers control

link not found. Please share it again
