### ISSUE TITLE
[Help wanted] How to change background colors

### ISSUE THREAD

**Issue by Pa-OShea** [dmtrKovalenko/material-ui-pickers#273]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   1.0.0-rc.2   |
| material-ui         |  1.0.0-beta.35       |
| React               |  16.2.0       |
| Browser             |   any      |
| Platform            |  win 10       |

How do i change the background colors.
**From**
![image](https://user-images.githubusercontent.com/25669834/37296584-50709964-2613-11e8-94e6-66613482e6d3.png)

**To**
![image](https://user-images.githubusercontent.com/25669834/37296756-d2053412-2613-11e8-8ed2-c72aef93ce90.png)

any help on how to do this would be great

**Comment by Pa-OShea** [comment]
I figured out how to change it to grey, but still not sure how to changed the selected day.

**Comment by Pa-OShea** [comment]
You can change the whole primary colour palette, using createMuiTheme from material-ui/styles. Then wrapping your app or date picker in MuiThemeProvider. 

This can only change the primary colour, as far as i know you cannot change the colour of individual parts of the picker

**Comment by dmtrKovalenko** [comment]
@Pa-OShea [here](https://material-ui-pickers.firebaseapp.com/guides/css-overrides) is an example of how to override particular control

**Comment by Pa-OShea** [comment]
Hello thanks for the reply, this works perfectly with the switch header and toolbar but does not work with the days for some reason

**Comment by dmtrKovalenko** [comment]
@Pa-OShea  Make sure that you are using the newest version. And try to use `backgroundColor` instead of `background`
