### ISSUE TITLE
Unable to select dates NOT in current month (only in chrome)

### ISSUE THREAD

**Issue by alexsinfarosa** [dmtrKovalenko/material-ui-pickers#279]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.3     |
| material-ui         |    1.0.0-beta.37    |
| React               |   16.2.0     |
| Browser             |   Chrome 65.0.3325.162     |
| Platform            |    mac  OS 10.11.6   |

## Steps to reproduce
1. Click on any dates not in the current month
2. Picker defaults to current month
3. Same behavior occurs for past years

## Expected behavior

Clicking on any dates should set the picker to the selected date

## Actual behavior

Clicking on any dates outside the current month sets the picker to a date in the current month

**Comment by dmtrKovalenko** [comment]
Cannot reproduce that, please create a codesandbox.

**Comment by alexsinfarosa** [comment]
Very strange. For some reasons the problem is caused by having DatePicker component inside of material-ui FormControl component. I replaced the FormControl component with a div, keeping the same css, and now it works.

**Comment by dmtrKovalenko** [comment]
@alexsinfarosa Oops sorry, we have several similar issues #217
