### ISSUE TITLE
Input Icon

### ISSUE THREAD

**Issue by salamaashoush** [dmtrKovalenko/material-ui-pickers#28]
is there is a way to provide an icon for the input something like ``<InputAdornment />`` in material UI input

**Comment by dmtrKovalenko** [comment]
Hi, yeah it would be really nice feature, so I will add it in the nearest release (alpha 12)

**Comment by dmtrKovalenko** [comment]
Hi, about your proposal. It would work for any version of material-ui-picker, because material-ui TextField has an ability to pass the icon to input 
Please refer
```jsx
<DatePicker
   InputProps={{
      endAdornment: (
        <InputAdornment position="end">
           <IconButton>  add_alarm  </IconButton>
        </InputAdornment>
     )
  }}
/>
```
Also I`ve add this example to the demo
