### ISSUE TITLE
DisableFuture includes today as well (only occurs with date-fns)

### ISSUE THREAD

**Issue by alexsinfarosa** [dmtrKovalenko/material-ui-pickers#280]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.3     |
| material-ui         | 1.0.0-beta.37        |
| React               |    16.2.0     |
| Browser             |   Chrome 65.0.3325.162      |
| Platform            |    mac OS 10.11.6     |

## Steps to reproduce
It seems the occur only with date-fns
1. add 'disableFuture' to picker

## Expected behavior

Today should be selectable from the picker

## Actual behavior

Today cannot be selected from the picker. It is included in the future.

## Live example
To test, add disableFuture prop to the picker in both examples below

Here moment is used: https://codesandbox.io/s/23qqkp07wp
Here date-fns is used: https://material-ui-pickers.firebaseapp.com/usage

**Comment by dmtrKovalenko** [comment]
But its selectable both with moment in your example and on the docs website with date-fns used. 😕

**Comment by alexsinfarosa** [comment]
Yes, it is working for me as well now. Sorry!
