### ISSUE TITLE
[Feature request] Custom arrow component prop

### ISSUE THREAD

**Issue by RusinovAnton** [dmtrKovalenko/material-ui-pickers#284]
Hello, Dmitriy. Thanks for nice components!

Currently we're not using icon font with material-ui but only `<SvgIcons />`, so calendar is now looks broken for our app. It would be nice to have option to provide icon component instead of just name of icon for icon font based `<Icon />`. I would like to work on PR for this if you find this worth to merge.

**Comment by dmtrKovalenko** [comment]
@RusinovAnton You can pass directly a component like its doing in a custom example [here](https://material-ui-pickers.firebaseapp.com/demo/datetimepicker)
