### ISSUE TITLE
Make it easier or document how to customize utils

### ISSUE THREAD

**Issue by charlax** [dmtrKovalenko/material-ui-pickers#285]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  1.0.0-rc.3       |

## Description

I might take a stab at a PR to fix this, creating an issue to start the discussion.

You often need to modify the utils class' functionality. For instance, the default display of the header makes no sense in French locale:

![image](https://user-images.githubusercontent.com/120501/37651747-872f2278-2c39-11e8-9390-793817bfc375.png)

This way of displaying the date is not idiomatic, in French it is very uncommon to abbreviate the day like this. So I replaced it by monkey patching the `getDatePickerHeaderText` method:

```
MomentUtils.prototype.getDatePickerHeaderText = date => {
  return date.format('D MMM YYYY');
};
```

![image](https://user-images.githubusercontent.com/120501/37651858-d9c43e06-2c39-11e8-9322-507886d0fe57.png)

**Comment by dmtrKovalenko** [comment]
@charlax thank you! Will do it :)
