### ISSUE TITLE
Option to clear value or at least callback on Cancel

### ISSUE THREAD

**Issue by reszli** [dmtrKovalenko/material-ui-pickers#29]
Hello,

first of all, thanks for these cool pickers!

I'm working on a personal project listing some data with @devexpress/dx-react-grid
and trying to use the date picker as a filter and edit widget for a date column
![screenshot-budget reszli-3000-2017-11-02-15-29-56-701](https://user-images.githubusercontent.com/112797/32328482-c977a0ba-bfe2-11e7-8918-61f884f29d01.png)

when I use it for the filter, I would like to be able to clear the value selected previously
for that I would think it would be best to have a Clear button next to Cancel and OK conditioned by a prop, plus having a callback called onClear, similar to onChange, would do the trick

I'd like to have your opinion on this, as I'm new to react

thanks,
Reszli

**Comment by dmtrKovalenko** [comment]
Hi, yes I think it would be nice feature, to have "Clear" button as action. 
Would you like to open a pull request?

**Comment by reszli** [comment]
I think I just did, although I'm new to github as well :)

**Comment by cherniavskii** [comment]
Closed by #143
