### ISSUE TITLE
Select doesn't work inside FormControl

### ISSUE THREAD

**Issue by markthiessen** [dmtrKovalenko/material-ui-pickers#298]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.4     |
| material-ui         |     1.0.0-beta.38    |
| React               |    16.2.0     |
| Browser             |     Chrome, IE11    |
| Platform            |     Windows    |

## Steps to reproduce
1. Wrap DatePicker in material-ui FormControl
2. Click the field to open the DatePicker
3. Select a date, click OK  

## Expected behavior
The selected date should be the new value.

## Actual behavior
The current date is the value regardless of which date was selected.
Also, if you navigate back through months, clicking the next month button skips several months and navigates to the current month + 1.

## Live example
https://codesandbox.io/s/m574q3l8mx

**Comment by dmtrKovalenko** [comment]
Why do you need to wrap it in form control. It’s already a form control

**Comment by markthiessen** [comment]
You're right, I don't need it.. I was doing some customization of the label and FormControl gave me some more consistent spacing. 

I can work around and It's working fine without it, but it took a while to find what was causing the issue.

**Comment by dmtrKovalenko** [comment]
OK that’s not the first such issue. I will see how to add this info. Maybe FAQ?
