### ISSUE TITLE
MuiPickersUtilsProvider and React Router

### ISSUE THREAD

**Issue by rvanmil** [dmtrKovalenko/material-ui-pickers#301]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc.4 |
| material-ui         | 1.0.0-beta.37 |
| React               | 16.2.0 |
| Browser             | electron 1.8.4 |
| Platform            | macOS 10.13.3 |

## Steps to reproduce
Use `MuiPickersUtilsProvider` as a child somewhere below `Router`, for example:

```
ReactDOM.render(
  <Provider store={store}>
    <MemoryRouter>
      <MuiThemeProvider theme={theme}>
        <MuiPickersUtilsProvider utils={MomentUtils}>
          <AppContainer/>
        </MuiPickersUtilsProvider>
      </MuiThemeProvider>
    </MemoryRouter>
  </Provider>,
  document.getElementById('app')
)
```

## Expected behavior
The router should still work.

## Actual behavior
The router no longer works because `MuiPickersUtilsProvider` is blocking updates, due to it being a PureComponent (see: https://reacttraining.com/react-router/web/guides/dealing-with-update-blocking)

## Live example
https://codesandbox.io/s/7y09n1pj6x

**Comment by rvanmil** [comment]
I'm not sure whether this is an issue, or just the way you're supposed to use react-router with other HOC's. Either way, I thought it would be a good idea to document and/or discuss this in an issue. As can be seen in the live example, moving the router down the child tree fixes the problem.

**Comment by dmtrKovalenko** [comment]
rc.5

**Comment by rvanmil** [comment]
Thanks 👍

**Comment by matdurand** [comment]
The fix for this issue has been lost in in RC9, so I created a PR to re-apply it.

**Comment by GaddMaster** [comment]
Hello . 

I get this failed prop type and cannot fix properly 

I think its a bug

Warning: Failed prop type: Invalid prop `variant` of value `h4` supplied to `Typography`, expected one of ["display4","display3","display2","display1","headline","title","subheading","body2","body1","caption","button"].
    in Typography (created by WithStyles(Typography))
    in WithStyles(Typography) (created by ToolbarButton)
    in ToolbarButton (created by WithStyles(ToolbarButton))
    in WithStyles(ToolbarButton) (created by DatePicker)
    in div (created by Toolbar)
    in Toolbar (created by WithStyles(Toolbar))
    in WithStyles(Toolbar) (created by PickerToolbar)
    in PickerToolbar (created by WithStyles(PickerToolbar))
    in WithStyles(PickerToolbar) (created by DatePicker)
    in DatePicker
    in WithUtils(DatePicker) (created by BasePicker)
    in div (created by DialogContent)
    in DialogContent (created by WithStyles(DialogContent))
    in WithStyles(DialogContent) (created by ModalDialog)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by Dialog)
    in Transition (created by Fade)
    in Fade (created by WithTheme(Fade))
    in WithTheme(Fade) (created by Dialog)
    in RootRef (created by Modal)
    in div (created by Modal)
    in Portal (created by Modal)
    in Modal (created by WithStyles(Modal))
    in WithStyles(Modal) (created by Dialog)
    in Dialog (created by WithStyles(Dialog))
    in WithStyles(Dialog) (created by ModalDialog)
    in ModalDialog (created by WithStyles(ModalDialog))
    in WithStyles(ModalDialog) (created by ModalWrapper)
    in ModalWrapper (created by BasePicker)
    in BasePicker
    in WithUtils(BasePicker) (created by DatePickerModal)
    in DatePickerModal
    in div (at Reports.jsx:394)
    in MuiPickersUtilsProvider (at Reports.jsx:393)
    in div (at Reports.jsx:392)
    in div (at Reports.jsx:391)
    in div (at Reports.jsx:376)
    in div (at Reports.jsx:347)
    in div (at Reports.jsx:346)
    in div (at Reports.jsx:344)
    in Reports (created by Route)
    in Route (created by withRouter(Reports))
    in withRouter(Reports) (created by Connect(withRouter(Reports)))
    in Connect(withRouter(Reports)) (created by Route)
    in Route (at Routes.jsx:19)
    in Switch (at Routes.jsx:17)
    in div (at Routes.jsx:15)
    in Routes (at App.jsx:161)
    in div (at App.jsx:158)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App.jsx:157)
    in div
    in FullScreen (at App.jsx:156)
    in App (created by windowSize(App))
    in windowSize(App) (created by Connect(windowSize(App)))
    in Connect(windowSize(App)) (at index.js:11)
    in Provider (at index.js:10)

**Comment by GaddMaster** [comment]
Hi . Where would be place repor bug ? for this package ?

**Comment by dmtrKovalenko** [comment]
@GaddMaster you must update material-ui version and use next variants version to fix that

**Comment by GaddMaster** [comment]
@dmtrKovalenko I changed the version to newest in package json
"@material-ui/core": "^3.7.1",
and running "yarn" now.
I don't know what you mean by use "next variants version"

**Comment by dmtrKovalenko** [comment]
https://material-ui.com/style/typography/#migration-to-typography-v2

**Comment by GaddMaster** [comment]
@dmtrKovalenko Issues resolved after updated like you explained btw. Thanks
