### ISSUE TITLE
Controlled DatePicker shows InputMask when cleared

### ISSUE THREAD

**Issue by FranBran** [dmtrKovalenko/material-ui-pickers#306]
1. Manipulate input by keyboard on a controlled DatePicker
2. reset input from "outside"

result: the mask is shown and overlaps the label

Reproducable on Demo-Page:

![animation](https://user-images.githubusercontent.com/1215407/38022989-606a1ffa-3281-11e8-9ae2-454dc8dd1664.gif)

**Comment by alexander-morozov** [comment]
@FranBran try to use function that return mask instead of string
It helped me.

`getMask = (value) => {
    return value ? this.props.mask : []
  }`

**Comment by dmtrKovalenko** [comment]
@alexander-morozov would you like to open a PR?

**Comment by alexander-morozov** [comment]
@dmtrKovalenko It doesn't need any code changes. Just pass function instead of value to mask prop.

https://github.com/text-mask/text-mask/blob/master/componentDocumentation.md#readme
See mask function section

**Comment by dmtrKovalenko** [comment]
We have not fixed that, just add example how to handle such situation in docs
