### ISSUE TITLE
Documentation link in readme.md doesn't work

### ISSUE THREAD

**Issue by nighk** [dmtrKovalenko/material-ui-pickers#308]
The documentation link to https://material-ui-pickers.firebaseapp.com/ in the main Readme.md file returns a 404

**Comment by dmtrKovalenko** [comment]
О_о

**Comment by dmtrKovalenko** [comment]
Can you please add a screen, share your browser, because for me it opens properly.

**Comment by nighk** [comment]
Ah it may be the network I am on then, as I connect through a proxy which may be blocking the link. It is impossible to tell which one is the issue. If it works ok for you I will try it on my homenetwork later.

Thanks for checking though :-)
