### ISSUE TITLE
Datepicker showing labels 'ev' and 'ke' instead of icons by default

### ISSUE THREAD

**Issue by abubberman** [dmtrKovalenko/material-ui-pickers#309]
The DatePicker component is not showing the  icons for keyboard/leftArrowIcon/rightArrowIcon. (See screenshot)
![image](https://user-images.githubusercontent.com/13328911/38077605-d093f478-3339-11e8-9bab-16f2d3a02fb0.png)
 
![image](https://user-images.githubusercontent.com/13328911/38077591-c16c1e62-3339-11e8-9762-2887982249a9.png)

I need to a to assign the icons like below:
```javascript
  <DatePicker
            autoOk={true}
            keyboard={true}
            value={selectedDate}
            onChange={this.handleDateChange}
            leftArrowIcon={<ChevronLeftIcon />}
            rightArrowIcon={<ChevronRightIcon />}
            keyboardIcon={<TodayIcon />}
            cancelLabel="Annuleren"
          />
````

Is this expected behavior?? 

I'm using version 1.0.0-rc.4

**Comment by dmtrKovalenko** [comment]
From documentation: 
And the last step of installation would be an icon font. By default we relying on material-icons font, but its possible to override any icons with a help of corresponding props.

```html 
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```

**Comment by abubberman** [comment]
Thanks for the quick response. I missed that part of the documentation
