### ISSUE TITLE
How can I change the calendar day format?

### ISSUE THREAD

**Issue by abubberman** [dmtrKovalenko/material-ui-pickers#310]
How can I change the calendar day format? In my case, i want to change '**woe, sep 19**' to '**wo 19 sep**'.

![image](https://user-images.githubusercontent.com/13328911/38079463-40eb976c-333f-11e8-85f5-5712d5fa8555.png)

**Comment by dmtrKovalenko** [comment]
Check out corresponding [documentation section](https://material-ui-pickers.firebaseapp.com/guides/formats)

**Comment by abubberman** [comment]
Thnx, will have a look!

**Comment by abubberman** [comment]
I'm trying to implement the sample in my code, but Typescript is complaining that 'DateFnsUtils' is not a constructor function type.  I'm probably missing something...?

```javascript
import DateFnsUtils from 'material-ui-pickers/utils/date-fns-utils';

class LocalizedUtils extends DateFnsUtils {
  getDatePickerHeaderText(date: Date) {
    return format(date, 'D MMM YYYY', { locale: this.locale });
  }
}
```

**Comment by dmtrKovalenko** [comment]
But its a constructor type https://github.com/dmtrKovalenko/material-ui-pickers/blob/master/lib/src/utils/date-fns-utils.js

Hmm I will check it when have a chance

**Comment by abubberman** [comment]
What seems to work is moving the d.ts files in a separate folder.

![image](https://user-images.githubusercontent.com/13328911/38082358-b5f71d90-3346-11e8-9ffe-c8faf41f05ce.png)

**Comment by dmtrKovalenko** [comment]
@abubberman you just disable ts definitions.

**Comment by abubberman** [comment]
yes.. you're correct... my conclusion was a bit to fast.

**Comment by abubberman** [comment]
indeed.. typing is disabled now..

**Comment by dmtrKovalenko** [comment]
Fix will appear in the nearest release

**Comment by abubberman** [comment]
Thanks for fixing! When is the nearest release?

**Comment by dmtrKovalenko** [comment]
@abubberman I hope at the beginning of next week

**Comment by abubberman** [comment]
ok, thnx!
