### ISSUE TITLE
How to remove OK and cancel buttons on Datepicker?

### ISSUE THREAD

**Issue by elzaresen** [dmtrKovalenko/material-ui-pickers#311]

**Comment by dmtrKovalenko** [comment]
There is no way. And we will not add such functionality. If you need so you can import directly `<DatePicker />` component and make your own modal. (`/DatePicker/DatePicker`)

**Comment by Brahimhz** [comment]
app.css : 

.MuiDialogActions-root.css-knqc4i-MuiDialogActions-root {
  display: none;
}
