### ISSUE TITLE
Wrong caret position on clearable masked input

### ISSUE THREAD

**Issue by alexander-morozov** [dmtrKovalenko/material-ui-pickers#314]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc.4 |
| material-ui         | 1.0.0-beta.38 |
| React               | 16.0.0 |
| Browser             | Chrome |

## Conditions
Datepicker should be clearable and with mask

## Steps to reproduce
1. Clear value
2. Set valid value

## Expected behavior
Cursor stays after text

## Actual behavior
Cursor moves inside text

## Live example

Reproducable on Demo-Page (Keyboard Input):

![wrong_caret_position](https://user-images.githubusercontent.com/32906351/38093808-bbee0b72-3374-11e8-8a31-759b1ac2f70d.gif)

**Comment by dmtrKovalenko** [comment]
As I have tried to reproduce that - got this feature is really minor and would be more effort to fix this issue then do nothing. 
If somebody also stacking out of that - please let me know and I`ll fix it
