### ISSUE TITLE
Warning: React does not recognize the `inputRef` prop on a DOM element.

### ISSUE THREAD

**Issue by shubham81407** [dmtrKovalenko/material-ui-pickers#318]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-beta.13.1     |
| material-ui         |     1.0.0-beta.32    |
| React               |   16.2.0      |
| Browser             |    Chrome     |
| Platform            |   Ubuntu16.04      |

## Expected behavior

No console errors
## Actual behavior

Warning: React does not recognize the `inputRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by dmtrKovalenko** [comment]
Please update to the newest version (v1.0.0-rc.4)
