### ISSUE TITLE
A statically position picker ?

### ISSUE THREAD

**Issue by iamdanthedev** [dmtrKovalenko/material-ui-pickers#330]
Hello Dmitry and thanks for awesome work

Do you think there is a possibility of having a picker embedded into the page somehow? I mean inline style..

Thank

**Comment by dmtrKovalenko** [comment]
Yes it’s possible by importing directly datepicker instead of wrapper. I think we should document this. I’ll send you an example bit later

**Comment by cherniavskii** [comment]
@iamdanthedev here's an example: https://codesandbox.io/s/m5n7jjzx1x

@dmtrKovalenko we should definitely document this!
Also it would be great to unify pickers API - currently picker receives date in `value` prop, but picker without wrapper (like `DatePicker/DatePicker`) has `data` prop instead, which may be confusing (and it *was* confusing for me, when I was trying to create example above).
What do you think?

**Comment by dmtrKovalenko** [comment]
Yep I think it’s also related to the refactoring base picker to hoc. When we do that it would be easy to render any part of picker independently

**Comment by dmtrKovalenko** [comment]
https://material-ui-pickers.firebaseapp.com/guides/static-pickers

**Comment by tpmh31292** [comment]
@dmtrKovalenko @cherniavskii 
How do I import the DatePicker directly instead of a wrapper in v3?
This code sand box is v2. https://codesandbox.io/s/m5n7jjzx1x
