### ISSUE TITLE
Using JSS provider breaks styling/alignment of DateTimePicker

### ISSUE THREAD

**Issue by Maher4Ever** [dmtrKovalenko/material-ui-pickers#338]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  1.0.0-rc.5 |
| material-ui         |  1.0.0-beta.41  |
| React               | 16.3.1 |
| Browser             |  Chrome  65.0.3325.181 (64bit) |
| Platform            |   macOS High Sierra   |

## Steps to reproduce
1. Wrap the `MuiPickersUtilsProvider` with a `JssProvider`
2. Add a `DateTimePicker` somewhere in your app

## Expected behavior
The DateTime picker doesn't take the full high of the window and looks normal as it does in the examples. 

## Actual behavior
The DateTime picker takes the entire height of the window. Also, only half of the the minutes selector is shown.

![screen shot 2018-04-08 at 17 49 48](https://user-images.githubusercontent.com/277764/38469465-8ef0824c-3b55-11e8-9de8-810be6654d6b.png)
![screen shot 2018-04-08 at 17 50 04](https://user-images.githubusercontent.com/277764/38469466-8f08abb0-3b55-11e8-84a6-e97bad922de6.png)
![screen shot 2018-04-08 at 17 50 11](https://user-images.githubusercontent.com/277764/38469467-8f1f96ae-3b55-11e8-9dc7-6b0371e9e7c6.png)

## Live example
https://codesandbox.io/s/k9xon2424v

**Comment by cherniavskii** [comment]
You are using rc4 in your demo, which works fine, but with rc5 it looks like you described

**Comment by cherniavskii** [comment]
And indeed, without `JssProvider` it works fine

**Comment by cherniavskii** [comment]
Ok, I figured out how to avoid that behavior.
You need to pass `createGenerateClassName` to `jss` instance.
Here's how to do that:

```
import jssPreset from 'material-ui/styles/jssPreset';
import createGenerateClassName from 'material-ui/styles/createGenerateClassName';

const jss = create(jssPreset());
jss.options.createGenerateClassName = createGenerateClassName;

...

<JssProvider jss={jss}>
```

That being said, I have no idea why it doesn't work without passing `createGenerateClassName` option :/

@dmtrKovalenko any ideas?

**Comment by cherniavskii** [comment]
@Maher4Ever here's your example, updated with code above:
https://codesandbox.io/s/8l7lv044w8

**Comment by Maher4Ever** [comment]
@cherniavskii Good catch! While trying to figure out what was happening I also saw that it works with RC4. MUI have been introducing a lot of breaking changes lately so the issue might be caused by one of them. Anyhow, I updated the URL to a demo using RC5.

**Comment by cherniavskii** [comment]
@dmtrKovalenko is it resolved somehow? I posted a workaround above, but it doesn't resolve issue itself :/

**Comment by dmtrKovalenko** [comment]
It should be resolved by unmounting clocks on fade out, didn’t it?

**Comment by cherniavskii** [comment]
Didn't know it's related to Fade, thanks for the info ;)
I'll try out rc6 later to make sure it is fixed

**Comment by cherniavskii** [comment]
Any thought what is the root of this issue?
From where I stand, `createGenerateClassName` option should not impact styles at all

**Comment by dmtrKovalenko** [comment]
Is this issue is still related? I will close it due to inactivity. But if its an issue feel free to ask for reopen. If we cannot fix it - will add it to the FAQ
