### ISSUE TITLE
MomentUtils getYearRange

### ISSUE THREAD

**Issue by alexander-morozov** [dmtrKovalenko/material-ui-pickers#340]
## Steps to reproduce
1. set minDate 'Jan 2 2017'
2. set maxDate 'Jan 1 2018'

## Expected behavior
2017 and 2018 years are available to select

## Actual behavior
only 2017 year is available to select in years picker

The main reason is that momentUtils.getYearRange returns only 2017 year in case above

**Comment by cherniavskii** [comment]
Here's an example: https://codesandbox.io/s/j7pvn7v4jy

P.S. Please include an example next time, it will save a lot of time for us ;)

**Comment by dmtrKovalenko** [comment]
Fixed in rc.7
