### ISSUE TITLE
Keyboard-Button position differs among browsers

### ISSUE THREAD

**Issue by FranBran** [dmtrKovalenko/material-ui-pickers#344]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    rc.5     |
| material-ui         |   latest      |
| React               |   latest      |
| Browser             |   IE11, Chrome      |
| Platform            |     win8    |

Keyboard-Button positioning differs among browsers (IE11, Chrome)

## Live example
From Demo-Page:
IE11:
![grafik](https://user-images.githubusercontent.com/1215407/38551697-2800adb2-3cba-11e8-9502-27161a55d4b5.png)

Chrome:
![grafik](https://user-images.githubusercontent.com/1215407/38551722-3744a7a6-3cba-11e8-8eb2-03e35013dd14.png)

Using FontAwesome for keyboard-button makes things worse for IE11:
![grafik](https://user-images.githubusercontent.com/1215407/38551903-b393eccc-3cba-11e8-8aa5-e83afce377c6.png)

**Comment by dmtrKovalenko** [comment]
We are using material-hi’s input adornment. So please refer to such issues in material-ui repo
