### ISSUE TITLE
DatePicker doesn't work when inside the FormControl element

### ISSUE THREAD

**Issue by tjaskula** [dmtrKovalenko/material-ui-pickers#348]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   ^1.0.0-rc.5      |
| material-ui         |    ^1.0.0-beta.40     |
| React               |     16.2.0    |
| Browser             |    Chrome Version 65.0.3325.181 (Build officiel) (32 bits)     |
| Platform            |         |

## Steps to reproduce
1. Embed DatePicker inside FormControl.
2. Open the picker
3. Select a date different that is selected by default
4. Make the focus is lost from the selected day by clicking for example on the white background of the popup (clicking on buttons has the same effect but you cannot see what happens as the popup closes)
5. See that the selections goes back to the default selection

## Expected behavior

Step 5, the new selection should be kept.

## Actual behavior

Step 4, makes the selection beeing lost to the default value selected when popups opens

## Live example

https://codesandbox.io/s/741wynl36j

**Comment by ekv88** [comment]
And you cant change month when DatePicker is inside FormControl!

**Comment by cherniavskii** [comment]
See https://github.com/dmtrKovalenko/material-ui-pickers/issues/287#issuecomment-374694268
