### ISSUE TITLE
Can't resolve 'date-fns/addDays'

### ISSUE THREAD

**Issue by LucasSeveryn** [dmtrKovalenko/material-ui-pickers#349]
./node_modules/material-ui-pickers/utils/date-fns-utils.js
Module not found: Can't resolve 'date-fns/addDays' in 'C:\FrontEnd\node_modules\material-ui-pickers\utils'

getting this error when trying to compile

**Comment by Peretz30** [comment]
Hey, did you fixed this issue? I had the same error.

**Comment by cherniavskii** [comment]
@Peretz30 use `date-fns` 2.x, instead of 1.x
