### ISSUE TITLE
Add month picker

### ISSUE THREAD

**Issue by idrm** [dmtrKovalenko/material-ui-pickers#355]
Currently, inside a date picker you can click on the year and select a new one from a pop-up list. It would be handy to have a similar feature for months as well (as is, if the picker is showing June and you want to select a date in December you have to click on the left/right arrows half a dozen times to get there).

**Comment by cherniavskii** [comment]
Hi,
While such feature may be useful in some use cases, it is not covered by [Material Design Guidelines](https://material.io/guidelines/components/pickers.html)

**Comment by dmtrKovalenko** [comment]
@idrm @cherniavskii as was mentioned it is not covered by md natively - we will not make such feature because from where I stand it is not so user friendly as seems.
