### ISSUE TITLE
feature/fix: return a new moment.js object onChange

### ISSUE THREAD

**Issue by adeelshahid** [dmtrKovalenko/material-ui-pickers#360]
When using moment.js return a new moment.js object rather then same object which was passed in as value to the **DatePicker**. Because settings the same value returned on change to state for most people would not trigger _render_

**Comment by dmtrKovalenko** [comment]
The moment is mutable by default. Thats an a global issue of moment, so if you need so you need to add `.clone()` before writing to the state by yourself

**Comment by dmtrKovalenko** [comment]
Or just use luxon or date-fns 😅

**Comment by adeelshahid** [comment]
not everyone will figure out this is bug and waste time :(
