### ISSUE TITLE
onError() does not get called in case of invalid date typed in keyboard

### ISSUE THREAD

**Issue by manastaldi** [dmtrKovalenko/material-ui-pickers#363]
Use case 

I have a "Save" button in my page which I want to disable as long as the date typed in the DatePicker is not valid. So I want to set one error flag in state which will be used to disable/enable the "Save" button. The DatePicker field is not an mandatory field though. I thought of using onError() to set the error flag in case user typed wrong date (could be the format is not correct or its out side of min and max date), but the function does not get called. I see only error message below the field.

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   1.0.0-rc.3
| material-ui         |   1.0.0-beta.36
| React               |       16.2.0
| Browser             |       Chrome Version 65.0.3325.146
| Platform            |        Windows

## Steps to reproduce
1.
2.
3.

## Expected behavior
onError() should be called whenever the date entered through keyboard is not correct 

## Actual behavior
onError() does not get called

Also if I type any value outside of max date it does not give any error. For e.g. if I have set max date as 01-01-2200 and I type 2200123 for the year field then I dont see any error message below the field

I am using following code snippet

            <MuiPickersUtilsProvider utils={DateFnsUtils}>
                <div className={this.props.classes.dateSelector}>
                    <DatePicker
                        keyboard
                        value={selectedDate}
                        invalidDateMessage={"Date is not in 'DD MMM YYYY' format"}
                        minDateMessage={"Date can not be earlier than 01 Jan 1900"}
                        maxDate={'2200-01-01'}
                        maxDateMessage={"Date can not be further than 01 Jan 2200"}
                        onError={this.handleError} 
                        label={this.props.label}
                        format="DD MMM YYYY"
                        onChange={this.handleDateChange} />
                </div>
            </MuiPickersUtilsProvider>

**Comment by dmtrKovalenko** [comment]
It is actually called with rc.7
