### ISSUE TITLE
I am still facing same issue in #362 how to fix

### ISSUE THREAD

**Issue by anilljoshi** [dmtrKovalenko/material-ui-pickers#365]
https://github.com/dmtrKovalenko/material-ui-pickers/issues/362

**Comment by dmtrKovalenko** [comment]
Update react and react-dom packages to 16.3.0

**Comment by anilljoshi** [comment]
I have updated my react and react-dom to 16.3.0 but still facing same issue

**Comment by cherniavskii** [comment]
@anilljoshi help us to help you - please submit a new issue with description and reproducible example.
And please, do *not* ignore issue template

**Comment by anilljoshi** [comment]
@cherniavskii Sorry for disturb but its working fine in codesandbox  https://codesandbox.io/s/7z837z07oq but its showing error in my app

**Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.**


pointing follwing code in 

function invariant(condition, format, a, b, c, d, e, f) {
  validateFormat(format);

  if (!condition) {
    var error;
    if (format === undefined) {
      error = new Error('Minified exception occurred; use the non-minified dev environment ' + 'for the full error message and additional helpful warnings.');
    } else {
      var args = [a, b, c, d, e, f];
      var argIndex = 0;
      error = new Error(format.replace(/%s/g, function () {
        return args[argIndex++];
      }));
      error.name = 'Invariant Violation';
    }

    error.framesToPop = 1; // we don't care about invariant's own frame
    throw error;
  }
}
