### ISSUE TITLE
Error message when disablePast is enabled and value is set to null

### ISSUE THREAD

**Issue by cherniavskii** [dmtrKovalenko/material-ui-pickers#368]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   rc.6    |
| material-ui         |  beta.42    |
| React               |   16.2.0   |
| Browser             |   every    |
| Platform            |         |

## Steps to reproduce
1. Enable `disablePast` option
2. Set picker's value to `null` (or use `Clear` button)

## Expected behavior

No error message under picker input

## Actual behavior

Error message appears: "Date should not be before minimal date"

## Live example
https://codesandbox.io/s/r5p5zqx7z4

**Comment by dmtrKovalenko** [comment]
:(
