### ISSUE TITLE
Prop type warnings when passing own icons for picker

### ISSUE THREAD

**Issue by lostpebble** [dmtrKovalenko/material-ui-pickers#37]
Hi there,

Thanks for putting this together!

I'm currently using the `DatePicker` component and it's working pretty great, but what I've noticed popping up in my console is a bunch of warnings such as:

```
Warning: Failed prop type: Invalid prop `leftArrowIcon` of type `object` supplied to `DatePickerWrapper`, expected `string`.
    in DatePickerWrapper
```

I'm passing in icons to the DatePicker from the `material-ui-icons` package like so:

```
import LeftArrowIcon from "material-ui-icons/KeyboardArrowLeft";

<DatePicker
    ...
    leftArrowIcon={<LeftArrowIcon />}
/>
```

As mentioned, it works perfectly fine and the icons are showing up nicely. I tried passing in the icons as just object, like `{LeftArrowIcon}`, but that doesn't work. So I think it may just be something wrong with your prop validation.

**Comment by dmtrKovalenko** [comment]
Fixed in [v1.0.0-alpha.13](https://github.com/dmtrKovalenko/material-ui-pickers/releases/tag/1.0.0-alpha.13)
