### ISSUE TITLE
Unable to delete the first character in keyboard mode

### ISSUE THREAD

**Issue by jankei** [dmtrKovalenko/material-ui-pickers#379]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   v1.0.0-rc.6     |
| material-ui         |    1.0.0-beta.34     |
| React               |    16.3.2     |
| Browser             |    Chrome     |

## Steps to reproduce
1. Enter a character in keyboard mode
2. Try deleting with backspace 

## Expected behavior
You should be able to delete the character

**This issue does not occur when using the mask attribute**

**Comment by dmtrKovalenko** [comment]
Cannot reproduce this issue, pls update to rc.7 and try to reproduce - if so create live example on codesandbox

**Comment by jankei** [comment]
https://codesandbox.io/s/rlqpv49ly4 try to erase

**Comment by dmtrKovalenko** [comment]
Thats really strange :)
Because on the docs website everything works fine

**Comment by jankei** [comment]
It might have to do with the mask attribute that is works
