### ISSUE TITLE
Cant resolve material-ui/Button

### ISSUE THREAD

**Issue by Return-1** [dmtrKovalenko/material-ui-pickers#382]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  1.0.0-rc.7 |
| material-ui         |  0.20.0   |
| React               |  16.2.0  |

## Steps to reproduce
1. Install the npm package
2. Add `MuiPickersUtilsProvider` and its corresponding `MomentUtils`
3. Simply `import { DatePicker } from 'material-ui-pickers'`;

##Error
```
Failed to compile.

./node_modules/material-ui-pickers/_shared/ModalDialog.js
Module not found: Can't resolve 'material-ui/Button' in '/Users/georgeavgoustis/Desktop/PROJECTS/novoville_webapp2/node_modules/material-ui-pickers/_shared'
```

Am i missing an installation step?

**Comment by dmtrKovalenko** [comment]
Yes, this package is actually for material-ui v1. Do `npm i material-ui@next`
