### ISSUE TITLE
Provided utils and locale changes are not received in pickers inside components using shouldComponentUpdate 

### ISSUE THREAD

**Issue by Mario-Eis** [dmtrKovalenko/material-ui-pickers#383]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |rc7|

## Steps to reproduce
Set up like in docs and change locale prop

## Expected behavior
date-picker should re-render with new locale settings

## Actual behavior
date-picker won't recognize locale changes, MuiPickersUtilsProvider doesn't create a new Utils instance. I also found out, that MuiPickersUtilsProvider uses the legacy Provider API and it seems it doesn't pass down locale changes at all.

**Comment by dmtrKovalenko** [comment]
But but - it works...

**Comment by dmtrKovalenko** [comment]
How did you get that out?

**Comment by Mario-Eis** [comment]
Right. I just created a sandbox and it seems to work correctly indeed.
I tried to do a custom implementation of Utils using date-fns for calculation and globalize.js for i18n. Maybe I did something wrong. I'm on it...

**Comment by Mario-Eis** [comment]
Sandbox is here: https://codesandbox.io/s/mq3xl413jy
It's still broken in my setup. Need some further investigation.

**Comment by Mario-Eis** [comment]
wrapping the picker inside the reduxForm() hoc breaks the updates in my case

**Comment by Mario-Eis** [comment]
I also found out, that the connect() hoc of react-redux breaks the provider from updating.
This part in the documentation of the legacy and unreleased context API seems to be the key here: https://reactjs.org/docs/legacy-context.html#updating-context

I suggest updating to the new (official) Context API.

**Comment by dmtrKovalenko** [comment]
I didn’t know about it! Thanks 🙏 
I will migrate to the context in the nearest release
