### ISSUE TITLE
LuxonUtils Formatting Problem

### ISSUE THREAD

**Issue by piordanov** [dmtrKovalenko/material-ui-pickers#384]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |1.0.0-rc.7|
| material-ui         |1.0.0-beta.36|
| React               |16.2.0|
| Browser             |Chrome/ Firefox|
| Luxon                | 1.2.0

Using LuxonUtils seems to fail to format properly on the TextField. I've put a codeshare that is forked from the usage example using Luxon instead of date-fns.

### Actual Behavior
<img width="236" alt="screen shot 2018-05-02 at 6 26 45 pm" src="https://user-images.githubusercontent.com/5401480/39554088-7964531a-4e36-11e8-9645-44cbcf354316.png">

## Live example
https://codesandbox.io/s/l98w3nlqpq

**Comment by dmtrKovalenko** [comment]
Luxon has a bit specific format token. Thus date-fans example would not just work :(

**Comment by piordanov** [comment]
Oh that makes a lot of sense now. I added the format prop and after playing around with Luxon's [formatting](https://moment.github.io/luxon/docs/manual/formatting.html) the sandbox above now works. When you get around to writing luxon docs, feel free to go off of that. Thanks for your input!
