### ISSUE TITLE
MinDateAttribute  Error

### ISSUE THREAD

**Issue by mohanajuhi** [dmtrKovalenko/material-ui-pickers#392]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.7     |
| material-ui         |   1.0.0-beta.34      |
| React               |      16.2.0   |
| Browser             |     Chrome    |
| Platform            |      Mac   |

## Steps to reproduce
Open example.
Tab to "Test" field.

## Expected behavior
The calendar shows today;s date selected as default(even if its disabled) . Clicking ok  submits without throwing any error even if the minDate is set in future and selected date-Today (by just clicking "ok") is invalid

## Actual behavior
Expect to throw error on just clicking "ok" if selected date is invalid

## Live example
https://codesandbox.io/s/m345k7232x

**Comment by dmtrKovalenko** [comment]
Published in rc.8

**Comment by raycashmore** [comment]
The findClosestEnabledDate function doesn't actually quite do what it I would hope. It simply defaults back to the min or max date. In the case where we may want to disable weekends, it is not desirable to default to 1900-01-01 when there is no existing value. It would be good to either set it to the closest Friday or the Monday or just not let that value get committed.

**Comment by noah-potter** [comment]
@raycashmore Yeah that was surprising for me too. Not sure if that could/should be built into this library though. The only way I can think of to actually find the closest date would be to iterate through dates until you find a valid one, but that could potentially be 200 years * 365 days ~= 53000 date checks
