### ISSUE TITLE
How to change the color of the buttons and style textfield?

### ISSUE THREAD

**Issue by amanshu-kataria** [dmtrKovalenko/material-ui-pickers#395]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    ^1.0.0-rc.7     |
| material-ui         |  ^1.0.0-beta.44       |
| React               |  ^16.2.0    |
| Browser             |  Chrome 66.0.3359.139      |
| Platform            |    Mac     |

I want to change the color of the Cancel and OK button. Also I want to change the styling of textfield. How to do this?

**Comment by dmtrKovalenko** [comment]
#393

**Comment by dmtrKovalenko** [comment]
https://material-ui-pickers.firebaseapp.com/guides/css-overrides
