### ISSUE TITLE
The state isn't set onChange

### ISSUE THREAD

**Issue by MoamenMohamed** [dmtrKovalenko/material-ui-pickers#396]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     1.0.0-rc.7    |
| material-ui         |      1.0.0-beta.45   |
| React               |       16.2.0  |
| Browser             |    Chrome 66.0.3359.139     |
| Platform            |    windows     |

## Steps to reproduce
1. click on the date
2. choose another date [x]
3. choose another date [y]

## Expected behavior
 1. The text box date is updated to [x]
 2. the console log contains 2 lines the selected date [x] and the object state is [x]
 3. The text box date is updated to [y]
 4. the console log contains 2 lines the selected date [y] and the object state is [y]

## Actual behavior
 1. The text box date is updated to [x]
 2. the console log contains 2 lines the selected date [x] and the object state is [empty] ??
 1. The text box date is updated to [y]
 2. the console log contains 2 lines the selected date [y] and the object state is [x] ???

## Live example
https://codesandbox.io/s/zx86l6w73

**Comment by dmtrKovalenko** [comment]
OnChange dispatching only when you click ok and accept the date. If you will click cancel you will see previous date even you have changed it in the pickers 100 times.

**Comment by dmtrKovalenko** [comment]
Is that an issue?

**Comment by MoamenMohamed** [comment]
yes it happens when i click ok. it is an issue

![inkedsketch_li](https://user-images.githubusercontent.com/7293235/39854416-f184290a-5427-11e8-9eb3-207e0441aaed.jpg)

**Comment by dmtrKovalenko** [comment]
Thats a new react api hang. Just do 
```js
 this.setState({ selectedDate: date.toString() }, () => console.log(this.state));
```

**Comment by MoamenMohamed** [comment]
Yes this doesn't work either properly if you tried to log it after setting the state it works only for the last logging statement.

![1ebb9bb6-a8d2-4e4a-ac4d-b43cd2b82a83](https://user-images.githubusercontent.com/7293235/39859772-47854b8c-543b-11e8-9c57-d1bba54ac169.png)
