### ISSUE TITLE
Year of maxDate not available to select with date-fns utils

### ISSUE THREAD

**Issue by klanchman** [dmtrKovalenko/material-ui-pickers#399]
## Environment

| Tech                | Version          |
|---------------------| ---------------- |
| material-ui-pickers | 1.0.0-rc7        |
| material-ui         | 1.0.0-beta.47    |
| React               | 16.2.0           |
| Browser             | Safari & Firefox |
| Platform            | macOS            |

## Steps to reproduce

1. Use date-fns utils
2. Set a `maxDate` some number of years in the future
3. Open the picker and click on the year in the header

## Expected behavior

A list is shown that ends at the year of `maxDate`

## Actual behavior

A list is shown that ends 1 year **before** `maxDate`. Using the left/right arrow buttons still allows the user to navigate to the actual `maxDate`.

## Other Notes

I tried with the Moment utils and it worked as expected, this appears to only affect the date-fns utils.

## Live example

https://codesandbox.io/s/z25q66q5zp - I have the `maxDate` set to `new Date()` plus 2 years

**Comment by dmtrKovalenko** [comment]
Published in rc.8
