### ISSUE TITLE
Missing documentation to override custom Icon for the picker.

### ISSUE THREAD

**Issue by soberteq** [dmtrKovalenko/material-ui-pickers#409]
Missing documentation to override custom Icon for the picker.

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.8     |
| material-ui         |    1.0.0-beta.47     |
| React               |    16.3.2     |
| Browser             |         |
| Platform            |         |

## Steps to reproduce
1. Read the main information. It state how to import Material Icon and that It can be overriden
2. Tried to find information on how to override, non found
3. Trial an error, could not find an easy to change the deault calendar icon

## Expected behavior
Instruction on how to customize calendar icon

## Actual behavior
No help provided. It look slike it's missing en example in the documentation.

**Comment by dmtrKovalenko** [comment]
«And the last step of installation would be an icon font. By default we relying on material-icons font, but its possible to override any icons with a help of corresponding props.»

From Readme | installation tab.
Also there are every icon prop docemented in the docs api section.
