### ISSUE TITLE
Allow to specify if date is UTC

### ISSUE THREAD

**Issue by MistyKuu** [dmtrKovalenko/material-ui-pickers#41]
Currently everywhere in your code you have moment(value). It will cause issues if I don't want to use local time.  The solution would be to add isUTC props and change moment() calls into moment.UTC() if isUTC is set to true. E.g. here

```
getValidDateOrCurrent = () => {
    const date = moment(this.props.value);

    return date.isValid() ? date : moment();
  }
```

**Comment by dmtrKovalenko** [comment]
Yep, pickers would work with your local time. And from where I stand they should. If you wont to create something like timezone control you should create wrapper of Picker, smth like

```jsx
const DateTimePickerWithTimeZone = props => {
  const { timezone, input: { onChange, value }, meta: { touched, error }, dispatch, ...other } = props
  const valueWithTimeZone = momentTz.tz(value, timezone)

  return (
    <DateTimePicker
      error={!!(touched && error)}
      helperText={touched && error}
      value={valueWithTimeZone}
      onChange={onChange}
      {...other}
    />
  )
}
```
