### ISSUE TITLE
Unusual issue: EventListener on window in Calendar component caused unexpected behavior

### ISSUE THREAD

**Issue by YaroslavHapon** [dmtrKovalenko/material-ui-pickers#412]
## Environment
| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc.4 |
| material-ui         |     1.0.0-beta.38    |
| React               |     16.0.0    |
| Browser             |      Chrome   |
| Platform            |     macOS    |

## Steps to reproduce
1. Import Calendar component to the separate UI module with input elements
2. Pressing keyboard arrow buttons on the input elemnt

## Expected behavior
Expected to work the keyboard arrow buttons events inside inputs correctly
Ability to toggle the option of changing the date using keyboard arrow buttons

## Actual behavior
Keyboard arrow buttons events inside input elements doesn't work because of attached event handler on window.

Though, when I  am clicking on keyboard arrow buttons the date value in Calendar changes and inside input element the cursor position doesn't change

Maybe will be useful to add some flag option that will toggle this ability. Now i fixed this, by commenting the attaching event handler on window in Calendar component node_module.

**Comment by cherniavskii** [comment]
Hi and thanks for finding this library useful!

Could you please provide an example reproducing this issue?

**Comment by YaroslavHapon** [comment]
Hi! Thank you, for quick answer.

Here is the link, with this issue.

https://codesandbox.io/s/1vxl711kj7

**Comment by cherniavskii** [comment]
From a fast look, `Calendar` component isn't a proper place to add event listeners to `window` if we want to allow standalone usage of `Calendar`.

The proper place should be a Modal, since it's the only place we actually care about listening keyboard events on `window`.
