### ISSUE TITLE
Current date-fns version (v2.0.0-alpha.8) breaks material-ui-pickers

### ISSUE THREAD

**Issue by NKozlov** [dmtrKovalenko/material-ui-pickers#414]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc.9        |
| `@material-ui/core`         | 1.0.0-rc.1      |
| date-fns        | 2.0.0-alpha.8    |
| React               |  16.3.2       |
| Browser             |  Chrome, Firefox       |
| Platform            |    macOS 10.13.3 (High Sierra)     |

## Steps to reproduce
1. Use live example 

## Expected behavior
All works (like a guide https://material-ui-pickers.firebaseapp.com/usage)

## Actual behavior
Most of the functionality has stopped working (calendar, weekday, text values, etc.) 
With `date-fns@2.0.0-alpha.7` all works.

## Live example
https://codesandbox.io/s/6wx18p6qjz

**Comment by dmtrKovalenko** [comment]
Oh god :)

**Comment by dmtrKovalenko** [comment]
Anyway as workaround you can use extending of utils and override broken formats. Example [here](https://material-ui-pickers.firebaseapp.com/guides/formats) 
If you do - feel free to open a PR.

**Comment by cherniavskii** [comment]
I would suggest to skip date-fns@2.0.0-alpha.8, since it temporary disables all locales except `en-US`, `ru` and `eo` - see [changelog](https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha8).

From our side, we can just mention in docs that we only support alpha.7 for now

**Comment by thlee1122** [comment]
I am experiencing the same issue here. I tried the suggested workaround of using extending of utils and overriding broken formats, but that still did not fix the issue.

Here is the screenshot of the issue I am having:
![image](https://user-images.githubusercontent.com/18387214/40122104-09e2c90c-58f1-11e8-9394-87fc10e8b3c5.png)

**Comment by dmtrKovalenko** [comment]
Actually we would not support new version of date-fns till all locales would be supported.

**Comment by NKozlov** [comment]
@dmtrKovalenko @cherniavskii , it's true way, but in the future this work must be done. I agree, that for now we need just to fix docs (support date-fns@2.0.0-alpha.7 only)

**Comment by tatarsky-v** [comment]
I have the same problem too

**Comment by cherniavskii** [comment]
Closed by #418

**Comment by MEmmanuel** [comment]
@thlee1122 @tatarsky-v 
I experienced the same issue. I managed to solve the problem by upgrading material-ui, react, react-dom.
You might need to refactor your imports though.

**Comment by cherniavskii** [comment]
@MEmmanuel sounds like totally unrelated issue to me.
The issue described by @NKozlov cannot be fixed using your recommendations.

**Comment by MEmmanuel** [comment]
Yes, I was referencing @thlee1122 which is different. (#424 in fact). But your answer in it is better ...  :)

**Comment by igorlesnenko** [comment]
I'm using date-fns `^2.0.0-alpha.7` but still see the issue

**Comment by dmtrKovalenko** [comment]
@igorlesnenko you should use not `^2.0.0-alpha.7` but actually `2.0.0-alpha.7`

**Comment by bennidhamma** [comment]
We've just  updated our date-fns to latest (yes, we had `^2.0.0-alpha.7` in our package.json as well). 

This is disappointing to have to go in and revert those changes because of this dependency. 

Does anyone know of a work-around to this issue?

**Comment by bennidhamma** [comment]
I made a lame fork to just deal with this issue until it gets sorted properly. Works fine for my team, anyone else is welcome to partake. (FWIW, the new format options are nice, esp. the 'bbbb' one to give noon and midnight as suffixes in addition to a.m. and p.m..)

https://www.npmjs.com/package/@maven-io/material-ui-pickers

**Comment by cherniavskii** [comment]
The reason we're stick to `2.0.0-alpha.7` is that it was stable enough and there were no newer releases for like 6 month.

I think we should wait for `date-fns@2.0.0` release, since there's too much breaking changes between new alpha releases.

**Comment by milonite** [comment]
I had the same issue with the last version so i downgraded to 2.0.0-alpha.7 but now i see only chars 
![picker](https://user-images.githubusercontent.com/28712349/45052669-ec84cd80-b087-11e8-80da-76f0b4a1a207.JPG)

**Comment by tariqsidd** [comment]
I am using "material-ui-pickers": "^1.0.0-rc.14",  "date-fns": "2.0.0-alpha.16",  but still have this
![image](https://user-images.githubusercontent.com/28774930/45808843-3a344380-bce0-11e8-8299-aa97bc2e71ba.png)

**Comment by omarcespedes** [comment]
> You need to use date fns v16 with date-fns-utils and v7 with date-fns-utils-old

Can be more explicit about this? I'm having the same issue as @milonite but I'm not sure how to fix it
