### ISSUE TITLE
Color-picker proposal

### ISSUE THREAD

**Issue by caub** [dmtrKovalenko/material-ui-pickers#415]
Awesome project you did there

I'll probably try to material-ui'fy my raw [color-wheel](https://caub.github.io/color-wheel/demo/) if you're interested (in helping maybe too)

**Comment by dmtrKovalenko** [comment]
I dont understand why we will need color picker for date picker.

**Comment by caub** [comment]
It's completely unrelated, but your repo is 'material-ui-pickers' so I thought about that kind of picker
