### ISSUE TITLE
"too much recursion" error

### ISSUE THREAD

**Issue by greemin** [dmtrKovalenko/material-ui-pickers#417]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc.9 |
| material-ui-next | 1.0.0-beta.44 |
| React | 16.3.2 |
| Moment | 2.22.1 |
| Browser | Firefox 59.0.3, Google Chrome 66.0.3359.181 |
| Platform | Windows 10 |

## Steps to reproduce
1. Implement any Picker Component like [here ](https://material-ui-pickers.firebaseapp.com/usage) (tested with Moment and date-fns utils)
2. Open Picker in rendered App and click somewhere
3. Errors in Console

## Expected behavior

To run without error

## Actual behavior

It runs but with following Console output:
-  "too much recursion" (Firefox)
- "Uncaught RangeError: Maximum call stack size exceeded" (Google Chrome)

**Comment by cherniavskii** [comment]
Hi Karl,
We do not support mui beta versions in rc.9 release.
You should update mui at least to rc.0 version:

https://github.com/dmtrKovalenko/material-ui-pickers/blob/208a987e9f29284cc41b943125ddf77978d9fd5a/lib/package.json#L34-L36

**Comment by greemin** [comment]
Was still using deprecated "material-ui-next" package. My bad! 
Thank you for the fast response.
