### ISSUE TITLE
 Can't resolve 'material-ui/styles/withStyles' (1.0.0-rc-X version)

### ISSUE THREAD

**Issue by LironGetJones** [dmtrKovalenko/material-ui-pickers#421]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    ^1.0.0-rc.9     |
| @ material-ui/core         |     ^1.0.0-rc.0    |
| React               |      ^15.6.1   |
| Browser             |    Chrome     |
| Platform            |    Linux, WIndows     |

## Steps to reproduce
1. create-react-app
2. yarn add @material-ui/core material-ui-pickers 
3. create react component:
import InputAdornment from '@material-ui/core/InputAdornment';
import IconButton from '@material-ui/core/IconButton';
import DateRangeIcon from '@material-ui/icons/DateRange';
import { DatePicker } from 'material-ui-pickers';
...
<DatePicker
            keyboard
            label="Masked input"
            format="DD/MM/YYYY"
            placeholder="10/10/2018"
            mask={value => (value ? [/\d/, /\d/, '/', /\d/, /\d/, '/', /\d/, /\d/, /\d/, /\d/] : [])}
            value={this.state.selectedDate}
            onChange={this.handleChange}
            disableOpenOnEnter
            animateYearScrolling={false}
          />

## Expected behavior
To see the component 

## Actual behavior
Error on compile:
./node_modules/material-ui-pickers/DateTimePicker/DateTimePickerView.js
Module not found: Can't resolve 'material-ui/styles/withStyles' in '<project_dir>/node_modules/material-ui-pickers/DateTimePicker'

## Live example
https://codesandbox.io/s/0m3p5yz6xp

**Comment by cherniavskii** [comment]
Hi,
your example throws errors related to:
- React version (we do not support v15.6)
- missing of MuiPickersUtilsProvider

Example you provided doesn't illustrate reported issue.
Please fix it so we can gave you feedback related to your issue.

**Comment by kwestlund** [comment]
You need to upgrade to the latest material-ui, which is, @material-ui/core

**Comment by istarkov** [comment]
Yep I'm expecting the same issue because of https://github.com/dmtrKovalenko/material-ui-pickers/blob/d43cff6e0dc2dd6e287f9cd5a75d65ff05330a4e/lib/src/DateTimePicker/DateTimePickerView.jsx#L4

**Comment by cherniavskii** [comment]
@istarkov are you sure you're using rc.9?

Everything looks fine on our side:
https://unpkg.com/material-ui-pickers@1.0.0-rc.9/DateTimePicker/DateTimePickerView.js

**Comment by istarkov** [comment]
I'm pretty sure what I use. Just install it. Open node_modules,
there would be package.json with
```  "name": "material-ui-pickers",
  "version": "1.0.0-rc.9",
```

and DateTimePickerView with
```var _withStyles = require('material-ui/styles/withStyles');```

Same as in your master see link I provided above

**Comment by cherniavskii** [comment]
The link you provided doesn't point to master branch.

Here's master:
https://github.com/dmtrKovalenko/material-ui-pickers/blob/8087e78dd6c9c71c9d8af6951c4c2ad74dc18a02/lib/src/DateTimePicker/DateTimePickerView.jsx#L3

**Comment by istarkov** [comment]
It's strange when i do
```
wget https://registry.yarnpkg.com/material-ui-pickers/-/material-ui-pickers-1.0.0-rc.9.tgz#f343c8af28c49cc397ccc5ce72eb8fff843855fc
tar -xvzf material-ui-pickers-1.0.0-rc.9.tgz
cat package/DateTimePicker/DateTimePickerView.js
```
I see `@material-ui/core` imports, 
when I do yarn install which should pick tgz from  same location I see what I see ;-)
Checking

**Comment by cherniavskii** [comment]
> Just install it. Open node_modules

Just did it, everything loooks fine to me

**Comment by cherniavskii** [comment]
Hmm, I'm using `npm`.
Looks like problem with `yarn`

**Comment by istarkov** [comment]
Oops I'm sorry,
seems like the problem was with my yarn cache
after `yarn cache clean && yarn`

Thank you!!!

**Comment by cherniavskii** [comment]
I'm glad you've solved your problem ;)
And thanks for posting your solution here :)

Closing the issue

**Comment by markthiessen** [comment]
Ran into the same issue.. strange, but for me `yarn cache clean` did not work. I had to delete my `node_modules` folder and then run `yarn` again.
