### ISSUE TITLE
Plan to switch to new lifecycle method in React 16.3 ?

### ISSUE THREAD

**Issue by t49tran** [dmtrKovalenko/material-ui-pickers#422]
First, thanks for the amazingly nice and useful lib @dmtrKovalenko , we use this at work as a complement for `material-ui` and `material-ui-pickers` ease us a lot of pain.

Recently we updated to React 16.3 on some of our more recent projects. I noticed that `material-ui-pickers` is currently on React 16.2 and there are few components using lifecycle methods that will be deprecated.

They can be found by wrapping the demo page: `docs/src/index.js` with `React.StrictMode`. These components are:

- `PickerBase`, `Calendar`, `DateTextField`  --- using `componentWillReceiveProps`

In all these cases, update from `componentWillReceiveProps` to `getDerivedStateFromProps` will be pretty straight forward.

Do we have a plan on updating them, or are we waiting for React 17 ? I am more than happy to lend a hand if it's needed.

**Comment by cherniavskii** [comment]
Hi,
We support react ^16.3.0 currently.

Yeah, we will definitely migrate to new lifecycle methods.
Your help will be very appreciated, feel free to open a PR ;)
