### ISSUE TITLE
How I can override style for :after :before pseudo elements ?

### ISSUE THREAD

**Issue by ritwickdey** [dmtrKovalenko/material-ui-pickers#423]
Example
```
.MuiInput-underline-4750:before { 
 //....
 // I want to override this.
}
```

Stackoverflow Question : https://stackoverflow.com/questions/50403424/how-to-disable-underline-to-material-uis-datepicker-in-react

**Comment by idtechnology** [comment]
I've noticed the class number can change, so I've been using [class*="MuiInput-underline"]:before and just making sure to add classes on the component if I want specificity.  Hope that helps.

**Comment by cherniavskii** [comment]
@ritwickdey your question is already answered on SO
