### ISSUE TITLE
Calendar Showing days of year number (0-365), instead of days of month (0-31)

### ISSUE THREAD

**Issue by idtechnology** [dmtrKovalenko/material-ui-pickers#424]
## Environment

| Tech                | Version |
|---------------------|---------|
| date-fns |2.0.0-alpha.8 (@next) |
| material-ui-pickers | 1.0.0-rc.7 |
| material-ui         | 1.0.0-beta.40 |
| React               | 16.3.0 |
| Browser             | tested: Safari/Chrome/Firefox | same issue everywhere

## Steps to reproduce
1. install SSR MERN app https://github.com/idtechnology/HERMN-2.0 
2. install material-ui@1.0.0-beta.40 and material-ui-pickers@1.0.0-rc.6
3. Setup basic example from mui-pickers website and provider from github setup example

## Expected behavior
A calendar with regular days

## Actual behavior
Previous to the latest update a few days ago, everything worked fine.  Now for some reason when I do a fresh install I get the days listed as the number of days from the beginning of the year, instead of from the beginning of the month.  I'm supposed to launch this site for a client in the next couple of days, any help would be much appreciated, thank you.

## Live example
please email me for live example, dont want to publicly post my clients page.  info@createdesign.tech

**Comment by lfalke** [comment]
I had the same issue. Try using `date-fns` in version `2.0.0-alpha.7`
They introduced a new format string API as a breaking change with the new alpha.
https://gist.github.com/kossnocorp/a307a464760b405bb78ef5020a4ab136#v200-alpha8

**Comment by cherniavskii** [comment]
Yes, use `date-fns@2.0.0-alpha.7`.
See #414 for more info.

**Comment by bennidhamma** [comment]
I made a lame fork to just deal with this issue until it gets sorted properly. Works fine for my team, anyone else is welcome to partake. (FWIW, the new format options are nice, esp. the 'bbbb' one to give noon and midnight as suffixes in addition to a.m. and p.m..)

https://www.npmjs.com/package/@maven-io/material-ui-pickers
