### ISSUE TITLE
Date returns to the previous value

### ISSUE THREAD

**Issue by hamart** [dmtrKovalenko/material-ui-pickers#426]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.9     |
| material-ui         |   1.0.0-rc.0      |
| React               |    16.3.2     |
| Browser             |    Chrome 66.0     |
| Platform            |   Windows 10      |

## Steps to reproduce
1. Include DatePicker on page
2. Open select date popup
3. Select any date
4. Press OK

## Expected behavior
Value of DatePicker is equals selected date in calendar

## Actual behavior
When press OK in the calendar, selected date quickly returns to the previous value

**Comment by cherniavskii** [comment]
> When press OK in the calendar, selected date quickly returns to the previous value

Why do you expect date to return to the previous value after pressing OK button?

**Comment by hamart** [comment]
> Why do you expect date to return to the previous value after pressing OK button?
Sorry, I mix up Expected and Actual behavior. Fixed description of the issue

**Comment by cherniavskii** [comment]
@hamart 
Oh, now it makes sense ;)

Can you provide an example which reproduces you issue?

P.S. make sure you're not wrapping picker with `FormControl` component

**Comment by hamart** [comment]
>P.S. make sure you're not wrapping picker with FormControl component

Actually, this is true. I removed FormControl wrapper and it's works fine now. Thank you

**Comment by cherniavskii** [comment]
Pickers use `TextField`, which uses `FormControl` under the hood - so there's no sense to wrap it with one more `FormControl` ;)

**Comment by chenop** [comment]
For me the issue was the following:
The parent component which hold the DatePicker was extending React.Component - after changing ALL components hierarchy to extend React.PureComponent problem was solved.
