### ISSUE TITLE
Touched is not effected to react-final-form

### ISSUE THREAD

**Issue by MichaelBuen** [dmtrKovalenko/material-ui-pickers#430]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |      1.0.0-rc.9   |
| material-ui         |   1.0.0      |
| React               |    16.4.0     |
| Browser             |    Chrome     |
| Platform            |     Sandbox    |

## Steps to reproduce
1. Tab over the a required date picker
2.  meta.touched did not become true.

## Expected behavior
meta.touched should become true when user visited and exited a required date picker.
So a validation message can be shown immediately when user skips a required date picker.

## Actual behavior
meta.touched stays as false even when the user visited and exited a required date picker.

## Live example

https://codesandbox.io/s/0y12x6j19l

For reference, I added a custom dropdown component that uses material-ui + react-final-form. The active, touched, visited are effected to react-final-form's meta object.

![image](https://user-images.githubusercontent.com/1811636/40468211-52e174e0-5f5f-11e8-9d48-550cd7b27d85.png)

Here's the material-ui-pickers' DateTimePicker that uses material-ui + react-final-form. The active, touched, visited are not effected to react-final-form's meta object.

![image](https://user-images.githubusercontent.com/1811636/40468274-84a74e46-5f5f-11e8-88c0-50b34bad792c.png)

![image](https://user-images.githubusercontent.com/1811636/40468315-9b9120e6-5f5f-11e8-8080-4fa1369b660a.png)

**Comment by cherniavskii** [comment]
Hi,
Is there particular issue with `material-ui-pickers` itself (without other libraries)?
Please try to reproduce issue without any 3rd-party libraries.

**Comment by MichaelBuen** [comment]
Closing the issue, no problem with `material-ui-pickers`. Just need to add onBlur from `react-final-form`'s Field to`material-ui-pickers`'s onBlur to effect true to `meta.touched`.

![image](https://user-images.githubusercontent.com/1811636/40471340-f2eb9d68-5f68-11e8-9d56-98bc079bcd26.png)
