### ISSUE TITLE
How to focus and select the date picker from external event?

### ISSUE THREAD

**Issue by Mario-Eis** [dmtrKovalenko/material-ui-pickers#431]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | rc.9 |

How can the date picker be focused from an external event? Getting a ref and call .focus() and .select() seems the recommended way with inputs. But it seems there is no focus() or .select() method on the pickerRef. And i can't find a way to get a ref to the input itself.

**Comment by dmtrKovalenko** [comment]
You can just open the picker for now. If you critically need this methods open feature request please.
