### ISSUE TITLE
DatePicker with react-slingshot - After selecting a date the date selection "jump" back to original

### ISSUE THREAD

**Issue by chenop** [dmtrKovalenko/material-ui-pickers#434]
## Environment
Windows 10

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  ^1.0.0-rc.9      |
| material-ui         |   1.0.0-rc.1      |
| React               |   16.3.1      |
| Browser             |   Chrome      |
| Platform            |    Windows     |

## Steps to reproduce
1. install fresh installation of react-slingshot
2. Add empty App.scss to styles directory
3. Paste the following code to index.js
```
/* eslint-disable import/default */

import {render} from 'react-dom';
import configureStore, {history} from './store/configureStore';
import './styles/styles.scss'; // Yep, that's right. You can import SASS/CSS files too! Webpack will run the associated loader and plug this into the page.
import React, {Component} from "react";
import {DatePicker, MuiPickersUtilsProvider} from "material-ui-pickers";
import MomentUtils from 'material-ui-pickers/utils/moment-utils';
import CSSModules from "react-css-modules";
import styles from "./styles/App.scss";

require('./favicon.ico'); // Tell webpack to load favicon.ico
const store = configureStore();

class HOCAppContainer extends Component {
  render() {
    return (
      <MuiPickersUtilsProvider utils={MomentUtils}>
        HOC
        <DatePicker />
      </MuiPickersUtilsProvider>
    );
  }
}

const AppContainer = CSSModules(HOCAppContainer, styles);

render(
  <AppContainer />,
  document.getElementById('app')
);

if (module.hot) {
  module.hot.accept('./components/Root', () => {
    const NewRoot = require('./components/Root').default;
    render(
      <AppContainer>
        <NewRoot store={store} history={history} />
      </AppContainer>,
      document.getElementById('app')
    );
  });
}
```
4. run: 

> npm start
5. open localhost --> Open DatePicker --> click the one of the dates --> it "jump" back to the initial date

## Expected behavior

The selection should stay on the selected day
Note: it reproduce only with react-slingshot

## Actual behavior

The selection "jump" back to the initial selection

## Live example
Could not upload react-slingshot to live example but created the repository with everything above
https://github.com/chenop/react-slingshot-material-ui-picker

**Comment by cherniavskii** [comment]
Hi,
Unfortunately we do not have time to debug issues related to 3rd-party libraries.
If you are *sure* it's `material-ui-pickers` bug - please submit an issue with reproducing example without any 3rd-party libraries.

That being said, looking at your issue, I'd suggest you to make sure that you're not wrapping picker with `FormControl` component.

**Comment by chenop** [comment]
Thanks @cherniavskii for responding.
I'll try to reproduce it .

Regarding you last comment - Maybe I missed Something - Where do I use FormControl?

**Comment by cherniavskii** [comment]
@chenop I'm not telling you're using it, but your issue seems similar to #426

**Comment by chenop** [comment]
Hi, After further investigate it - its seems I finally nailed it.
The parent component which hold the DatePicker was extending React.Component - after changing ALL components hierarchy to extend React.PureComponent problem was solved.

**Comment by chenop** [comment]
Its seems to me there is something kind of timing issue when selecting the hour.
