### ISSUE TITLE
LuxonUtils creates a Luxon DateTime object onChange

### ISSUE THREAD

**Issue by mschipperheyn** [dmtrKovalenko/material-ui-pickers#436]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc.9        |
| material-ui         | 1.0        |
| React               | 16.3        |
| Luxon               | 1.2.1.        |

## Actual behavior
When a date onChange event is generated the onChange event in the DatePicker passes a Luxon DateTime object in the event. 

## Expected behavior
It should pass a javascript Date object.

date-fns passes a Javascript Date object. This makes the behavior inconsistent. It also forces the end implementation code to be more tightly coupled with Luxon. 

I understand that this choice might be made. I just think that data passes across the API should not be "util" specific and should be a Date.

**Comment by dmtrKovalenko** [comment]
It should be util specific. If you need to manage `Date` object use date-fns
