### ISSUE TITLE
Missing Typescript type for value field

### ISSUE THREAD

**Issue by srmelody** [dmtrKovalenko/material-ui-pickers#438]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     ^1.0.0-rc.9     |
| material-ui         |      1.0.0-beta.38   |
| React               |     ^15.5.4   |
| Browser             |    Chrome     |
| Platform            |    OSX     |
| Typescript | 2.7.2 |

## Steps to reproduce
1. Drop a DatePicker into code that is using typescript
```
   <DatePicker
            value={this.state.dialogResponse}
            onChange={this.dialogResponseChange}
            />
```
gives
Property 'value' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<DatePickerWrapperProps, ComponentState>>...'.
## Expected behavior
Successful transpile

## Actual behavior

Hi there,
I installed material-ui-pickers and am getting an error while using typescript.  It looks like the value field is missing from DateTimePickerWrapperProps.

I have a fork that adds this field but the tsc step during npm test fails:
https://github.com/srmelody/material-ui-pickers/commit/c0d5890bd4cc273c2a54f246c4ddc8ee52594a10

> tsc -p tsconfig.json

src/DatePicker/DatePickerWrapper.d.ts(10,18): error TS2320: Interface 'DatePickerWrapperProps' cannot simultaneously extend types 'PickerBaseProps' and 'Pick<ModalWrapperProps, "required" | "error" | "hidden" | "dir" | "label" | "select" | "slot" | "...'.
  Named property 'value' of types 'PickerBaseProps' and 'Pick<ModalWrapperProps, "required" | "error" | "hidden" | "dir" | "label" | "select" | "slot" | "...' are not identical.
src/DateTimePicker/DateTimePickerWrapper.d.ts(11,18): error TS2320: Interface 'DateTimePickerWrapperProps' cannot simultaneously extend types 'PickerBaseProps' and 'Pick<ModalWrapperProps, "required" | "error" | "hidden" | "dir" | "label" | "select" | "slot" | "...'.
  Named property 'value' of types 'PickerBaseProps' and 'Pick<ModalWrapperProps, "required" | "error" | "hidden" | "dir" | "label" | "select" | "slot" | "...' are not identical.
src/TimePicker/TimePickerWrapper.d.ts(8,18): error TS2320: Interface 'TimePickerWrapperProps' cannot simultaneously extend types 'PickerBaseProps' and 'Pick<ModalWrapperProps, "required" | "error" | "hidden" | "dir" | "label" | "select" | "slot" | "...'.
  Named property 'value' of types 'PickerBaseProps' and 'Pick<ModalWrapperProps, "required" | "error" | "hidden" | "dir" | "label" | "select" | "slot" | "...' are not identical.

**Comment by dmtrKovalenko** [comment]
<img width="502" alt="2018-06-01 15 04 12" src="https://user-images.githubusercontent.com/16926049/40839913-2bab5eb4-65ad-11e8-931c-21a6d59a6791.png">

You need to update to @material-ui/core to use rc.9 version
