### ISSUE TITLE
Uncaught TypeError: _react2.default.createContext is not a function

### ISSUE THREAD

**Issue by tooppaaa** [dmtrKovalenko/material-ui-pickers#442]
Tech | Version
-- | --
material-ui-pickers | 1.0.0-rc.9
material-ui | 1.1.0
React | 16.4.0
Browser | Chrome
Platform |  

As mentionned in #435 This is still occuring

**Comment by dmtrKovalenko** [comment]
I have retest that and cannot reproduce this. Please provide codesandbox to reproduce this issue.
Till that issue closed

**Comment by lollotek** [comment]
@dmtrKovalenko 
Have you tried after a build ? 
Seems it occur only on production.

**Comment by tooppaaa** [comment]
Indeed fixed avec upgrading material-ui and material-pickers.

Sorry for the delay in my response !
