### ISSUE TITLE
Datepicker showing wrong year values

### ISSUE THREAD

**Issue by mohanajuhi166** [dmtrKovalenko/material-ui-pickers#446]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   1.0.0-rc.9      |
| material-ui         |   1.1.0      |
| React               |        16.3.2 |
| Browser             |    chrome     |
| Platform            |       OSX  |

## Steps to reproduce
1.Date picker showing wrong values for year and in display

## Expected behavior
Date picker to show correct value

## Actual behavior
Date picker showing wrong values for year in display 
<img width="277" alt="screen shot 2018-06-05 at 2 01 55 pm" src="https://user-images.githubusercontent.com/19162354/40964869-d23f9d5c-68c9-11e8-97b5-c6e022f8d14b.png">

**Comment by dmtrKovalenko** [comment]
Rollback to date-fns .7 version

**Comment by mohanajuhi166** [comment]
It produces multiple errors, one of them being
Module not found: Can't resolve 'date-fns/addDays' in '/Users/z0026zp/Documents/mygitrepos/FlytX/node_modules/material-ui-pickers/utils'

**Comment by mohanajuhi166** [comment]
It produces multiple errors, one of them being
Module not found: Can't resolve 'date-fns/addDays' in
'node_modules/material-ui-pickers/utils'

**Comment by dmtrKovalenko** [comment]
https://github.com/dmtrKovalenko/material-ui-pickers/blob/master/docs/package.json#L17

**Comment by mohanajuhi166** [comment]
Works!

**Comment by mohanajuhi166** [comment]
is there any predefined attribute to make this a required field? Thanks

**Comment by dmtrKovalenko** [comment]
Actually no. But you can pass any material-ui`s text field props so its possible to display any error with a help of `helperText` and `error` props. 
For management form state you can use [formik](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwi8xtmSobzbAhWECywKHeUBAf4QFggmMAA&url=https%3A%2F%2Fgithub.com%2Fjaredpalmer%2Fformik&usg=AOvVaw1KDhqWgGqD1QPxDj_jnJq6) or [redux-form](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiS4NyTobzbAhWHKCwKHVtlBEwQFggmMAA&url=https%3A%2F%2Fredux-form.com%2F&usg=AOvVaw04XbZSc-D6EAS1bR6hCFGy)

**Comment by jaredpetker** [comment]
Using formik doesn't really quite work out well since `material-ui-pickers` doesn't expose a native events.
