### ISSUE TITLE
Datepicker classes change from Mui to JSS once deployed

### ISSUE THREAD

**Issue by StefanoSega** [dmtrKovalenko/material-ui-pickers#447]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   1.0.0-rc.8      |
| material-ui         |   1.0.0-beta.47      |
| React               |    ^16.3.2     |
| Browser             |   Chrome 66      |
| Platform            |    MacOS     |

## Steps to reproduce
1. Create a react component with the MUI DatePicker in this way:
```
<MuiThemeProvider theme={materialTheme}>
          <MuiPickersUtilsProvider utils={DateFnsUtils}>
            <div
              className={`datetime-picker ${hasValue ? 'has-value' : ''}`}
              data-md-field
            >
              <DateTimePicker
                value={this.state.value}
                onChange={this.onChange}
                emptyLabel={this.props.placeholder}
                clearable={!this.props.required}
                shouldDisableDate={this.shouldDisableDate}
                format="DD/MM/YYYY hh:mm A"
                InputProps={{
                  endAdornment: (
                    <InputAdornment position="end">
                      <Icon className="datetime-picker-icon">event</Icon>
                    </InputAdornment>
                  ),
                }}
              />
              <label htmlFor={this.props.id} className="datetime-picker-label">{this.props.title}</label>
            </div>
          </MuiPickersUtilsProvider>
        </MuiThemeProvider>
```
2. Inspect the picker css classes: they're like MuiInput-input-710, MuiInput-root-702 MuiInput-formControl-703 MuiInput-underline-706 WithUtils-DateTextField--input-697, ...
3. Run the application in a Docker image deployed on AWS; in the Dockerfile run `npm install` with the package.json that specify the exact version of the dependencies without caret to update the minor version:
```
"@material-ui/core": "1.2.0",
"date-fns": "2.0.0-alpha.7",
"material-ui": "1.0.0-beta.47",
"material-ui-pickers": "1.0.0-rc.8",
```
4. Inspect the css classes of the app running on Docker: they all start with "jss"

## Expected behavior
css classes names should be consistent across development environment and a Docker image with the same packages installed

## Actual behavior
Thr css classes differs, in one case they start with "MUI-", in the other with "jss". Is this related to a certain version of material-ui-pickers or any dependency?

**Comment by dmtrKovalenko** [comment]
1. Which `NODE_ENV` is on your docker image. 
2. Every jss class name is generated by jss (check maybe you will find some useful info here https://github.com/dmtrKovalenko/material-ui-pickers/issues/338)

**Comment by StefanoSega** [comment]
1. production

**Comment by dmtrKovalenko** [comment]
@StefanoSega jss is creating more compact css names for production. Its a feature. You need to generate the names by yourself or just take it :D

**Comment by StefanoSega** [comment]
Actually seems that it doesn't depend on `NODE_ENV`.

I tried to run it in my dev env (running the server with nodemon, etc ...) with node_env=production and the classes stays as the MUI.

Otherwise, with the styling options I've how I can achieve this overwrite:
```
.datetime-picker {

  [class^="MuiFormControl-root-"] {
    width: 100%;
  }

  input[class^="MuiInput-input-"] {
    color: $color-gray;
  }

  &.has-value input[class^="MuiInput-input-"] {
    color: $color-black;
  }

  [class^="MuiInput-underline-"][class^="WithUtils-DateTextField--input-"] {
    &:hover::before {
      height: 1px;
      background-color: $color-gray;
    }

  }
}
```

**Comment by nozpheratu** [comment]
This seems to break in production for me, the jss class names don't seem to have any styles associated.

**Comment by oddlyfunctional** [comment]
Hey folks, I had this issue and fixed following the documentation in [JSS](https://github.com/cssinjs/react-jss#multi-tree-setup) such that the classes inside the `DatePicker` would always be prefixed and hence wouldn't conflict with my own even in production:

```jsx
import React from 'react';
import { JssProvider } from 'react-jss';
import MaterialDatePicker from 'material-ui-pickers/DatePicker/DatePicker';

const DatePicker = props => (
  <JssProvider classNamePrefix="Material-ui-pickers-">
    <MaterialDatePicker {...props} />
  </JssProvider>
);

export default DatePicker;
```

**Comment by jerome313** [comment]
@oddlyfunctional  
this method fails for me, I applied a prefix to the Grid component but in production only one instance of the component gets prefixed rest remains the same eg: jss.
I used three instances (container and two items inside ) of grid component after prefixing it, it got applied to only one instance of grid item and rest remained the same with the jss prefix.

**Comment by AtulKondekar** [comment]
Hi Guys and @StefanoSega , 
I found a hack where you css is not converted to jss-(number) in producion

```import React from "react";
import { DateTimePicker } from "material-ui-pickers";
import MuiPickersUtilsProvider from "material-ui-pickers/utils/MuiPickersUtilsProvider";
import MomentUtils from "material-ui-pickers/utils/moment-utils";
import moment from "moment";

import { jssPreset } from '@material-ui/core/styles';
import JssProvider from "react-jss/lib/JssProvider";
import { create } from "jss";

const jss = create(jssPreset());
var ruleCounter = 0;
jss.options.createGenerateClassName = function () {
    return function (rule, sheet) {
      ruleCounter += 1;
      var prefix = "";
      var jssId = '';
  
      if (sheet) {
        prefix = sheet.options.classNamePrefix;
        if (sheet.options.jss.id != null) jssId += sheet.options.jss.id;
      }
      return prefix + '-' + rule.key + (jssId && '-' + jssId) + '-' + ruleCounter;
    };
  };

class App extends React.Component {
  state = { date: moment() };

  handleDateChange = date => {
    this.setState({ date });
  };

  render() {
    return (
      <JssProvider jss={jss}>
        <MuiPickersUtilsProvider utils={MomentUtils}>
          <DateTimePicker
            value={this.state.date}
            onChange={this.handleDateChange}
          />
        </MuiPickersUtilsProvider>
      </JssProvider>
    );
  }
}
export default App;

**Comment by sebrana** [comment]
Hi. I ran into that issue and found how to fix it here : 
[https://material-ui.com/getting-started/faq/](url)
[https://material-ui.com/customization/css-in-js/#jssprovider](url)

Issue is caused by the use of distinct mui bundles and external components use distinct different jssClassNameGenerator. Uing a unique classNameGenerator fixed it in my case

`import JssProvider from 'react-jss/lib/JssProvider';
import { create } from 'jss';
import { createGenerateClassName, jssPreset } from '@material-ui/core/styles';

const generateClassName = createGenerateClassName();
const jss = create(jssPreset());

function App() {
  return (
    <JssProvider jss={jss} generateClassName={generateClassName}>
      ...
    </JssProvider>
  );
}

export default App;`
