### ISSUE TITLE
When wrapped by material-ui/core/FormControl, DatePicker doesn't work as expected

### ISSUE THREAD

**Issue by bandreetto** [dmtrKovalenko/material-ui-pickers#448]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.9    |
| material-ui         |    1.2.0     |
| React               |    16.3.2     |
| Browser             |     Chrome    |
| Platform            |     OSX    |

## Steps to reproduce
1. Create a `DatePicker` inside a FormControl
2. Set initial `DatePicker` value to null
3. Try to select a date different from the default date (today).

## Expected behavior
User should be able to select any date, even if the current date value is null.

## Actual behavior
On mouse click, the selected date falls back to the default value, on the release the desired date is selected, but due to anytime that the mouse button is clicked it falls back to the default value, when you press the button to actually select the date, the date selected is the default date.

When you try to select a date from another month rather than the default date's month, when you click it falls back to the default date changing the month and thus you can't select the desired date.

## Live example
https://codesandbox.io/s/ox53lpl41q

## Observations
This issue only happens when the `MuiPickersUtilsProvider` is wrapping the whole thing. If you put `MuiPickersUtilsProvider` right before the `DatePicker` it works as expected, but I don't think this is how it should be used.

**Comment by dmtrKovalenko** [comment]
Do not use FormControl

**Comment by dmtrKovalenko** [comment]
Closed as dupicalte of #217
