### ISSUE TITLE
Date pickers Icons are not visible 

### ISSUE THREAD

**Issue by ajkaushik** [dmtrKovalenko/material-ui-pickers#449]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   1.0.0-rc.9      |
| material-ui         |     @material-ui/core 1.0.0 and @material-ui/icons 1.0.0    |
| React               |    16.4.0     |
| Browser             |   Chrome      |
| Platform            |     Windows    |

## Steps to reproduce
1. Add simple data picker with keyboard input
2. Run the app

## Expected behavior
Date picker should use icons from @material-ui/icons

## Actual behavior
No icons are visible, instead it shows characters

**Comment by dmtrKovalenko** [comment]
Please read the installation guide https://material-ui-pickers.firebaseapp.com/installation

**Comment by ajkaushik** [comment]
Apologies, my bad. should have read props more carefully. Was able to supply icons from @material-ui/icons using relevant props.
