### ISSUE TITLE
allow custom input

### ISSUE THREAD

**Issue by sakulstra** [dmtrKovalenko/material-ui-pickers#45]
It would be cool if we could forward placeholder and label to the textfield inside DateTextField.
I'm not quite sure if this is the bast api, but I'd suggest a new renderInput prop which accepts a `() => XML` function.

I'd be happy to do the pr :) (not sure when though)

**Comment by dmtrKovalenko** [comment]
Hmm, you can pass any props to the textfield, pass them to the root, such like label, placeholder, className, etc.
Why do you need a custom renderer?

**Comment by sakulstra** [comment]
@dmtrKovalenko oh sry didn't see that, i guess we don't need it then.

Eventually it would still make sense though, as we would have a clean separation between inputProps and the pickerProps, but i guess it's more of a design/taste decision. It's working quite well as it is right now <3
