### ISSUE TITLE
Allow for option to pass "initialFocusedDate" to DatePicker

### ISSUE THREAD

**Issue by mcMickJuice** [dmtrKovalenko/material-ui-pickers#450]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     1.0.0-rc.9   |
| material-ui         |      1.2.0    |
| React               |    16.3.2     |
| Browser             |    Chrome - 66.0.3359.181     |
| Platform            |    OSX     |

## Steps to reproduce
1. Set value as null on DatePicker
2. Set minDate to a value greater than today
3. When you open the calendar, the focused date is today

## Expected behavior
I would like the ability to provide an "initial focused date" that would be highlighted when I open the picker and I don't have a selected value.  If a value is provided, this prop is ignored.

## Actual behavior
No ability to specify an initial focused date

## Live example

https://codesandbox.io/s/q7jxvqqqq9 - this code example uses an older version, which is where we first noticed the need for this prop (before we upgraded to rc9).  This feature is somewhat blocked by https://github.com/dmtrKovalenko/material-ui-pickers/issues/445

**Comment by dmtrKovalenko** [comment]
@mcMickJuice would you like to work on this and #445 issues and open a PR?

**Comment by mcMickJuice** [comment]
most definitely :)

**Comment by millnitzluan** [comment]
Can I try to do this?

**Comment by dmtrKovalenko** [comment]
@millnitzluan of course feel free to open a PR
