### ISSUE TITLE
Can't resolve 'react-event-listener'

### ISSUE THREAD

**Issue by jackjwilliams** [dmtrKovalenko/material-ui-pickers#453]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   1.0.0-rc.9      |
| material-ui         |  1.2       |
| React               |    16.3     |
| Browser             |    Chrome Latest    |
| Platform            |         |

## Steps to reproduce
1. npm run build

## Expected behavior

The build to pass

## Actual behavior

I've gotten all the rest of this issues fixed, except this one. 
```
ERROR in ./node_modules/material-ui-pickers/DatePicker/Calendar.js
    Module not found: Error: Can't resolve 'react-event-listener' in 'C:\Projects\Work\PROJ\src\node_modules\material-ui-pickers\DatePicker'
     @ ./node_modules/material-ui-pickers/DatePicker/Calendar.js 40:26-57
```

```
ERROR in ./node_modules/material-ui-pickers/_shared/ModalDialog.js
    Module not found: Error: Can't resolve 'react-event-listener' in 'C:\Projects\Work\PROJ\src\node_modules\material-ui-pickers\_shared'
     @ ./node_modules/material-ui-pickers/_shared/ModalDialog.js 32:26-57
```

I see the imports in these two files:

https://github.com/dmtrKovalenko/material-ui-pickers/search?q=react-event-listener&unscoped_q=react-event-listener

Yet I see no dependency on it in the package.json, am I missing something?

**Comment by oallouch** [comment]
+1

**Comment by dmtrKovalenko** [comment]
Ha. It was included as dependency in material ui

**Comment by cherniavskii** [comment]
And it’s still included https://github.com/mui-org/material-ui/blob/2d31ad0eb3b04843fcae01a731601d9fa2b63860/packages/material-ui/package.json#L57

**Comment by oallouch** [comment]
That's weird. I had to include it myself.
Ok, no big deal.

**Comment by jackjwilliams** [comment]
Yeah, I had to too, strange

**Comment by mnesov** [comment]
@dmtrKovalenko Why did you closed the issue, is it fixed?

**Comment by mnesov** [comment]
Still have `Module not found: Can't resolve 'react-event-listener'` error, and still have to add `react-event-listener` dependency to my project.

**Comment by dmtrKovalenko** [comment]
I found the reason!
We will fix it in the next release, please do `npm i react-event-listener` for now

**Comment by dmtrKovalenko** [comment]
Closed because this was fixed in the previous release :)
