### ISSUE TITLE
Not enough documentation on DatePicker available attributes minDate and maxDate 

### ISSUE THREAD

**Issue by maxchernin** [dmtrKovalenko/material-ui-pickers#454]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  1.0.0-rc.2  |
| material-ui         | 1.0.0-beta.37 |
| React               |      16.2.0   |
| Browser             |  Chrome       |
| Platform            |   Windows 10      |

## Steps to reproduce
set the following attributes on the <DatePicker> component
1. minDate = 'today'
2. maxDate = '1 year'

## Expected behavior
being able to select dates only in the 
ranges that was inputed, the problem is that the API is not informative enough 
## Actual behavior
the pickers can select dates and move mothes forward and backwards, and switching years,
when clicking on the year number, an empty box is displayed, without the years list, this is due to the mindate and maxdate attrs,
a better documentation is required on these attrs, there is no indication whats allowed and whats not on these attrs

## Live example
`<DatePicker
              format={dateFormat || undefined}
              label='select a date'
              minDate='today'
              maxDate='2 years'
              onChange={this.updateStore}
              value={value}
              />`

**Comment by maxchernin** [comment]
I can help with docs if needed.
project has dependencies which makes package updating a low priority due to collisions with material updated library and our current code.

**Comment by dmtrKovalenko** [comment]
@maxchernin yep it could be fine. I think about some article about accepted formats for each of date library.

**Comment by dmtrKovalenko** [comment]
Fixed https://material-ui-pickers.firebaseapp.com/parsing
