### ISSUE TITLE
Adding an icon to the DatePicker 

### ISSUE THREAD

**Issue by noucles** [dmtrKovalenko/material-ui-pickers#46]
Hello I wanted to know if there is a way to add an icon next to the date shown in the DatePicker just like the Custom DateTimePicker shown in the demo.

![image](https://user-images.githubusercontent.com/7742038/32666554-c5cb79f4-c605-11e7-85d2-8015b8342f2f.png)

**Comment by dmtrKovalenko** [comment]
https://github.com/dmtrKovalenko/material-ui-pickers/blob/5a749bbb3028375de7497af1de9693a5d90bdd82/docs/src/Demo/Demo.jsx#L152

**Comment by noucles** [comment]
Awesome, works perfectly. Thank you.
