### ISSUE TITLE
Format date with Redux-Form = Invalid Date

### ISSUE THREAD

**Issue by hugol1ma** [dmtrKovalenko/material-ui-pickers#464]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   1.0.0-rc.9      |
| material-ui         |     1.2.1    |
| moment        | 2.22.2 |
| React               |    16.3.2     |
| Browser             |    Firefox/Chrome     |
| Platform            |   Linux     |

## Steps to reproduce
1. Create DatePicker component with attr format="DD/MM/YYYY"
2. Integrate with redux-form

## Expected behavior

1 - Return valid date when select any date from picker
2 -  Attribute "format" doenst change from DD/MM/YYYY to MM/DD/YYYY (on blur event)

## Actual behavior

When select any date the day is greater than 12 and blur input show message: "Invalid date" and format pattern change from DD/MM/YYYY to MM/DD/YYYY
If select any day less or equal 12 works but format change day with month. (DD/MM/YYYY to MM/DD/YYYY)

## Live example

Example issue:
https://codesandbox.io/s/nwn73rz8nj
Example without redux-form (works fine):
https://codesandbox.io/s/vv7vnz60m7

**Comment by dmtrKovalenko** [comment]
https://codesandbox.io/s/xv4p6j0nq4
I forked your sandbox - and here everything fine.

Please note that redux-form `<Field />` has its own property called format, its a function. So if you want to pass format to the redux form`s field you need to add additional property to forward
