### ISSUE TITLE
Request for a Date-Time-Range Picker

### ISSUE THREAD

**Issue by mayhs19** [dmtrKovalenko/material-ui-pickers#47]
I love the way , on the "Date & Time picker" how the date , the hour and then the minute options seamlessly translate on the UI. I would be happy to see a Date&Time range Picker that would aid it picking a Timestamp range without using two separate pickers. Somethig similar to this but WITH TIME included

http://airbnb.io/react-dates/?selectedKind=DateRangePicker%20%28DRP%29&selectedStory=default&full=0&down=1&left=1&pa
nelRight=0

Let me know what you think. Thanks !

**Comment by dmtrKovalenko** [comment]
Hello!
Actually I have plans about implementing material design date (just only date) range picker as separate library with a peer of material-ui-pickers. But it was just plans for the future, and now I`m working on this project reliability now. But if there would be much requests for range pickers, maybe will work on them recently.
So I will live this issue open and link that, maybe from documentation, to check if range pickers is really need.

**Comment by yuchi** [comment]
Was this implemented?

**Comment by duongdev** [comment]
@dmtrKovalenko please implement this feature

**Comment by hrafaelveloso** [comment]
@dmtrKovalenko that would be awesome! I'm using two Datepickers now, side by side, but if there's one easier way to do it, I'm all in

**Comment by vishalrajole** [comment]
@dmtrKovalenko date range picker support would be great addition. I am also looking for date range picker with material ui
