### ISSUE TITLE
Broken calendar in case of null or empty value provided

### ISSUE THREAD

**Issue by igorlesnenko** [dmtrKovalenko/material-ui-pickers#472]
If value provided to datepicker is empty string or null it results to a broken calendar (see screenshot)

```js
<DatePicker
  value={null}
/>
```
![image](https://user-images.githubusercontent.com/466991/41468496-4a10d618-70bb-11e8-9244-b99737894e0b.png)

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   rc.10      |
| material-ui         |   1.2.1      |
| React               |    16.3.2     |
| Browser             |   Chrome     |
| Platform            |    Mac     |

## Steps to reproduce
1. Create DatePicker field with null value
2. Open DatePicker

**Comment by dmtrKovalenko** [comment]
Duplicate #414

**Comment by igorlesnenko** [comment]
I'm using date-fns ^2.0.0-alpha.7 but still see the issue if null of empty string provided as value
