### ISSUE TITLE
Why the picker is using `Paper` to build the layout?

### ISSUE THREAD

**Issue by dnaranjo89** [dmtrKovalenko/material-ui-pickers#474]
## Description
I've overriden the default Mui theme with a bunch of simple changes, being one of them the addition of a small padding por the Papers. But doing that is breaking the layout of the pickers :/

Why is the picker using Papers to build the layout? Is it really necessary or could styled divs be used instead?

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.10     |
| material-ui         |    1.1.0     |
| React               |    16.3.1     |
| Browser             |   chrome      |
| Platform            |   mac      |

## Steps to reproduce
1. Override MuiPaper
```
const theme = createMuiTheme({
  overrides: {
    MuiPaper: {
      root: {
        padding: '0.125rem 1rem',
      },
    },
  },
});
```
2. Open a picker

## Expected behavior
![image](https://user-images.githubusercontent.com/9324508/41503515-c3b6b4bc-71d6-11e8-92b8-5674b45dcc43.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/9324508/41503509-aec9ffc8-71d6-11e8-900a-c0bfc3e5cdea.png)

## Live example
https://codesandbox.io/s/vqz0vm4ryl

**Comment by dmtrKovalenko** [comment]
Because we need a shadow at the bottom of toolbar.
