### ISSUE TITLE
MaskedInput not registering input in React 16.4

### ISSUE THREAD

**Issue by nzacca** [dmtrKovalenko/material-ui-pickers#475]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |1.0.0-rc.10         |
| material-ui         |1.2.1         |
| React               |16.4.1         |
| Browser             |N/A         |
| Platform            |N/A        |

## Steps to reproduce
1. Create a DatePicker with mask with React 16.4.1
2. Attempt to type in the box.

## Expected behavior
When I type into input the value should register.

## Actual behavior
Value is being cleared immediately thus appearing as if the input is readonly.

## Live example
https://codesandbox.io/s/wnljy6rkok

Notes:
I reported a similar issue on the Formik library as well. Without digging into it much, my hunch is that it may be related to the changes to `getDerivedStateFromProps` in React 16.4 where this now fires on every render.

Also note, this does work if you choose a date first from the picker. This also works using React 16.3.

**Comment by waclock** [comment]
I'm currently facing a similar issue. I tried downloading the docs project (the website where the docs are stored), and if I try using the options mask + keyboard, when I click on the calendar option and then click "OK", the input value won't update, even though I can see the state of the component did change. I could not get the DatePicker with mask + keyboard to work, neither with React 16.4.1 nor 16.3.

**Comment by TioRuben** [comment]
@waclock Problem comes with react-text-mask. When PR is approved, the problem should fix. 
[https://github.com/text-mask/text-mask/issues/806](https://github.com/text-mask/text-mask/issues/806)
While PR approves, you can downgrade react-text-mask to older version.

**Comment by waclock** [comment]
@TioRuben Thank you, that was indeed the issue. It seems like the PR might be approved in the next days, so I'll just wait for the new release to come. Thanks again.

**Comment by DTupalov** [comment]
@TioRuben I've looked at the example, and see that [MaskedInput](https://github.com/dmtrKovalenko/material-ui-pickers/blob/master/lib/src/_shared/MaskedInput.jsx) pass `value="Unknown"` into `reactTextMask` component. Is this normal? `"Unknown"` value with mask `[/\d/, /\d/, "/", /\d/, /\d/, "/", /\d/, /\d/, /\d/, /\d/]` will display as empty value. It's not problem of `reactTextMask` lib in this case.

**Comment by TioRuben** [comment]
Ok, I guess @nzacca issue and (@waclock && me) issue are different. Ours is fixed with your PR, but the codesandbox example from @nzacca has a different behaivour than we experienced.

**Comment by AmanShurafa** [comment]
@waclock @TioRuben I experienced the same issue and was able to work around it by passing:
```
InputProps={{
  inputProps: {
    readOnly: false
  }
}}
```

**Comment by TioRuben** [comment]
@AmanShurafa this doesn't work for me, as the input mask doesn't show. I can pick the date, and manually enter it, but whithout the __/__/__ mask. Does this work for you?

**Comment by nzacca** [comment]
@TioRuben Try this instead:
```
InputProps={{
  inputProps: {
    mask: (value: Date) => (value ? [/\d/, /\d/, "/", /\d/, /\d/, "/", /\d/, /\d/, /\d/, /\d/] : []),
    readOnly: false,
    placeholderChar: "\u2000"
  }
}}
```

**Comment by nzacca** [comment]
@dmtrKovalenko #497 does not appear to have fixed this issue. I have updated the sandbox here with the latest material-ui-pickers (rc11) and material-ui (1.4.0) versions:

https://codesandbox.io/s/2xk3v45lr

**Comment by nzacca** [comment]
@dmtrKovalenko Could you kindly share which release fixes this issue? I have updated the sandbox example again with all of the latest versions and I'm still unable to type into the input box.

https://codesandbox.io/s/vyk5z3j3l

Please advise.
