### ISSUE TITLE
@material-ui/icons not supported

### ISSUE THREAD

**Issue by dustingraves** [dmtrKovalenko/material-ui-pickers#476]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.10     |
| `@material-ui/core`   |    1.2.1     |
| `@material-ui/icons` |   1.1.0   |
| React               |    16.4.1     |
| Browser             |   Chrome      |
| Platform            |     OS X 10.13.5    |

## Steps to reproduce
1. Copy and paste DateTimePicker example

## Expected behavior

Tabs should be icons
## Actual behavior

Tabs have cutoff text
## Live example
![image](https://user-images.githubusercontent.com/6600627/41519247-db6d48dc-727b-11e8-9796-c03681523b71.png)

**Comment by dmtrKovalenko** [comment]
Please read installation guide one more timr

**Comment by dustingraves** [comment]
I was just about to come back and close this as I did read the docs again. I think you should show in the examples using `@material-ui/icons`

```javascript
import DateRange from '@material-ui/icons/DateRange'
import AccessTime from '@material-ui/icons/AccessTime'

<DateTimePickerComponent
 dateRangeIcon={<DateRange />}
 timeIcon={<AccessTime />}
  //... other props
/>
```

**Comment by dmtrKovalenko** [comment]
Yes, you are right I will add an example with svg icons in the installation guide

**Comment by fonziemedia** [comment]
Just what I was looking for, thanks!
