### ISSUE TITLE
Runtime errors when rendering pickers in rc10

### ISSUE THREAD

**Issue by erickrawczyk** [dmtrKovalenko/material-ui-pickers#477]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc.10 |
| material-ui         | 1.2.1 |
| React               | 16.3.2 |
| Browser             | Chrome 66.0.3359.181 |
| Platform            | macOS 10.13.2 |

## Steps to reproduce
1. Create a basic `DatePicker` component with `value` state and `onChange` method (as seen in the [quick start guide](https://material-ui-pickers.firebaseapp.com/usage))
2. Observe errors during runtime

## Expected behavior
Expected behavior should be for the DatePicker to render without error

## Actual behavior
Fails to render with the following runtime errors:
```
TypeError
Cannot read property 'date' of undefined
```
```
Warning: Failed prop type: The prop `date` is marked as required in `DateTimePicker`, but its value is `undefined`.
```

## Live example
https://codesandbox.io/s/71w30mv8zj

/cc @millerized @tendrid

**Comment by erickrawczyk** [comment]
Wait I think i figured it out. I was importing the inner component.

```js
import {DateTimePicker} from 'material-ui-pickers/DateTimePicker/DateTimePicker.js';
```

instead of 
```js
import {DateTimePicker} from 'material-ui-pickers/DateTimePicker/index.js';
```

**Comment by dmtrKovalenko** [comment]
@erickrawczyk you can import just 
```jsx
import DateTimePicker from 'material-ui-pickers/DateTimePicker'
```

**Comment by erickrawczyk** [comment]
@dmtrKovalenko yeah that was totally it. My lint rules required full paths and I imported the inner `DateTimePicker` component by accident. Thanks for the help!
