### ISSUE TITLE
Ability to show an empty label if value is empty

### ISSUE THREAD

**Issue by royk** [dmtrKovalenko/material-ui-pickers#479]
Right now when value is null or undefined, current date is shown. There is no way to have an empty field (workarounds using labelFunc cause 'invalid date format' to appear).

There should be an option to show an empty field if value is empty.

**Comment by anthonyraymond** [comment]
If the `value` is equal to `null` no date is shown.

**Comment by dmtrKovalenko** [comment]
You can use mask as function for this case? 
Will it solve your problem?

**Comment by dmtrKovalenko** [comment]
Close due to `null` as default value works as expected

**Comment by vdsabev** [comment]
To expand on the author's response, there's an important distinction:
- Using `value={null}` makes the datepicker empty
- Using `value={undefined}` makes the datepicker show today's date

I struggled with this for a while, hopefully it helps someone else!

😉
