### ISSUE TITLE
IconButton tabIndex in keyboard mode

### ISSUE THREAD

**Issue by scristall** [dmtrKovalenko/material-ui-pickers#480]
The IconButton created in the BasePicker's keyboard mode gets a default tabIndex of "0" which causes the IconButton to be the next focused element after tabbing from the TextField.  For my application at least, this is never desired.  Consider setting the tabIndex to "-1" or creating an interface of some kind to control it.

**Comment by dmtrKovalenko** [comment]
I am not actually sure that its an issue, You can add your own props to input adromnet with InputAdornmentProps. But now focus flow is actually right

**Comment by wieseljonas** [comment]
This doesn't work with keyboad mode I cannot set tabIndex on `IconButton`

**Comment by giacomocusinato** [comment]
This would solve the issue: `KeyboardButtonProps={{ tabIndex: "-1" }}`

**Comment by Duelbat** [comment]
> KeyboardButtonProps={{ tabIndex: "-1" }}

No, this does not work.
