### ISSUE TITLE
Introduce defaultValue propertie

### ISSUE THREAD

**Issue by anthonyraymond** [dmtrKovalenko/material-ui-pickers#481]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.10     |
| material-ui         |    1.2.0     |
| React               |    NR     |
| Browser             |    NA     |
| Platform            |     NA    |

## Steps to reproduce
1. Add a `<DatePicker>`
2. It's populated with todays date

## Expected behavior
IMO it' would be nicer to have something like that :
<DatePicker defaultValue={new Date()} />
and set default value for `value` attribute to null.

Since the `DatePicker` triggers `onChange` only when leaving the field, maintaining the `value` attribute according to the internal state value is a pain in the ***.
And if the value does not matches the visual value, errors wont shows up under the field.

So, i feel like having a default value argument will be helpfull.

**Comment by dmtrKovalenko** [comment]
Would you like to open a PR?

**Comment by dmtrKovalenko** [comment]
InitialFocusedDate was introduced
