### ISSUE TITLE
Setting default date value doesn't allow date to update

### ISSUE THREAD

**Issue by bg87** [dmtrKovalenko/material-ui-pickers#482]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.9     |
| material-ui         |    1.0.0     |
| React               |     16    |
| Browser             |    Chrome     |
| Platform            |     mac os    |

## Steps to reproduce
1. set initial date in state
2. use date from state object on value attribute of DatePicker
3. update date picker with onChange

## Expected behavior

Expected the date passed to onChange handler to be the new selected date

## Actual behavior

The date passed to onChange handler is the date set in state

Basically, I want to set a default date and update that date if the user selects a new date. I can't update state though because DatePicker passes the original value to onChange. It updates the UI, you can see the new date, but you can't update the value in state.

See working example here:
https://codesandbox.io/s/o56kxp3226

```
state = {
    run_date: moment('2018-05-12'),
  }

  handleDateChange = (date) => {
    this.setState({ run_date: moment(date) })
  }


<Grid item>
            <MuiPickersUtilsProvider utils={MomentUtils}>
              <DatePicker
                className={classes.datePicker}
                margin="normal"
                keyboard
                format="MM/DD/YYYY"
                disableFuture
                autoOk
                mask={value => (value ? [/\d/, /\d/, '/', /\d/, /\d/, '/', /\d/, /\d/, /\d/, /\d/] : [])}
                value={this.state.run_date}
                onChange={this.handleDateChange}
                disableOpenOnEnter
                animateYearScrolling={false}
              />
            </MuiPickersUtilsProvider>
          </Grid>
```

**Comment by oddlyfunctional** [comment]
@bg87 How did you solve this? Is it in a new release?
