### ISSUE TITLE
Date picker broken

### ISSUE THREAD

**Issue by arshtepe** [dmtrKovalenko/material-ui-pickers#484]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     +    |
| material-ui         |         |
| React               |         |
| Browser             |         |
| Platform            |         |

## Steps to reproduce
1. 
``` js
import { DatePicker } from 'material-ui-pickers'
```
I have error:
`Module not found: Can't resolve '@material-ui/core/Button' `

## Live example
https://codesandbox.io/s/2r200k6pn

**Comment by dmtrKovalenko** [comment]
Install material-ui/core it’s a peer dependency

**Comment by HenriqueDerosa** [comment]
The documentation could be improved to avoid this kind of problem.
- must install `@material-ui/core` and `@material-ui/pickers`.
- must install `@date-io/{your-date-library}`

In the second point I also had problems with the version, I had to downgrade it to `^1.3.13`.
