### ISSUE TITLE
Problem with mask input

### ISSUE THREAD

**Issue by remy-poirier** [dmtrKovalenko/material-ui-pickers#494]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.10     |
| material-ui         |   @material-ui/core 1.2.1     |
| React               |     16.4.1    |
| Browser             |   67.0.3396.99   |
| Platform            |         |

## Steps to reproduce
1. Use an input with Mask
2. Try to pick a date from Datepicker by clicking on the icon

## Expected behavior
The Date should update

## Actual behavior
Date doesn't update

## Live example
You can see a live example on the website documentation: https://material-ui-pickers.firebaseapp.com/demo/datepicker

Try to pick a date from datepicker, it won't work. 
What can I do to fix this in my app ?

And I have one more question, can I pass null to default date ? Because if I do so, validation method is not called, neither onChange method.

Any ideas ?

**Comment by diegorodriguesvieira** [comment]
+1

**Comment by remy-poirier** [comment]
Oh so you think these two issues are related ? Because in this issue, the problem seems to be that mask input isn't shown, whereas my problem is that I can type in the mask, but value is not updated at the end, like on the demo + when I pick a date from the picker (by clicking on the calendar, date is not updated).

Anyway, I hope this will be fixed soon, is there a workaround to get it to work ?

**Comment by mbeneyto** [comment]
Same problem here, it seems like the date picked from the calendar is not set correctly to the masked input because if you open again the calendar, the value is correctly saved on it.
