### ISSUE TITLE
Date picker should allow keyboard entry when null or cleared

### ISSUE THREAD

**Issue by jazeee** [dmtrKovalenko/material-ui-pickers#495]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     1.0.0.rc.10    |
| material-ui         |     1.1.0    |
| React               |   16.4      |
| Browser             |    Chrome     |
| Platform            |     All    |

## Steps to reproduce

1. Open https://codesandbox.io/s/2x3l5m06o0
2. Attempt to type in input field

Observe no character entry
Expect character entry shows up.

Also: 
1. Click date picker icon
2. Choose a date and OK
3. Click date picker icon
4. Click Clear
5. Attempt to type in input field.

Observe no character entry
Expect character entry shows up.

## Live example
https://codesandbox.io/s/2x3l5m06o0

**Comment by jazeee** [comment]
Related to #470

**Comment by jazeee** [comment]
Note, rolling back in the example to `1.0.0.rc.9` seems to work.
However, in my local app, using `moment`, I still see the bug.

**Comment by dmtrKovalenko** [comment]
Fixed by https://github.com/dmtrKovalenko/material-ui-pickers/pull/499/commits/44b0de3002db586f16fcc8e7b7718bc93c1ae215

**Comment by jazeee** [comment]
Tested locally. Verified as fixed.

**Comment by PiotrSzlagura** [comment]
The same issue occurs in my case.

Tech | Version
-- | --
material-ui-pickers | 1.0.0.rc.11
material-ui | 1.4.0
React | 16.4.1
Browser | Chrome
Platform | All

Rolling back to 1.0.0.rc.9 did not help
I also use moment in this example.

**Comment by PiotrSzlagura** [comment]
Also, the same issue occurs on demo page:
https://material-ui-pickers.firebaseapp.com/demo/datepicker

Try clearing one of inputs, focus out, re-focus and start typing. You'll see that nothing happens.

**Comment by dmtrKovalenko** [comment]
@PiotrSzlagura there is no way to type to the first example - there `keyword={false}`.
And everything fine on `Keyboard input` section

**Comment by PiotrSzlagura** [comment]
@dmtrKovalenko try doing it on "Masked input" in "Keyboard" section.
BTW with uncontrolled input, this issue does not occur...

**Comment by PiotrSzlagura** [comment]
Sorry, I just realised that this error only occurs on MacOS. Tested on Windows now and indeed everything is fine there.

**Comment by PiotrSzlagura** [comment]
@dmtrKovalenko is there any possible workaround for it?
