### ISSUE TITLE
alignment bug with today button in IE11

### ISSUE THREAD

**Issue by ahce** [dmtrKovalenko/material-ui-pickers#496]
Today button need same fix: https://github.com/dmtrKovalenko/material-ui-pickers/pull/267
When showTodayButton is set to true, third button appears in DialogActions container.
First one is aligned to left side by setting margin-right to auto. This doesn't work in IE11.

## Expected behavior
![image](https://user-images.githubusercontent.com/12452003/42187451-1b20ba1a-7e1e-11e8-8868-c7cc936affc5.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/12452003/42187420-097f1f86-7e1e-11e8-9369-c92b5af22838.png)

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc11 |
| material-ui         | 1.3.1 |
| React               | 16.4.1 |

**Comment by dmtrKovalenko** [comment]
Please be descriptive.

**Comment by ahce** [comment]
@dmtrKovalenko Updated.

**Comment by dmtrKovalenko** [comment]
I am sorry but I have no chance to fix that, because have no windows machine available 🙁. I will close this issue because actually IE is smoked supported by everybody. But if it is critically for you feel free to open a PR.
