### ISSUE TITLE
Presentation issue

### ISSUE THREAD

**Issue by jamesskyoung** [dmtrKovalenko/material-ui-pickers#5]
You library looks promising... but this is what I get *(using the latest MUI beta)

![selection_177](https://user-images.githubusercontent.com/13589738/31990842-204c1f54-b96e-11e7-8ef4-9c40423599c9.png)

Thanks!

**Comment by dmtrKovalenko** [comment]
The issue is - you are not using both Roboto and Material-ui-icons font. Please check 
https://github.com/dmtrKovalenko/material-ui-pickers/blob/e109c3e2b706977cfece791b2d06941674d13443/docs/public/index.html#L13

**Comment by jamesskyoung** [comment]
That did it   Great  tx!
