### ISSUE TITLE
Request for formating date label hook

### ISSUE THREAD

**Issue by AlexzundeR** [dmtrKovalenko/material-ui-pickers#50]
In my case I would like to have a hook to change label formatting after date selection. For example to use moment method .fromNow() or someone else. 
How I see you have an inner date object that store the selected date, and it passed to onchange method. Maybe it is possible to store a second object for the view task.
Thank you for the great package!

**Comment by dmtrKovalenko** [comment]
As from my point, you need to know which date was displaying until accept? Can you provide more details about what you need. Thanks

**Comment by AlexzundeR** [comment]
I need a second form of the format property - the function that have in input the accepted date and in output returns formatted date.

**Comment by dmtrKovalenko** [comment]
For now text field doesn't updates until the user submits the input, so the user see previous date. I'm actually cannot figure out why do someone need to have an up-to-date view in the text field under the modal background.

**Comment by AlexzundeR** [comment]
No no no. I say about a submitted date, after the ok click. But I need a mechanizm to format output date in function (to call moment.fromNow method for example), not by passing a format string.
Sorry if I confused you.

**Comment by dmtrKovalenko** [comment]
Oh we have added the `labelFunc` prop to all pickers, you can check how it works on the demo page, in the `CustomElements` section in week picker. (If you havent this section please clean all the site data, that was cached by service worker 😕 )

**Comment by AlexzundeR** [comment]
Hmmm.. It's so strange, I tried to use this hook yesterday, but it had no effect. I will try it one more time today and give you a feedback. Thank you.

**Comment by AlexzundeR** [comment]
It works fine, thank you!
