### ISSUE TITLE
Add onAccept as a prop (null value after onChange triggers)

### ISSUE THREAD

**Issue by dabyland** [dmtrKovalenko/material-ui-pickers#504]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.11     |
| material-ui         |    1.2.2     |
| React               |    16.3.11     |
| Browser             |     Chome    |
| Platform            |    Mac     |

## Steps to reproduce
1. Add value that is accepted through onChange
2. Clear out value

## Expected behavior

I would expect to have the field clear out with no error at all. I should be able to enter a null value even after a value was accepted.

## Actual behavior

onChange never triggers as it's only fired upon an accepted value. Wondering if there's a workaround or possibly have an `onAccept` as well as `onChange`, each acting how they normal do with no tweaked behavior?

[See behavior here](https://media.giphy.com/media/c80MSdFWL9CnvepBls/giphy.gif)

## Live example

You can see in this [codepen](https://codesandbox.io/s/3wrzrlrx1). Nothing is really changed and I understand this is the default behavior but I should be able to have a null value even after one is accepted.

**Comment by anthonyraymond** [comment]
i used the `onClear`, but i agree that `onChange` should trigger when the field is clear

**Comment by dmtrKovalenko** [comment]
Closed due to wont be implemented
