### ISSUE TITLE
Cannot Access "mask" parameters?

### ISSUE THREAD

**Issue by kyledgreen** [dmtrKovalenko/material-ui-pickers#505]
I wanted to use the keepCharPositions prop for the MaskedInput component but I cant figure out how to get the prop down to the component or if it has not been exposed by the DateTextField component yet.
The addtional props could be accepted here: https://github.com/dmtrKovalenko/material-ui-pickers/blob/c02a0f2f68a3c463b3b271378dd80e522363bc72/lib/src/_shared/DateTextField.jsx#L298
or should the props for mask be spread in here?: https://github.com/dmtrKovalenko/material-ui-pickers/blob/c02a0f2f68a3c463b3b271378dd80e522363bc72/lib/src/_shared/DateTextField.jsx#L330

mask documentation: https://github.com/text-mask/text-mask/blob/master/componentDocumentation.md#readme

**Comment by rusomirt** [comment]
This method worked for me:
```javascript
<DatePicker
    ...
    InputProps={{
        inputProps: {
            mask: ...,
            keepCharPositions: true,
        }
    }}
    ...
/>
```

**Comment by kyledgreen** [comment]
That mostly works as a workaround, it overrides the localInputProps.inputProps completely which does some checking of keyboard input: 
inputProps: {
        mask: !keyboard ? null : mask,
        readOnly: !keyboard,
      },

but it should work for my use case, thank you.

**Comment by nikolayg** [comment]
This no longer works with `@material-ui/pickers` `3.1.0`.

For example, in the following code `keepCharPositions` does not take effect:


```
    <KeyboardDatePicker
      autoOk={false}
      variant="inline"
      label={"Test"}
      format={"dd/mm/yyyy"}
      inputValue={"12/12/1900"}
      value={null}
      InputAdornmentProps={{ position: "end" }}
      placeholder={"__/__/____"}
      onChange={(_date, value) => {
        console.log(value);
      }}
      InputProps={{
        inputProps: {
          keepCharPositions: true
        }
      }}
    />
```
