### ISSUE TITLE
Dependency seems to be vulnerable (Prototype pollution attack )

### ISSUE THREAD

**Issue by schmolst** [dmtrKovalenko/material-ui-pickers#506]
Your latest version rc11 seems to depend on a vulnerable lib:
nsp check
(+) 1 vulnerability found

material-ui-pickers@1.0.0-rc.11 >  codecov@3.0.3 > request@2.81.0 > hawk@3.1.3 > hoek@2.16.3

Prototype pollution attack 
Name: hoek 
CVSS 4 (Medium)
Installed  2.16.3 
Vulnerable <= 4.2.0 || >= 5.0.0 < 5.0.3 
Patched > 4.2.0 < 5.0.0 || >= 5.0.3
Path material-ui-pickers@1.0.0-rc.11 >  codecov@3.0.3 > request@2.81.0 > hawk@3.1.3 > hoek@2.16.3
More Info https://nodesecurity.io/advisories/566    

I would be very glad if you update your deps.

TIA
Steffen

**Comment by cherniavskii** [comment]
Hi Steffen,
thanks for opening the issue.

Please note, that `hoek` is used by `codecov`, which is dev dependency and shouldn't impact users' security.

Also, `request` doesn't longer depend on `hawk` - see https://github.com/request/request/blob/master/CHANGELOG.md#v2870-20180521

Finally, we're using request@2.87.0 on current master
https://github.com/dmtrKovalenko/material-ui-pickers/blob/c02a0f2f68a3c463b3b271378dd80e522363bc72/lib/package-lock.json#L10836-L10840

So it's already fixed and npm warning will disappear in next release.

**Comment by schmolst** [comment]
Thanks!!!!
