### ISSUE TITLE
Cant applie format in the MuiPickersUtilsProvider 

### ISSUE THREAD

**Issue by PatrickSannes** [dmtrKovalenko/material-ui-pickers#507]
## Environment
| material-ui-pickers | 1.0.0-rc.11 |
| material-ui         | 1.3.1 |
| React                 | 16.3.2  |
| Browser             | Latest chrome |
| Platform            | Windows   |
| Momentjs          | 2.22.2      |

## Steps to reproduce
1. Add a format to the MuiPickersUtilsProvider when using moment.js
2. Add a datepicker to a page

## Expected behavior
Having the format applied to all date components

## Actual behavior
No format is applied to the date components

## Live example
For some reason I dont get the MuiPickersUtilsProvider working on codesandbox, sorry.

**Comment by dmtrKovalenko** [comment]
Please provide an example of issue reproducing.
We don’t have time to reproduce your issue

**Comment by PatrickSannes** [comment]
I would love to do so, but getting the base libs working with the updated versions does not work.
https://codesandbox.io/s/lxom1kzx4q

**Comment by dmtrKovalenko** [comment]
Follow the installation guide

**Comment by PatrickSannes** [comment]
Got it working with an other example. Will see if I can figure out why my initial did not work.

Setting format works in this example on the specific item: https://codesandbox.io/s/yjnjv5q6n1

When setting on the MuiPickersUtilsProvider it does not work: https://codesandbox.io/s/l77qnqqq4q
