### ISSUE TITLE
Control over theme / css classes

### ISSUE THREAD

**Issue by danmce** [dmtrKovalenko/material-ui-pickers#51]
Is there a way of altering the theme for specific elements, I understand that the background color of the date pickers toolbar is using theme.palette.primary[500], if the theme is light, but if I wanted to use a different color how would I go about doing this (aside from altering the palettes primary color)?

**Comment by dmtrKovalenko** [comment]
There is no way currently.
I`ve known that some time we would need to implement the classes api for pickers. 
Actually I cant promise you anything, but will try to implement that in one of beta releases)
If you wont to open pull request, you are welcome)

**Comment by dmtrKovalenko** [comment]
As the variant you can override the whole theme of picker, by wrapping it in the custom `MuiThemeProvider`

**Comment by dmtrKovalenko** [comment]
@all 🎉  We have such ability, but I didn`t know about that - just refer  [here](https://material-ui-pickers.firebaseapp.com/guides/css-overrides) is an example of how to override particular control
