### ISSUE TITLE
Custom day element - Example based on moment.js

### ISSUE THREAD

**Issue by TheRealArlie** [dmtrKovalenko/material-ui-pickers#513]
Hi guys,

I love your pickers. Thanks for sharing them with the community!!!

I adapted your example for Custom day elements to work based on moment.js. Maybe you like to reference it anywhere in case someone else is searching for this solution that does not need date-fns.

https://codesandbox.io/s/mozqv539lp

**Comment by dmtrKovalenko** [comment]
Thank you :)

**Comment by dmtrKovalenko** [comment]
Added https://material-ui-pickers.firebaseapp.com/demo/datepicker
