### ISSUE TITLE
Need a possibility to change the first day of week

### ISSUE THREAD

**Issue by yaminyaylo** [dmtrKovalenko/material-ui-pickers#515]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.11     |
| material-ui         |    1.4.0     |
| React               |    16.4.0     |
| Browser             |     Chrome 67    |
| Platform            |   Windows 10      |

## Expected behavior

There is an API to change the first day of week (Monday or Sunday).

## Actual behavior

Only Sunday for now.

**Comment by dmtrKovalenko** [comment]
Actually this will works depends on user locale. If you have a locale with 1 day of week Monday - you will see the Monday as first day

**Comment by cherniavskii** [comment]
Yep, it depends on locale of your date utils. Configure your locale properly and it should be good.
That's out of `material-ui-pickers` scope.

**Comment by yaminyaylo** [comment]
OK, thanks!

**Comment by riccardogiorato** [comment]
How can I set the right locale to have the first day of the week as Monday?
