### ISSUE TITLE
24h support

### ISSUE THREAD

**Issue by sakulstra** [dmtrKovalenko/material-ui-pickers#52]
Hay, we'd like to use this package, but 24h format support would be a crucial feature for us.
I've seen it's already planned in the readme. Not sure if i'll find time the coming days, but is there already a wip-branch somewhere to contribute to? Eventually one could look at https://github.com/TeamWertarbyte/material-ui-time-picker/blob/master/src/Clock.js#L218 how they solved it.

Best Regards,
Lukas

**Comment by dmtrKovalenko** [comment]
I am on it 😎 
Will try to implement it for beta.3

**Comment by dmtrKovalenko** [comment]
🎉 Published in 1.0.0-beta.5

**Comment by sakulstra** [comment]
@dmtrKovalenko n:icecream: , thanks a lot! :dancer: :dancer: :dancer:
