### ISSUE TITLE
Feature Request - Keyboard accessibility - open dialog on tab into input

### ISSUE THREAD

**Issue by blainegarrett** [dmtrKovalenko/material-ui-pickers#520]
I'm using the input in a spreadsheet-esque situation and it'd be great to be able to tab through the fields and auto open the pickers. I attempted to define a custom material-ui <TextField> to add the onFocus handler and call this.picker.open() via the example. However, focus appears to be called in several instances including after picking a date. Similarly, once a date is picked, the focus doesn't return to the input to tab to the next input. This issue only seems to occur when a custom TextField is defined. The focus issue does not occur when no custom TextField is defined, but then there is no handler for the input focus. An onFocus prop for the pickers that only is called when the input is first entered OR a setting to simply opening the picker on keyboard focus would be great.

Apologies if I missed an existing setting.

## Environment
Tested on chrome in ios, desktop

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     material-ui-pickers@1.0.0-rc.11    |
| material-ui         |     @material-ui/core@1.0.0    |

**Comment by dmtrKovalenko** [comment]
Actually we have the issue that was literally differentiated from this one. For more accessability someone asked to disable open picker on tabbing into input and open the modal only on Enter press

**Comment by dmtrKovalenko** [comment]
Closed due to inactivity
