### ISSUE TITLE
No way to connect label & input via `htmlFor` and `name`

### ISSUE THREAD

**Issue by LouisRitchie** [dmtrKovalenko/material-ui-pickers#523]
I would like to see (or contribute) a way to connect DatePicker labels with their input elements by setting `htmlFor` prop on the label and `name` prop on the `input` tag.

The reason I would like to see this is because `react-testing-library` uses this convention to select elements from the DOM.

Let me know what you think.

**Comment by dmtrKovalenko** [comment]
It’s already possible because of possibility to pass down all the props to material ui TextField component. So you can use

**Comment by dmtrKovalenko** [comment]
It’s already possible because of possibility to pass down all the props to material ui TextField component. So you can use inputProps and InputProps for this purpose

**Comment by LouisRitchie** [comment]
Thank you sir

**Comment by digitalkaoz** [comment]
@dmtrKovalenko @LouisRitchie can you provide me with an example?

**Comment by digitalkaoz** [comment]
```jsx
  <TimePicker
    keyboard
    label="lolcat"
    InputLabelProps={{
      htmlFor:"foo"
    }}
/>
```

doesnt render to expected `for` attribute on the label!
