### ISSUE TITLE
localize date header

### ISSUE THREAD

**Issue by sakulstra** [dmtrKovalenko/material-ui-pickers#53]
For me, the current date isn't aligned with the day in datepicker.
Seems like today is thursday the 15. of november :) on locale('de')
I guess it's due to a localized `getDayOfWeek`, but non localized getDaysOfWeek (the week is starting on sunday instead of  monday).

I'll work on a fix
![wrong_day](https://user-images.githubusercontent.com/4396533/32845092-3143e8ac-ca24-11e7-8b06-34d2896cb725.png)

**Comment by dmtrKovalenko** [comment]
Please refer the code review

**Comment by sakulstra** [comment]
*accidentally closed*
> Please refer the code review
Not sure what this means.
