### ISSUE TITLE
Time is displayed as local greenwich time on iphone safari browser

### ISSUE THREAD

**Issue by maxchernin** [dmtrKovalenko/material-ui-pickers#533]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   1.0.0-rc.8    |
| material-ui         |   1.0.0-beta.37      |
| React               |    16.2.0     |
| Browser             |    Safari     |
| Platform            |      iOS   |

## Steps to reproduce
1. enter a date in the form of "2018-04-05T10:00:00",
2. iphone location is set to israel time \ or any other time, except london utc time
3. dateformat is :   "dddd, MMMM DD YYYY, hh:mm A"

## Expected behavior
display 
Saturday, July 14 2018, 10:00 AM

## Actual behavior
the date displayed as 
Saturday, July 14 2018, 01:00 PM - which is the greenwich time for 10:00 am in israel.

this happens only on iphone safari browser
i would reproduce some code, but the sandbox env provided here is not using moment or datefn

Update 29\07\18
my problem is only on load display, if i change the time chosen it will display proper time,
im looking to overwrite your component locally on my machine,
can you provide more info as to where the input string is transformed into date object?

displayed date appears in 
https://github.com/dmtrKovalenko/material-ui-pickers/blob/develop/lib/src/_shared/DateTextField.jsx
specifically - getDisplayDate function
L13-29 which returns utils.format(date);

**Comment by maxchernin** [comment]
@dmtrKovalenko 
i can't believe no one has encountered this bug yet.
this is **critical**.

i have re-created a fresh "create-react-app" project, added the material ui pickers.
the date is displayed correctly on Chrome (windows pc), and has a 2 hours offset on a macbook ), and on iphone
this happened on macOS or iOS regardless to the browser. happens both on chrome and on safari.

**Comment by dmtrKovalenko** [comment]
@maxchernin I am sorry for long respond. But I have no idea how to reproduce this. Can you please share your local macos timezone, because this issue seems to be related for some locales. 

And please share which lib you are using - moment, date fns or luxon?

**Comment by dmtrKovalenko** [comment]
@maxchernin I have investigated the issue with timezone and have not found anything. Date fns is not care about timezones anytime its just parsing the dates. For luxon and moment passing value with timezone will render proper hour with time offset. 

So there is no inconsistency in pickers work with date. If you found the reason of such behavior feel free to add a comment and I will reopen the issue.

**Comment by zaguiini** [comment]
Going through this as well...

**Comment by dmtrKovalenko** [comment]
Please give a way to reproduce

**Comment by dovanquynh** [comment]
I have the same problem [https://codesandbox.io/s/test-time-picker-4l6l1](url)
