### ISSUE TITLE
Hard-coded default formats are specific to locale and library

### ISSUE THREAD

**Issue by Philipp91** [dmtrKovalenko/material-ui-pickers#534]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    v1.0.0-rc.11     |
| date-fns | v2.0.0-alpha.12 |

## Steps to reproduce
1. Use the libraries above (especially the newer date-fns version).
2. Switch your locale to `de` (this is not necessary to reproduce the more severe part of this bug).
3. A `DateTimePicker` with the current date (2018-07-25T19:58:35).

## Expected behavior
The output should be "25. Juli, 21:58" because my locale is `de`.

## Actual behavior
The actual output is: "July 206. 21:58"
Firstly, the locale is wrong (note that "Juli 25. 21:58", the part-by-part translation, would also be wrong).
Secondly, the number 206 is the day of year, and not the day of month.

## What goes wrong

Everything works fine with `date-fns v2.0.0-alpha.7`. Since then, they have changed the meaning of the symbols in their format strings. `material-ui-pickers` cannot (easily) keep up with this change because the date formats are hard-coded throughout the code base (e.g. [here](https://github.com/dmtrKovalenko/material-ui-pickers/blob/master/lib/src/DateTimePicker/DateTimePickerWrapper.jsx#L56)). Changing it there would break compatibility with the other two supported date libraries.
The same hard-coding also makes it difficult to globally adjust the format (without passing as a prop to every single picker instance), which is necessary to localize these formats.

## Solution idea

Ideally, the localization would work out of the box, though that is a much more difficult goal to achieve. So as a first step, it should be possible to set the default format globally, e.g. through the "utils" which users can [customize](https://github.com/dmtrKovalenko/material-ui-pickers/blob/master/lib/__tests__/DatePicker/PatchedUtils.usage.tsx#L15-L19) or the `MuiPickersUtilsProvider`.

Since the formats are not only locale-specific, but also library-specific, I suggest integrating them in the utils. The shipped version of each utils class could:

- have properties like `DateTimePicker12hFormat`, which can be overridden in sub-classes,
- if possible, retrieve a sensible locale-specific default from the underlying library (e.g. from [here](https://github.com/date-fns/date-fns/blob/master/src/locale/de/_lib/formatLong/index.js#L3-L8)),
- optionally contain locale-specific formats in the `material-ui-pickers` file, at least for the most important locales,
- fall back to the English pattern, as users can always override.

The `format` props of all pickers would then default to `undefined`, and unless they are set, the pickers would use the applicable format from the utils (instead of hard-coding a value inside the pickers' code).

Let me know what you think.

**Comment by dmtrKovalenko** [comment]
You are talking bout format in text field?

**Comment by dmtrKovalenko** [comment]
Nice catch. We should do this.  Why we did not made this before? :D

**Comment by Philipp91** [comment]
Thanks!

**Comment by Philipp91** [comment]
As a follow-up to this change, it might be worth dragging the formats hard-coded inside date-fn-utils itself (e.g. the date picker header format here: https://github.com/dmtrKovalenko/material-ui-pickers/blob/develop/lib/src/utils/date-fns-utils.js#L199) into instance-level fields so that it's easier to override just them without duplicating the surrounding code.
