### ISSUE TITLE
How to properly use DateTimePicker's shouldDisableDate?

### ISSUE THREAD

**Issue by JMV2112** [dmtrKovalenko/material-ui-pickers#538]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     1.0.0-rc.12    |
| material-ui         |    1.4.0     |
| React               |    16.4.1     |
| Browser             |         |
| Platform            |    macOS High Sierra 10.13.4     |

## Steps to reproduce
1. Follow initial installation steps
2. Render out a DateTimePicker

## Expected behavior

Not sure yet.

## Actual behavior

N/A

Per the documentation, I'm unsure of how to fully use the DateTimePicker's `shouldDisableDate` function. Are you supposed to return a single date, an array of dates or something totally different? Currently, I have an array of future dates that should be disabled and am trying to accomplish it with this property. Any help would be greatly appreciated, thanks!

**Comment by dmtrKovalenko** [comment]
It’s firing for each date and expect to return Boolean. It is mentioned in the docs

**Comment by dmtrKovalenko** [comment]
😱😱😱 It is not mentioned. We should fix that

**Comment by JMV2112** [comment]
Okay, that was another way I that I figured it could work. I appreciate your timely response!

**Comment by dmtrKovalenko** [comment]
Fixed https://material-ui-pickers.firebaseapp.com/demo/datepicker
