### ISSUE TITLE
react-transition-group issues

### ISSUE THREAD

**Issue by sakulstra** [dmtrKovalenko/material-ui-pickers#541]
I'm not quite sure if this is a material-ui-pickers issue, but when upgrading to the recent rc.12 I faced some issues due to `Can't resolve 'react-transition-group/CSSTransitionGroup' in '(...)/node_modules/react-addons-css-transition-group'`. I solved it by manually installing an older version of react-transition-group(1.x). I don't know much about transitions, but I guess the solutions are:
1. use `react-transition-group` directly as `react-addons-css-transition-group` tries to access an outdated version of `react-transition-group` or
2. add `react-transition-group`@1.x to dev dependencies.

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  latest      |
| material-ui         |    latest     |
| React               |    latest     |

**Comment by benneq** [comment]
I guess that `react-addons-css-transition-group` should be removed, because it is deprecated.

See: https://www.npmjs.com/package/react-addons-css-transition-group

Though I'd say, that material-ui-pickers should depend on `react-transition-group` version `2.x`
