### ISSUE TITLE
Static <Calendar /> transitons broken

### ISSUE THREAD

**Issue by lesleychard** [dmtrKovalenko/material-ui-pickers#544]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |1.0.0-rc.12|
| material-ui         |1.4.2|
| React               |16.3.2|
| Browser             |Chrome|
| Platform            |MacOSX|

## Steps to reproduce
1. Render a static `<Calendar />`
2. Scroll through months using arrow buttons.

## Expected behavior
- Month names should not be visible as they scroll past the `<CalendarHeader />`. 
- Day numbers should not be visible as they scroll past the `transitionContainer`.

## Actual behavior
- Month names are visible outside of `<CalendarHeader />`.
- Day numbers either have broken transitions or are visible outside of `transitionContainer`.

## Live example
https://codesandbox.io/s/qqrjpzwry4
Note that this is [also broken on the doc site](https://material-ui-pickers.firebaseapp.com/guides/static-pickers).

I understand if you do not want to make this behaviour universal, but as it stands now I cannot customize a static Calendar to behave the way I described above.

I can easily force the behaviour I want for the day numbers by adding `overflow: hidden` to `transitionContainer`, but I cannot pass a custom `className` to `<CalendarHeader />` inside the `<Calendar />` component.

So, a possible solution would be adding a new `classes` key or adding a new prop `CalendarHeaderProps` to `<Calendar />`.

(P.S. Love the project so far - have implemented a date range picker using the static `<Calendar />` component and it is divine.)

**Comment by cherniavskii** [comment]
Hi Lesley,
AFAIK adding `overflow: hidden` to `Paper` would be enough:

https://codesandbox.io/s/7oxq13m2v6
