### ISSUE TITLE
With ampm set to false on DateTime picker; hour clock face still only goes up to 12

### ISSUE THREAD

**Issue by gunderjt** [dmtrKovalenko/material-ui-pickers#545]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     ^1.0.0-rc.12    |
| material-ui         |    ^1.2.2     |
| React               |     ^16.3.0    |
| Browser             |    Chrome 66.0.3359.181     |
| Platform            |         |

## Steps to reproduce
1.  Set up DateTime picker with ampm={false}
2. Click on Time tab

## Expected behavior
24 hour clock face to have all 24 hours available to select;  Same behavior as the Timepicker 24 hour example

## Actual behavior
Only 12 is selectable/shown.

## Live example
The demo currently has this bug as well.  https://material-ui-pickers.firebaseapp.com/demo/datetimepicker

Under basic usage, the middle example.

**Comment by cherniavskii** [comment]
Closed by #557
