### ISSUE TITLE
No option to style DateTextField?

### ISSUE THREAD

**Issue by wederer** [dmtrKovalenko/material-ui-pickers#546]
Could you add an example in the documentation on how to style the DateTextField?
E.g. font-size

Looking at the example at: https://material-ui-pickers.firebaseapp.com/guides/css-overrides I can't find the appropriate classname.

**Comment by dmtrKovalenko** [comment]
The className or classes property will be applied to textfield because of passing down to material ui textfield. So you can style it the same as material ui TextField

**Comment by MareoRaft** [comment]
dmtrKovalenko seems to be correct.  Here is what worked for me:

                <DateTimePicker
                    value={value}
                    onChange={this.props.onInputChange}
                    className={this.props.classes.dateTimePicker}
                />

and then my CSS class is:

        dateTimePicker: {
            '& > *': {
                fontSize: '0.7rem',
            },
        },
