### ISSUE TITLE
classes.input on DatePicker gets applied to MuiInput-root instead of Input

### ISSUE THREAD

**Issue by wederer** [dmtrKovalenko/material-ui-pickers#547]
Thanks for the answer in #546.

I think I found a "bug" or inconsistency when using the "classes" styling on DatePicker.

```
classes={{
  input: "input-class"
}}
```

This class "input-class" gets added to the div with class "MuiInput-root" instead of the <input> element itself. (https://material-ui.com/api/input/)

Is this intended?

edit:
I think passing "classes.input" as "className" in "localInputProps" is wrong. It should be passed as "classes" instead so one can access the whole css api of the input element (line 303 in datetextfield.jsx).

**Comment by asaivishal** [comment]
Hi @wederer, please see below solution to provide classes prop to the Input field.

### Code ###

```
import React, {PureComponent} from 'react';
import PropTypes from 'prop-types';
import DatePicker from 'material-ui-pickers/DatePicker';
import { withStyles } from '@material-ui/core/styles';

export class MyDate extends PureComponent {
    static propTypes = {
        onChange: PropTypes.func,
        classes: PropTypes.object
    };

    _onChange = (value) => {
        if (this.props.onChange) this.props.onChange(value);
    };

    render() {
        const {classes} = this.props;
        const inputProps = {
            disableUnderline: true,
            classes: {
                root: classes.input
            }
        };

        return (
            <DatePicker
                format="DD/MM/YYYY"
                onChange={this._onChange}
                InputProps={inputProps}
            />
        );
    }
}

const styles = () => ({
    input: {
        fontSize: 14,
        fontWeight: 600
    }
});

export default withStyles(styles)(MyDate);
```

### Screenshot ###
![image](https://user-images.githubusercontent.com/950650/44374008-76348700-a52f-11e8-8fa5-e7f8cf0b5f2e.png)

**Comment by wederer** [comment]
@asaivishal Thank you!
