### ISSUE TITLE
Option to treat null values as error

### ISSUE THREAD

**Issue by ValentinH** [dmtrKovalenko/material-ui-pickers#549]
Hey! First of all thanks for this great library. I hope it will end up in the material-ui core soon 🙂 

I would like to be able to display an error when the date input is empty (when `keyboard` is true).

I see [here](https://github.com/dmtrKovalenko/material-ui-pickers/blob/53fd240b868b9d0ff84c6333b89d42c84f59c4b8/lib/src/_shared/DateTextField.jsx#L48) that null value are excluded from errors.

One solution I have in mind would be to use the `required` prop of the `TextField` component to check this. If  `required` is true, then we should return an error if date value is null.

Finally, we would need a `requiredDateMessage` for this.

If this makes sense to you, I can contribute this.

**Comment by dmtrKovalenko** [comment]
Actually error management should be created not from pickers side. Because of required fields should restrict from form submission.
You should override the inline validation of pickers if you are using forms.

**Comment by ValentinH** [comment]
This is what I'm doing. However, an empty date (set by keyboard) doesn't trigger `onChange` nor `onError`. In my opinion, it should trigger `onError` is `required` is set on the field.

**Comment by dmtrKovalenko** [comment]
It is triggering onClear

**Comment by dmtrKovalenko** [comment]
Or onChange with null) 
I am not pretty sure but it should trigger something

**Comment by ValentinH** [comment]
OK I didn't see this in the documentation. For now I was using `onBlur` and checking for empty value.

Calling `onError` when required is true doesn't make sense to you?

**Comment by dmtrKovalenko** [comment]
Yep, I think no sense in adding new prop `required` so the checking for required is a part of form-management like formik or redux-form. We just should dispatch onChange with proper value when the field is cleared

**Comment by ValentinH** [comment]
Calling `onChange()` is also fine for me.
