### ISSUE TITLE
gregorian calander

### ISSUE THREAD

**Issue by soroushm** [dmtrKovalenko/material-ui-pickers#55]
Dear Friends,

Do You have any plane to using moment-jalali for Gregorian ? 
if answer is no i wanna take that part with your help
https://github.com/soroushm/material-ui-pickers-jalali
BR,

**Comment by dmtrKovalenko** [comment]
Actually I dont know is there any smooth way to support gregorian lanuguge? Maybe it would be more useful if we create something like plugin with a peer of material-ui-pickers that would use moment-jalali?

**Comment by sakulstra** [comment]
Not sure, but would it work when passing moment as a prop? (This could also solve the i18n problems of #8)
Then one could instead pass an instance of moment-jalali, but it's a really uneducated idea - nur sure if moment <-> moment-jalali behave exactly the same?

**Comment by dmtrKovalenko** [comment]
🎉 Published in 1.0.0-beta.5
