### ISSUE TITLE
Support `DialogProps` prop

### ISSUE THREAD

**Issue by imornar** [dmtrKovalenko/material-ui-pickers#552]
I would love to keep focus on date-picker custom input after onClose or onChange handlers trigger.
I can do it manually but the issue is in animation, so I need to add timeouts which is not ideal solution.

**Comment by dmtrKovalenko** [comment]
I propose add new prop `DialogProps` which will be passed directly to mui dialog which will add more customization

**Comment by dmtrKovalenko** [comment]
Released in rc.13
