### ISSUE TITLE
No value change when typing in an empty TextField

### ISSUE THREAD

**Issue by charlax** [dmtrKovalenko/material-ui-pickers#553]
Pretty similar to #470 (which has been closed).

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   1.0.0-rc12      |
| material-ui         |       1.4.2  |
| React               |       16.4.2  |
| Browser             |     N/A    |
| Platform            |      N/A   |

## Steps to reproduce

1. Open https://codesandbox.io/s/l416y7zqp9
2. Type in the text field

```jsx
import React, { PureComponent } from "react";
import DateFnsUtils from "material-ui-pickers/utils/date-fns-utils";
import MuiPickersUtilsProvider from "material-ui-pickers/utils/MuiPickersUtilsProvider";
import TimePicker from "material-ui-pickers/TimePicker";
import DatePicker from "material-ui-pickers/DatePicker";
import DateTimePicker from "material-ui-pickers/DateTimePicker";

export default class App extends PureComponent {
  state = {
    selectedDate: ""
  };

  handleDateChange = date => {
    this.setState({ selectedDate: date });
  };

  render() {
    const { selectedDate } = this.state;

    return (
      <MuiPickersUtilsProvider utils={DateFnsUtils}>
        <div className="pickers">
          <DatePicker
            keyboard
            clearable
            mask={[
              /[0-3]/,
              /\d/,
              "/",
              /0|1/,
              /\d/,
              "/",
              /1|2/,
              /\d/,
              /\d/,
              /\d/
            ]}
            value={selectedDate}
            onChange={this.handleDateChange}
            format="DD/MM/YYYY"
          />
        </div>
      </MuiPickersUtilsProvider>
    );
  }
}
```

## Expected behavior

Mask shows up, what you type shows up

## Actual behavior

Nothing happens - you don't see what you're typing.

It does work after you exit the field and enter it again (triggering `onBlur`).

## Live example

https://codesandbox.io/s/l416y7zqp9

**Comment by dmtrKovalenko** [comment]
The issue is that you are passing empty string as a value. It is not allowed, if you want to display nothing as default value you should pass `null`
I apologize for long answer

**Comment by charlax** [comment]
Thanks! Should this be documented somewhere?

**Comment by xingqiwu55555** [comment]
> The issue is that you are passing empty string as a value. It is not allowed, if you want to display nothing as default value you should pass `null`
> I apologize for long answer

Hi, here's a question: I need to handle error meesage, rather than component acquiescently handle.
