### ISSUE TITLE
Material ui babel module not found

### ISSUE THREAD

**Issue by jovankricka** [dmtrKovalenko/material-ui-pickers#556]
Started having this issue from today. Yesterday everything worked fine.

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui            |     1.3.1    |
| React                     |     16.4.1    |
| Chrome                 |     Chrome 67.0.3396.99   |
| Platform                |     Windows 10    |

## Steps to reproduce
1. npm start

## Expected behavior
Application started properly

## Actual behavior
Getting this error on startup:
Failed to compile
./node_modules/@material-ui/core/ButtonBase/ButtonBase.js
Module not found: Can't resolve '@babel/runtime/helpers/builtin/assertThisInitialized' in '...\node_modules\@material-ui\core\ButtonBase'

**Comment by TrySound** [comment]
Could you upgrade please?
https://github.com/mui-org/material-ui/releases/tag/v1.4.3

**Comment by jovankricka** [comment]
Worked!
Thank you!
