### ISSUE TITLE
Components get clipped on smaller screens

### ISSUE THREAD

**Issue by nickisaacs** [dmtrKovalenko/material-ui-pickers#559]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  1.0.0-rc.9   |
| material-ui         |  1.2.0       |
| React               |  16.4.0  |
| Browser             | Chrome   |
| Platform            | Android/iOS   |

## Steps to reproduce
1. Open Date/Time/DateTimepicker on smaller screens (like iPhone 5s, iPhone 4, Moto E 1st gen)
2. Calendar/Time is clipped at the bottom region, and I'm unable to choose dates which are clipped

![screen shot 2018-08-07 at 12 52 18 pm](https://user-images.githubusercontent.com/2580911/43760958-3b3cf536-9a41-11e8-82d4-8d02f0682392.png)

In the above screenshot you can see dates after 25 are not shown. 
Similar issue occurs for time picker but it's easier to choose time even when its clipped

**Comment by dmtrKovalenko** [comment]
Fixed in rc.14
