### ISSUE TITLE
Support for Firefox

### ISSUE THREAD

**Issue by mfolnovic** [dmtrKovalenko/material-ui-pickers#56]
Hello,

at the moment, this component doesn't work in Firefox. Picker opens on `mousedown`, but closes immediately on `mouseup`.

Browser: Firefox 56
OS: Linux

**Comment by dmtrKovalenko** [comment]
Thank you, will test and fix it in the nearest release

**Comment by fabyeah** [comment]
My colleague also has this problem with Firefox on Linux. With Firefox on MacOS, I don't have this problem.

**Comment by sakulstra** [comment]
The firefox issues are still present on linux with newest beta.

**Comment by dmtrKovalenko** [comment]
Oh, will test it, thanks

**Comment by sakulstra** [comment]
@mfolnovic is the issue still present for you?
Seems like for me it's gone with latest beta (both material ui and material ui pickers)

**Comment by mfolnovic** [comment]
firefox 58
material-ui-pickers 1.0.0-beta.7

![image](https://user-images.githubusercontent.com/20919/33552061-cebc9b96-d8f3-11e7-95dc-023466961986.png)
![image](https://user-images.githubusercontent.com/20919/33552068-db087b18-d8f3-11e7-808e-e26b8fad5516.png)

For some reason, text color for year and numbers on dial are white.

Other than that, it works, awesome! :)

**Comment by cherniavskii** [comment]
@mfolnovic Could you check latest beta [here](https://material-ui-pic.firebaseapp.com/)?
Looks like it works properly if FF now.

**Comment by cherniavskii** [comment]
I'm closing this for now, feel free to reopen if it's still an issue
