### ISSUE TITLE
Failed to overrides the color of the label of DatePicker Input

### ISSUE THREAD

**Issue by eldyvoon** [dmtrKovalenko/material-ui-pickers#560]
I did this but the label of the datePicker input did not change color to red.

```
const materialTheme = createMuiTheme({
  overrides: {
    MuiInput: {
      underline: {
        '&:after': {
          'border-bottom': '2px solid red'
        }
      }
    }
  }
})
```

## Expected behavior
The label should have the same color as the underline when the input is touched

## Actual behavior
I see underline of the input is red but the label's color still remained as the primary color which is purple color

**Comment by cherniavskii** [comment]
Hi,
Could you explain what you are trying to achieve?

**Comment by eldyvoon** [comment]
Found the solution:
```overrides: {
    MuiFormLabel: {
        focused: {
        '&$focused': {
            color: inputFocusColor
        }
        }
    },
    MuiInput: {
        underline: {
        '&:after': {
            'border-bottom': `2px solid ${inputFocusColor}`
        }
        }
    }
}
