### ISSUE TITLE
arrow icons not shown in Safari

### ISSUE THREAD

**Issue by Bosn** [dmtrKovalenko/material-ui-pickers#563]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.12 / official site demo     |
| material-ui         |    1.4.2     |
| React               |   16.4.1     |
| Browser             |   Safari 11.1.2      |
| Platform            |  MacOS 10.13.6 or iOS      |

## Steps to reproduce
1. Using safari to visit official demo page:  https://material-ui-pickers.firebaseapp.com/demo/datepicker
2. Click picker component to show calendar and mask
3. Left / right arrow icons are not shown correctly.

## Expected behavior

Arrow icons shown

## Actual behavior

Arrow icons now shown
## Live example

https://material-ui-pickers.firebaseapp.com/demo/datepicker

## Screenshot
![](http://cdn.actin.tech/public/uploads/20180808.png)

**Comment by NickToye** [comment]
I'm experiencing icons not showing either, just large letters.

**Comment by dmtrKovalenko** [comment]
@NickToye `<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">` this fill fix letters for you (not in iOS safari)

**Comment by NickToye** [comment]
I'm using the create-react-app and there is no <head> section for me to add this.

**Comment by NickToye** [comment]
Also worth noting that this was working last week, but now it isn't - so don't know if there was a change made with your stuff, or React itself.

**Comment by dmtrKovalenko** [comment]
@NickToye `public/index.html` not recreating - `build/index.html` is recreating so put the font to `public` folder

**Comment by hashwin** [comment]
Seems like the ```overflow: hidden``` in the styles for the arrows is causing the problem.

**Comment by chetferry** [comment]
Hi Bosn, would you be willing to show how the theme overide works.  I have been trying to figure it out but no luck.  I am also trying to make it work in Safari.  Thanks.

**Comment by chetferry** [comment]
Thanks so much!  I have it working now because of your help.

**Comment by chetferry** [comment]
Thanks so much! I have it working now because of your help.

**Comment by dmtrKovalenko** [comment]
Released in rc.13

**Comment by Jwing28** [comment]
I have this issue, but it's not only in Safari, I have it with Firefox and Chrome too. Does anyone else have this issue? The arrows are there and functioning just not visible.

![Screen Shot 2019-05-14 at 9 48 15 AM](https://user-images.githubusercontent.com/8518420/57707555-72044880-762d-11e9-8800-98a92ef01916.png)

**Comment by dmtrKovalenko** [comment]
Hmm. We are using plain svg there. Don’t you override arrowIcon props?
