### ISSUE TITLE
Feature Request: Seconds input option for DateTime Component

### ISSUE THREAD

**Issue by lucky24lx** [dmtrKovalenko/material-ui-pickers#564]
Thanks for the great component!

When editing a Javascript Date object, it's useful to be able to edit seconds along with the date/hours/minutes. Currently only the TimePicker component supports entering seconds. Having the option to enter seconds on the DateTimePicker component would be very handy. The only way to edit a timestamp date object and edit seconds currently is to use manual entry, or to use separate date/time components.

**Comment by VMBindraban** [comment]
Just noticed that we are also missing this feature.

**Comment by dmtrKovalenko** [comment]
We will not do that. It is actually design issue - there is no place for additional button.
