### ISSUE TITLE
Infinite month sliding

### ISSUE THREAD

**Issue by wenduzer** [dmtrKovalenko/material-ui-pickers#568]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  latest|
| material-ui         |   latest      |
| React               |     latest    |
| Browser             |   chrome      |
| Platform            |     windows 10 pro    |
| Peer library        |    moment latest     | 

## Steps to reproduce
1. just install and use DatePicker.
2.
3.

## Actual behavior

clicking on month right / left causes infinte sliding bug..

## Live example
![image](https://user-images.githubusercontent.com/12185681/43903477-3455edee-9bf5-11e8-9624-5fbccd6b5d2e.png)

**Comment by vramana** [comment]
This is fixed on the master.

**Comment by wenduzer** [comment]
yeah but, they probably didn't update npm.

**Comment by Koloto** [comment]
Please publish fix to npm. I need a new `container` prop introduced in rc12, but can't use rc12 because of the current bug.

**Comment by wenduzer** [comment]
@vramana @dmtrKovalenko can you please update npm repo?

**Comment by chaoriwei** [comment]
I am facing the monthly sliding issue too.
Appreciate if you can publish fix to npm.

**Comment by vramana** [comment]
@wenduzer Lol. I am not responsible for this repo. I just use it at work. So I currently copied the code and import it.

**Comment by cherniavskii** [comment]
Are you sure this issue reproduces in `material-ui-pickers` rc.12? I can't reproduce it, everything looks fine for me.

**Comment by Koloto** [comment]
Yes, sure. This bug is reproduced in rc12, rc11 is ok.

**Comment by dmtrKovalenko** [comment]
Released in rc.13

**Comment by chaoriwei** [comment]
Tested rc.13 and the issue confirm was fixed.
