### ISSUE TITLE
Slow slide transitions between months. 

### ISSUE THREAD

**Issue by karthikJagadeesh** [dmtrKovalenko/material-ui-pickers#569]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    master     |
| material-ui         |    1.3.0     |
| React               |    16.3.0     |
| Browser             |    chrome     |
| Platform            |    Ubuntu 18.04.1     |
| Peer library        |    date-fns@2.0.0-alpha.7     | 

## Steps to reproduce
1. Open DatePicker and click on next-month/previous button rapidly. 

## Expected behavior

     Smooth slide transitions 
## Actual behavior

      The month viewports quickly stack up one below the other and appear quirky.
## Live example

      
![janky](https://user-images.githubusercontent.com/5729651/43906610-50e5d822-9c11-11e8-8272-d02b118ea497.gif)

**Comment by cherniavskii** [comment]
Issue isn't reproducible in v1.0.0-rc.12

@karthikJagadeesh can you confirm?

**Comment by karthikJagadeesh** [comment]
This issue is on current master branch.

**Comment by dmtrKovalenko** [comment]
Released in rc.13

**Comment by Monfernape** [comment]
I'm facing this issue right now with exact same description.
