### ISSUE TITLE
when ampm set to false, not able to choose afternoon hours on DateTimePicker

### ISSUE THREAD

**Issue by FACOLOMBANI** [dmtrKovalenko/material-ui-pickers#573]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     1.0.0-rc.12   |
| material-ui         |   1.0.0     |
| React               |    16.3     |
| Browser             |   chrome      |
| Platform            |     linux    |
| Peer library        |    moment     | 

## Steps to reproduce
1. set prop ampm to false.
2. open DateTimePicker  and choose time tab.
3. try to set time to 15:30.

## Expected behavior

Be able to choose a range of 24 hours

## Actual behavior

only able to choose 12hours

## Live example
![peek 2018-08-14 14-52](https://user-images.githubusercontent.com/11721821/44092758-c4d63ac4-9fd1-11e8-99fb-4cb03fcdc23a.gif)

**Comment by sakulstra** [comment]
@FACOLOMBANI fixed on master, but not yet released - eagerly waiting for that release as well.

**Comment by dmtrKovalenko** [comment]
@sakulstra I’ve been hospitalized without my laptop so have no chance to release it. 
I apologize:(

**Comment by sakulstra** [comment]
@dmtrKovalenko sad to hear that - get well soon :+1:

**Comment by FACOLOMBANI** [comment]
Sad to hear that too, hope you get well soon.

**Comment by sakulstra** [comment]
For the meantime I published a `material-ui-pickers-fork` from current develop feel free to use that for now - I'm not going to maintain that fork. It's just to bridge the gap.

**Comment by dmtrKovalenko** [comment]
Thank you all! 
New version of material-ui-pickers has been released! 🚀
