### ISSUE TITLE
Ability to pass in custom error message?

### ISSUE THREAD

**Issue by bmueller-sykes** [dmtrKovalenko/material-ui-pickers#574]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     1.0.0-rc.12    |
| material-ui         |    1.4.2     |
| React               |   16.4.2      |
| Browser             |   All      |
| Platform            |    All     |
| Peer library        |    moment     |

Is there a way to pass in a custom error message into these pickers? e.g. let's say I create a valid date/time with `DateTimePicker`, then submit that to the server, but the server decides there's something wrong with the date (e.g. it's before/after another date that the server has, but the client doesn't). I'd like to be able to pass in the error message that the server sends back, but there doesn't seem to be a way to do that. Does that make sense? Am I missing something?

**Comment by cherniavskii** [comment]
Hi,
`DateTimePicker` uses materia-ui `TextField` under the hood.
So you're able to do something like:
```jsx
<DateTimePicker
  // ...
  error
  helperText="Your error message"
/>
```

**Comment by bmueller-sykes** [comment]
@cherniavskii thanks for the reply! Yes, that works, but only partially. Or, at least, there's another piece I can't figure out. The pickers often set their own internal error messages--for example if a user types in an invalid date, the components immediately display `Invalid Date Format`. What I'd like to do is say something like "if I have an external error message, display that; otherwise, display whatever error message is generated by the picker". I don't see a way to do that. e.g. if I do this:

```
      <DateTimePicker
        ...
        error={errorText && errorText.length > 0}
        helperText={(errorText && errorText.length > 0) ? errorText : null}
        ...
      />
```

...then the passed-in `helperText` value will always override the internally-generated message.

I think the only way to handle this right now is to set the component props outside the component itself, and then append a `helperText` prop if the parent component has an error value, like this:

```
    const pickerProps = {
       value: dateValue
      // other props...
    }

    if (errorText && errorText.length > 0) {
      pickerProps.helperText = errorText
    }

    return (
      <DateTimePicker
        {...pickerProps}
      />
    )
```

Maybe that's the "best" way to handle this condition, but it seems like it might be more elegant for the picker components to somehow allow for this.

**Comment by bmueller-sykes** [comment]
Sorry. You're right when you say that "passing `helperText` always overrides internal error message". What I'm saying is that it might be nice if there were a way for the internal error message to show, if the passed-in value of `helperText` is `null` or something like that. Here's your sandbox, modified with `helperText={null}`:

https://codesandbox.io/s/rjw3qk7k3p

In that example, if you type gibberish into the date/time field, you don't see the internal error message, even though the passed-in value of `helperText` is `null`. Maybe that's the right way to design the API for these components, but it seems like it would be nice for there to be certain conditions under which the internal error message overrides the passed-in value (e.g. for null and undefined). Does that make sense?

**Comment by pfortes** [comment]
Hey @bmueller-sykes!
I found a solution to your problem, you have to conditionally add the error and helperText properties to your react component, you can do this in the following way:
```
         <DatePicker
            value={selectedDate}
            onChange={this.handleDateChange}
            keyboard
            {...(hasError ? { error: true } : {})}
            {...(hasError ? { helperText: "Custom error message" } : {})}
          />
```
Where the variable "hasError" would be controlled by your external validation logic.

I modified your sandbox in:
https://codesandbox.io/s/wy4qxkqwj5

**Comment by tomas-light** [comment]
@bmueller-sykes You can use `DateValidationProps` and pass to component 
```js
<DatePicker
    {...props}
    minDateMessage="Date should not be in the past"
/>
```
