### ISSUE TITLE
Split out TextField from DatePicker

### ISSUE THREAD

**Issue by petja** [dmtrKovalenko/material-ui-pickers#577]
I would not like to have `TextField` at all and instead open modal programmatically only.

Is there way to do so?

Actually I would see forementioned as a default pattern and only in case **if** user needs `TextField`, they could `import` some special component to have it. This way:

```javascript
import {DatePicker, DatePickerInput} from 'material-ui-pickers'

// To render TextField with specific button to open the modal
<DatePickerInput />

// To render only programmatically openable modal and no TextField
<DatePicker isOpen={false} />
```

To justify, should we keep components as small as possible, and try to make assumptions about user needs as little as possible.

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc.12        |
| material-ui         | 1.3.0        |
| React               | 16.3.2        |

## Expected behavior
To split out `TextField` functionality out of `DatePicker` component to separate component.

## Actual behavior
`TextField` is bundled with `DatePicker` and thus making bundle size bigger (if I don't happen to need `TextField`) and making customization harder.

**Comment by cherniavskii** [comment]
You can use pickers without TextField.
Example:
https://codesandbox.io/s/y02n28825v

**Comment by petja** [comment]
That **doesn't** provide modal I asked for.

Yes, I can compose it up from `material-ui-pickers/wrappers/ModalWrapper`, `material-ui-pickers/DatePicker/DatePicker` and dozen of others, but then I have to handle all the internal props and so.

What we need is just:

```javascript
import {DatePicker} from 'material-ui-pickers'

<DatePicker
  isOpen={false}
  onChange={handleChange}
/>
```

**Comment by dmtrKovalenko** [comment]
We will not provide the way for controllable state. It is useless for most. 
As workaround you can control the modal by ref

**Comment by cherniavskii** [comment]
> I can compose it up

That's actually the main idea :)
We cannot provide composed components for everyone, but we provide composable components, so you can build your own pocket for your particular use case.

Note, that thanks to React composition, you don't have to compose it every time you use it. You can do this once by creating a component, and then use it everywhere you need.

It means, that behavior you described above is pretty easy to achieve, without shipping extra code to every user of ’material-ui-pickers’

**Comment by benneq** [comment]
@cherniavskii Your code doesn't work anymore :(

Here's the Code Sandbox: https://codesandbox.io/s/pjy7j7k7xm

Error message:
```
Can not find utils in context. You either a) forgot to wrap your component tree in MuiPickersUtilsProvider; or b) mixed named and direct file imports.  Recommendation: use named imports from the module index.
```

**Comment by cherniavskii** [comment]
I'm not surprised, a lot of things changed for the last 5 months :)
