### ISSUE TITLE
Slide transition of month goes into infinite loop once clicked on next-month/previous-month button

### ISSUE THREAD

**Issue by asaivishal** [dmtrKovalenko/material-ui-pickers#579]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.12     |
|@material-ui/core        |    ^1.4.3     |
| React               |    16.3.2     |
| Browser             |    Chrome     |
| Platform            |    macOs High Sierra     |
| Peer library        |    moment     | 

## Steps to reproduce
1.  Open CodeSandbox project: https://codesandbox.io/s/nrp49r8694
2.  Open DatePicker
3.  Click `>` button to go to next month
4.  Clicking `>` more times increases speed of transition x2

## Expected behavior
It should scroll to next month and should not keep transitioning infinitely

## Actual behavior
It scrolls to next month and goes into infinite transition

## Live example
https://codesandbox.io/s/nrp49r8694

**Comment by sambhav-gore** [comment]
@asaivishal FYI, rc.11 works fine.

**Comment by dmtrKovalenko** [comment]
Released in rc.13
