### ISSUE TITLE
Calendar day font isn't affected by font-family overrides

### ISSUE THREAD

**Issue by eldyvoon** [dmtrKovalenko/material-ui-pickers#580]
I tried to use the MuiThemeProvider to overrides the global font but the calendar body font isn't affected.

```
<MuiThemeProvider theme={createMuiTheme({
    typography: {
    fontFamily: 'monospace'
    }
})}>
...
...
</MuiThemeProvider>
```

## Expected behavior
calendar body font should be monospace

## Actual behavior
calendar body font isn't monospace
<img src="https://i.imgur.com/btSoiGe.png" />

**Comment by dmtrKovalenko** [comment]
Released in rc.13
