### ISSUE TITLE
Upgrade @babel/runtime to match @material-ui/core version

### ISSUE THREAD

**Issue by radicand** [dmtrKovalenko/material-ui-pickers#590]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  1.0.0-rc.13       |
| material-ui         | 1.5.1        |
| React               | 16.4.2        |
| Browser             | Chrome 68.0.3440.106        |
| Platform            |  macOS High Sierra       |
| Peer library        | luxon 1.3.3        | 

Similar to #561, I am facing issues in my production build of my app caused by multiple, incompatible versions of @babel/runtime in my project. @material-ui has upgraded their projects and dependencies to `7.0.0-rc.1`, and I am able to overcome my build issues by removing the version npm currently installs for material-ui-pickers (`7.0.0-beta.54`) and replacing it with `rc.1` (some edits to replace references to Object.keys required as core-js is no longer used, but this is besides the point).

I'd like to request that the @babel/runtime dependency be updated to `rc.1` to match the rest of the material-ui project and minimize build issues due to @babel/runtime version/api mismatches.

I apologize for not having a reproduction step, etc.

**Comment by strangewolf** [comment]
@radicand you found any solutions yet?

**Comment by radicand** [comment]
@strangewolf , until the dependency is updated in the package, you can manually overcome the issue (e.g., if you have a pressing build that this is blocking) by the steps I noted in the original post - remove the beta54 dependency from the filesystem, place in rc1, and then edit the MUI pickers project to replace references to _keys (which no longer comes with @babel/runtime) to use Object.keys or similar. It's a little bit of effort and will disappear if you run npm/yarn afterward, but will let you produce a build in the meantime.

**Comment by dmtrKovalenko** [comment]
Fixed in rc.14
