### ISSUE TITLE
minDate prop set to new Date() shows error if today is selected

### ISSUE THREAD

**Issue by asaivishal** [dmtrKovalenko/material-ui-pickers#591]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.13     |
| material-ui         |    1.5.1     |
| React               |    16.3.2     |
| Browser             |    Chrome     |
| Platform            |    MacOS High Sierra     |
| Peer library        |    moment     | 

## Steps to reproduce
1.  Open this project: https://codesandbox.io/s/mok3701mp9

## Expected behavior
Error message should only appear if previous date is selected

## Actual behavior
Error message appears if today's date is selected

## Live example
CodeSandbox URI: https://codesandbox.io/s/mok3701mp9

**Comment by dmtrKovalenko** [comment]
You should pass the value to make it works properly https://codesandbox.io/s/3vx4xm4lp1
