### ISSUE TITLE
Pickers can't scroll in small window

### ISSUE THREAD

**Issue by takobayashi** [dmtrKovalenko/material-ui-pickers#594]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |1.0.0-rc.12 and 1.0.0-rc.13|
| material-ui         |1.5.1|
| React               |16.4.2|
| Browser             |chrome68|

## Steps to reproduce
1.Open Picker dialog in small window.
2.Scroll dialog.

## Expected behavior
1.0.0-rc.11 can scroll.
![untitled](https://user-images.githubusercontent.com/1445180/44514044-fdcdf180-a6f9-11e8-8356-446f4380202c.gif)

## Actual behavior
Can't scroll.

**Comment by dmtrKovalenko** [comment]
Fixed in rc.14
