### ISSUE TITLE
Controlled DatePicker with keyboard enabled does not show partially entered date text

### ISSUE THREAD

**Issue by Cryza** [dmtrKovalenko/material-ui-pickers#597]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     1.0.0.rc-13    |
| material-ui         |      1.5.1   |
| React               |    16.4.2     |
| Browser             |     Chrome 68    |
| Platform            |    Mac OS X High Sierra     |
| Peer library        |     moment    | 

## Steps to reproduce
1. Create a controlled DatePicker with keyboard entry enabled, e.g. 
`<DatePicker keyboard value={this.state.date} onInputChange={e => this.setState({ date: e.target.value })} onChange={() => {}} />`, starting with `state = { date: null }`
2. Launch the application containing the component and try to type something into the date field

## Expected behavior
Whatever I enter should be visible so that I can manually enter a date

## Actual behavior
The text field switches to an unexpected value like `January 1st` if `1` is entered and afterwards changes to `Unknown`. It doesn't show the partial input even though the component state is updated whenever a key is pressed
In our production version of the component, we also set a `format` and a `mask`, which results in the field always staying empty instead.

## Live example
https://codesandbox.io/s/o7r02947p6

Side note: We reverted to version `1.0.0.rc-9` for now, the behavior there matches our expectations much better: `onChange` is also called with partial date input strings :+1: It would be great if you could consider going back to that API.

**Comment by dmtrKovalenko** [comment]
? It is actually invalid. Everything works perfectly - `onInputChange` returns only string. You should pass a `date` value from `onChange`  https://codesandbox.io/s/q70rvvmmoj
