### ISSUE TITLE
How to preview changes for a PR using the demo

### ISSUE THREAD

**Issue by ingro** [dmtrKovalenko/material-ui-pickers#6]
Hello, I've forked your library to create a PR but I can't preview the changes I wanted to implement. Trying to run the demo I get this error:

`Module not found: Can't resolve 'material-ui-pickers' in 'D:\projects\material-ui-pickers\docs\src\Demo'`

I also tried using symlinks but with no luck, webpack import the components as they are a static asset.

How can I run the demo locally?

**Comment by dmtrKovalenko** [comment]
Hi!
First of all want to thanks for contributing 🎉 
First of all you need to link material ui pickers from root
```sh
npm link
```

Than do 
```sh
cd docs && npm link material-ui-pickers
```

Thats it!

**Comment by dmtrKovalenko** [comment]
Also I have updated documentation for docs folder
https://github.com/dmtrKovalenko/material-ui-pickers/blob/master/docs/README.md

**Comment by ingro** [comment]
Thanks, it's working now!
