### ISSUE TITLE
date-fns versions questions

### ISSUE THREAD

**Issue by tjaskula** [dmtrKovalenko/material-ui-pickers#602]
Hi,

I've upgraded to latest version v1.0.0-rc.14 then I noticed that nothing was formatted correctly. Years displayed as `yyyy` strings instead of actual years, etc.
There is clearly stated in release notes that update was done to `date-fns@1.0.0-alpha.16`  which caused the break. I've used `utils/date-fns-utils-old` and all is good.

However, my question is the following. I'm using `"date-fns": "2.0.0-alpha.7"` meaning it is compatible with the old version but seems like version 2 of date-fns is newer than the 1? Are there any plans in using version 2?

**Comment by eloypnd** [comment]
I have similar issue.

I have updated to `date-fns@2.0.0-alpha.16` assuming that what is stated in the release notes is a typo.

But still I get multiple errors with the following pattern:
```
./node_modules/date-fns/locale/{langCode}/_lib/localize/index.js
Module not found: Can't resolve '../../../_lib/buildLocalizeArrayFn/index.js' in '.../node_modules/date-fns/locale/{langCode}/_lib/localize'
```
I am using `utils/date-fns-utils-old` for now.

> **NOTE**
> I am loading dynamically the locales with something like this:
> ```js
> import(`date-fns/locale/${iso639LangCode}`)
> ```

**Comment by dmtrKovalenko** [comment]
😮 The update was done to date-fns 2-alpha.14 

That seems to be a typo in release notes
