### ISSUE TITLE
Cannot install with yarn : Compose dependency

### ISSUE THREAD

**Issue by mael-jarnole** [dmtrKovalenko/material-ui-pickers#604]
Hello I recently ran into a problem when installing material-ui-pickers with yarn. The compose library was missing its utils folder in material-ui-pickers' node_modules, it could be a problem with the way yarn links dependencies, my project uses compose too. 
It works fine when using npm instead, oddly the node_modules folder in material-ui-pickers folder has different content when installing with npm. 
I reproduced it twice with yarn :/ Might be a problem on their end, as I am not sure I post it here first.

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |         |
| material-ui         |         |
| Compose |         |
| React               |         |
| Browser             |         |
| Moment       |         | 

## Steps to reproduce
1. A react project using yarn, 
2. try installing material-ui-pickers with yarn,
3. Try to render a DatePicker
4. Open a browser, you should see an error about missing dependency

## Expected behavior
be able to install material-ui-pickers with yarn

## Live example

Thank you for your work ! It fits my project needs perfectly apart from this issue, we needed to customize the way native date input work and format the date, and integrate it in our material ui layout. I did it in no time thanks to you 👍

**Comment by TrySound** [comment]
Do you mean `recompose`?

**Comment by mael-jarnole** [comment]
Yes

Here is the package.json if it helps : 
```{
  "name": "erget",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@fortawesome/fontawesome": "^1.1.8",
    "@fortawesome/fontawesome-free-regular": "^5.0.13",
    "@fortawesome/fontawesome-svg-core": "^1.2.2",
    "@fortawesome/react-fontawesome": "^0.1.2",
    "@material-ui/core": "^1.5.1",
    "@material-ui/icons": "^2.0.3",
    "classnames": "^2.2.6",
    "debug": "^3.1.0",
    "detect-browser": "^3.0.0",
    "eslint": "^5.4.0",
    "flag-icon-css": "^3.0.0",
    "history": "^4.7.2",
    "i18next": "^11.6.0",
    "i18next-browser-languagedetector": "^2.2.3",
    "i18next-locize-backend": "^1.6.0",
    "immutable": "^3.8.2",
    "lodash": "^4.17.10",
    "material-ui-chip-input": "^1.0.0-beta.6",
    "material-ui-pickers": "^1.0.0-rc.13",
    "moment": "^2.22.2",
    "moment-duration-format": "^2.2.2",
    "prop-types": "^15.6.0",
    "raven-js": "^3.26.4",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-dropzone": "^5.0.1",
    "react-helmet": "^5.2.0",
    "react-hot-loader": "^4.3.4",
    "react-i18next": "^7.10.1",
    "react-quill": "^1.3.1",
    "react-redux": "^5.0.7",
    "react-router": "^4.3.1",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.1.4",
    "react-swipeable-views": "^0.12.16",
    "react-transition-group": "^2.4.0",
    "recompose": "^0.28.2",
    "redux": "^4.0.0",
    "redux-actions": "^2.6.1",
    "redux-form": "^7.4.2",
    "redux-logger": "^3.0.6",
    "redux-saga": "^0.16.0",
    "reselect": "^3.0.1",
    "uuid": "^3.3.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "test-ci": "CI=true react-scripts test --env=jsdom --reporters=default --reporters=jest-junit || true",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.11.1",
    "jest-junit": "^5.1.0"
  },
  "proxy": "http://localhost:8080",
  "jest-junit": {
    "output": "../build/test-results/test-front/jest.xml",
    "classNameTemplate": "{classname}",
    "titleTemplate": "{title}",
    "ancestorSeparator": " › ",
    "usePathForSuiteName": "true"
  }
}```

**Comment by dmtrKovalenko** [comment]
Actually the same issue with #606 - but there its described better so closing this issue
