### ISSUE TITLE
recompose@^0.28.2 break material-ui-pickers

### ISSUE THREAD

**Issue by stefensuhat** [dmtrKovalenko/material-ui-pickers#606]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     rc.14    |
| material-ui         |    latest     |
| React               |     latest    |
| Browser             |     chrome    |

## Steps to reproduce
I have installed recompose@^0.28.2, and material-ui-pickers break after updating recompose.

`./node_modules/material-ui-pickers/node_modules/recompose/withHandlers.js
Module not found'`

Downgrading to rc.12 works perfect.

**Comment by mael-jarnole** [comment]
I confirm, this is the same issue we encountered

**Comment by TrySound** [comment]
I guess the problem with your build. This file exists
https://unpkg.com/recompose@0.28.2/withHandlers.js

Check your node_modules. Maybe it was corrupted. Try to reinstall.

**Comment by barbalex** [comment]
I have exact same problem and have spent hours trying to resolve it. As described in above link I have reinstalled node_modules and emptied it's cache multiple times.

According to https://github.com/acdlite/recompose/issues/723#issuecomment-418105981 the solution ist to update recompose.

Unfortunately I can't do it as - although I do have recompose as one of my dependencies - it's version 0.28.2 is included in material-ui-pickers. Which brings the problem up again.

Please update the recompose dependency.

**Comment by TrySound** [comment]
Will be fixed in https://github.com/dmtrKovalenko/material-ui-pickers/pull/632

**Comment by dmtrKovalenko** [comment]
Fixed in rc.15
