### ISSUE TITLE
Date days are added with additional digit

### ISSUE THREAD

**Issue by gairom** [dmtrKovalenko/material-ui-pickers#607]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  rc14       |
| material-ui         |    3.0.1     |
| React               |    16.4.2     |
| Browser             |   Chrome      |
| Peer library        |   date-fns alpha.16    | 

it also happens on the official docs example:
https://material-ui-pickers.firebaseapp.com/guides/formats

## Expected behavior
show the day properly

## Actual behavior
days are added with 3rd digit.

![image](https://user-images.githubusercontent.com/10984403/44952293-f7bbdb80-ae84-11e8-82f7-bab02fba6ecf.png)

![image](https://user-images.githubusercontent.com/10984403/44952307-03a79d80-ae85-11e8-9544-ec66dc3baa20.png)

**Comment by chaoriwei** [comment]
![image](https://user-images.githubusercontent.com/16182457/44964937-a46d8a00-af65-11e8-8b1c-d734c6e708c5.png)

I am facing the same issue too.
- Upgrade from rc13 to rc14
- Upgrade date-fns from 2.0.0-alpha.7 to 2.0.0-alpha.16

**Comment by chaoriwei** [comment]
@gairom ,

I have the same issue. I found out the issue is with the format.

The correct format is case sensitive
format="dd/MM/yyyy"

make sure the dd is not DD.

**Comment by gairom** [comment]
Yep, D -> d fixed it, thanks!
