### ISSUE TITLE
Warn Peer dependency material-ui 3.0.0

### ISSUE THREAD

**Issue by ahce** [dmtrKovalenko/material-ui-pickers#608]
## Expected behavior
No peer warn

## Actual behavior
material-ui-pickers@1.0.0-rc.14 requires a peer of @material-ui/core@^1.0.0-rc.0 but none is installed

## Steps to reproduce
- npm install --save @material-ui/core@3.0.0
 
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc14 |
| material-ui         | 3.0.2 |
| React               | 16.4.2 |

**Comment by greenteamsite** [comment]
Please, fix this.

**Comment by tantan587** [comment]
I upgraded to material ui 3.0.2 and now the the date picker looks like this. Not sure why this happens.

![screen shot 2018-09-15 at 1 48 11 pm](https://user-images.githubusercontent.com/9307306/45589601-22c71600-b8ee-11e8-9572-8e96185d0a83.png)
