### ISSUE TITLE
localization does not work properly anymore ( wrong day display in modal and field) 

### ISSUE THREAD

**Issue by peter-75** [dmtrKovalenko/material-ui-pickers#611]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  v1.0.0-rc.14  |
| material-ui         |  3.0.2  |
| React               |  16.4.2 |
| Browser             |   Chrome and firefox       |
| Peer library        |     date-fns -> 2.0.0-alpha.16   | 

## Steps to reproduce
I reproduce in my code but alson on the docs website :
1. Go [https://material-ui-pickers.firebaseapp.com/guides/formats] with french localization

## Expected behavior
Today's date : 05/09/2018
1. Click on the modal, the date in the title is 5 sept. 2018 
2. When you select the today's date it shows 5 sept. 2018 in the field

## Actual behavior 
Today's date : 05/09/2018
1. Click on the modal, the date in the title is incorrect (248 sept. 2018) 
2. When you select the today's date it shows 248 sept. 2018 in the field

**Comment by dmtrKovalenko** [comment]
You must update date-fns to v16. And also update your format symbols. DD => dd

**Comment by peter-75** [comment]
Thanks! it works perfectly again ^^
