### ISSUE TITLE
Picking maxDate in calendar trigger maxDateMessage

### ISSUE THREAD

**Issue by dimakTR** [dmtrKovalenko/material-ui-pickers#619]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     v1.0.0-rc.14    |
| material-ui         |   1.5.1      |
| React               |   16.4.2      |
| Browser             |         |
| Peer library        |     moment v2.15.2    | 

## Steps to reproduce
1. Pass maxDate as a prop to picker
2. Pick this date in calendar

## Expected behavior
Should pick the date without error message because this one is allowed date. Seems like the actual logic for check maxDate for calendar and show or not maxDateMessage are different.

Hack/Fix for now - If you pass maxDateMessage = "" as a prop to picker it will not trigger the error and won't change the input color to red so you can safely pick the maxDate from calendar.

## Actual behavior
Shows maxDateMessage error message on the input.

**Comment by dmtrKovalenko** [comment]
Fixed in rc.15
