### ISSUE TITLE
Datepicker Placeholder not working in IE11

### ISSUE THREAD

**Issue by JonesXavi** [dmtrKovalenko/material-ui-pickers#621]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  1.0.0-rc.14    |
| material-ui         |  v1.4.2   |
| React               |  v16.4.1   |
| Browser             |   IE11      |
| Peer library        |   moment v2.18.1   | 

## Steps to reproduce
1. Open https://material-ui-pickers.firebaseapp.com/demo/datepicker in IE 11.
2. Click on `Keyboard Input - Masked Input` example and delete the existing date.
3. Now, placeholder should be shown.

## Expected behavior
Placeholder should be visible just like chrome and firefox.

## Actual behavior
Its not showing placeholder only in IE 11. But after deleting the date and when you focus out from the datepicker, the placeholder text flicks (shows and hides) for a second.

## Live example
https://codesandbox.io/s/jv31w49wyy

I have reproduced the same example from the demo as a separate live example.
@dmtrKovalenko Any idea how to make this work?

**Comment by dmtrKovalenko** [comment]
Actually have no idea. Moreover have no chance to reproduce it now. 

Maybe try to reproduce it with plain masked input. And if you see it again raise the issue in masked input repo

**Comment by JonesXavi** [comment]
@dmtrKovalenko Thanks. For now I'm closing this. If I get any solution. Will update here.

**Comment by noranda** [comment]
This is still an issue. Did you ever find a fix @JonesXavi ?
