### ISSUE TITLE
InlineDatePicker doesn't display the clear button when clearable prop is set to true

### ISSUE THREAD

**Issue by dakisxx** [dmtrKovalenko/material-ui-pickers#622]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc.14 |
| material-ui         | 1.4.2 |
| React               | 16.4.2 |
| Browser             | Chrome 68 |
| Peer library        | moment 2.22.2 | 

## Steps to reproduce
1. Use an `<InlineDatePicker>` component
2. set the `clearable` prop to `true`
3. open the date picker in the browser

## Expected behavior
The "Clear" button should be displayed to allow clearing the input

## Actual behavior
The "Clear" button is not visible

**Comment by dmtrKovalenko** [comment]
Inline date picker is not supporting this functionality

**Comment by Hartzi** [comment]
Well is there any way to clear value when using InlineDatePicker?

**Comment by dmtrKovalenko** [comment]
You can do it manually. Add input adornment with button to clear the value

**Comment by nugz1012** [comment]
This was a solution I came up with for this. Hope this helps anyone who stumbles across this. If there is a better way let me know.

I am using Formik on my app so I included it in the example.
https://codesandbox.io/s/42y21jj057

**Comment by ptrushin** [comment]
Unfortunately last solution not worked with keyboard prop like
<InlineDatePicker keyboard ...

**Comment by ptrushin** [comment]
Workaround:
1) add onClick={openPicker} for IconButton Calendar
2) realize openPicker like https://material-ui-pickers.dev/guides/controlling-programmatically
