### ISSUE TITLE
InlineDateTimePicker not firing onChange

### ISSUE THREAD

**Issue by GioLogist** [dmtrKovalenko/material-ui-pickers#623]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    1.0.0-rc.14     | 
| material-ui         |     3.0.3    |
| React               |    16.4.2     |
| Browser             |    Chrome     |
| Peer library        |    moment 2.22.2    | 

## Steps to reproduce
1. Use InlineDateTimePicker as shown in demo
2. Click a date and time
3. Click anywhere on the screen to X the modal (no "ok" button present)

## Expected behavior
onChange event to fire, or "ok" button visible

## Actual behavior
date never changes

## Live example
https://material-ui-pickers.firebaseapp.com/demo/datetimepicker

**Comment by dmtrKovalenko** [comment]
You must select day, hour, minute and then it will be submitted. I know that it’s actually not user friendly but ok cancel buttons for me is worst
