### ISSUE TITLE
Clicking Today button when calendar is in a different month should bring it back to current month, even if todays date is already selected

### ISSUE THREAD

**Issue by Ethorsen** [dmtrKovalenko/material-ui-pickers#630]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | v1.0.0-rc.14        |
| material-ui         | 1.5.1       |
| React               | 16.4        |
| Browser             | N/A       |
| Peer library        |  moment       | 

## Steps to reproduce
1. Create a Date Picker with showTodayButton 
2. Open Date Picker, select current date
3. Change month
4. Click on Today button

## Expected behavior

Date Picker should go back to current month, to show todays date

## Actual behavior

Date picker does nothing

**Comment by dmtrKovalenko** [comment]
I will leave only #629 cause they are totally related
