### ISSUE TITLE
Preventing validation with initial value

### ISSUE THREAD

**Issue by kamranayub** [dmtrKovalenko/material-ui-pickers#631]
Using `DatePicker` with `minDate` or `maxDate` enabled will enforce validation on initial values even when value is technically valid from business logic POV.

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | rc13        |
| material-ui         | 3.0.2        |
| React               | 16.4        |
| Browser             | Chrome 69        |
| Peer library        | moment-timezone@0.5.21        | 

## Steps to reproduce
1. Enable `minDate` or `maxDate`
2. Set `value` prop initially to be a date that is outside of min/max range

## Requested Behavior

Sometimes validating initial value might be desired. In our case, it's undesired because value comes from database and could very well be in the past (which is valid for old data).

Would like the ability to "cancel" validation or handle validation in this case so we can ignore "current" values from the database and only apply validation to new user input. Essentially, this allows users to see what data is already saved in database but disallows setting a new past date.

Maybe `onlyValidateOnChange` or something like that.

## Current behavior

Always shows invalid date message.

## Live example

![image](https://user-images.githubusercontent.com/563819/45568876-791b5280-b823-11e8-9665-f65ca5399e65.png)

**Comment by dmtrKovalenko** [comment]
We would not fix that. You can disable validation on your side by passing props helperText and error. 

Also I am considering some prop as disableValidation to make this process more obvious.

**Comment by kamranayub** [comment]
Wouldn't passing those props disable validation even for user input? I
really only want to disable it for initial values. Is there a good way to
reenable validation with this approach?

**Comment by PiotrSzlagura** [comment]
@kamranayub if you still need solution here, you could do something like:

```jsx
state = { valueChanged: false };
onChange() { this.setState({ valueChanged: true }) }

// ...code

<DatePicker 
   {...props} 
   disableValidation={!this.state.valueChanged} 
   onChange={() => this.onChange()}
/>
```

**Comment by kamranayub** [comment]
Thanks! We ended up handling all validation ourselves since we have more
validations we needed and min/max is easy enough to do ourselves.
