### ISSUE TITLE
Consider replacing react-text-mask with rifm

### ISSUE THREAD

**Issue by TrySound** [dmtrKovalenko/material-ui-pickers#634]
react-text-mask has a few problems
- to big integration does not let authors to concentrate on specific bugs
- hard to debug because entry point is minified umd compiled by webpack
- by the same reason it's big
- hard to contribute because of tricky setup and too much integrations

[rifm](https://github.com/istarkov/rifm) is a small alternative with more specific tasks. It's quite small and highly customizable

/cc @istarkov

**Comment by dmtrKovalenko** [comment]
😱  We should definitely get rid of `react-text-mask` https://bundlephobia.com/result?p=material-ui-pickers@1.0.1

**Comment by dmtrKovalenko** [comment]
@sergiohgz it was already fixed in #822

**Comment by sergiohgz** [comment]
And next release when will be published??

**Comment by dmtrKovalenko** [comment]
New release will be published at the start of next week. For now just install typings for react-text-mask. We will add a dependency in the next release. 
P.S. Replacing will need a new major release so it will be not now

**Comment by sergiohgz** [comment]
Perfect, thanks a lot @dmtrKovalenko for the info :wink:

**Comment by dmtrKovalenko** [comment]
Shipped in v3
