### ISSUE TITLE
https://codesandbox.io/s/p0vnk7xzj

### ISSUE THREAD

**Issue by jinyanhuan** [dmtrKovalenko/material-ui-pickers#636]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc.14 |
| material-ui         | 1.0.0 |
| React               | 16.4.0 |
| Browser             | All |
| Peer library        | date-fns@2.0.0-alpha.16 | 

## Steps to reproduce
I am using the latest version 1.0.0-rc.14 with corresponding date-fns version 2.0.0-alpha.16, but I got a wrong date in the input after picking a date

## Expected behavior
should have the right date: 2018-09-17

## Actual behavior
I got '2018-09-260' instead of '2018-09-17'

## Live example
https://codesandbox.io/s/p0vnk7xzj

**Comment by jinyanhuan** [comment]
![image](https://user-images.githubusercontent.com/11350373/45613526-437f9f00-ba99-11e8-9a60-5f0d1c35625a.png)

**Comment by dmtrKovalenko** [comment]
Format string dd -> DD

**Comment by jinyanhuan** [comment]
o~~~ thank you~~~
