### ISSUE TITLE
Is this project support Material UI V3.1.0

### ISSUE THREAD

**Issue by syedabuthahirm** [dmtrKovalenko/material-ui-pickers#638]
Icons are broken if I use this package with Material UI V3.1.0.
![screenshot_2018-09-18 expenses](https://user-images.githubusercontent.com/22408257/45687823-5fed0b80-bb6d-11e8-9849-7ce52b9f5d09.png)

**Comment by dmtrKovalenko** [comment]
You must install icon font

**Comment by syedabuthahirm** [comment]
Already did!

![package](https://user-images.githubusercontent.com/22408257/45688098-1b15a480-bb6e-11e8-8bf3-53c81651f463.png)

**Comment by dmtrKovalenko** [comment]
@syedabuthahirm please, read installation guide one more time

**Comment by gustavopch** [comment]
This phrase in the guide is really confuse:
> In order if you can override with a help of corresponding props. Just add this to your html

I suggest the following:
> You should pass each icon from material-ui-icons (or any other icon lib) as a prop the picker. If you prefer, you can also simply add the following tag to the head of your HTML to let material-ui-pickers find the icons internally. Be warned that the latter may unnecessarily increase your network traffic if you already have the icons installed as a lib.

Examples would eliminate any remaining doubts.
