### ISSUE TITLE
Warning when using refs created by React.createRef()

### ISSUE THREAD

**Issue by vdmkotai** [dmtrKovalenko/material-ui-pickers#639]
In [this example](https://material-ui-pickers.firebaseapp.com/guides/controlling-programmatically) from docs callback refs are being used to open pickers programmatically.

If I create refs using React.createRef() the component still works but it shows warnings in the console.

```index.js:2178 Warning: Failed prop type: Invalid prop `forwardedRef` of type `object` supplied to `DatePickerModal`, expected `function`.```

**Comment by dmtrKovalenko** [comment]
Fixed in rc.15
