### ISSUE TITLE
name prop

### ISSUE THREAD

**Issue by maddhruv** [dmtrKovalenko/material-ui-pickers#644]
**Is your feature request related to a problem? Please describe.**
`event.target.name` is missing

**Describe the solution you'd like**
Add name prop

**Describe alternatives you've considered**
either will use native element or doing separate handlers

**Additional context**

![screenshot from 2018-09-20 18-57-21](https://user-images.githubusercontent.com/18121502/45821520-11737480-bd07-11e8-8318-28748affa0f4.png)

**Comment by dmtrKovalenko** [comment]
The event onChange is not provide an event argument cause there are quite a lot places from where you can submit an event. And that would not be an input. 
So you need to mock event, by creating the object with event.target.value by yourself
