### ISSUE TITLE
How can I make "TextField" supports outlined styling.

### ISSUE THREAD

**Issue by moremoretree** [dmtrKovalenko/material-ui-pickers#647]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want "TextField" supports outlined styling.
https://material-ui.com/demos/text-fields/#outlined

**Describe alternatives you've considered**
nothing

**Additional context**
No

**Comment by dmtrKovalenko** [comment]
pass `variant="outlined"`
