### ISSUE TITLE
clearable prop not working on inline components

### ISSUE THREAD

**Issue by FACOLOMBANI** [dmtrKovalenko/material-ui-pickers#651]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  1.0.0-rc.14       |
| material-ui         |   1      |
| React               |      16.3   |
| Browser             |     chrome    |
| Peer library        |     moment 2.22.2    | 

## Steps to reproduce
1. Use inline pickers
2. Set clearable true.

## Expected behavior

1. see a clear button inside inline component.
2. when using keyboard, clearing the input should reset the input value.

## Actual behavior

1. no clear button inside inline picker even when defining clearLabel.
2. when using keyboard and clearing input, value does not clear, need to define onInputChange function to handle clear.

**Comment by dmtrKovalenko** [comment]
It will not work

**Comment by FACOLOMBANI** [comment]
I am using the inline pickers in a framework based on redux-form, so to change the value of  my redux field i need to to trigger the onChange property of my redux field when i catch your value inside of your onChange handler. 

The problem is that when i clear the input with my keyboard, i have an invalid date message and your onChange event does not trigger.

If it isn't possible to add a clear button on the inline component, can you at least make a fix to trigger the onChange with a blank or null value when input is cleared with the keyboard, that way i can catch the event and trigger the onChange of my redux field.

I really like your inline components, but without this, i won't be able to use them.

**Comment by kamarajuPrathi** [comment]
@dmtrKovalenko Is there any change to above component , will he clearable work for inline ?

**Comment by marjan2k** [comment]
Why can't we add the clearable to inline picker?

I'm using inline picker for desktop view and picker when tablets, Both pickers having the same props will simplify and reduce boilerplate.
