### ISSUE TITLE
wrong date format in the documentation

### ISSUE THREAD

**Issue by bbigras** [dmtrKovalenko/material-ui-pickers#652]
## Steps to reproduce
1. go to https://material-ui-pickers.firebaseapp.com/guides/formats

## Actual behavior
I don't think "268" is right. I noticed because I had code to show the day of the week and I saw some numbers instead. I guess the format changed.

![image](https://user-images.githubusercontent.com/24027/46031982-6d077e80-c0c8-11e8-9960-ca755bb0fe79.png)

I had to revert both date-fns and material-ui-pickers to older versions to fix the problem.

**Comment by dmtrKovalenko** [comment]
Fixed in rc.15
