### ISSUE TITLE
Can you please add utils functions or expose utils in index.d.ts? It would be great.

### ISSUE THREAD

**Issue by qburst-sharath** [dmtrKovalenko/material-ui-pickers#653]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |         |
| material-ui         |         |
| React               |         |
| Browser             |         |
| Peer library        |    x    |  

## Steps to reproduce
1.
2.
3.

**Comment by dmtrKovalenko** [comment]
No, utils directly imports moment, date-fns or luxon. If we will import them from the root everybody will need to install all 3 lib
