### ISSUE TITLE
Adornment icon does not display properly with mui@3.1.1

### ISSUE THREAD

**Issue by alex-fournier** [dmtrKovalenko/material-ui-pickers#655]
When upgrading to latest version of `@material-ui/core` (`v3.1.1`), the adornment icon of date and time picker does not display properly.

It is caused by the style `alignItems: 'flex-end'` set in `DateTextField`. With the value `center`, it's better.

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   `1.0.0-rc.14`      |
| material-ui         |    `3.1.1`     |
| React               |    `16.4.0`     |
| Browser             |    any     |
| Peer library        |    date-fns     | 

## Live example

https://codesandbox.io/s/8n5nlorkv8

**Comment by chaoriwei** [comment]
I am facing the same issue.
Right now remove the icon for calendar icon temporarily.

**Comment by LeoLozes** [comment]
Same issue here. 
It seems that removing the `0.01em height` in `MuiInputAdornment-root` also fixes the problem, but @alex-fournier solution is probably cleaner.

**Comment by dmtrKovalenko** [comment]
Fixed in rc.15
