### ISSUE TITLE
rc15 gives you a Cannot read property 'date' of undefined

### ISSUE THREAD

**Issue by jjdp** [dmtrKovalenko/material-ui-pickers#660]
This is on a basic example. I upgraded from rc14. It's all on the codesandbox @dmtrKovalenko .

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  1.0.0-rc.15       |
| material-ui         |   3.1.1      |
| React               |  16.5.2       |
| Browser             |         |
| Peer library        |  moment 2.22.2       | 

## Live example
https://codesandbox.io/s/24jrrx5o7y

**Comment by andokai** [comment]
Your example doesn't have a `MuiPickersUtilsProvider`

You also need to change your import statements
`import { DatePicker } from 'material-ui-pickers';` 
should be changed to 
`import DatePicker from 'material-ui-pickers/DatePicker';`

**Comment by dmtrKovalenko** [comment]
😱

**Comment by andokai** [comment]
Updated your sandbox for you
https://codesandbox.io/s/6wr43j40q3

**Comment by jjdp** [comment]
changing the import fixes things

**Comment by TrySound** [comment]
@preciserobot Show all imports from this library in your app.
