### ISSUE TITLE
align input with input-adornment for margin:dense

### ISSUE THREAD

**Issue by FranBran** [dmtrKovalenko/material-ui-pickers#665]
When using DatePicker with prop `margin:'dense'` and `keyboard:true` the input is not aligned correctly with the Input Adornment

![grafik](https://user-images.githubusercontent.com/1215407/46335293-43e67100-c627-11e8-9b00-8442a43cc6b8.png)

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    rc17     |
| material-ui         |     3.1.2    |
| React               |         |
| Browser             |    Firefox, Chrome     |
| Peer library        |         |

**Comment by dmtrKovalenko** [comment]
These props works as designed
