### ISSUE TITLE
Example on Codesandbox.io is broken

### ISSUE THREAD

**Issue by anthonybrown** [dmtrKovalenko/material-ui-pickers#666]
## Environment

| Tech                |    Version   |
|---------------------|--------------|
| material-ui-pickers |1.0.0-rc.14 . |
| material-ui/cpre    |1.1.0         |
| React               |16.4.0        |
| Browser             |Chrome        |
| date-fns            |2.0.0-alpha.16| 

## Steps to reproduce
1.Go to https://material-ui-pickers.firebaseapp.com/usage
2.
3.

## Expected behavior

To see the latest example of a working datepicker

## Actual behavior

Broken Sandbox.io app

**Comment by dmtrKovalenko** [comment]
Fixed
