### ISSUE TITLE
Changing year doesn't fire "onChange" event.

### ISSUE THREAD

**Issue by MakaryHryshkin** [dmtrKovalenko/material-ui-pickers#667]
Changing year doesn't fire "onChange" event. A user needs to click on selected or another date to change the year. Could you please add some prop to fire "onChange" event when the year has been selected?

**Comment by MakaryHryshkin** [comment]
@dmtrKovalenko I'm using inline date picker, maybe it is reasonable to provide the same behavior as clicking on OK button when you click outside **inline** date picker area.

**Comment by dmtrKovalenko** [comment]
Then you can press enter and that will submit the value. 
We will not add buttons to the inline date picker

**Comment by MakaryHryshkin** [comment]
I don’t mean adding ok button to inline date picker ,I mean adding the same behavior, please ,check inline date picker ,when you select another year and next close date picker by clicking away ( outside the date picker),the year in input doesn’t change because onChange event is not fired. Thanks.

**Comment by dmtrKovalenko** [comment]
Yep. think adding fire onChange on closing datepicker nice way
