### ISSUE TITLE
Incorrect parse date with MomentUtils

### ISSUE THREAD

**Issue by MakaryHryshkin** [dmtrKovalenko/material-ui-pickers#668]
I use MomentUtils in MuiPickersUtilsProvider:
`
 <MuiPickersUtilsProvider utils={MomentUtils}>
      ....
 </MuiPickersUtilsProvider>
`
In DateTextField.jsx method value is parsed by util that i've passed:
`const parsedValue = utils.parse(e.target.value, format);`
and then `getError` method is called with `parsedValue` as an argument.

The problem is that when I use fns this code returns null - `const parsedValue = utils.parse(e.target.value, format);`, when I use moment it returns an object with an invalid value, so invalidDateMessage will be shown always and this checking in `getError` method of DateTextField.jsx doesn't work - 
`if (!utils.isValid(value)) {
    // if null - do not show error
    if (utils.isNull(value)) {
      return '';
    }
    return invalidDateMessage;
  }
`

**Comment by dmtrKovalenko** [comment]
Please provide codesandbox that reproduces this issue.

**Comment by MakaryHryshkin** [comment]
@dmtrKovalenko Try to leave blank both fields, the field with moment util stays with "Incorrect date" message. https://codesandbox.io/s/l430l38pzq

**Comment by dmtrKovalenko** [comment]
Sorry. I will fix it in the next patch release

**Comment by dmtrKovalenko** [comment]
Update to @date-io/date-fns@0.0.2
