### ISSUE TITLE
Incorrect date message when mask and format are different

### ISSUE THREAD

**Issue by MakaryHryshkin** [dmtrKovalenko/material-ui-pickers#672]
The input shows up with the incorrect date message when format and mask are different - https://codesandbox.io/s/6xnol1om8r

**Comment by dmtrKovalenko** [comment]
Your example doesn’t show any error message.

**Comment by MakaryHryshkin** [comment]
Try to change the year by keyboard

**Comment by dmtrKovalenko** [comment]
Yes. But musk using dashes and format -slashes. What do you expect? We are parsing date relying on the format string. If mask differences from format string - this makes input value unparseable and prints Invalid date. 

The mask must be the same as format. I thought that should be clear
