### ISSUE TITLE
Dev mode

### ISSUE THREAD

**Issue by fbarbare** [dmtrKovalenko/material-ui-pickers#675]
Hello,

I'm just opening this issue because I wanted to have a go at creating the DateRangePicker, but I can't seem to figure out the dev environment, I just keep running into issues. Could you share the dev environment setup so I can try to make a PR for the DateRangePicker?

Thanks!

**Comment by dmtrKovalenko** [comment]
Thanks for taking care of the project. 
Just now everything will change. Now I am working hard to redo the full codebase in typescript. And also dev environment will also be changed.

**Comment by dmtrKovalenko** [comment]
Also I have considered to split out range pickers to another npm module. For better bundle-size of default

**Comment by AkselsLedins** [comment]
@dmtrKovalenko  Any updates on this ? 
I would like to contribute on this project, but I can't figure out the dev env.

I tried multiple ways, but I always end up encountering errors.

**Comment by fbarbare** [comment]
Any help needed for that? If you got a branch and a couple of tasks, I can help

**Comment by dmtrKovalenko** [comment]
For now everything should be fine. Just make `npm i` & `npm start` from the root. And everything should work

**Comment by fbarbare** [comment]
@dmtrKovalenko I tried using that, but from the Docs site, it doesn't seem to take the components directly from the `lib` directory, does it?
How do you dev the components? How do you see what you're doing?
I'm sure I'm just missing something 😂

**Comment by dmtrKovalenko** [comment]
@fbarbare We are using Lerna for linking components in dev mode

**Comment by AkselsLedins** [comment]
@dmtrKovalenko well it works when you do `npm i & npm start` but this is not a ready-to-go dev env. 

I tried to link the packages using `npm link` & `lerna link` but my attempts were unsuccessful:

(even if my newly added `console.log` was executed)

![image](https://user-images.githubusercontent.com/18367406/51241349-e67bf300-197d-11e9-9215-8a6ef8be9a9e.png)

Can you tell me how do you use Lerna for linking components in dev mode ?
I'm pretty sure it would be useful to update [CONTRIBUTING.md](https://github.com/dmtrKovalenko/material-ui-pickers/blob/develop/CONTRIBUTING.md).

Thank you for your time

**Comment by dmtrKovalenko** [comment]
`npx lerna bootstrap`

**Comment by AkselsLedins** [comment]
Same issue (`lerna bootstrap` is executed in postinstall, then I guess it's not the problem)

![image](https://user-images.githubusercontent.com/18367406/51252548-63b66080-199c-11e9-89d0-2d6505c5b07f.png)
![image](https://user-images.githubusercontent.com/18367406/51252569-70d34f80-199c-11e9-8aca-57532f7bc850.png)

```
npm version : 6.5.0
```

![image](https://user-images.githubusercontent.com/18367406/51252961-6feeed80-199d-11e9-87a8-464eccace969.png)
