### ISSUE TITLE
Date marking on Material Calendar

### ISSUE THREAD

**Issue by JoeKyy** [dmtrKovalenko/material-ui-pickers#680]
I searched and did not find this on documentation so I'm come here to ask about date marking on specific dates on the Calendar, is possible to do that?

Like this
![image](https://user-images.githubusercontent.com/2018763/46635571-4cf5a780-cb2b-11e8-91e0-df9528c4a289.png)

**Comment by dmtrKovalenko** [comment]
Yep, you can pass day rendered component. Example on the docs, datepicker — week picker

**Comment by JoeKyy** [comment]
But how can I select only one day instead of selecting the week?

**Comment by dmtrKovalenko** [comment]
This is an example displaying you can pass custom component for rendering day.

**Comment by JoeKyy** [comment]
Ok, I can rendering a day, but how I can mark multiple days? Sorry for asking too much I trying to understand

**Comment by dmtrKovalenko** [comment]
Add marking logic inside render day component

**Comment by Dukler** [comment]
I'm sorry for necroing this thread, but how did you actually solve this? Because I cannot find the example anymore.

**Comment by dmtrKovalenko** [comment]
@Dukler https://material-ui-pickers.dev/api/datepicker#customization

**Comment by Dukler** [comment]
@dmtrKovalenko Thanks!
