### ISSUE TITLE
Add example usage with formik (with keyboard entry)

### ISSUE THREAD

**Issue by charlax** [dmtrKovalenko/material-ui-pickers#682]
**Is your feature request related to a problem? Please describe.**

It's pretty difficult to get material-ui-pickers working with formik. Adding an example that would be tested would be great - while I can get it to work with RC9, I can't get it working with RC 17.

**Describe the solution you'd like**

An example formik usage in the docs.

**Describe alternatives you've considered**

Even better: a test with formik.

**Additional context**

I've started adding one here: https://codesandbox.io/s/38qpxym5w5

I can't set the original date, for some reason it defaults to today regardless of `initialValues`.

**Comment by AndreiEnache** [comment]
Please check this example: https://codesandbox.io/s/73zk08l6l1
If you use the format prop you must provide a string in that format.
You can think of it like this: that string is being sent into moment(value, <format>) in order to create the moment object.

**Comment by charlax** [comment]
Thanks! What'd be great is to include it in the doc, so that it's kept up to date. What do you think?

**Comment by dmtrKovalenko** [comment]
https://material-ui-pickers.firebaseapp.com/guides/formik-integration
