### ISSUE TITLE
Arrow Icon Navigation not styled properly when not importing material icons

### ISSUE THREAD

**Issue by valoricDe** [dmtrKovalenko/material-ui-pickers#689]
As a proposal:
we could use `import { KeyboardArrowRight, KeyboardArrowLeft } from '@material-ui/icons'`
```
<Calendar
                date={new Date()}
                onChange={(date) => console.log(date)}
                leftArrowIcon={<KeyboardArrowLeft/>}
                rightArrowIcon={<KeyboardArrowRight/>}
              />
```
What do you think?

**Comment by greenteamsite** [comment]
I got the same issue - by default instead of left/right icons the DatePicker renders default names: 'keyboard_arrow_left', 'keyboard_arrow_right'

![image](https://user-images.githubusercontent.com/16587979/46924647-8457dd00-d072-11e8-9283-14167497a403.png)

**Comment by valorize** [comment]
@greenteamsite If you do not use `import { KeyboardArrowRight, KeyboardArrowLeft } from '@material-ui/icons'` than you have to add `<link rel='stylesheet' href='https://fonts.googleapis.com/icon?family=Material+Icons'>` to your index.html

**Comment by valorize** [comment]
@dmtrKovalenko I think the bundle size would be smaller if the picker would use the icons from `@material-ui/icons` directly instead of the font and would prevent errors like the one stated by @greenteamsite above.

**Comment by sensorii** [comment]
https://material-ui.com/style/icons/#font-vs-svg--which-approach-to-use-

> Font vs SVG. Which approach to use?
> Both approaches work fine, however, there are some subtle differences, especially in terms of performance and rendering quality. Whenever possible SVG is preferred as it allows code splitting, supports more icons, renders faster and better.

**Comment by nrkroeker** [comment]
Would it be possible to add functionality for both? Idk if there's a way to determine if the font package exists to default check that first, since the icon package would always be included.

There may be differences in performance but it would then take convenience into account as well for those users (like myself) who don't use the font package in their current build.

**Comment by dmtrKovalenko** [comment]
Because of `@material-ui/icons` is not a dependency of `@material-ui/core` package we will not made the required. Not now. Maybe in the next major release

**Comment by dmtrKovalenko** [comment]
Already moved to custom svg icons instead of icon font
