### ISSUE TITLE
Add option for DatePicker to return calendar dates without time and timezone ("2018-10-15")

### ISSUE THREAD

**Issue by charlax** [dmtrKovalenko/material-ui-pickers#694]
**Is your feature request related to a problem? Please describe.**

I'm using the current latest version with `date-fns`.

In my app, I need `DatePicker` to pick calendar date - where there is no notion of timezone. Yet by default the value returned by a `DatePicker` is a datetime including the timezone offset. So for instance, if the user picks today in the `europe/paris` timezone, it will be passed as `"2018-10-14T22:00:00.000Z"`. Which is annoying because I need to know the user's timezone to know which day they meant.

**Describe the solution you'd like**

Add an option `useCalendarDates`?

**Describe alternatives you've considered**

I couldn't find a simple way to do this. I checked the method exposed in the utils, but they don't discriminate between `DatePicker` and `DateTimePicker`. I guess I could hijack the `onChange` callback.

**Additional context**

The Python standard library has `datetime` for specific point in times (timezone-aware and timezone-naive) as well as `date` objects for calendar days.

I checked #517 which is totally unrelated.

**Comment by charlax** [comment]
Well this is one way:

```jsx
<DatePicker ... onChange={d => onChange(format(d, 'yyyy-MM-dd'))} />
```

**Comment by dmtrKovalenko** [comment]
You can pass Luxor or moment objects with configured time zone. And picker will return back the same time zone. But if you are using date-fns — it’s impossible

**Comment by aiavci** [comment]
I think this is a valuable feature. You'd need a simple way of picking dates such as birthdays.

**Comment by rwb196884** [comment]
This thing is absolutely useless: a user types in a date and then sometimes the data picker changes the date. It's unclear what it's doing -- besides some timezone bollocks -- or how to stop it.
