### ISSUE TITLE
Datepicker has inconsistent time behavior based on user input

### ISSUE THREAD

**Issue by jarradsl** [dmtrKovalenko/material-ui-pickers#697]
Datepicker has inconsistent time behavior based on whether the user allows date to default (today), or clicks on a date (today or something else).

## Environment
| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 1.0.0-rc.17 |
| material-ui         | 3.1.2 |
| React               | 16.4.0  |
| Browser             | Chrome 69.0.3497.100 |
| Peer library        | date-fns 2.0.0-alpha.16 |

## Steps to reproduce
1. Initialize DatePicker with selectedDate null (date picker will be empty).
2. Set Datepicker to "today" date without actually clicking "today" date in calendar. Datepicker time component will be set to current date AND current time.
3. Set Datepicker to a date by actually clicking on the date. Datepicker time component will be set to current date however time will be set to midnight.

## Expected behavior
Time component should be consistent whether you explicitly click on a date or allow it to default to today (recommend midnight for DatePicker).

## Actual behavior
See above in Steps to reproduce. Datepicker time component behavior is based on how to user selects the date.

## Live example
https://codesandbox.io/s/pjw1x3x5v0

**Comment by dmtrKovalenko** [comment]
Released in v2
