### ISSUE TITLE
Migration to MUI typography v2 

### ISSUE THREAD

**Issue by sebastianvoss** [dmtrKovalenko/material-ui-pickers#704]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |1.0.0-rc.17         |
| material-ui         |3.2.0         |

Migrate to new typography variant according to https://material-ui.com/style/typography/#migration-to-typography-v2. Support for the currently used ones will end with the next major release v4.0.0 (planned for Q1 2019).

Currently, when using `material-ui-pickers` there are many errors being logged as it is using deprecated typography variants:

```
index.js:2178 Warning: Material-UI: You are using the deprecated typography variant display1 that will be removed in the next major release. 
Please read the migration guide under https://material-ui.com/style/typography#migration-to-typography-v2
__stack_frame_overlay_proxy_console__ @ index.js:2178
3index.js:2178 Warning: Material-UI: You are using the deprecated typography variant display2 that will be removed in the next major release. 
Please read the migration guide under https://material-ui.com/style/typography#migration-to-typography-v2
__stack_frame_overlay_proxy_console__ @ index.js:2178
index.js:2178 Warning: Material-UI: You are using the deprecated typography variant subheading that will be removed in the next major release. 
Please read the migration guide under https://material-ui.com/style/typography#migration-to-typography-v2
```

**Comment by dmtrKovalenko** [comment]
It’s already done. Just not deployed.

**Comment by tjaskula** [comment]
Because I have still warnings popping up after migrating to new Typography variants, so was curious if this could come from material-ui-pickers.

**Comment by miguel719** [comment]
I have the same waning in fresh installed material-ui-pickers. via npm v1.0.1

index.js:1452 Warning: Failed prop type: Invalid prop `variant` of value `subtitle1` supplied to `Typography`, expected one of ["display4","display3","display2","display1","headline","title","subheading","body2","body1","caption","button","srOnly","inherit"]

**Comment by grachet** [comment]
same as miguel719

**Comment by dmtrKovalenko** [comment]
You must update to new material-ui-typography https://material-ui.com/style/typography/#migration-to-typography-v2 @grachet @miguel719

**Comment by evansdianga** [comment]
@dmtrKovalenko Could we add this to the docs.
I would be willing to give it a stab
