### ISSUE TITLE
Add .nvmrc file

### ISSUE THREAD

**Issue by zachwolf** [dmtrKovalenko/material-ui-pickers#71]
Hello! Thanks for the package, it's a huge time saver. 

It would be a really nice feature if this package leveraged use of a [`.nvmrc`](https://github.com/creationix/nvm#nvmrc) config.

Out of the box, I currently get 7 failed tests, a handful of errors, and warnings because of a different node version. I'd be happy to submit a PR with the change. What are your thoughts?

**Comment by dmtrKovalenko** [comment]
Yep, it would be really helpful, thank you.

**Comment by dmtrKovalenko** [comment]
Thank you!
