### ISSUE TITLE
Breaking change in 1.0.0 release: MuiPickersUtilsProvider has been moved

### ISSUE THREAD

**Issue by troig** [dmtrKovalenko/material-ui-pickers#710]
There is a breaking change in the new 1.0.0 release:
MuiPickersUtilsProvider has moved from /utils to the root  of material-ui-pickers.
This usually implies to change the import:

Old version:
`import MuiPickersUtilsProvider from 'material-ui-pickers/utils/MuiPickersUtilsProvider'`

New version: 
`import MuiPickersUtilsProvider from 'material-ui-pickers/MuiPickersUtilsProvider'`

Maybe you could add a note in the change log of the release readme .

Thanks for your awesome work! :)

**Comment by dmtrKovalenko** [comment]
Of course. Sorry :)

**Comment by dmtrKovalenko** [comment]
Done

**Comment by troig** [comment]
Thank you!

**Comment by fonziemedia** [comment]
Thanks for posting this!
