### ISSUE TITLE
Support for moment-hijri

### ISSUE THREAD

**Issue by Roshdy** [dmtrKovalenko/material-ui-pickers#714]
Is there a plan to support hijri dates?

if not, could you please guide me through making one on my own?

**Comment by dmtrKovalenko** [comment]
https://github.com/alitaheri/material-ui-pickers-jalali-utils

Here is a nice example. You can publish your own utils and create PR on usage of your utils to the our docs.

**Comment by dmtrKovalenko** [comment]
We are focusing on typescript definitions, so it’s required to write the utils in typescript. I can help you with that. You can commit the file as you have in js and I will rewrote it in typescript

25 окт. 2018 г., в 16:24, Roshdy Kamel <notifications@github.com<mailto:notifications@github.com>> написал(а):


I forked it, and started playing around with moment-hijri but it doesn't have types file, is it mandatory?
