### ISSUE TITLE
Cannot resolve 'tslib' error after upgrading to v1

### ISSUE THREAD

**Issue by darthmooguy** [dmtrKovalenko/material-ui-pickers#718]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  1.0.0       |
| material-ui         |  3.3.1       |
| React               |  16.4.1       |
| Browser             | Firefox        |
| Peer library        |  moment  2.22.2     | 

## Steps to reproduce
I upgraded to version 1 and my project doesn't start anymore! I get the following error:
```
./node_modules/material-ui-pickers/dist/material-ui-pickers.esm.js
Module not found: Can't resolve 'tslib' in '/home/my_project_dir/node_modules/material-ui-pickers/dist'
```

I use `yarn@1.10.1` as a dependancy manager.

**Comment by TrySound** [comment]
Thank you for report. It was accidentally missed. You may just at it to your dependencies for now.
