### ISSUE TITLE
Doc Site Getting Started WRONG

### ISSUE THREAD

**Issue by kyledgreen** [dmtrKovalenko/material-ui-pickers#720]
The Getting Started [Installation](https://material-ui-pickers.firebaseapp.com/installation) and [Usage](https://material-ui-pickers.firebaseapp.com/usage) sections indicated to:
`import MuiPickersUtilsProvider from 'material-ui-pickers/MuiPickersUtilsProvider';`

When it needs to be: 
`import { MuiPickersUtilsProvider } from 'material-ui-pickers';`

Otherwise, you get:
> Error: Can not find utils in context. You either a) forgot to wrap your component tree in MuiPickersUtilsProvider; or b) mixed named and direct file imports.  Recommendation: use named imports from the module index.

**Comment by sebastianvoss** [comment]
I'm still getting this error even with `import { MuiPickersUtilsProvider } from 'material-ui-pickers'`. See https://codesandbox.io/s/qko2xqv93q.

**Comment by danimbrogno-pml** [comment]
@sebastianvoss For some reason the problem disappeared for me when I changed:

```
import { MuiPickersUtilsProvider } from 'material-ui-pickers';
```

to 

```
import MuiPickersUtilsProvider from 'material-ui-pickers/MuiPickersUtilsProvider';
```

**Comment by TrySound** [comment]
@danimbrogno-pml You should use only named exports or path imports, but not both together.
```js
import { DatePicker, MuiPickersUtilsProvider } from 'material-ui-pickers';
```

or

```js
import { DatePicker } from 'material-ui-pickers/DatePicker';
import MuiPickersUtilsProvider from 'material-ui-pickers/MuiPickersUtilsProvider';
```

**Comment by TrySound** [comment]
I recommend named exports because bundles have more optimizations.

**Comment by stefensuhat** [comment]
docs write

`import { DatePicker } from 'material-ui-pickers';` 

it should be

`import DatePicker from 'material-ui-pickers/DatePicker';`

**Comment by itoed** [comment]
Can anybody tell what the problem is with the example from @sebastianvoss here: https://codesandbox.io/s/qko2xqv93q?

**Comment by TrySound** [comment]
@stefensuhat Not necessary. `import { DatePicker } from 'material-ui-pickers';` is recommended way.

**Comment by TrySound** [comment]
@itoed Same problem as everywhere above. Import from only one place.
https://codesandbox.io/s/q36ql75q3j

**Comment by itoed** [comment]
Ahh, I get it now from your exampe.  Thank you @TrySound!

**Comment by barbalex** [comment]
@TrySound yeah, you are right but what you say does not work for `DateFnsUtils` or, in my case, `MomentUtils`. Which is rather unintuitive and sent me on a debugging adventure.

Anyway: Thanks for this great tool.

**Comment by barbalex** [comment]
Also: The docs are not consistent on importing utils:

- according to the readme it is `import MomentUtils from 'material-ui-pickers/moment-utils'`. Which errors in my case
- according to the [documentation website](https://material-ui-pickers.firebaseapp.com/installation) it is `import MomentUtils from 'material-ui-pickers/utils/moment-utils'`

**Comment by TrySound** [comment]
Bad merge. Never mind. These utils will be provided as separate packages soon
https://github.com/dmtrKovalenko/date-io

**Comment by kamarajuPrathi** [comment]
Should we have to install date-io instead of individual utils , how to resolve the issue 
Error: Can not find utils in context. You either a) forgot to wrap your component tree in MuiPickersUtilsProvider; or b) mixed named and direct file imports.  Recommendation: use named imports from the module index.

**Comment by kamarajuPrathi** [comment]
@dmtrKovalenko how should fix the above issue `<MuiPickersUtilsProvider utils={DateFnsUtils}><InlineDatePicker
            key={index}
            label={ label }
            value={ value }
            clearable
            onChange={ (e) => onChange(e) }
          /></MuiPickersUtilsProvider>` do you see anything wrong in this , i get this error Error: Can not find utils in context. You either a) forgot to wrap your component tree in MuiPickersUtilsProvider; or b) mixed named and direct file imports. Recommendation: use named imports from the module index.

**Comment by TrySound** [comment]
Yes, use named imports from material-ui-pickers entry point. If you still get the error show your imports.

**Comment by kamarajuPrathi** [comment]
@TrySound 
`import { InlineDatePicker } from 'material-ui-pickers'
import DateFnsUtils from "material-ui-pickers/utils/date-fns-utils";
import MuiPickersUtilsProvider from "material-ui-pickers/MuiPickersUtilsProvider";`

these are the imporst

**Comment by TrySound** [comment]
Import provider from entry point too. I already attached the example above.

**Comment by deeptikanta** [comment]
import { InlineDatePicker } from 'material-ui-pickers';

this import giving me error.

**Comment by TrySound** [comment]
@deeptikanta 
```js
import { InlineDatePicker, MuiPickersUtilsProvider } from 'material-ui-pickers'
import DateFnsUtils from "material-ui-pickers/utils/date-fns-utils";
```

**Comment by GarrettJMU** [comment]
I'm still seeing this issue:
    "material-ui-pickers": "^2.02",
    "@date-io/moment": "^0.0.2",


import MomentUtils from "@date-io/moment"
import MuiPickersUtilsProvider from 'material-ui-pickers/MuiPickersUtilsProvider';

          <MuiPickersUtilsProvider utils={MomentUtils} >
              {children}
          </MuiPickersUtilsProvider>

**Comment by joelvh** [comment]
When  will the docs website be updated with  v2 docs?

**Comment by dmtrKovalenko** [comment]
@joelvh they are updated

**Comment by joelvh** [comment]
awesome!  Thanks @dmtrKovalenko -  that ought to help avoid some  confusion :-)

**Comment by josoroma** [comment]
To me works with:

```
import { MuiPickersUtilsProvider } from 'material-ui-pickers'
import DayJSUtils from '@date-io/dayjs'
```

```
      <MuiThemeProvider theme={theme}>
        <MuiPickersUtilsProvider utils={DayJSUtils}>
         ....
        </MuiPickersUtilsProvider>
      </MuiThemeProvider>
```

**Comment by aihihi** [comment]
I had the same issue after installing more time libraries. Read this post and tried some provided ways. Finally, this work for me.

import { DatePicker, MuiPickersUtilsProvider } from 'material-ui-pickers';
import MomentUtils from '@date-io/moment';

<MuiPickersUtilsProvider utils={MomentUtils}>
   ......
</MuiPickersUtilsProvider>

**Comment by chenop** [comment]
For me the issue was that the specific component I tried to use with `DatePicker `was not wrapped with `MuiPickersUtilsProvider`
