### ISSUE TITLE
Month view to select a month only without selecting a specific day

### ISSUE THREAD

**Issue by basselAhmed** [dmtrKovalenko/material-ui-pickers#736]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Implementation of an option like monthOnly=true or something.

**Describe alternatives you've considered**
an alternative would be letting the user select any day normally but actually use the month only and discard the day, but this isn't the best user experience.

**Additional context**
Something like this.
![image](https://user-images.githubusercontent.com/17992240/47966446-17c17400-e05b-11e8-8c25-6a49127f55b3.png)

**Comment by basselAhmed** [comment]
@dmtrKovalenko 
This isn't strictly for selecting month only, take a look at this datepicker component from Vuetify, this is exactly what I requested but with the ability to skip selecting the day.
https://vuetifyjs.com/en/components/date-pickers
The feature I described will use year and month and as a user I don't think having 2 dropdown elements for selecting year and month is better than having a datepicker that combines both.

**Comment by dmtrKovalenko** [comment]
I know that vuetify use this way to render control but it’s not material design way for now. 
And personally I didn’t like that control. So I have not intent to integrate it
