### ISSUE TITLE
Unable to select seconds in datetimepicker

### ISSUE THREAD

**Issue by VMBindraban** [dmtrKovalenko/material-ui-pickers#739]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     1.0.1    |
| material-ui         |     3.3.1    |
| React               |   16.5.1     |
| Browser             |    Chrome 70     |
| Peer library        |   date-fns 2.0.0-alpha.16      | 

## Expected behavior
To be able to select seconds in the `datetimepicker` when the property is set.

## Actual behavior
It's not possible to select seconds in the `datetimepicker` through the dialog.

The `timepicker` has the property `seconds` which determines to show it. The `datetimepicker` doesn't have this option.

We are currently using `format="MMMM do yyyy HH:mm:ss"` but the seconds are being reset to `00` when you chose a date and time.
## Live example
See `Seconds input` https://material-ui-pickers.firebaseapp.com/demo/timepicker

**Comment by dmtrKovalenko** [comment]
Yes, because of ui reason

**Comment by VMBindraban** [comment]
What kind of UI reason?

I can't imagine this to be a problem for users since they already have to select the hours and minutes.
Ofcourse this can be toggled by a option.

**Comment by dmtrKovalenko** [comment]
It will make date picker to wide

**Comment by bikeshedder** [comment]
I also need seconds in my `DateTimePicker`. It should be no big deal if the font was a tad smaller if seconds are to be shown, no? It really is weird that `seconds` are an option for `TimePicker` but not for `DateTimePicker`.

**Comment by vianneyguesdon** [comment]
Found a module that does this with seconds : 
https://material-ui-pickers.dev/demo/timepicker

**Comment by GlennS** [comment]
I would also use seconds in DateTimePicker if it were available.

For now I will make something custom.

**Comment by flying-falcon** [comment]
Documentation says 

views=["date", "year", "month" , "hours", "minutes"]  | Array of views to show

But seconds are missing, can you help adding seconds to views as many users are asking for this feature.

**Comment by Billy-** [comment]
I also really need this feature. I was able to easily add it in the v3-x branch. @dmtrKovalenko would you be willing to accept a PR to that branch? The contributing says to develop on the `next` branch, but it seems to be for the next major release.. Not sure when this will be, and I had some problems trying to work on that branch anyway. It seems very different to the 3.x release I am using now.

![image](https://user-images.githubusercontent.com/4316168/83270539-85df0600-a1c0-11ea-81c7-8817210455d4.png)

**Comment by victor-trx** [comment]
@Billy- Could you please share your PR?

**Comment by ololoepepe** [comment]
Not a 100% solution, but you may pass `views={[..., 'seconds']}` prop, and the user will be prompted to enter seconds. Although the value will not be displayed anywhere in the modal, it will be saved. Sadly, libs' authors always know better what we, users, actually need (at least they think so).
