### ISSUE TITLE
Jalaali Calendar System

### ISSUE THREAD

**Issue by alitaheri** [dmtrKovalenko/material-ui-pickers#74]
Hi, I'm willing to implement jalaali calendar system for your date-picker. I'll make it opt-in to prevent extra bytes for those who don't need it.

However, before spending time I would like to know if you ( and the community ) is open to the idea.

Some background: Iran uses a different calendar system. With different years, months and days. The conversion is straightforward but calendar integration is complex.

I have done this before for the 0.x version of material-ui. I solved it by passing a utils object that handles the calculations and formatting. I can do the same here, Are you ok with it?

Related #55

**Comment by dmtrKovalenko** [comment]
Hi, thank you so match, I think it would be really helpful.
But we are using `moment` as a core dependency to calculate and format data. Would it works if simply replace moment with [moment-jalaali](https://github.com/jalaali/moment-jalaali)? 
Anyway if you have any idea of how it can be implemented, feel free to open a pull request, or ask me to implement something. 
I think your work would be appreciated

**Comment by alitaheri** [comment]
@dmtrKovalenko No it's a lot more complex than that 😅 😅

I'll do my best to have the lowest impact on the code when not using the jalaali system. And I've already implemented most of the logic [here](https://github.com/alitaheri/material-ui-persian-date-picker-utils), I only need to patch your repository to be compatible.

**Comment by dmtrKovalenko** [comment]
🎉   Published in 1.0.0-beta.5
