### ISSUE TITLE
[2.0.0] MIgration problem with moment

### ISSUE THREAD

**Issue by karensg** [dmtrKovalenko/material-ui-pickers#745]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   2.0.0      |
| material-ui         |   3.4.0      |
| React               |      16.6.0   |
| Browser             |    Any     |
| Peer library        |  moment @date-io/moment       | 

Just tried to migrate to 2.0.0 and replaced the import to `import MomentUtils from '@date-io/moment';` like said in the Readme. The peer libraries are installed `moment @date-io/moment`.

Getting an error:
`Can not find utils in context. You either a) forgot to wrap your component tree in MuiPickersUtilsProvider; or b) mixed named and direct file imports.  Recommendation: use named imports from the module index.`

Are there some missing migration steps?

**Comment by TrySound** [comment]
@karensg There wasn't an issue. Just don't mix path imports and named imports. Import everything from `material-ui-pickers`
