### ISSUE TITLE
[DatePicker] Warning: Received `false` for a non-boolean attribute `ampm`.

### ISSUE THREAD

**Issue by romandubrov** [dmtrKovalenko/material-ui-pickers#748]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  2.0.0  |
| material-ui         |  3.4.0  |
| React               |   16.6.0      |
| Browser             |   Chrome 70.0.3538.77      |
| Peer library        |   moment 2.22.2      | 

## Steps to reproduce
set ampm prop of DatePicker to false

## Expected behavior
No warning

## Actual behavior
got a warning in console
Warning: Received `false` for a non-boolean attribute `ampm`.

however, [https://material-ui-pickers.firebaseapp.com/demo/datepicker](https://material-ui-pickers.firebaseapp.com/demo/datepicker) says that ampm is boolean

## Live example
https://codesandbox.io/s/myzv4q395j

**Comment by dmtrKovalenko** [comment]
Oh, thats my fault :( 
Datepicker doesn't have this property. Only time and datetime picker do
