### ISSUE TITLE
Calendar widget access

### ISSUE THREAD

**Issue by mokargas** [dmtrKovalenko/material-ui-pickers#75]
Hey there,

Is it possible just to expose the Calendar widget alone instead of the entire Date Picker?

**Comment by dmtrKovalenko** [comment]
Hi, seems that there is no way for now)
Because of its build with rollup as entire module, with just 3 exports.
Hmm I think we should change build strategy like in material ui to have exported all component.

**Comment by alitaheri** [comment]
@dmtrKovalenko Will you take care of this? I can reuse the same methods used by material-ui.

**Comment by alitaheri** [comment]
@mokargas Now you can access whatever you want. it's all under `material-ui-pickers/src`.

```ts
import Calendar from 'material-ui-pickers/src/DatePicker/Calendar';

...
```
