### ISSUE TITLE
Example Using locale date fns with V2.0

### ISSUE THREAD

**Issue by jkeruzec** [dmtrKovalenko/material-ui-pickers#750]
Could you provide an example using locale with V2.0 and date fns please ? or maybe update the documentation site ?

Thanks !

**Comment by dmtrKovalenko** [comment]
@jkeruzec documentation site is up-to-date try to clear your cache

**Comment by jkeruzec** [comment]
You're right ! Cache cleared, it's OK!

Thanks for reactivity!
