### ISSUE TITLE
Fully controlled picker

### ISSUE THREAD

**Issue by gustavopch** [dmtrKovalenko/material-ui-pickers#757]
**Is your feature request related to a problem? Please describe.**
I need to validate a date from DateTimePicker externally (using Formik in my case).

**Describe the solution you'd like**
To do that, DateTimePicker should let me store a partially typed value outside (so that I can validate by myself without relying on `onError`) and pass it back through `value` prop without screwing everything.

**Describe alternatives you've considered**
Couldn't find a decent alternative yet.

**Additional context**
Is there any other way to use DateTimePicker with Formik without storing in the formik state partially typed dates that I'm not considering?

**Comment by gustavopch** [comment]
Yes. But does the picker need to have the Date object coming from the props? Couldn't it try to parse the string internally wherever needed?

**Comment by dmtrKovalenko** [comment]
Exectly need

**Comment by gustavopch** [comment]
Why couldn't you parse the Date from the raw string where a Date is required?

**Comment by dmtrKovalenko** [comment]
Because partial date can be unparseable
