### ISSUE TITLE
Clear selected date with simply a clear icon without opening the calendar

### ISSUE THREAD

**Issue by killjoy2013** [dmtrKovalenko/material-ui-pickers#758]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dmtrKovalenko** [comment]
Do it by yourself

**Comment by nugz1012** [comment]
This was a solution I came up with for this. Hope this helps anyone who stumbles across this. If there is a better way let me know.

I am using Formik on my app so I included it in the example.
https://codesandbox.io/s/42y21jj057
