### ISSUE TITLE
minDate prop in not working.

### ISSUE THREAD

**Issue by omerquyyum** [dmtrKovalenko/material-ui-pickers#76]
Warning: React does not recognize the `minDate` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `mindate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by dmtrKovalenko** [comment]
Please provide the code, you are using

**Comment by dmtrKovalenko** [comment]
Closing issue due to no steps to reproduce
