### ISSUE TITLE
Access onBlur handler of the calendar icon of Datepicker

### ISSUE THREAD

**Issue by sedi0861** [dmtrKovalenko/material-ui-pickers#760]
A onBlur handler & onKeyDown handler is needed for the Datepicker icon component in order to call a function or change focus.

A onBlur handler and onKeyDown handler for the icon will be a good solution.

![image](https://user-images.githubusercontent.com/36396597/48405434-4674d400-e758-11e8-9447-88046d689428.png)

**Comment by dmtrKovalenko** [comment]
You can use `InputAdornmentProps ` for that purpose
