### ISSUE TITLE
Cannot integrate form validation

### ISSUE THREAD

**Issue by JavierLight** [dmtrKovalenko/material-ui-pickers#761]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  v.2.0.0       |
| material-ui         |   v3.4.0      |
| React               |    v16.4.2     |
| Browser     |  Chrome v.70.0.3538.67       |    
|   Peer dependency      |  luxon v1.5.0      |

## Steps to reproduce
1. Using keyboard input mode
2. Using `react-material-ui-form-validator` to avoid sending a request to BE when FE validation is incorrect. Ideally to be integrated with `react-material-ui-form-validator`: 
https://github.com/NewOldMax/react-material-ui-form-validator/wiki/Material-ui-v1-datepickers-example

## Expected behavior
Since `DatePicker` is wrapping a `TextField`, I would expect to get an `onChange` callback whenever the input is changed, as it happens in a `TextField` component. 

## Actual behavior
The `onChange` and `onError` callbacks are only executed in the parent component when clicking somewhere else, even though validation is being performed inside the `DatePicker` component (the error message is shown).

I think it'd be great to have a way to get information about date validation status so that this component can be integrated in a `ValidationForm`, like an `isValid` prop callback, so that the form is not submited if internal validation failed.

Is there any workaround to get to know from the parent if the date is valid whenever it's modified in keyboard input mode? This way we would be able to disable the `Save` button if `DatePicker` is displaying any kind of error message.

Thank you very much for your time!

**Comment by dmtrKovalenko** [comment]
http://localhost:3002/guides/formik-integration
