### ISSUE TITLE
onChange function prop BasePicker not called 

### ISSUE THREAD

**Issue by Anwardo** [dmtrKovalenko/material-ui-pickers#762]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |      2.0.1  |
| material-ui         |     3.5.1    |
| React               |     16.6.3    |
| Browser             |     Chrome    |
| Peer library        |   date-fns      | 

## Steps to reproduce
1. Create a static picker using `<BasePicker>` and `<Calendar>` as per the documentation example
2. Add a function to the onChange prop to the BasePicker
3. Function is not called

## Expected behavior

onChange prop on BasePicker should call the function passed with the changed date as variable.

## Actual behavior

The function inside the onChange handler is not called. The onChange handler on the Calendar component _is_ fired as you can see in the sandbox below.

## Live example

Check here for a live example:
https://codesandbox.io/s/xp347yn3pw

**Comment by dmtrKovalenko** [comment]
On change will be called if autoOk is passed or handleAccept was called https://codesandbox.io/s/k205qokwxr
