### ISSUE TITLE
Date part is set to today when using keyboard input on TimePicker

### ISSUE THREAD

**Issue by benochr** [dmtrKovalenko/material-ui-pickers#763]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |2.0.1         |
| material-ui         |3.5.1         |
| React               |16.6.3         |
| Browser             |Electron 3.0.9         |
| Peer library        |moment 2.22.2         | 

## Steps to reproduce
1. Set a time field in the state to a specific value not on the current day.
2. Create a `TimePicker` element with keyboard input enabled and the value from the previously created field in the state.
3. Put the cursor in the input field and press backspace.
4. Check the new time value in the `onChange` handler

## Expected behavior

The time that is passed to the `onChange` handler represents the new time value and the date part is not changed.

## Actual behavior

The time is passed but the date part is set to the current day. When selecting a new time with the clock the date part is kept as set.

## Live example

https://codesandbox.io/s/wyr82wlqkk

**Comment by dmtrKovalenko** [comment]
https://codesandbox.io/s/nw32rvw8r4
