### ISSUE TITLE
Bug Fixes did not apply on develop

### ISSUE THREAD

**Issue by johannwagner** [dmtrKovalenko/material-ui-pickers#764]
Hey Guys, 

I fixed a bug earlier and introduced a PR, which was merged into develop. We wanted to update to `2.0.1` and ran into the same bug and now, we saw, that the commit was rebased to an commit, which does not introduce a fix, but it did earlier (see PR #722). In the commit in develop, it is empty (see https://github.com/dmtrKovalenko/material-ui-pickers/commit/2066d8a8bcb31e8639a0e789af84bd17630646f5).

How do we fix this?

Best Regards, 
   Johann

//cc @martenwallewein

**Comment by dmtrKovalenko** [comment]
Hmm I see only `package.json` and `package-lock.json` file changes in the commit.
