### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by alitaheri** [dmtrKovalenko/material-ui-pickers#78]
material-ui supports typescript. I think we should do the same. I'm willing to write and maintain the typings. Are you open to the idea? @dmtrKovalenko

**Comment by dmtrKovalenko** [comment]
Yes. Really I am intent on support both flow and typescript. But unfortunatly I have really little time now, so the most relevant feature would be 24 hours, that I would work on. 
If you wanna create typings for ts - **BIG THANKS**
Your work would be appreciated.

**Comment by alitaheri** [comment]
@dmtrKovalenko This is blocked by the deployment method. Since we don't distribute every component like material-ui and instead distribute a bundle of the three main components the typings won't be much of use. We should focus on the build process first and then worry about the typings.

**Comment by dmtrKovalenko** [comment]
Ohh, I see. But its just like declarations for the file, it doesnt possible to declare all types in one file?

**Comment by alitaheri** [comment]
@dmtrKovalenko It is possible, but not really recommended since it becomes hard to maintain. We should first decide on way we wish to deploy the package then write the typings.

**Comment by dmtrKovalenko** [comment]
Hmm I`ll take a look on that, I think we should implement that anyway

**Comment by KKrisu** [comment]
Greetins @alitaheri How is it going, are the typings already available? (I can't find them on npm :thinking: )

**Comment by dmtrKovalenko** [comment]
They are provided with the project directly. No need to install @types
