### ISSUE TITLE
PropTypes warning

### ISSUE THREAD

**Issue by aeciolevy** [dmtrKovalenko/material-ui-pickers#781]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    2.0.2     |
| material-ui         |    3.0.1     |
| React               |    16.6     |
| Browser             |    Chrome 70     |
| Peer library        |   date-io       | 

## Steps to reproduce
1. Open a TimerPicker

## Expected behavior

Don't show prop-types warning to typography.

## Actual behavior

PropTypes warning:
Failed prop type: Invalid prop `variant` of value `h2` supplied to `Typography`, expected one of ["display4","display3","display2","display1","headline","title","subheading","body2","body1","caption","button","srOnly","inherit"].

**Comment by dmtrKovalenko** [comment]
Update to the new material-ui text formats

**Comment by aeciolevy** [comment]
Sorry, @dmtrKovalenko what do you mean by that?
