### ISSUE TITLE
Adornment Padding Causing Console Error

### ISSUE THREAD

**Issue by kyledgreen** [dmtrKovalenko/material-ui-pickers#784]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     1.0.0   |
| material-ui         |    3.3.1     |
| React               |    16.6.0     |
| Browser             |   Chrome      |
| Peer library        |    moment     |

## Steps to reproduce
1. Go to the Documentation here: https://material-ui-pickers.firebaseapp.com/api/datepicker
2. On the Keyboard Input section, where the picker has a calendar button, open the console by inspecting the page.
3. Use the element selector from the dev controls and move it between the input element and the calendar button. There is an 8px padding space that exposes the form control between the input and the button.
4. Disable the element selector and click that space.

## Expected behavior
There should be no space between the input and the Button exposing the form control element. Clicking should either enter the input or the button.

## Actual behavior
There is a space exposing the Form Control element that if clicked throws an unhandled error.

## Live example
https://material-ui-pickers.firebaseapp.com/api/datepicker
Use the one with the calendar button.

**Comment by dmtrKovalenko** [comment]
![image](https://user-images.githubusercontent.com/16926049/49695880-18917c80-fbaa-11e8-9848-cd81e56a860a.png)
Do you mean this margin? I am sorry cannot really reproduce the bug

**Comment by kyledgreen** [comment]
Yes, if you click that space it causes an exception in the console.

**Comment by dmtrKovalenko** [comment]
https://github.com/mui-org/material-ui/issues/13894#issuecomment-447724356

**Comment by harinarayanan-gooner** [comment]
I apologize for being abrupt. I am facing an issue where the input adornment mentioned above has a padding left of 8px. How can i remove the 8px padding ? breaking my head over this.
