### ISSUE TITLE
Feature request: "Clear" icon button in date input.

### ISSUE THREAD

**Issue by stsiarzhanau** [dmtrKovalenko/material-ui-pickers#790]
**Is your feature request related to a problem? Please describe.**
It's quite common when we need to clear selected date in datepicker. Currently this feature is not implemented for inline datepicker. So we need to add external controls and logic to handle it.

**Describe the solution you'd like**
It'd be very handy to have optional "X" icon button in date input itself (like in [react-datepicker](https://reactdatepicker.com/#example-25)) that allows us to clear selected date when clicking on it.

**Comment by dmtrKovalenko** [comment]
Would you like to open a PR?

**Comment by stsiarzhanau** [comment]
I have never used TypeScript, but I can try.

**Comment by dmtrKovalenko** [comment]
@stsiarzhanau nice way to start with ts. Its pretty awesome
