### ISSUE TITLE
shouldDisableDate sets all disabled dates with the wrong date

### ISSUE THREAD

**Issue by canastro** [dmtrKovalenko/material-ui-pickers#791]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    2.0.4     |
| material-ui         |     3.5.1    |
| React               |     16.6.0    |
| Browser             |     chrome@70    |
| Peer library        |      moment@2.22.2   |

## Steps to reproduce
1. npm i --save material-ui-pickers@2.0.4
2. Create a datepicker
3. Use shouldDisableDate and try to enable only a specific weekday

## Expected behavior
I expect only mondays to be selectable

## Actual behavior
Everyday of the week is rendered with the date of the closest monday.

## Live example
https://codesandbox.io/s/32081pr86

**Comment by dmtrKovalenko** [comment]
I am seeing plain example of picker in sandbox

**Comment by canastro** [comment]
@dmtrKovalenko  Sorry, forgot to save the file, check it now

**Comment by dmtrKovalenko** [comment]
Instead of checking day for Monday you are mutating each day object to be the Monday of the week 
Try (date) => date.day() === 1

**Comment by canastro** [comment]
Ops, that was noobish of me. Thanks
