### ISSUE TITLE
Cannot compile project

### ISSUE THREAD

**Issue by bernhardwaidacher** [dmtrKovalenko/material-ui-pickers#792]
I cannot build the project since adding this as dependency. 

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |2.0.4|
| material-ui         | 3.5.1|
| React               |16.6.3|
| Browser             |Safari 12.0.1|
| Peer library        |moment|

## Steps to reproduce
1. execute `yarn install material-ui-pickers`
2.  add 
```
import {InlineDatePicker} from "material-ui-pickers";
import moment from "moment"

              <InlineDatePicker
                label="Inline"
                value={moment()}
                onChange={(d) => {console.log(d)}}
              />
```
3. execute `yarn start`

## Expected behavior
App should start and display the date picker

## Actual behavior
Project cannot compile because of this error:
```
/node_modules/material-ui-pickers/wrappers/InlineWrapper.d.ts
Type error: Type 'string | number | symbol' does not satisfy the constraint 'string'.
  Type 'number' is not assignable to type 'string'.  TS2344

    49 |     classes: Record<"popoverPaper", string>;
    50 |     innerRef?: ((instance: any) => void) | React.RefObject<any> | null | undefined;
  > 51 | } & Pick<PropTypes.InferProps<any>, string | number | symbol>, string | number | symbol> & import("@material-ui/core/styles/withStyles").StyledComponentProps<"popoverPaper">>;
       |                                     ^
    52 | export default _default;
```

This is the `tsconfig.json`:

```
{
  "compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
    "lib": [
      "es2018",
      "dom"
    ],
    "sourceMap": true,
    "allowJs": true,
    "jsx": "preserve",
    "moduleResolution": "node",
    "rootDir": "src",
    "forceConsistentCasingInFileNames": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "importHelpers": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": true,
    "keyofStringsOnly": true,
    "skipLibCheck": false,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest",
    "src/setupTests.ts",
    "node_modules/**"
  ],
  "include": [
    "src",
    "./typings.d.ts"
  ]
}
```

and `tslint.json`
{
    "extends": ["tslint:recommended", "tslint-react", "tslint-config-prettier"],
    "linterOptions": {
        "exclude": [
            "config/**/*.js",
            "node_modules/**/*.ts",
            "coverage/lcov-report/*.js",
            "src/assets/**/*.jsx",
            "src/components/**/*.jsx",
            "src/views/**/*.jsx",
            "**/node_modules/**/*",
            "node_modules/**/*",
            "node_modules",
            "node_modules/**/**/*.d.ts",
            "node_modules/**"

        ],
        "include": [
            "src/**/*.ts"
        ]
    },
    "rules": {
        "no-console": false,
        "object-literal-sort-keys": false,
        "ordered-imports": false,
        "member-ordering": false,
        "no-switch-case-fall-through": true,
        "no-namespace": false,
        "jsx-no-lambda": false
    }
}
```

**Comment by dmtrKovalenko** [comment]
Please share the versions of `@types/react` you use

**Comment by bernhardwaidacher** [comment]
I'm usung `"@types/react": "16.7.7"`

**Comment by nick-gaudreau** [comment]
This is what I'm using and it works just fine:

 "dependencies": {
    "@date-io/date-fns": "0.0.2",
    "@material-ui/core": "^3.4.0",
    "@material-ui/icons": "^3.0.1",
    "@types/jest": "23.3.9",
    "@types/node": "10.12.2",
    **"@types/react": "^16.7.6",**
    "@types/react-dom": "16.0.9",
    "@types/react-router-dom": "^4.3.1",
    "@types/recharts": "^1.1.1",
    "date-fns": "^2.0.0-alpha.21",
    "material-ui-pickers": "2.0.4",
    **"react": "^16.6.3",**
    "react-dom": "^16.6.0",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.1",
    "recharts": "^1.3.6",
    **"typescript": "3.1.6"**
  }

**Comment by olee** [comment]
The issue is with this declaration when using keyofStringsOnly=true in typescript options:
```typescript
declare const _default: React.ComponentType<Pick<InlineWrapperProps & {
    classes: Record<"popoverPaper", string>;
    innerRef?: ((instance: any) => void) | React.RefObject<any> | null | undefined;
} & Pick<PropTypes.InferProps<any>, string | number | symbol>, string | number | symbol> & import("@material-ui/core/styles/withStyles").StyledComponentProps<"popoverPaper">>;
```

It should be instead
```typescript
declare const _default: React.ComponentType<Pick<InlineWrapperProps & {
    classes: Record<"popoverPaper", string>;
    innerRef?: ((instance: any) => void) | React.RefObject<any> | null | undefined;
} & Pick<PropTypes.InferProps<any>, keyof any>, keyof any> & import("@material-ui/core/styles/withStyles").StyledComponentProps<"popoverPaper">>;
```

**Comment by dmtrKovalenko** [comment]
Already fixed

**Comment by olee** [comment]
Can you reference the checkin that fixed this please?
