### ISSUE TITLE
Display Time in one timezone and not local timezone

### ISSUE THREAD

**Issue by withakw** [dmtrKovalenko/material-ui-pickers#793]
**Is your feature request related to a problem? Please describe.**
I have a need to be able to display a time in one Timezone no matter where in the world it is displayed. We have a central system to which things happen and we would like to display the times of the actions based on the time for where the system is so that when people discuss it they all use the same time and do not have to do any time conversions

**Describe the solution you'd like**
I would like to have a timezone option on DateTime and Time pickers which specifies the timezone to be used on the display which stops the local timezone being used

**Describe alternatives you've considered**
I have used textfields to display the date and times and setting the string to the desired times. This works if it is not being updated but to allow a user to change the time requires the pickers to be used

**Additional context**
None

**Comment by dmtrKovalenko** [comment]
You must use `luxon` or `moment-timezone` to work with dates. Just pass an object with configured timezone in picker and it will return timezoned object as well

**Comment by jakeleventhal** [comment]
@dmtrKovalenko I was trying to understand how this works using this page on the documentation https://material-ui-pickers.dev/localization/moment. It isn't clear as to how you are supposed to actually set the timezone for the picker.

Example: say I want my picker to always be in French time. In US EST time it is May 28, but in Paris it is May 29. The picker should show that "Today" is May 29 even if the user is in the United States

**Comment by jakeleventhal** [comment]
@dmtrKovalenko Wanted to follow up on this

**Comment by behnamazimi** [comment]
@jakeleventhal What if we need to set the default value as null? 
So when the picker opens, it will show the local time.
