### ISSUE TITLE
Поддержка выбора месяца

### ISSUE THREAD

**Issue by borm** [dmtrKovalenko/material-ui-pickers#795]
Сабж
Можно [сюда](https://github.com/dmtrKovalenko/material-ui-pickers/blob/develop/lib/src/DatePicker/DatePicker.tsx#L147) добавить какой нибудь свитч кейс и сделать еще один компонент, Month Picker?

**Comment by borm** [comment]
Похожее поведение как тут
https://material.angular.io/components/datepicker/overview

**Comment by dmtrKovalenko** [comment]
Please rise issues in english
