### ISSUE TITLE
Any DatePicker component immediately errors with missing utils from Context

### ISSUE THREAD

**Issue by JReinhold** [dmtrKovalenko/material-ui-pickers#800]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |2.0.4    |
| material-ui         |@material-ui/core@3.6.2    |
| React               |16.6.3   |
| Browser             |Chrome v70.0.3538.110|
| Peer library        |date-fns@2.0.0-alpha.25, @date-io/date-fns@0.0.2|

## Steps to reproduce
1. Add `<MuiPickersUtilsProvider utils={DateFnsUtils} />` to top-level component
2. Add `<InlineDatePicker onChange={console.log} value={new Date()} />` somewhere in app 
3. Get error:
```
Can not find utils in context.
You either a) forgot to wrap your component tree in MuiPickersUtilsProvider;
or b) mixed named and direct file imports.
Recommendation: use named imports from the module index.
```

## Expected behavior
It rendered a basic inline datepicker.

## Actual behavior
I get an error, see above.

## Live example
I've created a basic CodeSandbox that (should) use the most up-to-date versions of all the libraries.
[Basic CodeSandbox](https://codesandbox.io/s/qxwnw8vnn9)

## Additional Information
I can't get anything to work with this basic setup, it is not just the `InlineDatePicker` that is faulty. I also tried using the basic `DatePicker` component, (because I wanted to copy the "Integration with Formik" guide), but its propTypes stated that it needed an `utils` prop that I couldn't find mentioned anywhere in the docs. Let me know if you need more information from me.

Thanks!

**Comment by dmtrKovalenko** [comment]
# Do not mix direct and named imports
https://codesandbox.io/s/r405k1w8yn

**Comment by JReinhold** [comment]
oh THAT was what it meant, thanks! I confused it with "named" and "default" imports, and made absolutely sure that I wasn't using any default imports.

Sorry for the inconvenience, thanks for the help!

**Comment by bogdibota** [comment]
If this happens in a `yarn workspace` scenario (like Lerna) and the imports are correct, check this answer https://stackoverflow.com/a/66639496/6615035
