### ISSUE TITLE
update your doc

### ISSUE THREAD

**Issue by zijian-etc** [dmtrKovalenko/material-ui-pickers#801]

**Comment by dmtrKovalenko** [comment]
?

**Comment by Cherviakov** [comment]
Please update documentation on your website, it is still for version 1

**Comment by dmtrKovalenko** [comment]
![image](https://user-images.githubusercontent.com/16926049/49927390-78e42f00-fec6-11e8-8604-97d968a6be70.png)

**Comment by kr3zw** [comment]
The fact that up top says `2.0.4` doesn't mean your examples reflect to the said version.  
All your examples are outdated!
For example, you showcase a **DatePicker** having the `value` property, which does not exist anymore and it's been replaced by `date`!  
That's what the guys meant with.. `Update your doc`. It does need to be updated!  

![image](https://user-images.githubusercontent.com/19870633/49931568-d335bd80-fecf-11e8-85ad-733b797a83f4.png)

**Comment by dmtrKovalenko** [comment]
It wasn’t replaced

**Comment by dmtrKovalenko** [comment]
@kr3zw If you find out we exposing up not date picker by itself but `BasePicker` HOC. It requires actually `value` and pass down to `Datepicker` a `date` prop

**Comment by dmtrKovalenko** [comment]
https://github.com/dmtrKovalenko/material-ui-pickers/blob/develop/lib/src/DatePicker/DatePickerModal.tsx#L39
