### ISSUE TITLE
Localize 'Cancel' button

### ISSUE THREAD

**Issue by airled** [dmtrKovalenko/material-ui-pickers#803]
Hello. Control buttons (ok and cancel) stay the same even if I pick some localization.

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   1.0.0-rc.14      |
| material-ui         |      1.5.1   |
| React               |   16.4.2      |
| Browser             |    every     |
| Peer library        |     date-fns 2.0.0-alpha.16    | 

Screenshot from your [site](https://material-ui-pickers.firebaseapp.com/localization/date-fns)
![2018-12-12-154439_1600x900_scrot](https://user-images.githubusercontent.com/10863999/49870609-f0618200-fe24-11e8-9620-ca0416bd01e5.png)
My app:
![2018-12-12-154654_1600x900_scrot](https://user-images.githubusercontent.com/10863999/49870696-34548700-fe25-11e8-995d-f6cd2b0cbfeb.png)

**Comment by dmtrKovalenko** [comment]
Do you think we need to bundle and provide all translations for all locales? You must do it by yourself

**Comment by dmtrKovalenko** [comment]
Pass custom label for ok and cancel

**Comment by airled** [comment]
> Do you think we need to bundle and provide all translations for all locales? You must do it by yourself
I did not mean for all localizations but for existing. But ok, I will pass by myself. Thanks.

**Comment by CapitanFuture** [comment]
How did I pass the text to the cancelLabel ? It's a ReactNode property ?

**Comment by dmtrKovalenko** [comment]
Yes it is react node

**Comment by raniel90** [comment]
```javascript
clearLabel={React.createElement('span', null, 'Limpar')}
cancelLabel={React.createElement('span', null, 'Cancelar')}
```
