### ISSUE TITLE
[Typescript] TypeError: Utils is not a constructor

### ISSUE THREAD

**Issue by CharlieIGG** [dmtrKovalenko/material-ui-pickers#805]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   2.0.4  |
| material-ui         |    1.2.2    |
| React               |     16.5.0     |
| Browser             |    Chrome / Node    |
| Peer library        |     moment -> 2.22.2    | 

## Steps to reproduce
1.  Given the following component:
```jsx
import MomentUtils from "@date-io/moment";
import DatePicker from "material-ui-pickers/DatePicker";
import MuiPickersUtilsProvider from "material-ui-pickers/MuiPickersUtilsProvider";
import * as moment from "moment";
import "moment/locale/es";
import * as React from "react";
moment.locale("es");

export function CustomDatePicker(props) {
  const { date, handleDateChange, ...rest } = props;
  return (
    <MuiPickersUtilsProvider utils={MomentUtils} moment={moment} locale="es">
      <DatePicker
        value={date}
        onChange={handleDateChange}
        {...rest}
      />
    </MuiPickersUtilsProvider>
  );
}

export default CustomDatePicker;
```
2. When mounted in a test using Jest + Enzyme like this:
```jsx
it("renders without crashing", () => {
  let elem = mount(
    <CustomDatePicker
      date={new Date().toString()}
      handleDateChange={e => console.log(e)}
    />
  );
});
```
3.  I get the following runtime error: `TypeError: Utils is not a constructor`.
If I use `shallow` instead then the test passes, but I get this warning: `Warning: Failed prop type: The prop 'utils' is marked as required in 'MuiPickersUtilsProvider', but its value is 'undefined' in MuiPickersUtilsProvider`.

In the real world, A.K.A outside of my tests the actual component seems to mount and work without issues, but this messes up not only my unit tests but all my integration tests. 

## Expected behavior
MuiPickersUtilsProvider shouldn't complain, my component should mount inside the test, and the test should pass. 

## Live example
I'm trying to reproduce this here, but MuiPickersUtilsProvider just refuses to render (?) 🤔
https://codesandbox.io/s/20j8zl8zzj

Thanks in advance for your help y'all!

**Comment by TrySound** [comment]
What do you use for bundling?

**Comment by dmtrKovalenko** [comment]
Because of mount actually deeply renders full tree of react component. It also renders picker's components that require context, provided by `<MuiPickersUtilsProvider />` so you must wrap your components with provider

**Comment by dmtrKovalenko** [comment]
```jsx
it("renders without crashing", () => {
  let elem = mount(
    <MuiPickersUtilsProvider utils={MomentUtils}>
      <CustomDatePicker
        date={new Date().toString()}
        handleDateChange={e => console.log(e)}
      />
    </MuiPickersUtilsProvider>
  );
});
```

**Comment by CharlieIGG** [comment]
@dmtrKovalenko so you mean **in addition** to the provider I'm already using inside the exported `<CustomDatePicker />` component as shown below? Isn't it weird I have to wrap things twice in the same provider?

```jsx
export function CustomDatePicker(props) {
  const { date, handleDateChange, ...rest } = props;
  return (
    <MuiPickersUtilsProvider utils={MomentUtils} moment={moment} locale="es">
      <DatePicker
        value={date}
        onChange={handleDateChange}
        {...rest}
      />
    </MuiPickersUtilsProvider>
  );
}
```

**Comment by CharlieIGG** [comment]
> What do you use for bundling?

I use Yarn for everything in this project @TrySound. Is that what you mean?

**Comment by dmtrKovalenko** [comment]
Indeed I am wrong. Can you please provide a repo with reproduction of these error. I need to look out on the jest config and so on

**Comment by CharlieIGG** [comment]
You know what @dmtrKovalenko, although I'm using Typescript on this project I've been trying to reproduce this in a simplified way, using just ES6, but it all works then... I'm thinking this might have something to do with how this library plays with TS...

**Comment by CharlieIGG** [comment]
Yeah, take a look at this Codesandbox:
Using ES6: https://codesandbox.io/s/82p2wlnmjl it all works, renders fine, test works
Using Typescript: https://codesandbox.io/s/j48672m8k9, same test, getting `Utils is not a constructor` both when rendering using ReactDOM, as well as with Enzyme.

**Comment by dmtrKovalenko** [comment]
I will take a look on it. That seems to be really strange bug 🐜

**Comment by CharlieIGG** [comment]
Thanks for your attention @dmtrKovalenko !

**Comment by dmtrKovalenko** [comment]
Hmm, thinks that something is happen with `esModuleIntertop` option. Can you play around with this option for your tests and code?

**Comment by CharlieIGG** [comment]
So I played around with a bunch of combinations in tsconfig.json and tsconfig.test.json for `module`, `esModuleInterop` and `allowSyntheticDefaultImports`.

The winning combo for my project was: 

tsconfig.json
```json
{
"compilerOptions": {
    "outDir": "build/dist",
    "module": "esnext",
    "target": "es5",
     ...
    "allowSyntheticDefaultImports": true
  },
}
```

tsconfig.test.json
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "esModuleInterop": true
  }
}
```

I hope that helps anybody facing the same issue. I think the issue can now be closed.

**Comment by sruthisripathi** [comment]
> What's funny is that I cannot replicate what I have on my real-life project.
> In this project the following happens:
> 
> 1. Using `import MomentUtils from "@date-io/moment"` works for the actual rendering with React-DOM, but breaks my tests.
> 2. Using `import * as  MomentUtils from "@date-io/moment";` makes the tests pass, but breaks the rendering of with React-DOM.
> 
> In both cases (respectively) the error is that instead of the `MomentUtils(_a) { … }` constructor function, the component receives an object that contains the constructor, like so `{default: MomentUtils(_a) { … }}`. I can make it work in this case by passing it like so `utils={MomentUtils.default}`, but _because the import result is always the other way around on my tests_ I always break either the tests or the real thing... 🤔 this is driving me nuts hahaha!
> 
> EDIT ---
> Correction: calling `import MomentUtils from "@date-io/moment"` results in MomentUtils being nothing in the test env?

Hi,
Were you able to figure out how to fix this??

**Comment by dmtrKovalenko** [comment]
@sruthisripathi the issue is in resolving modules. Your tests resolving modules differently with app. 
Default imports must be resolved by esm convention.

**Comment by sruthisripathi** [comment]
@dmtrKovalenko I'm sorry I didn't get you. Now how do I fix this issue?

**Comment by florleb** [comment]
Hey i'm facing the same issue but i can't use the "esModuleInterop" option. Do you have any clue to fix it by another way ?
