### ISSUE TITLE
Using the static Calendar with shouldDisableDate crashes the component

### ISSUE THREAD

**Issue by natehardy** [dmtrKovalenko/material-ui-pickers#806]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 2.0.4   |
| material-ui         | 3.6.1   |
| React               | 16.6.3  |
| Browser - Chrome    |         |
| "@date-io/moment": "0.0.2",   | 

## Steps to reproduce
1.
2.
3.

## Expected behavior

The shouldDisableDate should only process the dates on the current month displayed.

## Actual behavior

The function processes every single date

## Live example

I am using this function with moment
```js
function disableDateFunction(d) {
  let then = d.toDate();
  console.log(then);
  if (then > new Date()) {
    return true;
  }

  then.setHours(0, 0, 0, 0);
  let disabled = true;

  data.forEach(function(product) {
    console.log("product: ", product);
    if (new Date(product.source).getTime() === then.getTime()) {
      disabled = false;
    }
  });
  
  return disabled;
}
```

**Comment by dmtrKovalenko** [comment]
Calendar prerender 1 month before and after for animation purpose. I have run your codesnippet and everything works for me. feel free to ask reopen the issue if something was unclear
