### ISSUE TITLE
Allow CalendarHeader to be part of the static Calendar component

### ISSUE THREAD

**Issue by natehardy** [dmtrKovalenko/material-ui-pickers#807]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to use the modal as a static component as opposed to just the Calendar

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dmtrKovalenko** [comment]
I dont understand what you are meaning. Static calendar is actually contains header.
![image](https://user-images.githubusercontent.com/16926049/50599009-52a62380-0eb5-11e9-818b-559bdc6a6190.png)
