### ISSUE TITLE
Add minutesStep property to TimePicker

### ISSUE THREAD

**Issue by galechus** [dmtrKovalenko/material-ui-pickers#809]
It would be nice to add minutesStep property to TimePicker. This property would be responsible for how many minutes should be added/subtracted when moving the clock pointer - like in Materia-UI v0.xx TimePicker component.

**Comment by NikoLedesma** [comment]
Nice, either i suggest adding two poperties, minTime and maxTime. These properties would be checked if are in the range (between minTime and maxTime) after filling the input; If it is not in range the  function prop onError would be trigged and the input highlighted in red. Thk you.
