### ISSUE TITLE
 TimePicker OnError don´t  work

### ISSUE THREAD

**Issue by NikoLedesma** [dmtrKovalenko/material-ui-pickers#811]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    2.0.4     |
| material-ui         |    3.0.3     |
| React               |    16.6.3     |
| Browser             |    Chrome     |
| Peer library        |         | 

## Steps to reproduce
1. introduce a time after to current hours
2.don´t highligth with red color 
3.

## Expected behavior

when I input an hour higher than the current time I want to highlight the input with red color (error)

## Actual behavior

Don´t highlight the input. OnError behavior don´t catch error

## Live example
<TimePicker
          onError={e => {
            debugger;
            if (selectedDate !== null && selectedDate !== undefined) {
              var strDate = moment(selectedDate).format("MM/DD/YYYY");
              var strHour = moment(e).format("HH:mm");
              var newMoment = moment(strDate + " " + strHour);
              if (e._isValid) {
                handleChange(newMoment);
                if (newMoment > maxTime) {
                  handleChangeError();
                }
              } else {
                handleChangeError();
              }
            } else {
              handleChangeError();
            }
          }}
          keyboard
          ampm={false}
          format="HH:mm"
          placeholder="HH:MM"
          value={this.getSelectedHour()}
          onChange={e => {
            var moment = this.setOnChangeHour(e);
            handleChange(moment);
            if (moment > maxTime) {
              handleChangeError();
            }
          }}
          mask={[/\d/, /\d/, ":", /\d/, /\d/]}
          keyboardIcon={<AlarmIcon>event</AlarmIcon>}
          label="¿A qué hora?"
          className={classes.textField}
          helperText="Indicá la hora aproximada"
          maxDate={maxTime.toDate()}
          maxDateMessage={"No superar el horario actual."}
          disableOpenOnEnter
        />

**Comment by dmtrKovalenko** [comment]
For me it works as expected. Make sure that its working only in keboard mode
![image](https://user-images.githubusercontent.com/16926049/50386325-0573c600-06ed-11e9-9a51-edfae616b48c.png)
