### ISSUE TITLE
Is there a way to show 'Cancel' and 'OK' buttons on the InlineDatePicker?

### ISSUE THREAD

**Issue by franciscoduluc** [dmtrKovalenko/material-ui-pickers#816]
**Is your feature request related to a problem? Please describe.**
Yes, I need to be able to show Cancel & OK buttons on the InlineDatePicker.

**Describe the solution you'd like**
I see that the Cancel & OK buttons were implemented in DatePickerModal with DialogActions component.

For the InlineDatePicker Calendar, I see it is wrapped in a PopOver in the InlineWrapper component. Can we add the Cancel & OK buttons somewhere here? Thanks!

**Describe alternatives you've considered**
Has anyone else thought of this?

**Additional context**
Great job guys, these pickers are awesome!

**Comment by dmtrKovalenko** [comment]
No, and we will not integrate it. Shortly it is not material design way
