### ISSUE TITLE
Warning: Material-UI: you have provided a `inputComponent` to the input component that does not correctly handle the `inputRef` property

### ISSUE THREAD

**Issue by chattling** [dmtrKovalenko/material-ui-pickers#817]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 2.0.4    |
| material-ui         | 3.7.1   |
| React               | 16.7.1  |
| Browser             | Chrome  |
| Peer library        | date-fns 2.0.0-alpha.26 | 

## Steps to reproduce
```javascript
import DateFnsUtils from '@date-io/date-fns'
import { MuiPickersUtilsProvider } from 'material-ui-pickers'
import { InlineDatePicker } from 'material-ui-pickers'
import EventIcon from '@material-ui/icons/Event'
import KeyboardArrowLeftIcon from '@material-ui/icons/KeyboardArrowLeft'
import KeyboardArrowRightIcon from '@material-ui/icons/KeyboardArrowRight'

    <MuiPickersUtilsProvider utils={DateFnsUtils}>
          <InlineDatePicker
            required
            keyboard
            margin="normal"
            id="deploymentDate"
            label="Deployment Date"
            value={deploymentDate}
            onChange={this.handleDeploymentDateChange}
            keyboardIcon={<EventIcon />}
            leftArrowIcon={<KeyboardArrowLeftIcon />}
            rightArrowIcon={<KeyboardArrowRightIcon />}
            fullWidth
            format="MM/dd/yyyy"
            mask={[/\d/, /\d/, '/', /\d/, /\d/, '/', /\d/, /\d/, /\d/, /\d/]}
          />
        </MuiPickersUtilsProvider>
```

this is just a part of bigger component. If I remove the JSX part above from render function no warning comes in console, so it produced by this part only. Please help.

## Expected behavior
Renders without warnings

## Actual behavior
Renders with following warning in browser console:

Warning: Material-UI: you have provided a `inputComponent` to the input component
that does not correctly handle the `inputRef` property.
Make sure the `inputRef` property is called with a HTMLInputElement.

**Comment by dmtrKovalenko** [comment]
It will be fixed in the nearest realease

**Comment by jmtoung** [comment]
Also seeing this issue. Look forward to it being fixed. Thanks

**Comment by iamvane** [comment]
Im looking forward to this being fixed as well. ⭐️ Thanks!

**Comment by chattling** [comment]
Confirming issue is resolved with version 2.0.5.

**Comment by tschirkow** [comment]
same behavior
"@material-ui/core": "^3.9.2",
    "material-ui-pickers": "^2.2.4",
    "react": "^16.4.1",

**Comment by SuEric** [comment]
same behavior
"@date-io/date-fns": "^1.3.13",
"@material-ui/core": "^4.8.3",
"@material-ui/pickers": "^3.2.10",
"react": "^16.8.6",
