### ISSUE TITLE
v2.0.5 Typescript does not build.

### ISSUE THREAD

**Issue by ideoclickVanessa** [dmtrKovalenko/material-ui-pickers#822]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  v2.0.5       |
| material-ui         |   v3.7.1      |
| React               |    v16.7.0     |
| Browser             |         |
| Peer library        |  luxon v1.8.3       | 

## Steps to reproduce
1. Updated material-ui-pickers from 2.0.4 to 2.05
2. Ran npm start

## Expected behavior
Project to build without me needing to install types for a library used solely within the `material-ui-pickers` project

## Actual behavior
Compile error:
```
Failed to compile.

C:/Repos/MyProject/node_modules/material-ui-pickers/_shared/DateTextField.d.ts
Type error: Could not find a declaration file for module 'react-text-mask'. 'C:/Repos/MyProject/node_modules/react-text-mask/dist/reactTextMask.js' implicitly has an 'any' type.
  Try `npm install @types/react-text-mask` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-text-mask';`  TS7016

    1 | import { BaseTextFieldProps, TextFieldProps } from '@material-ui/core/TextField';
    2 | import * as React from 'react';
  > 3 | import { MaskedInputProps } from 'react-text-mask';
      |                                  ^
    4 | import { DateType } from '../constants/prop-types';
    5 | import { MaterialUiPickersDate } from '../typings/date';
    6 | import { ExtendMui } from '../typings/extendMui';

```
While installing the type library resolved the build issue, I should not need to do so when I am not directly using the `react-text-mask` package in my project. :(

**Comment by wichert** [comment]
After installing `@types/react-text-mask` another TS error also pops up:

```
Type error: Generic type 'SyntheticEvent<T>' requires between 0 and 1 type arguments.  TS2707

     99 |     handleBlur: (e: React.ChangeEvent<HTMLInputElement>) => void;
    100 |     handleChange: (e: React.ChangeEvent<HTMLInputElement>) => void;
  > 101 |     handleFocus: (e: React.SyntheticEvent<Element, Event>) => void;
```

**Comment by wichert** [comment]
Interestingly the SyntheticEvent error goes away after upgrading from React 16.6 to 16.7.

**Comment by dmtrKovalenko** [comment]
@wichert yep, the `SyntheticEvent` type was changed in @types/react^16.7
