### ISSUE TITLE
Opening a DateTimePicker with invalid default value throws an error

### ISSUE THREAD

**Issue by wichert** [dmtrKovalenko/material-ui-pickers#824]
This uses the same example as #823, but shows a different issue. 

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     2.0.5    |
| material-ui         |    3.7.1     |
| React               |    16.4.0     |
| Browser             |     all    |
| Peer library        |  Luxon 1.8.3        |

## Steps to reproduce
1. Click on the date-time picker

## Expected behavior
I expect the modal to open up with the current input value selected, so I can change it to something else.

## Actual behavior
An uncaught exception is thrown:
```
TypeError
value.set is not a function. (In 'value.set({ hour: count })', 'value.set' is undefined)
```

## Live example
https://codesandbox.io/s/6wxqo5mxnz

**Comment by dmtrKovalenko** [comment]
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/16926049/50510257-acf84c00-0a91-11e9-9737-c40c2996dd28.png">

**Comment by wichert** [comment]
Can you try https://codesandbox.io/s/k0xymx0wx5 as sandbox? That gives me:

<img width="835" alt="screenshot 2018-12-28 at 13 18 07" src="https://user-images.githubusercontent.com/199657/50515123-12086d80-0aa3-11e9-912d-f32e637d36e3.png">

**Comment by dmtrKovalenko** [comment]
@wichert it doesnt throw an exception for me, but selecting incorrect date as default

**Comment by dmtrKovalenko** [comment]
Another issue I found. That it should not disable today with `disablePast` option

**Comment by wichert** [comment]
@dmtrKovalenko Are you clicking the datetime picker? That gives me an exception on multiple browsers.

**Comment by dmtrKovalenko** [comment]
@wichert that not an issue. I figured out that you have set the date manually to the December 24th. So it is in the past now :)
