### ISSUE TITLE
Receiving wrong argument when using  moment as date provider

### ISSUE THREAD

**Issue by rafael-sousa** [dmtrKovalenko/material-ui-pickers#830]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  2.0.5       |
| material-ui         |    3.8.1     |
| React               |     16.7.0    |
| Browser             |  Chrome 71.0.3578.98      |
| Peer library        |    moment 2.20.1     | 

## Steps to reproduce
1. Setup moment as date provider
2. Use the `DatePicker` component

## Expected behavior
The `onChange` function should receive a date object as an argument, according to the signature `(date: any) => void` described in the docs.

## Actual behavior
Instead, it receives a moment object as argument. Messing up with the format and mask params. I've tried switching from `moment` to `date-fns` and it worked as expected.

## Live example
https://codesandbox.io/s/7kmz41p84x

**Comment by dmtrKovalenko** [comment]
@rafael-sousa that is expected. You are using moment so you are receiving moment object in onChange. In the signature type is actually `any` cause it can return moment, native date or luxon's datetime.

**Comment by rafael-sousa** [comment]
Is there a way to apply the `mask` and `format` using the props given the `DatePicker` or I'll have to do it manually?

**Comment by dmtrKovalenko** [comment]
You must pass custom mask every time. And for format you can override it globally using utils https://material-ui-pickers.firebaseapp.com/guides/formats
