### ISSUE TITLE
DateTime shows different dates and times between browsers Chrome and Safari 

### ISSUE THREAD

**Issue by moorthi07** [dmtrKovalenko/material-ui-pickers#835]
DateTime shows different dates and times between browsers Chrome and Safari 

Chrome: 11/17/2018 03:17 AM

 results in 

Safari: 11/16/2018 07:17

**Comment by dmtrKovalenko** [comment]
Please provide an [example](https://codesandbox.io/) to reproduce it. Also provide browser version and OS

**Comment by zaguiini** [comment]
+1
