### ISSUE TITLE
RTL date picker month arrows are upside down..

### ISSUE THREAD

**Issue by omerman** [dmtrKovalenko/material-ui-pickers#839]
When opening the date picker in RTL, the month selecting arrows are messed up pointing to the opposite directions

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |         |
| material-ui         | 1.5.0 |
| React               | 16.4.2 |
| Browser             |   Chrome      |
| Peer library        |    date-fns 2.0.0-alpha.16     | 

## Steps to reproduce
1. Open date picker when theme direction is rtl.
2. See wrong month arrows.

## Expected behavior
 should render: < {days of the month..} >

## Actual behavior
renders as such: > {days of the month..} <

## Screenshot
https://paste.pics/ea4b8f40c10a286a260c2bec6d28592a

**Comment by dmtrKovalenko** [comment]
Seems, like you are doing something wrong. Have you read the [following](https://material-ui.com/guides/right-to-left/#3-jss-rtl) guideline? 

![image](https://user-images.githubusercontent.com/16926049/50784375-24aa5000-12b6-11e9-9f78-a110af661d7f.png)

**Comment by omerman** [comment]
Hi thanks for your response.

I did follow the guide you mentioned,
and now I also found what seems to be the problem..
I am having a specific rtl view, therefore the `dir` property is not set on the `<body>` tag, so the popover itself is not contained by a tag with direction property set to rtl..

Is it possible for the popover to open using a direction property that will equal the MuiThemeProvider's `theme.direction`?

**Comment by dmtrKovalenko** [comment]
I am not quite get in your question

**Comment by omerman** [comment]
First of all I found a solution to my problem..
Im using the `PopoverProps` property to override the `dir` of the popover..
Im doing it because I have the root that is ltr, and a nested view that is rtl ( I know that its kind of an edge case..)
So since the popover is opening under the body, I inject it with `dir` property that matches the theme provider.

attached my solution in cased any one else has a similar case.
```
import React from 'react';
import { InlineDatePicker } from 'material-ui-pickers/DatePicker';
import { withTheme, WithTheme } from '@material-ui/core';

export interface DatePickerProps extends WithTheme {
  label?: string,
  value: number,
  onChange: (d: number) => void,
  format?: string,
}

export const DatePicker = withTheme()(({
  label,
  value,
  onChange,
  format = 'dd/MM/yyyy',
  theme,
}: DatePickerProps) => (
  <InlineDatePicker
    PopoverProps={{
      dir: theme.direction,
    }}
    format={format}
    value={value || null}
    onChange={(d: Date) => onChange(d.getTime())}
    label={label}
    keyboard
    mask={[/\d/, /\d/, '/', /\d/, /\d/, '/', /\d/, /\d/, /\d/, /\d/]}
  />
));
```
