### ISSUE TITLE
DateTimePicker tab icons are not vertically centred when using useNextVariants typography in theme

### ISSUE THREAD

**Issue by mymattcarroll** [dmtrKovalenko/material-ui-pickers#841]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    2.0.5     |
| material-ui         |  3.8.2       |
| React               |     16.7.0    |
| Browser             |       Chrome  |
| Peer library        |      moment   | 

## Steps to reproduce
1. Create Material UI theme with `typography.useNextVariants` set to `true` 
2. Use DateTimePicker

## Expected behavior

Tabs icons to displayed vertically centred

## Actual behavior

![image](https://user-images.githubusercontent.com/16235788/50867622-e1f48f00-13ff-11e9-8031-d964b6058529.png)

## Live example

https://codesandbox.io/s/n054206o9j

**Comment by dmtrKovalenko** [comment]
Fixed in 2.1.0
