### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isValid' of null

### ISSUE THREAD

**Issue by PaulBrandt** [dmtrKovalenko/material-ui-pickers#848]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    2.0.5     |
| material-ui         |    3.8.3     |
| React               |    16.7.0    |
| Browser             |    Chrome 71.0.3578.98     |
| Peer library        |     "moment": "^2.23.0", "@date-io/moment": "^1.0.0",   | 

I just did a big update to my tech-stack and updated react, material-ui and many other packages.
After getting everything back to work I still have a problem with material-ui-pickers.
Once any of my DateTimePicker is about to be rendered the application crashes logging:
```
Uncaught TypeError: Cannot read property 'isValid' of null
    at MomentUtils.isValid (index.esm.js?0e83:27)
...
The above error occurred in the <DateTextField> component:
    in DateTextField (created by Context.Consumer)
    in WithUtils(DateTextField) (created by ModalWrapper)
    in ModalWrapper (created by BasePicker)
```

As it says isValid is read on null and MomentUtils.isValid I suppose there ist something wrong with my MomentUtils.
This is what is imported right in my index.js and how it is used.

```
import { MuiPickersUtilsProvider } from 'material-ui-pickers';
import moment from 'moment';
import 'moment/locale/de';
import MomentUtils from '@date-io/moment';
[...]
moment.locale('de');
[...]
render(
    <Provider store={store}>
        <JssProvider jss={jss} generateClassName={generateClassName}>
            <MuiThemeProvider theme={theme}>
                <MuiPickersUtilsProvider utils={MomentUtils} locale="de" moment={moment}>
                    <React.Fragment>
                        <CssBaseline />
                        <App />
                    </React.Fragment>
                </MuiPickersUtilsProvider>
            </MuiThemeProvider>
        </JssProvider>
    </Provider>,
    document.getElementById('app'),
);
```

Then far inside my App, a DateTimePicker is rendered like this.
```
<DateTimePicker
    value={filter.startvalue}
    onChange={date => this.handleStartDateChange(filter.id, date)}
    helperText={'sometext'}
    clearable
    placeholder={'sometext'}
    ampm={false}
    maxDate={filter.endvalue || "2099-12-31T23:59:59.999Z"}
    id={filter.id}
/>
```

Is there anything obvious I am doing wrong or is there a version problem?
Thank you very much!

**Comment by dmtrKovalenko** [comment]
Please update both material ui pickers and date io

**Comment by PaulBrandt** [comment]
I do use the latest material-ui-pickers (2.0.5) I did use @date-io/moment 1.0.0 and an hour ago it was updated to 1.0.1. 1.0.1 actually fixed this. So I was just just very unlucky with my moment of updating everything?

**Comment by dmtrKovalenko** [comment]
The latest version of material-ui-pickers now is 2.1.0. And yes - wery unlacky hour to update :D

**Comment by PaulBrandt** [comment]
Oh wow. I still had an tab of npm open showing "2.0.5" as newest. Thanks for the fast help.

**Comment by PaulBrandt** [comment]
Also 2.0.5 with 1.0.1 does render the input field, but the calender fails to open. Now with 2.1.0 and 1.0.1 everything works nicely again. Thank you for this great project and the help.
