### ISSUE TITLE
2.1.1 + 1.0.1 crash when using minDate on DateTimePicker

### ISSUE THREAD

**Issue by PaulBrandt** [dmtrKovalenko/material-ui-pickers#850]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    2.1.1     |
| material-ui         |    3.8.3     |
| React               |    16.7.0    |
| Browser             |    Chrome 71.0.3578.98     |
| Peer library        |     "moment": "^2.23.0", "@date-io/moment": "^1.0.1",   | 

```
<DateTimePicker
    value={filter.startvalue}
    onChange={date => this.handleStartDateChange(filter.id, date)}
    helperText={''}
    clearable
    placeholder={''}
    ampm={false}
    maxDate={filter.endvalue || "2099-12-31T23:59:59.999Z"}
    id={filter.id}
/>
<DateTimePicker
    value={filter.endvalue}
    onChange={date => this.handleEndDateChange(filter.id, date)}
    helperText={''}
    clearable
    style={{ marginLeft: '16px' }}
    placeholder={''}
    ampm={false}
    minDate={filter.startvalue}
    maxDate={"2099-12-31T23:59:59.999Z"}
    id={filter.id}
/>
```

First one opens fine, second cant be opened and crashes saying:
```
Uncaught TypeError: Cannot read property 'clone' of null
    at MomentUtils.startOfMonth (webpack-internal:///./node_modules/@date-io/moment/build/index.esm.js:104)
    at Calendar._this.shouldDisablePrevMonth (webpack-internal:///./node_modules/material-ui-pickers/dist/material-ui-pickers.esm.js:1456)
    at Calendar.render (webpack-internal:///./node_modules/material-ui-pickers/dist/material-ui-pickers.esm.js:1615)
    at finishClassComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14534)
    at updateClassComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14489)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15335)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:18150)
    at workLoop (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:18190)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:199)
webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16013 The above error occurred in the <Calendar> component:
    in Calendar (created by Context.Consumer)
    in WithUtils(Calendar) (created by WithStyles(WithUtils(Calendar)))
```

**Comment by PaulBrandt** [comment]
Me again, I'm sorry I missed the whole techstack. I'm using "@date-io/moment": "^1.0.1" and all the same stuff as in earlier issue.

**Comment by dmtrKovalenko** [comment]
@PaulBrandt do not pass `null` to the `minDate` it is not designed to support null for that kind of values. Pass `undefined` to make default props work (1900-01-01 & 2100-01-01)

**Comment by PaulBrandt** [comment]
Correct. Working now as expected. Thank you.

**Comment by AlbertoTonegari** [comment]
> @PaulBrandt do not pass `null` to the `minDate` it is not designed to support null for that kind of values. Pass `undefined` to make default props work (1900-01-01 & 2100-01-01)

Guys, THANK YOU SO MUCH! I was pulling my hair trying to figure out how to fix this. 
Thank you again @dmtrKovalenko for the solution and thank you @PaulBrandt for opening this issue!

**Comment by oliviertassinari** [comment]
@AlbertoTonegari Which version of the pickers are you using?
It sounds like we could have added a custom propType to warn against this case or have null treated as undefined, maybe the latter?

**Comment by oliviertassinari** [comment]
I couldn't reproduce on https://codesandbox.io/s/flamboyant-allen-213pl?file=/src/App.jsx:0-678. But it's strange, I couldn't unlock selecting a date < 1900 either.

**Comment by AlbertoTonegari** [comment]
Hello @oliviertassinari I am using version `@3.2.10` of the material-ui pickers. Here is a [sandbox](https://codesandbox.io/s/agitated-star-dzdpz?file=/src/App.jsx) with the picker that I use in the application and the exact package versions and it crashes(when you open the calendar) if `null` is provided to either `minDate` or `maxDate`. To explain the problem, I pass `mindDate` and `maxDate` as props to the `KeyboardDatePicker`, but I have defaultProps in case `minDate` or `maxDate` are not passed. The defaultProps set `minDate` and `maxDate` = `null` and that crashes the application. 

Based on your example 👆, it seems that in version 4.x it works with `null` also. But that is still in alpha.
