### ISSUE TITLE
Rigidly fixed version - "react-text-mask": "=5.4.1"

### ISSUE THREAD

**Issue by in19farkt** [dmtrKovalenko/material-ui-pickers#854]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 2.1.1        |
| react-text-mask         | 5.4.3        |

## Steps to reproduce
1. npm i react-text-mask
2. npm i material-ui-pickers

## Expected behavior
One version of react-text-mask in my node_modules

## Actual behavior
There are 2 versions of the react-text-mask library in my project at the same time. The first step installs the 5.4.3 version of the react-text-mask. The second step additionally installs the 5.4.1 version of the react-text-mask.

**Comment by dmtrKovalenko** [comment]
Hmm, there was an error in one of the react-text-mask. So we needed to fix it. 
I will check and if everything works we will update and use `^=`

**Comment by ahce** [comment]
@dmtrKovalenko the error is only in v5.4.2.
v5.4.3 was fixed with this [pr](https://github.com/text-mask/text-mask/pull/807/files)

**Comment by ahce** [comment]
@dmtrKovalenko the error is only in v5.4.2
v5.4.3 was fixed with this [pr](https://github.com/text-mask/text-mask/pull/807)
