### ISSUE TITLE
Warning: Material-UI: you have provided a `inputComponent` to the input component that does not correctly handle the `inputRef` property

### ISSUE THREAD

**Issue by elehaf16** [dmtrKovalenko/material-ui-pickers#857]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    2.1.1     |
| material-ui         |    3.8.3     |
| React               |    16.7.0     |
| Browser             |   Chrome      |
| Peer library        | moment        | 

## Steps to reproduce
<DatePicker
          keyboard
          label={label}
          value={input.value}
          onChange={this.handleChange}
          format={format}
          className={classes.formControl}
          InputLabelProps={{shrink: true}}
          placeholder={placeholder}
          allowKeyboardControl
          mask={value => (value ? [/\d/, /\d/, '-', /\d/, /\d/, '-', /\d/, /\d/, /\d/, /\d/] : [])}
          showTodayButton
          todayLabel="HOY"
          okLabel="OK"
          autoOk
          onFocus={this.selectText}
          onOpen={this.handleOpen}
          error={Boolean(error || localError)}
          onError={this.handleError}
          helperText={localError ? localError : error}
          disableOpenOnEnter
        />

it happens when using DatePicker Component, it does't matter which options are used ...

## Actual behavior

Warning: Material-UI: you have provided a inputComponent to the input component
that does not correctly handle the inputRef property.
Make sure the inputRef property is called with a HTMLInputElement.

**Comment by SergeyWebDeveloper** [comment]
@elehaf16, I had it when I used in the project react-text-mask and in the component was
```
<MaskedInput
       ref = {inputRef}
       mask = {mask}
       placeholderChar = "_"
       guide = {true}
       keepCharPositions = {true}
       showMask = {true}
       {... other}
     />
```
Removing ```ref = {inputRef}``` fixed the problem.

**Comment by elehaf16** [comment]
Thanks, but it's not my case I don't use the option ref. Perhaps <DatePicker> use it internally...

**Comment by charlax** [comment]
Same here.

**Comment by dmtrKovalenko** [comment]
Please provide codesandbox with an error. Without it we cannot help you cause this warning is not reproducible for me

**Comment by elehaf16** [comment]
I don't know what I've done, but now I'm not able to reproduce the warning again, I've made same package updates and perhaps that the reason.

Sorry for the inconvenience... and thanks!
