### ISSUE TITLE
Mobile Device > iPad > "Look Up" is displayed instead of displaying Calendar Modal

### ISSUE THREAD

**Issue by zulucoda** [dmtrKovalenko/material-ui-pickers#860]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  2.0.2 & 2.1.1  |
| material-ui         | 3.3.2 |
| React               | 16.4.0 |
| Browser             | Safari |
| Peer library        | 1.80 | 

## Steps to reproduce
1. Click on the date field
2. Click on "cancel" the on modal
3. Now, click on the date field, "Look up" is displayed (see screen-print below)

## Expected behaviour
It should display Date modal again

## Actual behaviour
It does not display date modal, but displays "Look up", see screen-print below for more info.

## Live example
Test on https://codesandbox.io/s/q9l2j10wr4?from-embed

## Screenprints
![image](https://user-images.githubusercontent.com/994819/51165721-a1db5380-18ba-11e9-8a65-87ff279bd77b.png)

![image](https://user-images.githubusercontent.com/994819/51165732-aa338e80-18ba-11e9-81c3-302c426a094e.png)

**Comment by dmtrKovalenko** [comment]
The issue - the focus stays on the input after closing modal. It is required for accessibility. When you are clicking next time to the readonly textfield IOS opens text-edit menu. 
That is expected

**Comment by zulucoda** [comment]
@dmtrKovalenko thank you for kindly getting back to me. 

Yes, I agree with you the focus stays on the input, the same is true on the desktop. However, on the desktop when you click on the date field again, it still displays the modal, whereas on the iPad it does not show the modal, but instead it displays "Look Up" tooltip on the date field. Should it not behave the same as on the desktop?

**Comment by dmtrKovalenko** [comment]
@zulucoda here IOS overrides the click event. You can test it. Simply click 2 times on IOS input. You will see that event fires only 1 time
