### ISSUE TITLE
RFC: Material-ui-pickers v3 breaking changes

### ISSUE THREAD

**Issue by dmtrKovalenko** [dmtrKovalenko/material-ui-pickers#862]
TBD: Breaking changes plan for material-ui-pickers v3

* 🎉 Hooks powered api 
* Replace react-text-mask with rifm #634 
* Split `keyboard` components to separate for 
  1). Enabling treeshaking of masked input
  2). Changing `onChange` signature for better form integration experience
* Get rid of path imports `material-ui-pickers/DatePicker`. This will reduce imports mess with React Context 
* Remove export of Consumer from entry point (now deprecated) 
* Provide internal hook for accessing utils by endpoint user.
* Use hook for managing state of `BasePicker` and get rid of `<BasePicker` hoc
* Remove `openToYearSelection` prop in favor of `openTo` 
* Use `@material-ui/styles` #918 
* Add concrete type of MaterialUiPickersDate. Or provide a way to change it with module augmentation.

**Comment by Akirtovskis** [comment]
Are there any changes related to datePicker i18n coming out with the new v?

**Comment by dmtrKovalenko** [comment]
@Akirtovskis I am not fully understand what do you mean.

**Comment by Akirtovskis** [comment]
@dmtrKovalenko  I have been struggling for past couple of days to implement different locales for DatePicker, but so far no luck with any of the workarounds I found here or in other sources.  My goal is to add such functionality that whenever I toggle between languages DatePicker language also changes.  Also appreciate the fast response! 🥇 👍

**Comment by dmtrKovalenko** [comment]
https://material-ui-pickers.firebaseapp.com/localization/date-fns
Something like that? If you will pass the new `locale` to the provider any DatePicker in the component tree will rerender with proper locale

**Comment by Akirtovskis** [comment]
Thanks for the guidance, that will probably solve the issue. 🙏  However my problem was probably related to using some older MUI and React versions, which will take some time to upgrade. As I said previously, appreciate the fast answers!

**Comment by RedHatter** [comment]
v3 can't run without being wrapped in a `ThemeProvider`.

    // Works fine
    <ThemeProvider theme={createMuiTheme({})}>
      <MuiPickersUtilsProvider utils={DateFnsUtils}>
        <DatePicker />
      </MuiPickersUtilsProvider>
    </ThemeProvider>

    // Crashes
    <MuiPickersUtilsProvider utils={DateFnsUtils}>
      <DatePicker />
    </MuiPickersUtilsProvider>

Should use the default theme if one isn't provided.

**Comment by dmtrKovalenko** [comment]
@RedHatter I am not really sure, but that seems to be material ui issue. We just using their new @material-ui/styles package

**Comment by merceyz** [comment]
@dmtrKovalenko https://github.com/mui-org/material-ui/issues/15278#issuecomment-481407180

**Comment by dmtrKovalenko** [comment]
ALL CHANGES ARE DONE 🔥 🔥 🔥 🔥

**Comment by mtrenker** [comment]
hi, just a quick question, how is "changing onChange signature" improving anything? instead of relying on a standard that everybody agreed on for some decade now you break this AND compatibility with material-ui form elements.
