### ISSUE TITLE
Bug format date

### ISSUE THREAD

**Issue by SergeyWebDeveloper** [dmtrKovalenko/material-ui-pickers#863]
If you set the format for the component, it is possible that the date / time is not displayed correctly.
Most often this happens when the month changes

![photo_2019-01-15_16-23-54](https://user-images.githubusercontent.com/12486958/51183541-9439c400-18e2-11e9-8554-08d12a6f2da7.jpg)

Example - https://codesandbox.io/s/rj9j85324

**Comment by dmtrKovalenko** [comment]
Please, investigate first - then create issues. You must update format strings after date-ins update
