### ISSUE TITLE
How to show Year after picking date

### ISSUE THREAD

**Issue by yuwiggin** [dmtrKovalenko/material-ui-pickers#869]
I tried [the demo](https://material-ui-pickers.firebaseapp.com/usage) and found that only month and day are showed after picking date.
I want to show a full date format, i.e. "January 20th, 2001".  I tried an attribution `showYearSelection="true"`, but didn't work. 

```
                <DatePicker
                    value={value}
                    showYearSelection="true"
                    onChange={this.handleDateChange}
                    label="Your Birth Date"
                />
```
Any suggestion?

**Comment by dmtrKovalenko** [comment]
You can use ‘openToYearSelection’ if you need open datepicker on the year view. It is not possible to open year after the date

**Comment by yuwiggin** [comment]
I want to show the result in the TextField with a full format of date, i.e. "January 20th, 2001". How to do?

**Comment by dmtrKovalenko** [comment]
Than use custom format string via `format` prop
