### ISSUE TITLE
onMonthChange public API

### ISSUE THREAD

**Issue by bilgin1500** [dmtrKovalenko/material-ui-pickers#875]
**Is your feature request related to a problem? Please describe.**
I'm experiencing the same problem mentioned [here](https://github.com/mui-org/material-ui/issues/6886). In my current project we need to make an API call on every month change so that we can fetch the disabled dates for the current month. It would be too expensive to fetch the dates beforehand. I scanned the open issues but couldn't find any related feature request and this might not even be considered in v3 as far as I can [see](https://github.com/dmtrKovalenko/material-ui-pickers/issues/862).

**Describe the solution you'd like**
I scanned the codebase and a similar API is already exposed [here](https://github.com/dmtrKovalenko/material-ui-pickers/blob/659f981920f1ebc3550277fecf2c92c3d9a725fd/lib/src/wrappers/InlineWrapper.tsx#L61) for `onOpen`. I believe we can implement the same approach with `onMonthChange` and maybe even with onYearChange. (I didn't analyze the latter one yet but I believe it won't be tricky.) 

I need your feedback and suggestions before diving more into this. I'll be happy to contribute to add this feature!

**Comment by dmtrKovalenko** [comment]
I think here you can use default `onChange` and for `onMonthChange` for example do 
```js
onChange = (newValue) => {
  if (newValue.diff(currentValue, 'month') > 1) {
     // month changed
  }
}
```

From my point of view getting callback when month changed is useless for 90% devs that using material-ui-pickers but will brings more complexity to the API

**Comment by bilgin1500** [comment]
What I meant was a callback after the month has changed via the calendar's prev or next month buttons. I believe `onChange` is too late for this kind of action. Consider the scenario where I want to pull new invalid dates (of the new selected month) from server on every `prev month` or `next month` button click and rerender the new month's view according the results to disable some of the dates. How can I manage this via `onChange`?

And regarding the use cases and dev complexity I can give you examples from other libraries which already exposes such an API:
- In [React Dates](https://github.com/airbnb/react-dates) it is called `onPrevMonthClick ` and `onNextMonthClick`
- In react-datepicker it must be on its [way](https://github.com/Hacker0x01/react-datepicker/pull/626)
- In Pikaday `onDraw` can be used for similar actions.
- In jQuery datepicker it's called [onChangeMonthYear](http://api.jqueryui.com/datepicker/#option-onChangeMonthYear)

**Comment by dmtrKovalenko** [comment]
@bilgin1500 I am not understand why do you need for end-user. Please provide business scenario

**Comment by bilgin1500** [comment]
In our product we have an API endpoint which returns invalid dates for *every month*. I want to pull these invalid dates and render the picker's calendar according to these dates. The user *should only be able to select the valid dates* for its locale as this data may change from region to region. 

- When the user opens the calendar a spinner shows up and the invalid-dates-API is called. 
- The API returns the invalid dates for this current selected month.
- The calendar rerenders and using `shouldDisableDate` updates the current month accordingly.
- Now the user can only select the permitted dates.
- When the user clicks prev/next month or changes the year the process repeats...

**Comment by dmtrKovalenko** [comment]
@bilgin1500 I see...
I will think about it
