### ISSUE TITLE
Keyboard Icon doesnt render on TimeField but on DateField

### ISSUE THREAD

**Issue by digitalkaoz** [dmtrKovalenko/material-ui-pickers#883]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    2.1.2     |
| material-ui         |     3.9.0    |
| React               |    1.16     |
| Browser             |   every      |
| Peer library        | moment        |

## Steps to reproduce
1. create a TimeField with keyboard input
2.
3.

## Expected behavior
the icon button renders

## Actual behavior
it doesnt render the icon as svg only as text

## Live example
https://time-calc.digitalkaoz.net

**Comment by dmtrKovalenko** [comment]
https://codesandbox.io/s/q9l2j10wr4?from-embed

**Comment by dmtrKovalenko** [comment]
Seemed you are still using old version of material-ui-pickers on the env you provided

**Comment by digitalkaoz** [comment]
it seems we now need an react element as `keyboardIcon` and not a simple `string` like `timer`

**Comment by dmtrKovalenko** [comment]
Yep - we do not support icon font as from 2.0.0

**Comment by Amareis** [comment]
Can you renders `access_time` icon on TimePicker with `keyboard` by default? It seems very straightforward and easy to implement.
