### ISSUE TITLE
Localization also for "OK" and "CANCEL" buttons

### ISSUE THREAD

**Issue by korshavn** [dmtrKovalenko/material-ui-pickers#884]
Hi.
It would be really nice if also the buttons OK and Cancel were possible to localize.

![image](https://user-images.githubusercontent.com/462345/51801283-ead8c380-223b-11e9-9fc1-c946393e6ce9.png)

As you can see, these buttons are always displayed in English.

**Comment by dmtrKovalenko** [comment]
You must localize them by yourself
There is props like okLabel and cancelLabel for this purpose

**Comment by korshavn** [comment]
Indeed you are right. My apologies.
Great library you have made! Thanks a lot.
