### ISSUE TITLE
InlineDatePicker isn't clearable via keyboard

### ISSUE THREAD

**Issue by afrankel-sfdo** [dmtrKovalenko/material-ui-pickers#886]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   2.1.2      |
| material-ui         |   3.2.0      |
| React               |    16.5.2     |
| Browser             |    Chrome     |
| Peer library        |    moment     | 

## Steps to reproduce
1. Clear out the input field value
2. See the console log for the onChange event only firing for the regular DatePicker and not the InlinePicker

## Expected behavior
- Clearing out the input for an inline date picker should fire onChange event with null value

## Actual behavior
- Doesn't fire event.
- Works fine with regular DatePicker

## Live example
(side note: the example sandbox link has very outdated dependancies)

https://codesandbox.io/s/50pn28k03k

![clear-calendar](https://user-images.githubusercontent.com/31106469/51848875-b3b9ef00-22db-11e9-8633-3dce76e71784.gif)

**Comment by dmtrKovalenko** [comment]
Nice catch! Will be fixed asap

**Comment by afrankel-sfdo** [comment]
> Nice catch! Will be fixed asap

Many thanks!!

**Comment by Saranchenkov** [comment]
Tech | Version
-- | --
material-ui-pickers | 2.1.1
material-ui | 3.7.0
React | 16.7.0
Browser | Chrome
Peer library | date-fns

+1

**Comment by kvss1992** [comment]
Did anyone was able to fix it?

**Comment by visarts** [comment]
I wanted to ask a question here without creating a whole new bug, since it's related to the inline date picker -- is there a reason the dialogActions are disabled in the inline version? So if I want the ability to set 'today' I have to use the regular modal version?

**Comment by kvss1992** [comment]
Thanks @dmtrKovalenko  for the quick work around.
You can close this issue

**Comment by afrankel-sfdo** [comment]
> Thanks @dmtrKovalenko for the quick work around.
> You can close this issue

agreed, thanks!
