### ISSUE TITLE
Support for disabled prop

### ISSUE THREAD

**Issue by mfolnovic** [dmtrKovalenko/material-ui-pickers#89]
At the moment, it seems that `<DateTimePicker>` doesn't support prop `disabled`, like other material-ui inputs: https://material-ui-next.com/demos/text-fields/#inputs.

**Comment by dmtrKovalenko** [comment]
:(

**Comment by bernalrs** [comment]
@mfolnovic  I tried using the disabled property and the DateTextField associated to the DateTimePicker is indeed disabled with the appropriate grey-out styles applied. It appears not all props have been included in the docs. 

` <DateTimepicker   label=(ReasonReact.stringToElement("Report Date"))
   value=state.report
   label="Auto"
   onChange=(reduce((value) => HandleChangeReportDate(value)))
   style=inputStyle
   disabled=state.autoReport
/>
`
(by the way the snippet above is in ReasonML JSX )

**Comment by dmtrKovalenko** [comment]
@bernalrs @mfolnovic 
-_- I'm sorry its my mistake - **All** text field props can be passed to the root of the any picker and it would works.
:D I'm sorry I have not looked deeply to the question, just have test that and its work like a charm
