### ISSUE TITLE
The field's label does not shrink on focus with material ui 3.9.1

### ISSUE THREAD

**Issue by francoiscabrol** [dmtrKovalenko/material-ui-pickers#890]
## Environment
"material-ui-pickers": "^2.1.2",
"@material-ui/core": "^3.9.1",
"react": "^16.7.0",
Chrome Version 71.0.3578.98 (Build officiel) (64 bits)

## Steps to reproduce
1. Create an outlined DatePicker field like

```
const value = defaultValue ? moment.utc(Number(defaultValue)) : null;
return <DatePicker
    id={id}
    disableOpenOnEnter
    fullWidth
    keyboard
    label={label}
    autoOk
    clearable
    disableFuture
    placeholder="mm/dd/yyyy"
    maxDateMessage="Date must be less than today"
    value={value}
    onChange={(date: Moment) => {
      const newDate = date
        ? date
            .toDate()
            .getTime()
            .toString()
        : null;
      onChange(newDate);
    }}
    format="L"
    mask={val => (val ? [/\d/, /\d/, '/', /\d/, /\d/, '/', /\d/, /\d/, /\d/, /\d/] : [null])}
    variant="outlined"
  />
```
2. Focus on the field

## Expected behavior
The field's label should "shrink"

## Actual behavior
The field's label does not "shrink"

Note that the component was working before the material-ui update 
```
-    "@material-ui/core": "^3.7.1",
+    "@material-ui/core": "^3.9.1",
```

**Comment by dmtrKovalenko** [comment]
https://material-ui.com/demos/text-fields/#limitations
Ok Inthink we need to add shrink true by default. Or no 🤔?

**Comment by francoiscabrol** [comment]
Or we could set the shrink boolean dynamically, I did something similar for my inputs:
```
<TextField
  InputLabelProps={{
    shrink: (!isNil(input.value)) || isFocused,
  }}
{...}
/>
```
I guess the focus' state is accessible from inside the DatePicker component.

**Comment by dmtrKovalenko** [comment]
Closing issue, cause we are not controlling shrink. All shrink state controlling goes down to material ui textfield

**Comment by redgumnfp** [comment]
In case anyone else comes across this whilst debugging... the below may be of use:

```
<KeyboardDatePicker
    {...otherprops}
    InputLabelProps={{
        shrink: value ? true : undefined,
    }}
/>
```

Undefined, not false, to use the inherited focus stuff. 

False would mean you'd need to manage focus state etc...
