### ISSUE TITLE
Runtime error in material-ui-pickers

### ISSUE THREAD

**Issue by vishnu-nt** [dmtrKovalenko/material-ui-pickers#895]
Error thrown in production

reactTextMask.js:1 Uncaught TypeError: Super expression must either be null or a function, not undefined
    at reactTextMask.js:1
    at reactTextMask.js:1
    at Object.<anonymous> (reactTextMask.js:1)
    at t (reactTextMask.js:1)
    at reactTextMask.js:1
    at reactTextMask.js:1
    at Object.<anonymous> (reactTextMask.js:1)
    at n (bootstrap:19)
    at Object.<anonymous> (material-ui-pickers.cjs.js:15)
    at n (bootstrap:19)

found this in material-ui-pickers.js:
var MaskedInput = _interopDefault(require('react-text-mask'));

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |      2.1.2   |
| React               |    16.6.3     |
| Peer library        |   react-text-mask      | 

## Steps to reproduce
1. include a sample DateTimePicker exactly as in example code
2. Take the prod build
3. serve the prod file

## Expected behavior
 Date time picker should render

## Actual behavior
App crashes cause of this error

**Comment by dmtrKovalenko** [comment]
Which version of react-text-mask you r using?

**Comment by vishnu-nt** [comment]
version 5.4.3
