### ISSUE TITLE
Suggestion: Mention in docs about `toShowTabs` flag

### ISSUE THREAD

**Issue by danielverejan** [dmtrKovalenko/material-ui-pickers#898]
**Is your feature request related to a problem? Please describe.**
```javascript
var toShowTabs = Boolean(showTabs && typeof window !== 'undefined' && window.innerHeight > 667);
```
This line of code. 
Working on a 15 inch MacBook with developer tools opened and integrated on bottom results in an `innerHeight` value smaller than `667px`, which means that the tabs won't be visible even if all the configuration and params are set.

**Describe the solution you'd like**
Mention this flag in the documentation so other people won't lose time thinking this is a bug/conflict with other packages that leads to unexpected behaviour.

**Comment by dmtrKovalenko** [comment]
![2019-02-04 14 17 08](https://user-images.githubusercontent.com/16926049/52207934-9eb70000-2887-11e9-996c-0c00e8f68bd4.png)

**Comment by dmtrKovalenko** [comment]
Fixed
