### ISSUE TITLE
[InlineDateTimePicker] Initial state date null dont fire onChange when you select only a day

### ISSUE THREAD

**Issue by Abbo44** [dmtrKovalenko/material-ui-pickers#900]
![fun image](https://media.giphy.com/media/l3q2K5jinAlChoCLS/giphy.gif)
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 2.1.2|
| material-ui         |3.9.0|
| React               |16.6.3|
| Peer library        | date-fns : 1.0.2, moment:  2.19.1| 

## Steps to reproduce

1. Click on the keykoard button
2. Click on a day
3. Click outside the card --> nothing append
4. Re-enter a date until the end --> date is changed
5. Change the day date and click outsite --> date is changed

## Expected behavior
When initial date is null, I expect date change if I select a day and leave . 
It's a regression because it works on material-ui-picker v2.0.4

## Actual behavior
When initial date is null and I select a day and leave, nothing append.

## Live example
https://codesandbox.io/s/p9y2871yq

**Comment by dmtrKovalenko** [comment]
We will proceed with dispatching value onChange if passed `null` and revert #773 changes
