### ISSUE TITLE
TimePicker Warning: React does not recognize the `initialFocusedDate` prop on a DOM element.

### ISSUE THREAD

**Issue by jeroenhoebe** [dmtrKovalenko/material-ui-pickers#907]
initialFocusedDate gives a warning Error if put on a TimePicker. But it does still work.

## Environment
| material-ui-pickers | 2.1.2
| material-ui               | 3.8.2
| React                       | 16.7.0
| Browser                   | chrome 71
| date-fns                  | 2.0.0-alpha.21

## Steps to reproduce

```
<TimePicker
  placeholder="time"
  value={selectedDate}
  onChange={handleDateChange}
  initialFocusedDate={new Date().setMinutes(0)}
 />
```

## Expected behavior
No warning and set the initial time when you open the modal and the value is null

## Actual behavior
Warning: React does not recognize the `initialFocusedDate` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `initialfocuseddate` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

But it does work and sets the initial time.

## Live example
[https://codesandbox.io/s/mzlwpr06qy](https://codesandbox.io/s/mzlwpr06qy)
Sometimes the first time it doesn't show a warning but after you refreshed the browser it shows the error.

**Comment by dmtrKovalenko** [comment]
I don't think we supporting `initialFocusedDate` for TimePicker

**Comment by dmtrKovalenko** [comment]
But I think it will be nice to support it. I will add it

**Comment by jeroenhoebe** [comment]
> I don't think we supporting `initialFocusedDate` for TimePicker

Yeah that was what I initially though but it does says so in the docs at the TimePicker Component API.
