### ISSUE TITLE
disable specific date

### ISSUE THREAD

**Issue by soroushm** [dmtrKovalenko/material-ui-pickers#91]
Dear,

How can i disable  specific date? like 'shouldDisableDate={disableWeekends}' in material-ui v0 
http://www.material-ui.com/#/components/date-picker

i try to use renderDay but onClick still working :dagger:  and i cant disable date any solution?
```
  renderDay(date, selectedDate, dayInCurrentMonth) {
    return (
      <IconButton
        disabled>
        <span> {jMoment(date).format('jD')} </span>
      </IconButton>
    )
  }
```

**Comment by soroushm** [comment]
@dmtrKovalenko

**Comment by dmtrKovalenko** [comment]
@soroushm  Feel free to open a PR, if you need :)

**Comment by dmtrKovalenko** [comment]
🎉  beta.8
