### ISSUE TITLE
Date is `Unknown` in IE11

### ISSUE THREAD

**Issue by quentincrinon** [dmtrKovalenko/material-ui-pickers#910]
![Unknown](https://media1.tenor.com/images/acd12151cd1c65d364350e53ca918e25/tenor.gif?itemid=11015126)

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   2.1.2      |
| material-ui         |   0.20.2      |
| React               |    16.4.1     |
| Browser             |    IE11     |
| @date-io/date-fns       |    1.0.2    | 

## Steps to reproduce
1. Choose a date in IE11 and see the date set as 'Unknown' in the input

## Expected behavior
Date shown as 08/02/2019, for example.

## Actual behavior
Date shown as 'Unknown'

May caused by the new Date() which returns an invalid date in IE11.

**Comment by dmtrKovalenko** [comment]
I am sorry but I don't have IE11 and cannot fix that myself 😢 r

**Comment by younes0** [comment]
I don't have this problem with latest version and IE11, using date-fns and date format "MM-dd-yyyy"

**Comment by dmtrKovalenko** [comment]
I will close the issue, until someone will create a real reproduction. With screen and so on. Then will use browserstack or something to fix it
