### ISSUE TITLE
How to customise the day with 3 letter  SUN MON TUE ... instead of 2 letters su mo tu we th fr sa 

### ISSUE THREAD

**Issue by vooralaxmikanth** [dmtrKovalenko/material-ui-pickers#913]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |         |
| material-ui         |         |
| React               |         |
| Browser             |         |
| Peer library        |         | 

## Steps to reproduce
1.
2.
3.

**Comment by dmtrKovalenko** [comment]
Please use the template

**Comment by vooralaxmikanth** [comment]
![image](https://user-images.githubusercontent.com/28594684/52498009-98b17e00-2bfd-11e9-811b-076d2f9c7680.png)

**Comment by vooralaxmikanth** [comment]
@dmtrKovalenko . Thank you for your time.
can you please guide me how to use the template for day name to change as "Sun" instead of "Su"

**Comment by dmtrKovalenko** [comment]
https://material-ui-pickers.firebaseapp.com/guides/formats 
Override `getWeekDays`

For fontsize use `leftArrowIcon` and `rightArrowIcon` to pass custom components

**Comment by vooralaxmikanth** [comment]
Thank you , Can you please suggest me how to add close icon on right top corner to close the calendar.
