### ISSUE TITLE
this.props.getFormatString is not a function

### ISSUE THREAD

**Issue by aditya81070** [dmtrKovalenko/material-ui-pickers#915]
![A GIF or MEME to give some spice of the internet](url)

## Environment
I am using Ubuntu 18.04. 
| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   ^2.2.0   |
| material-ui         |    ^3.8.1     |
| React               |    16.7.0     |
| Browser             |      Chrome   |
| Peer library        |    moment@2.23.0     | 

## Steps to reproduce
1. Use `Datepicker` for selecting date in dd/mm/yyyy
2. use `format` attribute and use `this.props.getFormatString` function and pass `js {moment: 'DD/MM/YYYY'}`
3. Error will be `this.props.getFormatString` is not a function

## Expected behavior

Should show the date in given format

**Comment by nichgalea** [comment]
Have a similar issue with `_this.props.utils.startOfMonth is not a function`... not sure if related.

My dependencies:
material-ui-pickers - 2.2.1
material-ui/core - 3.9.2
React -  16.8.1
moment - 2.24.0

**Comment by dmtrKovalenko** [comment]
this.props.getformatstting is used only on the docs to support different libs at once. You need to pass a string directly to the component.

**Comment by aditya81070** [comment]
@dmtrKovalenko atleast you should put a comment there.

**Comment by faq885** [comment]
Totally agree with @aditya81070 , it isn't clear that! i ran into the same problem
