### ISSUE TITLE
@material-ui/styles doesn't work with this package

### ISSUE THREAD

**Issue by MathiasKandelborg** [dmtrKovalenko/material-ui-pickers#918]
![It doesn't work that way](https://flamableconcrete.github.io/python-automation-presentation/images/doesnt-work.jpg)

It would be really, really nice if we could provide our own theme in order to avoid unnecsessary overhead and maybe get a free perf boost. I'm aware that this might not be possible though. Now to the actual bug/problem I've experienced:

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 2.2.1  |
| material-ui/core      | 3.9.2 |
| material-ui/styles    | 3.0.0-alpha.10 |
| React                      | 16.8.1  |

## Steps to reproduce
1. Make app with material-ui styles (https://material-ui.com/css-in-js/basics/)
2. Import material-ui-pickers and use it somewhere
3. See the theming go wonky

## Expected behavior

That it wouldn't work yet

## Actual behavior

It doesn't work yet

## What could be done
I would love to help to update this package to use material-ui/styles. I know it's a big challenge and a lot of stuff needs to be re-written. But I'd really like to help - my only problem is that I'm not familiar with lerna or rollup, and my efforts so far have been in vain. If you could provide some information or links to relevant docs, I'd be so happy! :relaxed: 
 
I'm really sorry if this is redundant because of #862. I'm mostly creating this issue, because the current state of MUI, material-ui-pickers  and the documentation are out of sync. No info anywhere tells you about material-ui-pickers using the default styling solution from MUI - while MUI is currently moving towards a new default solution which they've said is hopefully included in v4.0.

This results in the MUI documentation on styling having this new 'alpha' solution as the default, with only a link to the current solution at the top. This in turns make most end-users oblivious to the compatability changes around the styling solutions - until their theming goes wonky ofc.

I guess this this is related to #876 - the MUI team has made the v4(next) branch of the project default and are currently working on that instead of 3.x [(see here)](https://github.com/mui-org/material-ui/issues/13663#issuecomment-459673205)

Finally, thanks for this package! It's super good, I really enjoy using it and the source is great, having looked through the code the past few hours. :grinning:

**Comment by dmtrKovalenko** [comment]
Hey! Thanks a lot. We really appreciate such effort!
To be honest I am a bit out of context with new `@material-ui/styles` so I don't know - how many effort will take to support them. #876 was fine with that. But we are open to new and we will definitely will support **default** styling solution of material-ui. We also starting work on v3 (next) and there will use `@material-ui/styles` :)

**Comment by MathiasKandelborg** [comment]
I'm quite sure I can navigate the project by now in regards to Lerna and project structure. I'm uncertain of how much work has been done already and if you're thinking if the whole project should be functional components with hooks or what pattern you wish to follow. 

I have been trying a few things and besides a few places where I'm inexperienced; most components can be converted to use the hook pattern. 


Should I just try and make a PRwith some suggested initial changes and a roadmap on what I think should be done?

**Comment by dmtrKovalenko** [comment]
Shipped in v3
