### ISSUE TITLE
Feature Request: Manual entry

### ISSUE THREAD

**Issue by justinanastos** [dmtrKovalenko/material-ui-pickers#92]
# High Five

This is really awesome work, thank you for putting in the time to build this.

# Feature Request

I have a use case where I have a list of dates that I need to enter into several pickers. I would like to be able to copy-paste or manually type the dates in. It appears to me that this component _only_ allows entry via the calendar. 

The obvious solution from a user standpoint would be to have a prop that tells the component to accept text entry and then to open the picker interface on clicking an adornment.

# PR

I would be happy to submit a PR for this if this is something you'd be willing to accept. We just need to iron out exactly how it should behave first.

**Comment by dmtrKovalenko** [comment]
Hi, seems the PR is almost there #90

**Comment by dmtrKovalenko** [comment]
:tada: beta.8
