### ISSUE TITLE
Can't pass a value of null

### ISSUE THREAD

**Issue by Auchindoun** [dmtrKovalenko/material-ui-pickers#921]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |2.2.1|
| material-ui         |3.9.2|
| React               |16.7|
| Browser             |Chrome 72.0.3626.109|
| Peer library        |Luxon| 

## Steps to reproduce
Pass date as null

## Expected behavior

When passing a value of `null`, I expect the field to display as empty empty.

![image](https://user-images.githubusercontent.com/11381794/52866513-6f648680-3104-11e9-8ba8-9bf4dc62679b.png)

## Actual behavior

I see a value of "Unknown" and an error message of "Invalid Date Format" when the value is `null`.

![image](https://user-images.githubusercontent.com/11381794/52866433-417f4200-3104-11e9-9087-4d6a347d73a2.png)

**Comment by dmtrKovalenko** [comment]
Please provide a way to reproduce. Checkout demo - https://material-ui-pickers.firebaseapp.com/api/datetimepicker, customization section. There is an example with clear initial state. It works with luxon as well

**Comment by Auchindoun** [comment]
My mistake. I was converting value to an ISO string somewhere down the line before it got passed to the date time picker. I'll close this ticket. Apologies
