### ISSUE TITLE
views prop does not work with InlineDatePicker

### ISSUE THREAD

**Issue by bhgoal** [dmtrKovalenko/material-ui-pickers#925]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    2.2.1     |
| material-ui         |     3.7.0    |
| React               |    16.6.3     |
| Browser             |     Chrome    |
| Peer library        |    date-fns     | 

## Steps to reproduce
1. Create InlineDatePicker component
2. Pass prop 'view={['year', 'month']}

## Expected behavior
Inline datepicker appears, opened to Months.

## Actual behavior
Inlinedatepicker appears, opened to Days.
Works without issue when using DatePicker, but not InlineDatePicker

**Comment by SergeySiuchanka** [comment]
Same issue for material-ui: 3.8.3 and react: 16.7.0.

**Comment by SergeySiuchanka** [comment]
Also reproduced here https://codesandbox.io/s/zrql0n958m.
