### ISSUE TITLE
Date Picker Auto change to previous state on state change

### ISSUE THREAD

**Issue by msg2santoshsagar** [dmtrKovalenko/material-ui-pickers#927]
Assume in a component  there is checkbox and date picker. 
Keyboard is allowed for date picker.

## Steps to reproduce
1. Enter partial date in date picker.
2. Click on check box

## Expected behavior
Date picker should Still show what user typed.

## Actual behavior
Date picker become empty.

## Live example
https://codesandbox.io/s/xvzollx44q

**Comment by dmtrKovalenko** [comment]
Oh, I got it. That’s sucks and we will redo it in v3. The issue in current keyboard mode architecture.

**Comment by msg2santoshsagar** [comment]
@dmtrKovalenko Thanks. When I can expect V3. my application is about to go live and we got this bug.

**Comment by dmtrKovalenko** [comment]
:( 
I suppose it’s not a bug. Think about keyboard mode as separate component. In v3 keyboard will accept string, and not keyboard the date
