### ISSUE TITLE
`openTo` prop is not working

### ISSUE THREAD

**Issue by SergeySiuchanka** [dmtrKovalenko/material-ui-pickers#929]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 2.2.1 |
| material-ui         | 3.8.3 |
| React               | 16.7.0 |
| Browser             | Chrome 72 |
| Moment        | 2.24.0 |

## Steps to reproduce
1. Create DatePicker (`DatePicker`);
2. Add views prop (`views={['year', 'month', 'day']}`);
3. Add openTo prop (`openTo="day"`);

## Expected behavior
When one opens a Date picker, it should be opened with the calendar view.

## Actual behavior
Date picker is opened with the year view.

## Live example
https://codesandbox.io/s/6vvr9mm26w

**Comment by MikeAski** [comment]
I confirm this, plus: Even if I define `views={['day', 'month', 'year']}`, the picker still opens on year.

**Comment by dmtrKovalenko** [comment]
Released in 2.2.2
