### ISSUE TITLE
`openTo` prop is not recognised by InlineDatePicker

### ISSUE THREAD

**Issue by SergeySiuchanka** [dmtrKovalenko/material-ui-pickers#930]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 2.2.1 |
| material-ui         | 3.8.3 |
| React               | 16.7.0 |
| Browser             | Chrome 72 |
| Moment        | 2.24.0 |

## Steps to reproduce
1. Create DatePicker (`InlineDatePicker`);
2. Add views prop (`views={['year', 'month', 'day']}`);
3. Add openTo prop (`openTo="year"`);

## Expected behavior
When one opens a Date picker, it should be opened with the year view.

## Actual behavior
Date picker is opened with the calendar view.
There is a warning in console that React does not recognize the `openTo` prop on a DOM element. Which means that InlineDatePicker does not recognise the `openTo` prop and pass it to the material-ui TextField component.

## Live example
https://codesandbox.io/s/zrql0n958m

**Comment by dmtrKovalenko** [comment]
Released in 2.2.2
