### ISSUE TITLE
Changing Date icon

### ISSUE THREAD

**Issue by felixnielsen** [dmtrKovalenko/material-ui-pickers#931]
Hi

Would it be possible to add a property that allows for changing the Date icon?
![image](https://user-images.githubusercontent.com/157148/53579747-6f3f9e80-3b7a-11e9-9a86-67e458c4b02b.png)

**Comment by dmtrKovalenko** [comment]
keyboardIcon

**Comment by alexnez96** [comment]
@dmtrKovalenko With v3.0.0 I tried `KeyboardDatePicker` with both

```js
KeyboardButtonProps={{
  children: <CustomIcon />
}}
```

and

```js
InputAdornmentProps={{
  children: <IconButton><CustomIcon /><IconButton />
}}
```

but the icon never changes. Is there a demo in the docs? Can you provide a runnable example please?
