### ISSUE TITLE
Swipe between months

### ISSUE THREAD

**Issue by katy6514** [dmtrKovalenko/material-ui-pickers#932]
[Swipe happy](https://gph.is/2gRD4UP)

HI folks, thanks for a fantastic library, I love the time picker.

I was wondering if there was any plan (so far I can't find anything in my searches) to include a swipe option between months for the DatePicker? I'm building a calendar app in React, on desktop views it makes sense to have the "next month" and "previous month" arrows for mouse clicks but on mobile  swipe for "next month" and "previous month" would be awesome.

I've looked at [React Swipeable Views](https://react-swipeable-views.com/) for a possible solution but I'm still a pretty junior javascript developer, and I'm not sure where to start with the DatePicker.js file!

| Tech        | Version           | 
| ------------- |-------------:|
| material-ui-pickers     | 2.2.0 | 
| @material-ui/core      | 3.9.2      |
| react | 16.4.1     |

**Comment by dmtrKovalenko** [comment]
I am actually aware of integration because of [additional 5.7kb gzipped](https://bundlephobia.com/result?p=react-swipeable-views@0.13.1) 

And not really popularity of the swiping functionality, mostly will just use arrows.

**Comment by Benew** [comment]
I have users requesting this feature too. Could this be done by adding an optional prop to pass down the SwipableView component (or a custom implementation) and thus not adding a new lib to the project ?

**Comment by dougkulak** [comment]
I'd love to see this functionality as well.
