### ISSUE TITLE
Performance leak in case of luxon date utils and non-english locale

### ISSUE THREAD

**Issue by pomadin** [dmtrKovalenko/material-ui-pickers#936]
## Environment
| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  2.2.1       |
| material-ui         |     3.9.2    |
| React               |    16.8.3     |
| Browser             |    chrome     |
| luxon              |    1.11.3     |
| @date-io/luxon    |    1.1.0     |

## Steps to reproduce
1. Open the demo from codesandbox
2. Ensure the locale is set for MuiPickersUtilsProvider, for instance 'ru'
3. Open picker and click prev/next month few times quickly

## Expected behavior
At least the same performance as english locale has.

## Actual behavior
The month viewes switchces slowly with some visual glitches.
Chrome traces verbose messages about long time running handlers.
![video_2019-03-02_174530](https://user-images.githubusercontent.com/9018346/53681026-faa16700-3d15-11e9-8a99-d4710b7c112d.gif)

## Live example
- [Demo](https://codesandbox.io/s/lrxz636xml)

**Comment by dmtrKovalenko** [comment]
I have created a benchmark with comparison of all date managment libs and [here](https://github.com/dmtrKovalenko/date-io/tree/master/packages/benchmark) you can see results.  
As you can see there luxon is 175 times slower than moment in case of formatting dates. Seems like you just need to [accept](https://github.com/moment/luxon/issues/321) this... 😞 

We must use `Intl` to compute strings. If you have any idea how to improve please, rize them in the @date-io library
