### ISSUE TITLE
Material UI Example Sandbox not working after Recent Update

### ISSUE THREAD

**Issue by BunnyMan1** [dmtrKovalenko/material-ui-pickers#937]
## Environment
https://codesandbox.io/s/0y7vqw3o6v

## Actual behavior

Error
Could not fetch dependencies, please try again in a couple seconds: Something went wrong while packaging the dependency material-ui-pickers@2.2.2: ENOENT: no such file or directory, scandir '/tmp/957365525/node_modules/material-ui-pickers/build/dist'

**Comment by dmtrKovalenko** [comment]
@BunnyMan1 I am really sorry 😞 that was my fault. Released v2.2.4 with a fix https://codesandbox.io/s/825vlr6j6l
