### ISSUE TITLE
Support for IE 11

### ISSUE THREAD

**Issue by zdrummond** [dmtrKovalenko/material-ui-pickers#94]
I just did a test on IE 11 and I got hit with `Object doesn't support property or method 'values'` inside `Clock` and `DateTimePicker`. It looks like `.values` is part of ES7, is not [supported in IE 11](http://kangax.github.io/compat-table/es2016plus/#test-Object_static_methods_a_href=_https://tc39.github.io/ecma262/#sec-object.values_Object.values_/a_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;), and Create React App does not Polyfill it. 

Can you move to using `keys` [instead](https://stackoverflow.com/a/38748490)? Thanks!

**Comment by alitaheri** [comment]
@zdrummond Use a polyfill. @dmtrKovalenko I think we should document that.

**Comment by dmtrKovalenko** [comment]
Maybe we should replace that with smth else, to not force customers polifilll.

**Comment by artursmirnov** [comment]
I have also faced issues with IE11 and CRA. My bundle has been missing `Array.from`. After adding a polyfil, it still does not work. The calendar appears but the grid is empty, no days. Same with year picker, it appears empty. Although there's no errors in console, it breaks silently.

**Comment by dmtrKovalenko** [comment]
@artursmirnov 
We cannot easily replace array from :( Its like a core dependency :(

**Comment by dmtrKovalenko** [comment]
Have removed object values in the beta.8

**Comment by artursmirnov** [comment]
@dmtrKovalenko I completely understand, and that's not an issue, I just added polyfill and the error has gone. But still this is what I see in IE 11:

![image](https://user-images.githubusercontent.com/4066489/33930577-714ec53a-dffe-11e7-9fd6-dc522a200a62.png)

The same for year selector.

I used the polyfill from MDN documentation.

**Comment by bmuenzenmeyer** [comment]
This is still broken even with the Array.from polyfill.

I've polyfilled `Array.from()` using both [array.from](https://www.npmjs.com/package/array.from) and the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from).

I think what's happening is that `moment.range()` below is [not returning a supported iterator in IE](https://github.com/rotaready/moment-range/issues/172). [and more?](https://github.com/rotaready/moment-range/issues/167)

[`utils.js` LN#74:](https://github.com/dmtrKovalenko/material-ui-pickers/blob/master/lib/src/utils/utils.js#L74)

``` js
const weeks = Array.from(moment.range(start, end).by('week'));
```

Adding this [babel polyfill](https://babeljs.io/docs/usage/polyfill) as mentioned with https://github.com/rotaready/moment-range/issues/172#issuecomment-339256528 resolved the issue  for me

![image](https://user-images.githubusercontent.com/298435/34121227-ee911e1a-e3ed-11e7-8a2c-2958f91aa2af.png)

This seems like an okay, if not pretty heavy-handed workaround until `moment-range` can resolve this.

Hope this helps someone else 🔬

**Comment by artursmirnov** [comment]
@bmuenzenmeyer thanks, your solution worked for me as well!

**Comment by edidiway** [comment]
I tried to open Basic Usage Calendar on the demo page in IE 11, [https://material-ui-pic.firebaseapp.com/](https://material-ui-pic.firebaseapp.com/),

the calendar is not appear, instead the screen become crash.

**Comment by cherniavskii** [comment]
@edidiway please read comments above - you need to include some polyfills to make it work in IE11.
https://material-ui-pic.firebaseapp.com/ most probably has no polyfills included.
