### ISSUE TITLE
Won't reconize utils

### ISSUE THREAD

**Issue by RedHatter** [dmtrKovalenko/material-ui-pickers#941]
I just update `material-ui-pickers` and now it won't pickup utils. I get `Error: Can not find utils in context. You either a) forgot to wrap your component tree in MuiPickersUtilsProvider; or b) mixed named and direct file imports.  Recommendation: use named imports from the module index. 2 WithUtils.js:26`.

My index files is as follows.

```
import '@babel/polyfill'
import React from 'react'
import ReactDOM from 'react-dom'
import Amplify from 'aws-amplify'
import { Authenticator } from 'material-ui-utils'
import { MuiPickersUtilsProvider } from 'material-ui-pickers'
import DateFnsUtils from '@date-io/date-fns'
import MuiThemeProvider from '@material-ui/core/styles/MuiThemeProvider'
import createMuiTheme from '@material-ui/core/styles/createMuiTheme'
import blue from '@material-ui/core/colors/blue'

import App from './App.jsx'

Amplify.configure({
  Storage: {
    region: 'us-west-1',
    bucket: '...'
  },
  Auth: {
    region: 'us-west-2',
    identityPoolId: '...',
    userPoolId: '...',
    userPoolWebClientId: '...'
  }
})

const theme = createMuiTheme({
  palette: {
    primary: { main: blue[500] }
  }
})

ReactDOM.render(
  <MuiThemeProvider theme={theme}>
    <MuiPickersUtilsProvider utils={DateFnsUtils}>
      <App />
    </MuiPickersUtilsProvider>
  </MuiThemeProvider>,
  document.getElementById('root')
)

```

**Comment by dmtrKovalenko** [comment]
`You either a) forgot to wrap your component tree in MuiPickersUtilsProvider; or b) mixed named and direct file imports.`

You must use or path imports or absolute. 
```diff
- import DatePicker from 'material-ui-pickers/DatePicker'
+ import { DatePicker } from 'material-ui-pickers;
```

**Comment by RedHatter** [comment]
It might be more clear to say "mixed default imports and named imports"

**Comment by chenop** [comment]
For me the issue was that the specific component I tried to use with `DatePicker `was not wrapped with `MuiPickersUtilsProvider`

**Comment by zackify** [comment]
Is there any reason for this? Was hard for me to figure out as well. Curious what the technical reason this project doesn't use destructuring with full path imports. We have some old code from an old version of this lib that I updated, it imports components directly, like `import PickerToolbar from 'material-ui-pickers/_shared/PickerToolbar'. So I am now stuck using full path imports for everything.

P.S. love this library and thanks for all the hard work!

**Comment by dmtrKovalenko** [comment]
That’s because of react context. When you importing from root - you are getting esm bundle. But when you are using path imports - cjs. 

But if you are trying to import context instance from different files it breakes :)
You can wrap the tree with 2 same instances - but you will have 2 duplicated components in bundle. 1 from esm and 1 from cjs

**Comment by zackify** [comment]
Ah I see. I know it would be possible to change it to use a babel build so that paths are still there with the es module stuff. But then that would possibly break things for other people who need the cjs part of it... 

I wish the module system was setup better to handle this stuff!
