### ISSUE TITLE
on Edit DatePicker need a callback

### ISSUE THREAD

**Issue by bag3557** [dmtrKovalenko/material-ui-pickers#942]
I want to validate selected/entered date from datepicker component on keyboard props. So want a callback on key press.

**Comment by dmtrKovalenko** [comment]
Pls follow the template

**Comment by bag3557** [comment]
I can't find any template...

**Comment by dmtrKovalenko** [comment]
New issue -> feature request
![image](https://user-images.githubusercontent.com/16926049/53880652-31c78f00-401a-11e9-9788-014d6fc1aef8.png)

And please be descriptive

**Comment by bag3557** [comment]
I have been using the date-time picker. I am unable to get a callback if my date is invalid.
I do have a validation of the date-picker which is internal.
For eg:
1) I am gonna select a proper date then my state gets updated. (01-01-1990)
2) Now, I am gonna change my date to (01-01-199) removing 0 from the last making the date invalid, now, in this case, the internal state of the date-picker works perfectly fine but I don't get a callback to update my state of the date.

**Comment by andreypopp** [comment]
I second this — it would be nice if pickers will provide controlled mode where all state is routed through the parent component.

**Comment by dmtrKovalenko** [comment]
@andreypopp #946

**Comment by andreypopp** [comment]
@dmtrKovalenko thanks, just spotted this. The proposed API looks great!
