### ISSUE TITLE
Time Digits in date time/time picker wont be loaded for the peer library localization

### ISSUE THREAD

**Issue by ahmad-rzk** [dmtrKovalenko/material-ui-pickers#950]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |   2.2.4      |
| material-ui         |     3.9.2     |
| React               |     16.8.4    |
| Browser             |   Chrome 72.0.3626.121      |
| Peer library        |     moment, 2.24.0    | 

## Steps to reproduce
1.Use date time picker with "ar" localization on moment 
2.Note the time picker captions are still in "en" while the selected time is shown in the correct caption

## Expected behavior
Time picker digits should be as the time result

## Actual behavior
Digits are different 

## Live example
https://codesandbox.io/s/00kwz8v540?fontsize=14

**Comment by dmtrKovalenko** [comment]
Thats a bug :) Maybe

**Comment by dmtrKovalenko** [comment]
Just wondering - you are not using `@date-io/jalaali` just moment. I am wondering that it will be not so easy as I supposed

**Comment by dmtrKovalenko** [comment]
Checkout this example https://material-ui-pickers.dev/localization/persian#example
And https://material-ui-pickers.dev/guides/formats#utils-interface

You can override `formatNumber` method to make it works for you

**Comment by ahmad-rzk** [comment]
Thank you so muck it worked 💯 .

For anyone wondering how , here is an example :
https://codesandbox.io/s/00kwz8v540?fontsize=14
