### ISSUE TITLE
Setting max/min date to null crashing application

### ISSUE THREAD

**Issue by msg2santoshsagar** [dmtrKovalenko/material-ui-pickers#952]
## Steps to reproduce
1. Set max/min date to null
2. Click on calendar icon

## Expected behavior
Calendar should open to choose date

## Actual behavior
Application is crashing

## Live example
https://codesandbox.io/s/yqz5vv04z9?fontsize=14
Here you can click on set max date to null to set max date as null.

**Comment by dmtrKovalenko** [comment]
The null value is not supported. Please use undefined
