### ISSUE TITLE
Support `ModalProps` prop

### ISSUE THREAD

**Issue by depiction** [dmtrKovalenko/material-ui-pickers#955]
I'm using a datepicker within a custom modal component that uses `focus-trap-react`. The date picker modal uses Material UI's modal component. Because both FocusTrap and Material UI's Modal components try to trap focus, a `Maximum call stack size exceeded` error appears when the date picker modal opens.

Material UI's Modal API (https://material-ui.com/api/modal/) has a prop called 'disableEnforceFocus'. I think I could solve the error by setting that prop to true. 

The DatePicker component doesn't appear to support ModalProps, so for now I have to remove FocusTrap.

I see that support for `DialogProps` was supposedly added (https://github.com/dmtrKovalenko/material-ui-pickers/issues/552), however it's not listed in the documentation.

**Comment by dmtrKovalenko** [comment]
DialogProps should work for you

**Comment by depiction** [comment]
I got it working with DialogProps, thanks. It would be nice if DialogProps was documented at https://material-ui-pickers.dev/api/datepicker
