### ISSUE TITLE
Moment locale 'nl' displaying unexpected value in input

### ISSUE THREAD

**Issue by cameleater** [dmtrKovalenko/material-ui-pickers#956]
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |    2.2.4     |
| material-ui         |    3.1.2     |
| React               |     16.5.2    |
| Browser             |   Chrome 72      |
| Peer library        |  Moment.js       | 

## Steps to reproduce
1. Render <DatePicker /> component
2. Set moment.locale('nl')
3. selectedDate = moment();

## Expected behavior

Input should display "maart 20"
(todays date)

## Actual behavior

input displays 'maart 20ste"

## Live example
https://codesandbox.io/s/y3lo1pjj4j

**Comment by dmtrKovalenko** [comment]
Relative time formatting? March 19th <- th - relative patt

**Comment by cameleater** [comment]
> Relative time formatting? March 19th <- th - relative patt

Oh yes it is. I am not native 'nl' so I did not recognize it.

And this page in the documentation helped me format the date in the input
https://material-ui-pickers.dev/guides/formats

Thank you
