### ISSUE TITLE
Typing in a DateTimePicker should replace instead of shift values

### ISSUE THREAD

**Issue by leroydev** [dmtrKovalenko/material-ui-pickers#957]
**Is your feature request related to a problem? Please describe.**
When typing in a DateTimePicker with keyboard input, the values shift to the right instead of getting replaced.

**Describe the solution you'd like**
I'd like it to replace values, so it'd be possible to change only parts of the date.

**Describe alternatives you've considered**
n/a

**Current way of typing**
Gif with typing and undoing:
![datetime keyboard input](https://user-images.githubusercontent.com/2467392/54745523-06bc6e00-4bca-11e9-9c7f-fb78af8e994f.gif)
(can be reproduced at https://material-ui-pickers.dev/api/datetime-picker)

**Ideal way for me personally**
Ideally, I'd like it to work something like this:
![native datetime input](https://user-images.githubusercontent.com/2467392/54745847-e80aa700-4bca-11e9-993f-50f995baf007.gif)

It'd also be fine if it was just possible to replace instead of shift values though. Is there any way to do this?

**Comment by leroydev** [comment]
When checking the options of `react-text-mask`, I noticed the [`keepCharPositions`](https://github.com/text-mask/text-mask/blob/master/componentDocumentation.md#keepcharpositions) option, which comes very close to what I want to achieve. Do you think it'd be a good idea to add that option to the documentation of `material-ui-pickers`?

**Comment by dmtrKovalenko** [comment]
We support that option as a prop https://github.com/dmtrKovalenko/material-ui-pickers/blob/develop/lib/src/_shared/DateTextField.tsx#L38

That's awful that not documented

**Comment by dmtrKovalenko** [comment]
Updated docs https://material-ui-pickers.dev/
