### ISSUE TITLE
DateTimePicker views switch bug

### ISSUE THREAD

**Issue by RinatRezyapov** [dmtrKovalenko/material-ui-pickers#958]
Sorry if this bug was already reported. Didn't find any related reports in history.

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     2.2.4    |
| material-ui         |    3.8.2     |
| React               |     16.8.4    |
| Browser             |   chrome (latest)      |
| Peer library        |     momnet 1.1.0    |

## Steps to reproduce
See live example

## Expected behavior
Views should be switched the same way as they are switching in DatePicker

## Actual behavior
It shows only year if openTo set to year and then skips month select.

## Live example
https://codesandbox.io/s/zr3zz5ln3l

**Comment by dmtrKovalenko** [comment]
Date time picker doesn’t support month.

**Comment by RinatRezyapov** [comment]
> Date time picker doesn’t support month.

Thank you @dmtrKovalenko. Any plans to add support in the future? I suppose documentation for DateTimePicker (https://material-ui-pickers.dev/api/datetime-picker) should be changed as it points out that DateTimePicker supports all views:
`views | ("year" \| "month" \| "day")[]`

**Comment by dmtrKovalenko** [comment]
Updated docs https://material-ui-pickers.dev/
