### ISSUE TITLE
Mindate does not limit time

### ISSUE THREAD

**Issue by AugustoAmaral** [dmtrKovalenko/material-ui-pickers#959]
![](https://thumbs.gfycat.com/DifficultDiligentCobra-small.gif)
Hello guys, how are you?

I was using the minDate props on dateTime picker and I noticed that only past dates are limited and not past hours, my solution was use a validation to block submit but it would be awesome if i could disable past hours like dates.

**Comment by JavierLight** [comment]
Is any provisional workaround for this? I think this would be a great feature! 👍

**Comment by dhruuuuuv** [comment]
seconded! This functionality seems strange... can anyone suggest a fix?

**Comment by dmtrKovalenko** [comment]
Duplicate of #519 0
