### ISSUE TITLE
Inline mode, add buttons

### ISSUE THREAD

**Issue by denis-n** [dmtrKovalenko/material-ui-pickers#962]
![image](https://user-images.githubusercontent.com/4423231/54928006-e79c4400-4f1b-11e9-8150-69adf57589b4.png)

**Is your feature request related to a problem? Please describe.**
There are no Today, Cancel and OK buttons in **InlineDatePicker,  InlineDateTimePicker**

**Describe the solution you'd like**
Please add Today, Cancel and OK buttons to **InlineDatePicker,  InlineDateTimePicker**

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dmtrKovalenko** [comment]
We are following material design principles. From the guidance the pop up should represent 1 action, without any submit.

**Comment by dmtrKovalenko** [comment]
We will not support dialog actions in inline mode

**Comment by denis-n** [comment]
Thanks

**Comment by multivitamine** [comment]
still would be a nice addition
