### ISSUE TITLE
DatePicker onChange value includes current timepart

### ISSUE THREAD

**Issue by mcMickJuice** [dmtrKovalenko/material-ui-pickers#963]
I recently upgraded from `1.0.0-rc.10` to `2.2.4` and I noticed that when using the `DatePicker` component, the date passed to `onChange` includes a time part pertaining to the current time.  This is a change from rc.10 where the value reported to onChange is the selected date and the time is midnight of system time zone

I looked through the changelog and didn't see anything related to this change.

## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |     2.2.4    |
| material-ui         |   3.9.2     |
| React               |      16.8.4   |
| Browser             |    All     |
| Peer library        |    "@date-io/moment": "1.1.0"     | 

## Steps to reproduce
1. Use `DatePicker` component, console.log out the date passed to onChange handler
2. Notice that date includes a timepart corresponding to the current time

## Expected behavior

Since I'm using just a datepicker, I expect the value passed to `onChange` to be the date I selected at midnight

## Actual behavior

The date passed to onChange handler is the selected date plus the current time

## Live example

- [Code Sandbox with version 1.0.0-rc.10](https://codesandbox.io/s/rjyx0jw944) showing desired behavior (midnight of selected date)
- [Code Sandbox with version 2.2.4](https://codesandbox.io/s/rjp5885x04) showing actual behavior where value includes current time

**Comment by dmtrKovalenko** [comment]
Yep. From now this is by design. From the flip side that’s really strange when the datepicker looses the time part. 
So if you need to get the midnight —
pass the midnight as value.

**Comment by mcMickJuice** [comment]
So the onus is on the user to convert the date that they picked to midnight?  If this is the case, should this not be documented? Or at least called out as a breaking change?

**Comment by dmtrKovalenko** [comment]
Actually that was a bug - that datepicker loosing the time part. So it was documented in patch somewhere. :)

**Comment by mcMickJuice** [comment]
Fair enough. Thanks for your quick response, even though I disagree with the outcome 😄
