### ISSUE TITLE
Attribute for "readonly" input

### ISSUE THREAD

**Issue by highfield** [dmtrKovalenko/material-ui-pickers#968]
Since this is an input control as others, it would be nice having the `readOnly` attribute (not `disabled`!).

I tried to pass the attribute to the underlying `Input` component. That effectively turns the input area as readonly, but does not prevent the click to open the popup editor.

Actually, it would be even nicer having the ability to treat the *Picker components as a normal Input, so that the following snippet would work:

```
        <FormControl required>
          <InputLabel htmlFor="p1" shrink>
            Label
          </InputLabel>
          <DatePicker
            id="p1"
            value={selectedDate}
            onChange={handleDateChange}
            margin="normal"
            InputProps={{ readOnly: true }}
          />
          <FormHelperText id="hp1">Error</FormHelperText>
        </FormControl>

```
Notice the hacks like the "shrink" on the InputLabel, etc.

**Comment by dmtrKovalenko** [comment]
We are using FormControl and label under the hood, so it will not work :) 
You need to combine `inputProps` and `InputProps` to make it works. 

Note that this will work fine
```
InputProps={{ shrink: true }}
inputProps={{ readOnly: true }}
```

**Comment by highfield** [comment]
Well, I see that there's something I can do, but how to prevent the user opens a "readonly"-marked picker by clicking against it? If you try, you can modify the field value.

**Comment by dmtrKovalenko** [comment]
You can use `error` and `helperText` to override. Btw we completely redoing the design in v3. Mostly of that will be changed

**Comment by highfield** [comment]
Aww, yeah! works fine!...
I need something decent for the UI in the meantime, so a patch is suitable.
I will dig for a patch for the readonly-click problem...
