### ISSUE TITLE
Implement MaterialUiPickersDate typing

### ISSUE THREAD

**Issue by sperry94** [dmtrKovalenko/material-ui-pickers#970]
**Is your feature request related to a problem? Please describe.**
The `MaterialUiPickersDate` provided is currently just an alias for the `any` type. This should be changed to give better type safety for consumers.

**Describe the solution you'd like**
Give a concrete typing to the `MaterialUiPickersDate` type.

**Describe alternatives you've considered**
N/A

**Additional context**
None.

**Comment by dmtrKovalenko** [comment]
Actually that’s a point of todo in v3. Here is an issue in real. We can do only Luxon | Moment | Date | Dayjs type. That’s sucks because you it will error you anytime you use it. :)

**Comment by sperry94** [comment]
ah I understand, so the output type isn't dependent on the `utils` you use? So that if someone is using `date-fns` for example, they will only ever be provided with a `Date` object, but since the `MaterialUiPickersDate` would be `Luxon | Moment | Date | Dayjs`, then they'd have to handle all those possibilities in any callbacks they had?

So the idea then would be to base the `MaterialUiPickersDate` off of what `utils` library the user is actually using?

**Comment by abidRahim** [comment]
How to implement the Type for `MaterialUiPickersDate` ?
