### ISSUE TITLE
Allow `defaultTimezone` prop to determine timezone the first time a date is selected

### ISSUE THREAD

**Issue by johnnyji** [dmtrKovalenko/material-ui-pickers#971]
First of all, thank you for this amazing library! It has done wonders for so much people 👏 👏 👏 

We are a SaaS application that allows users to set timezones for themselves. Whenever a date picker is rendered without an initial date passed in, there is no way to specify a timezone for the initially selected date. Therefore, the first time a user selects a date, it will always default to your date implementation library's timezone (which for `moment` is your local browser timezone by default I believe).

Currently, we get past this by using `moment.tz.setDefault(currentUserTimezone)` which technically solves the issue. However, having to set a global timezone for this one case feels wrong and could potentially introduce bad habits of developers relying on that global timezone in the future.

Instead, it would be great if we could allow a `defaultTimezone` prop that can be used to provide a timezone to use if there's no date already passed to the picker.

**Comment by dmtrKovalenko** [comment]
Have you tried to pass your moment instance?

```javascript
<MuiPickersUtilsProvider moment={moment} utils={MomentUtils}>
...
</MuiPickersUtilsProvider>
```

**Comment by johnnyji** [comment]
@dmtrKovalenko 

Thanks for getting back to me, I tried your proposed solution and it doesn't solve the issue mentioned. As far as I can tell this only passes my instance of `moment` to MUI Pickers. But if I don't set a timezone globally via `moment.tz.setDefault`, the individual date picker component still just default to my browser timezone.

Just to reiterate, the issue I'm coming across is that there's no way to provide a timezone to a date picker component unless I somehow set a global timezone in `moment` itself as far as I'm aware of. Therefore, as far as I know, the date picker will always handle timezones in the user's browser local time. This is troublesome because even if a user is in Honolulu for example, they may have set their timezone to Los Angeles in my app's settings.

I can see 2 ways to possibly solve this issue:

1. When the user logs in, set `moment.tz.setDefault("America/Los_Angeles")` and undo this when they log out

2. Pass a prop called `timezone` to `DatePicker` and `DateTimePicker` so that the pickers know what timezone to use when selecting dates.

I think the latter is cleaner because setting global defaults feels wrong in general, and especially in this case, setting a global default just for date pickers feel wrong.

Sorry if I was unclear in my initial explanation. Does my description of the problem make sense?

**Comment by dmtrKovalenko** [comment]
Passing time zone is really not a good solution. If your time zone a dynamic — pass value as moment object with time zone. In onChange you will get new date in same time zone

**Comment by johnnyji** [comment]
@dmtrKovalenko 

Unfortunately, I can't always pass a moment object with a configured timezone. There are some cases where the DateInput needs to be empty to start with (i.e., "Delivery Arrived Date" in which case having a prepopulated initial date makes no sense). Do you have any other suggestions to approach this?

**Comment by dmtrKovalenko** [comment]
Then use `intialFocusedDate` or pass properly configured moment instance to the provider
