### ISSUE TITLE
onChange event not triggering in forms tag

### ISSUE THREAD

**Issue by VagnerNico** [dmtrKovalenko/material-ui-pickers#972]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 2.2.4  |
| material-ui              | 3.9.2  |
| React                     | 16.8.4 |
| Browser - Chrome | 73.0.3683.86 |
| Peer library            | date-fns 2.0.0-alpha.27 |

## Steps to reproduce
1. Wrap the picker on any form with onChange or onInput event or both.

## Expected behavior
Expected to trigger onChange or onInput when change the value of picker.

## Actual behavior
Value changes, the input value changes but the onChange event don't trigger.

[Live example](https://codesandbox.io/embed/o4ov6kvr05)

**Comment by dmtrKovalenko** [comment]
https://material-ui-pickers.dev/guides/form-integration

**Comment by dmtrKovalenko** [comment]
You have not passed name

**Comment by VagnerNico** [comment]
Sorry my mistake.
