### ISSUE TITLE
Reset of a form does not reset picker to initial value

### ISSUE THREAD

**Issue by jookshub** [dmtrKovalenko/material-ui-pickers#973]
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers |  2.2.4       |
| material-ui         |    3.9.3     |
| React               |  16.8.6       |
| Browser             |   Chrome 73      |
| Peer library        |   date-fns@2.0.0-alpha.27, @date-io/date-fns@1.1.0 |

## Steps to reproduce
1. use Formik-Example from https://material-ui-pickers.dev/guides/form-integration and add a form-reset-button - e.g.: https://codesandbox.io/embed/l9zr45yx9m
2. change the initial date
3. click reset-button

## Expected behavior
the date should be reset to the initial date e.g. 03/04/2019

## Actual behavior
it visibly clears the date, although internally the value is reset to the initial date

## Live example
https://codesandbox.io/embed/l9zr45yx9m

**Comment by dmtrKovalenko** [comment]
Shipped in v3
