### ISSUE TITLE
Overlay doubleclick prevents from closing modal

### ISSUE THREAD

**Issue by michalpokojski** [dmtrKovalenko/material-ui-pickers#98]
Like described in the title

**Comment by dmtrKovalenko** [comment]
Maybe, you should open this issue in material-ui? We have just reused controls, so it seems to be the bug from material-ui side :)

**Comment by alitaheri** [comment]
@dmtrKovalenko Not really, look at [this line](https://github.com/dmtrKovalenko/material-ui-pickers/blob/master/lib/src/wrappers/ModalWrapper.jsx#L45). It shouldn't **toggle** it should **close**. Simple fix really, @michalpokojski Can you take care of it? 😅
