### ISSUE TITLE
next : inline `only calendar` displays the big header

### ISSUE THREAD

**Issue by ngouy** [dmtrKovalenko/material-ui-pickers#984]
![](https://media.giphy.com/media/YQitE4YNQNahy/giphy.gif)

## Steps to reproduce
1. go to https://material-ui-pickers.dev/api/datepicker#inline-mode
2. click on `only calendar`
3. it works
4. do the same on next (https://next.material-ui-pickers.dev/api/datepicker#inline-mode)
5. it doesn't works

## Expected behavior
we expect the header to not display

## Actual behavior
![image](https://user-images.githubusercontent.com/12391171/55987258-1ed65900-5c6f-11e9-8ada-abbc0fa0d146.png)

**Comment by dmtrKovalenko** [comment]
Thanks a lot. Seems like it was missed in rewrote and lacking of tests. Will be fixed   🙏
