### ISSUE TITLE
Datepicker : year change doesn't update calendar

### ISSUE THREAD

**Issue by liitfr** [dmtrKovalenko/material-ui-pickers#99]
Hello !

Details to reproduce this issue:

- Component : Datepicker
- Browser : Chrome 63.0.3239.84 / Firefox 57.0.1
- OS : Ubuntu 
- material-ui version : 1.0.0-beta.21
- material-ui-pickers : 1.0.0-beta.7
- react : 15.6.2 

Component Code :

```
/**
 * DatePicker
 *
 * Map Material DatePicker component to Redux-form Field component
 */

import React from 'react';
import PropTypes from 'prop-types';

import { DatePicker } from 'material-ui-pickers';

import FormControl from './FormControl';

const CustomDatePicker = props => {
  const { id, input: { value, onChange } } = props;
  return (
    <FormControl>
      <DatePicker
        id={id}
        value={value}
        onChange={onChange}
        invalidLabel="DD/MM/YYYY"
        format="DD/MM/YYYY"
        disableFuture
      />
    </FormControl>
  );
};

CustomDatePicker.propTypes = {
  input: PropTypes.shape({
    onChange: PropTypes.func.isRequired,
  }).isRequired,
};

export default CustomDatePicker;
```

I use this component with Redux-form.

Observed Behavior :

![picker2](https://user-images.githubusercontent.com/24525920/33896244-a1d23850-df62-11e7-9b06-9e3bdadffa40.gif)

agenda isn't refreshed when a past year has been chosen.
If I select a day in agenda it stays in 2017. But instead, if I directly click on OK button, it keeps expected year (here, 2010)

There surely must be something wront with my setup but I can't find out what.

Thanks for this very promising package !

**Comment by dmtrKovalenko** [comment]
Thank you, I think its related to react version. For 16+ it doesnt reproducible

**Comment by liitfr** [comment]
ho ok, thanks for your really quick answer ! I will have some update to do on project :)

since this issue is functionally blocking,
maybe `^15.6.2` compatibility should be removed from `package.json` ?
https://github.com/dmtrKovalenko/material-ui-pickers/blob/master/lib/package.json#L34

**Comment by dmtrKovalenko** [comment]
Yes, anyway we should do something with that, thx

**Comment by dmtrKovalenko** [comment]
@liitfr  We have removed support of `15.6.2` in beta.8
